mbta/dotcom

apps/site/assets/ts/app/global-navigation.ts, apps/site/assets/ts/helpers/media-breakpoints.ts, cypress/integration/global_navigation.spec.js
**Asana Ticket:** [Add "veil"/modal cover when search is open](https://app.asana.com/0/555089885850811/1201764117511338/f)
When the viewport is "tablet-sized" (I used the `lg` breakpoint for this), focusing the nav search bar will show the modal veil and prevent scrolling.
=> Show veil when focusing header search on <=tablet widths

apps/site/assets/ts/app/global-navigation.ts
**Asana Ticket:** [Remove flashing when clicking T logo](https://app.asana.com/0/555089885850811/1201764117487461/f)
This should fix a bunch of issues on the homepage when the mobile menu
is open, including:
- menu popping in when the T logo is clicked twice
- theme flickering on mobile Chrome and Safari
- modal veil remaining open
=> Call `closeAllMenus` when clicking T logo

apps/site/lib/site_web/router.ex, apps/site/test/site_web/router_test.exs
No ticket.
Adds the ability to activate a feature flag via URL. This was added with the intent of sharing flagged features with stakeholders in an easier manner. Maybe it'll help! 🙂
Deployed on dev-blue for the time being.
Some open questions...
* Technically this sets a cookie that expires after a month (which is exactly what the "enable" button does). So you can activate it by navigating to the appropriate URL with query parameter. But if you subsequently go to the URL without the query parameter, the feature is still activated! So how problematic is that?
* Should this support activating more than one feature at once?
* Maybe the function belongs in `SiteWeb.Plugs.Cookies`
=> feat: activate feature flag via URL

apps/site/assets/css/export-headerfooter.scss, apps/site/assets/export-headerfooter.js, apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/webpack.config.export-headerfooter.js, apps/site/lib/mix/tasks/header_footer.ex
**Asana Tickets:** 
- [Embed extracted CSS and JS into header and footer ](https://app.asana.com/0/385363666817452/1201237493995166/f)
- [Minify CSS and JS output](https://app.asana.com/0/0/1201540410191367/f)
- [Separate HTML tags into multiple files](https://app.asana.com/0/0/1201540410191368/f)
Uses a custom Webpack configuration to generate and copy the necessary files for duplicating MBTA.com's header and footer. Some custom Elixir code is used to scrape MBTA.com, parse the header and footer, add/rewrite a few link attributes, and copy that into new files. It's all zipped together when running the new mix task, `mix export.header_footer`.
The output will all be copied to https://github.com/mbta/dotcomchrome (e.g. there's no automated process for that part).
There's some more …
=> feat: Add mix task to output the header and footer

apps/site/lib/site_web/templates/layout/_desktop_menu_more.html.eex, apps/site/lib/site_web/templates/static_page/about.html.eex, apps/site/lib/site_web/views/layout_view.ex
**Asana Ticket:** [replace GLT page with new Capital Transformation page in header & footer navigation](https://app.asana.com/0/385363666817452/1201782887147816/f)
swapped out Green Line Transformation page references with Capital Transformation page link.
=> feat: replace Green Line Transformation links with Capital Transformation link

apps/site/assets/css/_header.scss, apps/site/assets/css/_mixins.scss, apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/ts/app/global-navigation.ts, apps/site/assets/webpack.config.base.js, apps/site/lib/site_web/templates/layout/app.html.eex
**Asana Ticket:** [Update button toggle color to default after it's been pressed](https://app.asana.com/0/555089885850811/1201764117487423/f)
This PR:
- Adds `focus-visible` to our dependencies (so that we can use `:focus-visible` in Safari. WebKit has recently merged support for the selector but it's still not widely available).
- Configures webpack to copy `focus-visible.min.js` to our output directory
- Conditionally loads the dependency based on whether or not the browser supports `:focus-visible`
- Updates the styles for the header menu toggle buttons to use `:focus-visible` and use `$brand-secondary` as the border color (matching the accordion buttons)
Let me know if the webpack configuration and load strategy makes sense :)
I've tested this locally on Firefox, Safari (desktop), and …
=> Button focus state

apps/site/assets/ts/schedule/components/line-diagram/line-diagram-helpers.ts, apps/site/lib/green_line.ex, apps/site/lib/site_web/controllers/schedule/line/diagram_helpers.ex, apps/site/test/green_line_test.exs, apps/site/test/site_web/controllers/schedule/line/diagram_helpers_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs
No ticket, but this is a short-term fix to accommodate the upcoming extra Green-E stops by extending the end of the consolidated Green line diagram.
See it on dev-blue or run it locally against the api-dev-blue API to see it with the upcoming GLX stops to open next month.
**Front-end change:**
* Adjusts the logic of determining whether a branched line diagram is branching inward or outward.
**Back-end changes** 
* Adjusts `SiteWeb.ScheduleController.Line.DiagramHelpers` to display the new stops, 
* adjusts `GreenLine` to stop hardcoding the termini stops.
* This is probably an expensive way to calculate it so frequently and I might change approaches
=> Line Diagram hotfix for GLX

apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/trip_plan/test/transfer_test.exs
No ticket, but the new rating's schedules and data are up on dev-green so I figured I'd proactively see which tests would fail this time, and try to fix them!
(_Why is this needed?_ Some of our unit tests tend to fail after a rating change because the underlying data returned changes. Often the change is inconsequential, but it makes a test fail anyway because the test itself is usually seeking an overly specific set of IDs, or other specific order of data.)
So this PR has two test adjustments, described in more detail in the commit messages for each.
=> chore: Adjust tests for Summer 2022 rating

apps/site/assets/css/_header.scss
**Asana Ticket:** [Update sticky behavior when pulling down menu](https://app.asana.com/0/555089885850811/1201764117487427/f)
This prevents overscroll effects in the mobile menu. WebKit has only recently merged support for this property, so the behavior is still observable on macOS and iOS Safari, but once broader support for the property rolls out this should solve the issue.
=> Prevent overscroll in mobile menu 

apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/ts/app/global-navigation.ts, apps/site/assets/webpack.config.base.js, apps/site/lib/site_web/templates/layout/app.html.eex
**Asana Ticket:** [Update scroll behavior when opening accordion](https://app.asana.com/0/555089885850811/1201764117487465/f)
This PR implements a scroll-to-top behavior when the accordions in the mobile nav menu are expanded. This functionality is not enabled if the user has indicated that they prefer reduced motion.
WebKit has only very, very recently gotten support for smooth scrolling behavior in the various `scroll*` functions, and as far as I can tell there are no WebKit-based browser releases that support it yet. Thus, I've added a polyfill for the smooth scrolling functionality, and taken an approach similar to #1190 for feature detection and lazy-loading.
=> Scroll menu accordion to top

apps/site/lib/site_web/templates/layout/app.html.eex
**Asana Ticket:** [Update nav bar background color](https://app.asana.com/0/555089885850811/1201764117487457/f)
The page currently starts out using the darker blue as the theme color, which looks out-of-sync on initial page load on iOS Safari
=> Update theme color to use lighter blue on initial page load

apps/site/lib/site_web/controllers/trip_plan_controller.ex
**Asana Ticket:** [Fix: Trip Planner returns error on Union Square - NEU plan](https://app.asana.com/0/555089885850811/1201500059383446/f)
Change allow the trip planner to suggest the returned OTP itinerary for an MBTA Bus even if a specific leg of a trip is not present via the api to fetch additional details for things such as shuttle buses. 
Details not fully present so from the detailed view it's not indicated fully that this is a shuttle bus, but the icon indicates that it is a shuttle bus.
=> fix trip planner returning 500 when suggested itinerary route is not queryable via api

apps/site/assets/css/_global-navigation.scss
**Asana Ticket:** [Reduce spacing between lists of links and top of menus](https://app.asana.com/0/555089885850811/1201764117511355/f)
This more closely matches the amount of space present in the mocks
=> Reduce top spacing in desktop menu dropdown

apps/site/assets/css/_header.scss
**Asana Ticket:** [Update T logo to stay in the same place](https://app.asana.com/0/555089885850811/1201764117487441/f)
Specifically on the large tablet breakpoint, the text changing from `Menu` to `Close` caused the menu button to expand ever so slightly, causing visual shifting of the MBTA logo. To fix this, I've set a static width and centered the text, and there appears to be no more visual shifting when expanding the menu.
=> Fix shifting logo on large tablet breakpoint

apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/plugs/glx_now_open.ex, apps/site/test/site_web/plugs/glx_now_open_test.exs
**Asana Ticket:** [Store station opening dates and check age](https://app.asana.com/0/555089885850811/1201708898492590/f)
Added plug to set an assign within conn if the current date after the set opening date for the glx expansion and not more than 3 months after that date.
=> Plug to check if within range of glx opening date

apps/site/lib/site/body_tag.ex
Adding this so we can start to collect data on how many requests are from user agents without JavaScript enabled.
Pursued in support of [Check existing logging or add logging to trace source of Maps Static API requests](https://app.asana.com/0/385363666817452/1201938268964502/f)
=> Add logging for when no-js class is added

apps/location_service/lib/result.ex, apps/location_service/lib/suggestion.ex, apps/location_service/lib/utils.ex, apps/location_service/lib/wrappers.ex, apps/location_service/test/utils_test.exs, apps/location_service/test/wrappers_test.exs, apps/site/assets/js/algolia-result.js, apps/site/assets/ts/helpers/__tests__/text-test.ts, apps/site/assets/ts/helpers/text.ts, apps/site/test/site_web/controllers/places_controller_test.exs
**Asana Ticket:** [Rework the search result text highlighting to work with both Google Maps and AWS](https://app.asana.com/0/555089885850811/1201936731451754/f)
This PR implements the search result highlighting in a backend-agnostic manner. The basic approach is:
- For Google suggestion results, simply take the `matched_substrings` field and re-encode it to our internal structure
- For AWS suggestion results, apply some simple regex-based logic to determine which parts of the address should be highlighted (there are examples of how the logic works in the associated text)
- On the frontend, take this information from the backend and build a string with `<em>` tags inserted at the proper locations.
The AWS highlighting logic is not 1:1 with the highlighting information that Google applies, …
=> Rework the search result text highlighting to work with both Google Maps and AWS

apps/site/assets/ts/components/Modal.tsx, apps/site/assets/ts/components/__tests__/__snapshots__/ModalTest.tsx.snap
**Asana Ticket:** [Can't scroll in Schedule Finder](https://app.asana.com/0/555089885850811/1201973783756879/f)
The linked ticket has a video showing reproduction steps of a specific case, but more generally what is happening here is that turbolinks doesn't touch the root `html` element between loads, thus the `modal-open` class is sticking around. This PR moves the `modal-open` class to the `body` element, which turbolinks will properly merge between loads. As far as I can tell this should be safe to do, but let me know if I've missed anything.
This also adds a `turbolinks:before-visit` event listener which closes the modal. This is to fix a bug I noticed where going back to the previous page would open 2 modals.
=> Fix schedule finder navigation scroll issue

apps/site/assets/css/_glx-open.scss, apps/site/assets/ts/components/GlxOpen.tsx, apps/site/assets/ts/schedule/components/line-diagram/StopCard.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/StopListWithBranchesTest.tsx.snap
**Asana Ticket:** [GLX "NOW OPEN" in line diagrams](https://app.asana.com/0/555089885850811/1201915536508565/f)
add glx now open component to show in line diagrams.
=> add glx now open messaging to line diagrams

apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/controllers/schedule/timetable_controller.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
A couple tweaks to avoid known sources of server errors in user flows. These two problems were found in Sentry months ago and keep coming up, usually around times when certain routes have shuttles. Investigating/debugging the underlying data is beyond the scope of fixing these errors.
**Asana Ticket:** [no function clause matching in SiteWeb.CustomerSupportController.submit/2](https://app.asana.com/0/0/1200334203657800)
Turns out we thought we had fixed this in https://github.com/mbta/dotcom/pull/969 but had left out one case.
* Function clause added to the submit function to handle cases where the second argument does not include the "support" key.
**Asana Ticket:** [function nil.id/0 is undefined](https://app.asana.com/0/0/1200951746296209)
This seems related to …
=> Misc. bugfixes

apps/site/assets/ts/components/GlxOpen.tsx
Updated glx now open station list checking to include 0 (first) index.
=> bugfix: correctly allow matching of 0 index in glx open stations

apps/site/lib/site_web/plugs/glx_now_open.ex, apps/site/test/green_line_test.exs, apps/site/test/site_web/controllers/schedule/green_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/excluded_stops_test.exs, apps/site/test/site_web/plugs/glx_now_open_test.exs, apps/util/lib/util.ex
I noticed we were checking the date against `#DateTime<2022-03-21 00:55:00-04:00 EDT America/New_York>`, which isn't quite right.
Upon investigation I realized that `Util.to_local_time()` assumes an input `NaiveDateTime` is in UTC. 🤷🏼‍♀️ 
To fix I swapped it out for `Util.convert_using_timezone()` to get the right `DateTime`.
=> fix: Check GLX opening in corrected TZ

apps/site/assets/css/_glx-open.scss, apps/site/assets/css/_stop-page.scss, apps/site/assets/ts/components/Alerts.tsx, apps/site/assets/ts/components/GlxOpen.tsx, apps/site/assets/ts/hooks/useIsGlxOpen.ts, apps/site/assets/ts/schedule/components/direction/GreenLineMenu.tsx, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageTest.tsx.snap, apps/site/assets/ts/stop/components/Header.tsx, apps/site/assets/ts/stop/components/StopPage.tsx, apps/site/lib/site_web/plugs/glx_now_open.ex, apps/site/lib/site_web/templates/layout/app.html.eex, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs
**Asana Ticket:** [Remainder of GLX "NOW OPEN" treatment for /stops pages](https://app.asana.com/0/555089885850811/1201984803295268/f)
This was fairly involved! I attempted to organize this info smaller, logically self-contained commits.
- To be able to render the desired text, I had to explicitly add the date as well as the new stop IDs to be assigned in the plug.
- Extracted a hook from the existing React component file to be able to reuse the DOM-querying logic in other places
- Added the desired coloring to the stop page's stop name and station information tab
- Added the desired text under Station Information
Also: Updated some failing unit tests
TODO: I still need to add a unit test to test the new hook.
=> Remainder of GLX "NOW OPEN" treatment for /stops pages

apps/site/assets/ts/hooks/__tests__/useIsGlxOpenTest.tsx, apps/site/assets/ts/hooks/useIsGlxOpen.ts
Also adds a small refactor to the hook to avoid returning an opening date when the station will not newly open.
( Leftover task from #1243 )
=> test: add unit test for useIsGlxOpen hook

apps/site/assets/ts/components/StopCard.tsx, apps/site/assets/ts/helpers/__tests__/routes-test.ts, apps/site/assets/ts/helpers/routes.ts, apps/site/assets/ts/schedule/components/line-diagram/StopFeatures.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap, apps/site/assets/ts/stop/components/Header.tsx, apps/site/assets/ts/stop/components/StopAccessibilityIcon.tsx, apps/site/assets/ts/stop/components/StopCard.tsx
**Asana Ticket:** [Show accessibility icon for all bus stops](https://app.asana.com/0/385363666817452/1201894234147725/f)
This PR updates the gating logic for the accessibility icons to always render for bus routes. The following locations have been updated:
- Line Diagram
- Stop pages (both the header and the nearby transfers)
- Transit Near Me
I decided to tackle this on the front end since I figured it was more of a rendering concern, and didn't want to muck with any of the accessibility data we return from the back end.
I did some light testing, and don't believe that these changes should have any unexpected side effects, but let me know if there is a cleaner approach for any of these.
=> Always render acccessibility icon for bus stops

apps/site/assets/ts/schedule/components/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap, apps/site/assets/ts/schedule/components/direction/BusMenu.tsx, apps/site/assets/ts/schedule/components/direction/GreenLineMenu.tsx, apps/site/assets/ts/schedule/components/direction/ScheduleDirectionMenu.tsx, apps/site/assets/ts/schedule/components/direction/__tests__/__snapshots__/BusMenuTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/StopCard.tsx, apps/site/assets/ts/schedule/components/line-diagram/StopPredictions.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/StopListWithBranchesTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/StopPredictionsTest.tsx.snap
**Asana Ticket:** [Prevent stop name translation on line diagrams](https://app.asana.com/0/555089885850811/1201938268964507/f)
Don't translate stop names on line diagram pages, including direction selector
=> Prevent stop name translation on line diagrams

apps/site/lib/site_web/controllers/schedule/finder_api.ex
Sometimes, for certain unusual route pattern IDs on added trips, we can't actually find the route pattern! In that case we should return nil rather than trying to retrieve the (nonexistent) route pattern's route ID.
**Asana Ticket:** [Schedules Finder API | Elixir.BadMapError: expected a map, got: nil](https://app.asana.com/0/385363666817452/1202045696470901/f)
See ticket for the Sentry bug report.
=> fix: Tighter logic for fetching route id

apps/site/assets/js/trip-planner-location-controls.js
**Asana Ticket:** [Selecting custom locations in trip planner should populate map](https://app.asana.com/0/385363666817452/1202050563424979/f)
This was missed when previously deleting this method and was silently breaking selecting locations in the trip planner
=> Remove `resetSessionToken` call

apps/site/assets/ts/schedule/components/__tests__/__snapshots__/ScheduleFinderTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/OriginModalContent.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleFinderForm.tsx, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/__snapshots__/ScheduleFinderFormTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/__snapshots__/ScheduleFinderModalTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/__snapshots__/ScheduleModalContentTest.tsx.snap, apps/site/lib/site_web/templates/schedule/_line_header.html.eex
**Asana Ticket:** [Prevent stop name translation in Schedule Finder](https://app.asana.com/0/555089885850811/1201984535304524/f)
Add notranslate tag to schedule finder dropdown menu, schedule modal, and stop name header.
=> Prevent stop name translation in Schedule Finder

apps/site/assets/css/_header.scss, apps/site/assets/js/google-translate.js, apps/site/assets/ts/app/global-navigation.ts
**Asana Ticket:** [Menu button inaccessible](https://app.asana.com/0/385363666817452/1202041767361060/f)
This PR adds some JS logic to ensure that the header elements remain positioned on the page.
Things that are positioned:
- The desktop menu dropdowns
- The modal veil
- The tablet / mobile nav content
The mobile nav search doesn't need to be positioned.
The positioning logic is triggered on page load, when the viewport is resized, and when the translation language changes.
=> Position header elements when resizing viewport or translating

apps/cms/lib/page/event_agenda.ex, apps/cms/priv/event_agenda.json, apps/cms/test/page/event_agenda_test.exs, apps/site/lib/site_web/templates/event/show.html.eex, apps/site/lib/site_web/views/event_view.ex, apps/site/test/site_web/views/event_view_test.exs
**Asana Ticket:** [🐞 elixir isn't checking published status of an agenda that is displayed on an event](https://app.asana.com/0/553506286097126/1201886553089889/f)
If an agenda is not published, don't show it unless `?preview` is in query params.
Adds boolean prop for `published` which is checked on-the-fly when rendering the agenda section of the event show template.
---
=> only show hidden agendas if preview is requested

apps/site/assets/css/_icons.scss
**Asana Ticket:** [CR zone badge cut off in suggestions](https://app.asana.com/0/0/1201994835377135/f)
On Chrome and Firefox on Windows in particular, the commuter rail zone "pill" was getting cut off vertically in different situations. Switching to `inline-block` alleviates this without otherwise affecting layout in my testing.
=> Fix rendering issues with CR zones

apps/site/lib/site/trip_plan/map.ex, apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/templates/trip_plan/index.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site/trip_plan/map_test.exs, apps/site/test/site_web/controllers/trip_plan_controller_test.exs, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [Remove Maps Static API integration on Trip Planner](https://app.asana.com/0/555089885850811/1202072976283731/f)
Remove references to google static map within different views of trip planner and code that sets the url within the page(s).
=> Remove Maps Static API integration on Trip Planner

apps/site/lib/site_web/templates/page/_important_links.html.eex
**Asana Ticket:** [Replace "Transit App" link with "Parking" on homepage](https://app.asana.com/0/385363666817452/1202097035977692/f)
Might want to swap out the icon for a monochrome version later:
=> swap Transit App link for Parking page

apps/site/assets/.eslintrc.js, apps/site/assets/css/_header.scss, apps/site/assets/css/export-headerfooter.scss, apps/site/assets/export-headerfooter.js, apps/site/assets/js/trip-planner-location-controls.js, apps/site/assets/ts/app/global-navigation.ts, apps/site/assets/ts/schedule/components/ScheduleDirection.tsx, apps/site/assets/ts/schedule/components/ScheduleLoader.tsx, apps/site/assets/webpack.config.export-headerfooter.js, apps/site/lib/mix/tasks/header_footer.ex
This PR builds upon the work from https://github.com/mbta/dotcom/pull/1170, tweaking it a bit to be compatible with our newly designed navigation.
The output of the revised `mix export.header_footer` task is currently in a PR over at the dotcomchrome repo: https://github.com/mbta/dotcomchrome/pull/5 - and there's details in _that_ repo's README on how to preview the output in the browser.
**Asana Ticket:** [Update dotcomchrome repo with new desktop/mobile menu output](https://app.asana.com/0/385363666817452/1202012916713299/f)
* Updates the header and footer with the latest content
* Adds the mobile menu to the extracted header, and makes it work
The first two commits are small adjustments to our current navigation implementation that I found that I needed to do in order to get the …
=> Export header and footer again

apps/site/assets/js/algolia-autocomplete.js
When navigating from a 'parent' page for a type of service:
These search boxes are present within the page and an embedded algolia search object is generated for each search input. When a user navigates to a more specific pages, say for the red line only:
The from, to, and middle search are no longer present within the dom, but the objects are still loaded in memory. So when the app fires the resize event (sometimes happens on page load, especially on mobile) it kicks off the `onOpen` call which attempts to re-query the dom for the element group which it has already been attached to, but since the 3 fields are no longer 'physically' present, the call returns null and destructuring null throws an error.
=> Use pre-cached object reference for checking offset

apps/site/assets/ts/helpers/icon.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LiveCrowdingIconTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/VehicleIconsTest.tsx.snap
**Asana Ticket:** [HTML displaying in title of vehicle icon](https://app.asana.com/0/385363666817452/1202074066973267/f)
removed title text from icons so that only the custom tooltips are displayed.
=> HTML displaying in title of vehicle icon

apps/site/assets/js/trip-planner-location-controls.js
Auto complete result no longer populates a 'description' field for 'locations' type of results. Change the input to be populated w/ returned full address instead of leaving blank/null.
=> fix: blank to/from trip planner. use address instead of description for trip planner controls 

apps/location_service/config/config.exs, apps/location_service/config/dev.exs, apps/location_service/config/prod.exs, apps/location_service/config/test.exs, apps/location_service/lib/aws_location/request.ex, apps/location_service/test/aws_location/request_test.exs
Requests to AWS Location Service are made to a specific place index. This PR stops hardcoding those index names (`dotcom-dev-here` and `dotcom-dev-esri`). 
It does assume that we'll keep naming place indexes in a "`prefix`-esri" and  "`prefix`-here" format. We already have `dotcom-prod-here` and `dotcom-prod-esri` set up with intended use for our production website. And we likely won't be making more place indexes anyway....
=> Make AWS Location Service place index configurable

apps/site/assets/js/app.js, apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/webpack.config.prod.js, apps/site/config/config.exs, apps/site/config/prod.exs, apps/site/lib/site_web/templates/layout/app.html.eex
This is a reworked version of https://github.com/mbta/dotcom/pull/1272
This follows closely with other applications under the CTD umbrella - for example https://github.com/mbta/signs_ui/pull/525
* includes support for multiple environments - this will be an environment variable in our deployed applications set to `prod`, `dev`, `dev-green` or `dev-blue`
* adds a new tag, `dotcom.application` that will let us filter Sentry issues by backend vs frontend
* removed `@sentry/tracing` because I don't think our Sentry plan supports transactions anyway
=> feat: add Sentry support to the front-end

apps/site/assets/css/_project.scss, apps/site/lib/site_web/controllers/cms_controller.ex, apps/site/lib/site_web/templates/alert/_item.html.eex, apps/site/lib/site_web/templates/alert/group.html.eex, apps/site/lib/site_web/templates/cms/page/_alerts.html.eex, apps/site/lib/site_web/templates/cms/page/_project.html.eex, apps/site/lib/site_web/views/page_content_view.ex, apps/site/test/site_web/views/page_content_view_test.exs, apps/site/test/site_web/views/project_contact_test.exs
**Asana Ticket:** [Display alerts list on project page](https://app.asana.com/0/385363666817452/1200671244979944/f)
**NOTE**: This also closes [this ticket](https://app.asana.com/0/385363666817452/1200311487753031/f)
Some changes from the design:
- The design calls for this section to be below the header image on the page. However, the header image comes back to us as a "section" of the content we get from the CMS. We could probably do some smarts to properly split the image from the rest of the sections and inject this section, but I think it'll be relatively tricky. Steve gave the go-ahead for keeping it at the top for now, and we can circle back to this later if need be.
- I changed the "Show / Hide Alerts" text to be a static "Details". The switch between "Show Alerts" and "Hide …
=> Add alerts to project pages

apps/site/assets/css/_project.scss, apps/site/lib/site_web/templates/cms/page/_project.html.eex, apps/site/lib/site_web/views/page_content_view.ex, apps/site/test/site_web/views/page_content_view_test.exs
This injects the alerts section after the first `<figure>` tag present in the `body` of a project page. If a `<figure>` tag is not the first tag, the alerts section is injected before the first element.
I believe this should be (reasonably) robust if for some reason the `<figure>` tag is missing, but let me know if I'm missing anything.
=> Inject alerts section after first image

apps/site/assets/css/_schedule-page-line-diagram.scss
**Asana Ticket:** [Part of alert icon is blue on line diagrams](https://app.asana.com/0/385363666817452/1202341293911737/f)
Make ! on alert icon one consistent color.
=> Fix part of alert icon is blue on line diagrams

apps/site/lib/site_web/templates/alert/_item.html.eex
This prevents a page rendering error when the assign isn't present (e.g.
for trip planner alerts)
=> Access :hide_url via assigns map

apps/site/lib/site_web/views/page_content_view.ex, apps/site/test/site_web/views/page_content_view_test.exs
**Asana Ticket:** [Linked alerts not displaying on project pages](https://app.asana.com/0/555089885850811/1202368368463960/f)
- Ignore casing in paths
- No longer ignore URLs that don't have `/project` in them. We sometimes
create "vanity URLs" which link to project pages, so this accounts for
them
=> Change project alerts related alerts logic

apps/site/assets/css/_homepage.scss, apps/site/lib/site_web/templates/page/_user_guides.html.eex, apps/site/lib/site_web/templates/page/index.html.eex
**Asana Ticket:** ["MBTA User Guides" section](https://app.asana.com/0/555089885850811/1202075661172622/f)
There's probably some unification work that can be done with the "What's Happening" sections, but those need different enough logic to render them that I didn't do it here.
**NOTE**: The Abstract designs linked in the ticket have slightly different properties than the existing "What's Happening" section. For the most part I've opted to match Abstract, so there are slight differences between how these sections look.
=> Add user guides section to homepage

apps/location_service/lib/utils.ex, apps/location_service/test/utils_test.exs
Make sure to escape any necessary characters in the text when creating the regex expression. From Sentry reports this was most often text containing parentheses or brackets.
Added a test using a search term from one of our error reports.
**Asana Ticket:** [LocationService | Elixir.MatchError: no match of right hand side value: {:error, {'missing )', 17}}](https://app.asana.com/0/385363666817452/1202185936565802/f)
=> fix(LocationService.Utils): compile with unmatched parenthesis

apps/site/assets/css/_trip-plan-form.scss, apps/site/assets/css/_trip-plan-widget.scss, apps/site/lib/site_web/templates/page/_tabbed_nav.html.eex, apps/site/lib/site_web/templates/trip_compare/_to_from_inputs.html.eex, apps/site/lib/site_web/templates/trip_plan/_to_from_inputs.html.eex
**Asana Ticket:** [Trip Planner design updates](https://app.asana.com/0/555089885850811/1202384504606984/f)
I ended up reworking the Trip Planner widget to use CSS grid for its layout rather than Flexbox.  It simplifies a lot!
I considered adjusting the layout using a container query (based on the width of the widget container) rather than a media query (based on size of the window), but we only use the horizontal layout on the homepage - so this code only switches the layout on the homepage and not anywhere else the widget is applied.
=> Trip Planner design updates

apps/site/assets/css/_datepicker.scss
**Asana Ticket:** [Trip Planner | Datepicker buttons misaligned](https://app.asana.com/0/385363666817452/1202407129112905/f)
I have no idea why the `pull-right` and `pull-left` CSS classes (very common Bootstrap utility classes) were not doing their job now....
Before:
Updated:
=> fix: lay out datepicker buttons as expected

apps/site/lib/site_web/templates/layout/_new_nav_desktop.html.eex
**Asana Ticket:** [Replace "tabpanel" role with disclosure pattern](https://app.asana.com/0/385363666817452/1202299919599010/f)
Turns out we pretty much had the disclosure pattern established!
The one thing I didn't do was replace the links with buttons - I really wanted to keep them as links with `href` attributes because these are what's used for navigation when a user doesn't have JavaScript enabled. So for those I added `role="button"`, which I think should suffice.
=> a11y: remove inappropriate tab roles

apps/site/assets/css/_homepage.scss
**Asana Ticket:** [Upcoming Public Meetings section cropped](https://app.asana.com/0/555089885850811/1202522864391322/f)
Added overflow: auto styling so that event info doesn't crop.
Note: pasted text using dev tools to increase characters in event description
=> Upcoming Public Meetings section cropped

apps/site/lib/site_web/templates/mode/_grid_button.html.eex, apps/site/lib/site_web/templates/mode/_grid_button_condensed.html.eex, apps/site/lib/site_web/templates/page/_find_a_location.html.eex, apps/site/lib/site_web/templates/page/_tabbed_nav.html.eex, apps/site/lib/site_web/templates/trip_compare/_to_from_inputs.html.eex, apps/site/lib/site_web/templates/trip_plan/_to_from_inputs.html.eex
**Asana Ticket:** [Prevent screen readers from reading multiple elements](https://app.asana.com/0/555089885850811/1202570650180350/f)
Added aria-hidden="true" label to following sections to prevent them from being read.
=> Prevent screen readers from reading multiple elements

apps/site/lib/site_web/templates/layout/_new_nav_contact_numbers.html.eex, apps/site/lib/site_web/templates/layout/_new_nav_desktop.html.eex, apps/site/lib/site_web/templates/layout/_new_nav_popular_fares.html.eex
**Asana Ticket:** [Make the desktop column headings into heading elements ](https://app.asana.com/0/385363666817452/1202308344478711/f)
changed divs into h3 elements for desktop nav section headers.
=> Use heading elements instead of div for desktop nav sections

apps/site/assets/js/sticky-tooltip.js, apps/site/lib/site/components/icons/svg_icon/component.html.eex
**Asana Ticket:** [Recently Visited Routes alert tooltip issues](https://app.asana.com/0/555089885850811/1202570650180355/f)
=> Homepage Alert Icon fixes

apps/site/lib/site_web/templates/page/_whats_happening.html.eex
**Asana Ticket:** [Section header should be hidden when there's no content available](https://app.asana.com/0/555089885850811/1202532801799502/f)
Hide what's happening header if no content. Note there is already a check for events section
`<%= unless Enum.empty?(@event_teasers) do %>`
=> Section header should be hidden when there's no content available

apps/site/lib/site_web/controllers/stop/curated_street_view.ex
**Asana Ticket:** [GTFS | update street view for Brockton Station](https://app.asana.com/0/385363666817452/1202664751368463/f)
Here's where the new link goes, which I felt was the closest I could get to an accessible station entrance:
=> fix: add custom Street View link for Brockton

apps/site/assets/ts/app/global-navigation.ts
**Asana Ticket:** [Header | Veil does not disappear after completing search](https://app.asana.com/0/385363666817452/1202668336235923/f)
Adds an event listener to the dropdown's `autocomplete:selected` event and runs `closeAllMenus()`, which might be kinda overkill given the only thing left open was the veil, but this striked me as more readable and clear.
=> fix(nav): remove veil after clicking search result

apps/site/lib/site_web/templates/event/_event_teaser.html.eex, apps/site/lib/site_web/templates/page/_homepage-events.html.eex
**Asana Ticket:** [Homepage | Show six events at large breakpoints](https://app.asana.com/0/385363666817452/1202641648100462/f)
Show next six events. Updated event ended check to check date rather than just the day.
=> Homepage | Show six events at large breakpoints

apps/site/assets/js/algolia-autocomplete-with-geo.js, apps/site/assets/js/algolia-autocomplete.js, apps/site/assets/js/algolia-embedded-search.js, apps/site/assets/js/algolia-homepage-search.js, apps/site/assets/js/algolia-result.js
**Asana Ticket:** [Update "Use my location" label](https://app.asana.com/0/385363666817452/1202299919599024/f)
Can't get screenshots, but this updates the "Use my location" text in the header search and on schedule hubs (e.g. `/schedules`) to be "Use my location to find transit near me". Any other locations (including the trip planner widget on the schedule hubs) retain the original text.
To do this, I've parameterized the templates we use for the results.
=> Update "Use my location" label in header search and schedule hubs

apps/cms/lib/api/static.ex, apps/cms/lib/repo.ex, apps/cms/priv/cms/schedule-pdfs.json, apps/cms/test/repo_test.exs, apps/site/lib/site/route_pdfs.ex
**Asana Ticket:** [Elixir integration](https://app.asana.com/0/385363666817452/1202623240995537/f)
Mostly opening this on behalf of @thecristen since all of the actual work has been done by her :) I just confirmed things worked locally.
One question that came up: From the ticket, it sounds like we are transtioning bus routes fully to this new endpoint ~soon, and other modes later on. The code is currently hitting _both_ endpoints and combining the resulting lists. @amaisano Is there any worry that we'll run into a situation where we have PDFs coming from both endpoints for modes we don't want to support yet? Or can we make the assumption that if the schedules are on the prod CMS we do indeed want to show them?
Thanks!
=> Fetch Schedule PDFs from new endpoint

apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
**Asana Ticket:** [Limit vehicle number input to 8 digits](https://app.asana.com/0/385363666817452/1201613685853937/f)
This also maintains the existing (but perhaps unintended?) behavior of successfully validating empty strings in the `vehicle` input
=> Validate that a vehicle number is between 1 and 8 digits

apps/routes/lib/parser.ex, apps/routes/test/parser_test.exs, apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/test/green_line_test.exs, apps/site/test/site_web/controllers/schedule/finder_api_test.exs, apps/site/test/site_web/controllers/schedule/green_test.exs, apps/site/test/site_web/controllers/schedule/line/diagram_helpers_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/excluded_stops_test.exs, apps/stops/test/repo_test.exs, apps/stops/test/route_stops_test.exs, apps/v3_api/test/routes_test.exs
No ticket, fixes a [failing test in CI](https://github.com/mbta/dotcom/runs/7865831703?check_suite_focus=true).
The train isn't running past Government Center starting in a few days.
---
=> fix(test): Update E-line test to match suspension data

apps/fares/lib/fare_info.ex, apps/site/lib/site_web/templates/trip_compare/_fare_calculator.html.eex, apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex
**Asana Ticket:** [Calculate some CR legs as $0 during OL shutdown](https://app.asana.com/0/555089885850811/1202802897881991/f)
If leg in itinerary is 1A,1, or 2 don't charge for that section.
=> Calculate some CR legs as $0 during OL shutdown

apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/green_line_test.exs, apps/site/test/site_web/controllers/schedule/finder_api_test.exs, apps/site/test/site_web/controllers/schedule/green_test.exs, apps/site/test/site_web/controllers/schedule/line/diagram_helpers_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/excluded_stops_test.exs, apps/site/test/site_web/views/schedule_view_test.exs, apps/stops/test/nearby_test.exs, apps/stops/test/repo_test.exs, apps/stops/test/route_stops_test.exs
No ticket, fixes currently failing tests
- fix: Properly handle different valid input types
- fix(test): Improve tests to match descriptions
- fix(test): Fix test assertions for Green Line suspension data
- fix(test): Fix more test data
~~Note: I left that last commit separate because those failures seem more suspicious to me. I'm going to keep looking into them as I work through the GL diagram issues.~~
Given that the line diagram is working better with the latest GTFS data, I'm actually probably less worried about those failures than I was at first glance.
---
=> fix(test): Fix test assertions for Green Line suspension data

apps/site/test/site_web/views/trip_plan_view_test.exs, apps/trip_plan/lib/trip_plan/transfer.ex, apps/trip_plan/test/transfer_test.exs
**Asana Ticket:** [Investigate making OL/GL shuttle to subway transfer not free](https://app.asana.com/0/555089885850811/1202824647488182)
Shuttles have free fares, but if a rider then transfers to a subway or
bus line they have to pay the normal fare for that route.
---
=> feat: Transfers from a shuttle should not be free

apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/views/schedule_view_test.exs
**Asana Ticket:** [Apply schedule PDF title logic to files from old and new endpoint](https://app.asana.com/0/385363666817452/1202824647488158/f)
Previously, we made a change to use the `name` field on the PDF data to disambiguate the test data that was uploaded as part of the new schedule process changes. Now that these are ironed out, we can revert that logic
=> Don't use PDF name to render PDF link

apps/fares/lib/fare_info.ex, apps/fares/lib/fares.ex, apps/fares/lib/format.ex, apps/fares/test/fares_test.exs, apps/fares/test/format_test.exs, apps/site/lib/site/content_rewriters/liquid_objects/fare.ex, apps/site/test/site/content_rewriters/liquid_objects/fare_test.exs
**Asana Ticket:** [Add East Boston ferry fare](https://app.asana.com/0/385363666817452/1202953235045313/f)
Adds the one-way fare of $2.40, payable via mTicket, paper ticket, or cash, for the upcoming East Boston ferry service between the `Boat-Long` and `Boat-Lewis` stops. The tests updated here confirm the new ferry fare ranges of $2.40 - $9.75 and $1.10 - $4.85 (reduced).
=> Add East Boston ferry fare

apps/fares/lib/fare_info.ex, apps/fares/test/format_test.exs
**Asana Ticket:** [Remove "or Paper Ferry Ticket" from East Boston Ferry card](https://app.asana.com/0/385363666817452/1202964593147464/f)
Unlike the other ferries, the East Boston ferry fare cannot be purchased with cash nor with a paper ferry ticket. mTicket is the only way to pay the fare.
---
=> feat: Remove paper ticket option for East Boston Ferry

apps/site/assets/css/_link-block.scss, apps/site/assets/css/_transit-near-me.scss, apps/site/assets/ts/components/RouteCardHeader.tsx, apps/site/assets/ts/components/__tests__/__snapshots__/RouteCardHeaderTest.tsx.snap, apps/site/assets/ts/stop/__tests__/__snapshots__/DeparturesTest.tsx.snap, apps/site/assets/ts/stop/__tests__/__snapshots__/RouteCardTest.tsx.snap, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageTest.tsx.snap, apps/site/assets/ts/tnm/__tests__/__snapshots__/RouteCardTest.tsx.snap, apps/site/assets/ts/tnm/__tests__/__snapshots__/RoutesSidebarTest.tsx.snap
**Asana Ticket:** [Add clearer link to schedule page in Departures](https://app.asana.com/0/home/1201123880594717/1202908385566824)
**Follow Up Ticket:** [Design Fixes](https://app.asana.com/0/555089885850811/1202967204475095/f)
Added the text - View Schedule to the card header, and removed the upper casing from the card header as well.
---
=> feat(RouteCardHeader): Add copy that makes the card header look clickable

apps/site/assets/css/_homepage.scss
No ticket, this should resolve this error message that was failing some of our homepage accessibility tests:
```
Fix any of the following:\n  Element has insufficient color contrast of 3.67 (foreground color: #ffffff, background color: #7c878e, font size: 10.5pt (14px), font weight: bold). Expected contrast ratio of 4.5:1
```
---
=> a11y: increase color contrast for SL pill

apps/site/lib/site_web/controllers/schedule/line/diagram_helpers.ex, apps/site/test/site_web/controllers/schedule/green_test.exs, apps/site/test/site_web/controllers/schedule/line/diagram_helpers_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs
**Asana Ticket:** [Union Square displayed in middle of line diagram](https://app.asana.com/0/555089885850811/1203005769296541)
fix: Move Union Square to the end of the line diagram
---
=> fix: Move Union Square to the end of the line diagram

apps/site/assets/ts/schedule/components/ScheduleLoader.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/lib/site_web/controllers/schedule/line.ex, apps/site/test/site_web/controllers/schedule/line_test.exs
**Asana Ticket:** [Schedule Finder | Multi-Route Trips should show all possible origin stops ](https://app.asana.com/0/385363666817452/1201022904675406/f)
- Return all stops for all route patterns in schedule page data
- Make clicking "View schedule" set the Schedule Finder direction to match the map / line diagram (an existing bug :))
This is a lot lower lift than the initial PR, and works just about as well :)
=> Support viewing route variant stops in Schedule Finder

apps/site/assets/js/algolia-search.js, apps/site/assets/js/test/algolia-search_test.js
**Asana Ticket:** [All search inputs are generating faceted search requests that aren't necessary](https://app.asana.com/0/555089885850811/1203050684098647/f)
See Asana ticket for details.
We ultimately figured this change probably won't impact our bottom line anyway. But removing this here doesn't seem to adversely impact anything, so may as well clean things up?
=> remove extra faceted search queries

apps/site/lib/site_web/controllers/schedule/line_controller.ex
**Asana Ticket:** [501 and 505 do not display scheduled trips in Schedule Finder](https://app.asana.com/0/385363666817452/1203082825839704/f)
Group services with additional field of `valid_dates`. Currently up on green.
=> 501 and 505 do not display scheduled trips in Schedule Finder

.husky/pre-commit, apps/site/assets/package-lock.json, apps/site/assets/package.json, package.json
No ticket. This is proposed as an improvement to #1398. I found the prior implementation did not permit me to stage and commit certain lines of file changes - it would let me stage partial changes but ultimately commit the entire set of changes.
I found [`lint-staged`](https://github.com/okonet/lint-staged), which seems to be a more fully developed implementation of the same idea.
=> refactor: format files in pre-commit hook with `lint-staged`

apps/site/assets/ts/schedule/components/ScheduleLoader.tsx
Asana ticket: [Schedule | Investigate direction_id url parameter](https://app.asana.com/0/385363666817452/1200154423941953)
Fixes an existing bug. Steps to reproduce:
1. Go to a line page, e.g. https://www.mbta.com/schedules/1/line
2. See that it defaults to direction 0, showing "Nubian" as the first stop
3. Click "Change Direction"
4. See that direction 1 is specified in the URL query, and the page correctly shows direction 1, with "Massachusetts Ave @ Holyoke St" as the first stop
5. Refresh the page
**Expected behavior:**
The page loads based on the URL query, showing direction 1, with "Nubian" as the first stop.
**Observed behavior:**
The page displays direction 0, with "Massachusetts Ave @ Holyoke St" as the first stop.
I couldn't find an existing ticket for this issue, but please …
=> fix: Use the direction_id param on the line page

apps/fares/lib/fare_info.ex, apps/site/test/site/content_rewriters/liquid_objects/fare_test.exs
**Asana Ticket:** [Liquid replacements for monthly passes](https://app.asana.com/0/385363666817452/1203017920930544/f)
Edited fare info to add some missing information needed to generate the shortcodes used in the CMS to render certain fare information, and added a test case for each:
* Added a monthly reduced price for `:commuter_ferry` fare
* Edited the unused monthly reduced price for express buses, and added this `:express_bus` fare
=> Liquid replacements for monthly passes

apps/site/assets/ts/helpers/service.ts, apps/site/lib/site_web/controllers/schedule/line_controller.ex
**Problem:** instead of selecting weekday service as the default on a weekday, we were finding cases where Saturday is selected instead.
This seems to be happening when the typical weekday service that _should_ be selected happens to have an empty value for `valid_days`. One example (typical weekday service for the 1 bus): https://api-v3.mbta.com/services/BUS422-hbc42cl1-Wdy-02
**This PR:** When evaluating whether a given service is "current": for services where `valid_days` is an empty array, skip the valid day check. This falls back to instead checking whether the service is within the rating dates, which should generally produce a favorable result.
=> fix: account for services with empty `valid_days`

apps/site/assets/css/_accordion-ui.scss, apps/site/assets/css/_svg.scss, apps/site/assets/ts/app/global-navigation.ts, apps/site/assets/ts/ui/__tests__/accordion-test.ts, apps/site/assets/ts/ui/accordion.ts, apps/site/lib/site_web/templates/layout/_new_nav_mobile.html.eex, apps/site/lib/site_web/templates/partial/_accordion_ui_no_bootstrap.html.eex
**Asana Ticket:** [GA4 click event clean-up](https://app.asana.com/0/385363666817452/1203009465850182/f)
* Adjusted the accordion code to support explicitly defining expanded state on each section, and refactors our mobile menu to use that instead of relying on a `click()` with JavaScript.
* Adds `pointer-events: none` to all SVG icons.
=> GA4 click event clean-up

Dockerfile, README.md, apps/site/assets/package-lock.json, apps/site/assets/package.json
No ticket. I was motivated to update this as I noticed in a [deploy from #1444](https://github.com/mbta/dotcom/actions/runs/3299840723/jobs/5443665167) that the Docker image was having trouble following along with the lockfile. In the printed messages it's shown to be using npm v8, which isn't really what we want.
The issue: `npm` updated how it creates/works with `package-lock.json` in version 7 - the differences prior and after are pretty substantial, leaving to large diffs and console messages about the lockfile detected as being made with an older/newer version of npm, etc. You may have run into this! 
It turns out I (and maybe also others?) had upgraded our local `npm` versions from 6 to 7 or 8, resulting in the different `lockfileVersion: 2` lockfile. And then whenever a dev using …
=> chore: use consistent npm version

apps/routes/lib/route.ex, apps/routes/test/route_test.exs
**Asana Ticket:** [Rendering news entries with related transit of "the ride" break things](https://app.asana.com/0/385363666817452/1203353754294449/f)
When processing a CMS news entry tagged with "The RIDE" under related transit, the homepage would break with the following error:
```
** (FunctionClauseError) no function clause matching in Routes.Route.type_atom/1
(routes 0.0.1) lib/route.ex:55: Routes.Route.type_atom("the_ride")
(site 0.0.1) lib/site_web/views/partial_view.ex:72: SiteWeb.PartialView.news_entry/2
(elixir 1.10.4) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
(site 0.0.1) lib/site_web/views/page_view.ex:248: SiteWeb.PageView.do_render_news_entries/1
```
This PR adds an entry to handle `Routes.Route.type_atom("the_ride")`. This ultimately renders the correct icon for the …
=> fix(Routes.Route): add the ride to type_atom

apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/router.ex, apps/site/test/site_web/controllers/trip_plan_controller_test.exs
**Asana Ticket:** [/from links: Pre-populate origin stop for trip planner from URL](https://app.asana.com/0/555089885850811/1203192939356021)
Populate trip planner origin stops from the URL path. Parallels how the existing "to" field works. Supports both lat-lon and geocoding addresses.
lat-lon:
geocoding:
---
=> feat: Populate trip planner origin stops from URL param

.envrc.template, .tool-versions, README.md, apps/v3_api/config/config.exs, apps/v3_api/lib/headers.ex, apps/v3_api/lib/stream.ex, apps/v3_api/test/headers_test.exs
No ticket, but am setting up Dotcom on my new laptop and saw some opportunities to clarify the docs a bit and make some improvements.
- Some of the install guidance was out of date, so removed some of the parts we won't be likely to need.
- I also noticed there's a chromedriver asdf plugin now, so I updated the docs to use that instead of having devs install chromedriver+chrome separately
- The error when running Dotcom when I forgot to set up my environment variables wasn't very helpful! So the second commit adds an error message for this scenario.
- The third commit adds a header to every API request according to the guidance in https://www.mbta.com/developers/v3-api/versioning -- I want this to take precedence when the API key is a different version than the one we support, but I …
=> miscellaneous set-up updates

apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs
There've been enough times where the line diagram page has been compromised on occasions where there are no route patterns with a typicality of 1. Currently it's happening on CR-Fitchburg outbound:
This PR is an experiment... it uses whatever available route patterns have the lowest typicality value (e.g. if none have 1 but a route pattern is present with `typicality=2`, use that to build the line diagram). This technique was already in use for one of the ferry routes; this PR simply uses that for _every_ route.
There might be side effects on various routes! So I'd like to deploy this to a staging server for QA.
---
=> fix?: filter by smallest typicality for all routes

apps/site/assets/css/_schedule-page.scss
**Asana Ticket:** [Destination header in Schedule Finder should be left-aligned](https://app.asana.com/0/555089885850811/1203117266516157/f)
left align header in modal
=> Destination header in Schedule Finder should be left-aligned

apps/site/assets/ts/helpers/__tests__/stop-tree-test.ts, apps/site/assets/ts/helpers/stop-tree.ts, apps/site/assets/ts/schedule/components/ScheduleDirection.tsx, apps/site/lib/site_web/controllers/schedule/line/helpers.ex
**Asana ticket:** [Bus Schedules/Maps Not Showing for Select Routes](https://app.asana.com/0/385363666817452/1203554997501355/f)
* Adds a front-end check to avoid creating errors if the stop tree data that populates the line diagram is empty (before it was only checking if it was _defined_)
* Loosen the filtering of route patterns on the backend
This function is something we have to fiddle with a lot... I've added a comment, but basically we should stop using shape priority. I think we implemented this in the past to avoid issues with conflicting branches on light or heavy rail routes. Doing a cursory check with this change, it doesn't seem to adversely affect rail lines.
---
=> Adjust route pattern filtering on backend (again)

apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/stops/lib/route_stop.ex, apps/stops/test/route_stop_test.exs
Just removing some old line diagram backend code we don't need anymore. This also modifies the list_from_route_pattern function to remove the now-unused `direction_id` argument. The removed code focused on these things:
1. Consolidating overlapping route patterns, covering an edge case on the Kingston/Plymouth Line where one route pattern terminated at Kingston and the other continued one stop further to Plymouth.
2. Manually removing stops that were added during commuter rail replacement bus service, covering an edge case on the Fitchburg Line where rail replacement bus service additionally stopped at Alewife, but "normal" service does not.
3. Manual corrections to the Green Line route during Lechmere shuttle service.
All of these edge cases are over with! So …
=> cleanup: remove code from earlier line diagram workarounds

apps/site/assets/css/_timetable.scss, apps/site/lib/site_web/templates/schedule/_timetable.html.eex, apps/site/lib/site_web/views/schedule/timetable.ex
**Asana Ticket:** [Horizontally Align Parking, Handicap, Service Alert Icons on Schedule Pages](https://app.asana.com/0/385363666817452/1203492984939266/f)
Attempting to fix the icon alignment. Will be deploying to dev-green to facilitate testing across different browsers.
=> fix: timetable icon alignment

apps/routes/lib/repo.ex, apps/routes/test/repo_test.exs, apps/site/assets/ts/schedule/components/line-diagram/StopCard.tsx, apps/site/assets/ts/schedule/components/line-diagram/StopConnections.tsx, apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/stops/lib/route_stop.ex
If `connecting_stops` are included in the fetched routes from the API: lookup `V3Api.Routes.by_stop` again for each connecting stop, and merge resulting routes into the response.
This will happen when the `[include: stop.connecting_stops]` option is passed to `Routes.Repo.by_stop`.
**Asana Ticket:** [Missing stop connections on line diagram](https://app.asana.com/0/385363666817452/1198864672065648/f)
Going to deploy this somewhere for QA, as I'm not quite sure how many areas of the website this is going to end up affecting!
---
=> feat(Routes.Repo): use stop.connecting_stops relation

.github/workflows/algolia-update.yml, .github/workflows/changed-files.yml, .github/workflows/crawler.yml, .github/workflows/deploy-pr.yml, .github/workflows/docker.yml, .github/workflows/shellcheck.yml, .github/workflows/tests.yml, .github/workflows/use-deploy-ecs.yml, .github/workflows/use-notify-slack.yml, .tool-versions, README.md, docs/TESTING.md, mix.exs, scripts/setup_chromedriver.sh
Goal is to avoid mismatch between local Chrome version and chromedriver version. Can be used both in CI and locally to download the correct chromedriver version that matches your Google Chrome install.
Ran into that issue while working on #1494.
This doesn't require any changes to a developer's local environment if not running the Elixir integration tests (unit tests with the "wallaby" tag).
We'll see here if CI works!
=> experiment: alternate chromedriver source

apps/routes/lib/route.ex, apps/site/lib/site_web/views/helpers.ex, apps/trip_plan/lib/trip_plan/api/open_trip_planner/parser.ex
Lets us use new Massport GTFS with agency IDs 2274 and 2272, adds these to the relevant helpers so that we can parse and display itineraries in our Trip Planner without crashing. :) Will test on dev-green (which has OTP with the relevant GTFS set up via [chore: Use Trillium-hosted GTFS file for Massport](https://github.com/mbta/OpenTripPlanner/pull/48)).
**Asana Ticket:** [Suggested trips do not include Massport shuttles](https://app.asana.com/0/385363666817452/1203244406551664/f)
=> hotfix(Trip Planner): parse new Massport GTFS

.github/workflows/algolia-update.yml
The Algolia indexing job does not need to run on forks (and in fact, breaks).
---
=> fix: only run Algolia update in MBTA org

apps/site/config/config.exs, apps/site/lib/site_web/controllers/bus_stop_change_controller.ex, apps/site/lib/site_web/router.ex, apps/site/lib/site_web/templates/bus_stop_change/index.html.eex, apps/site/lib/site_web/views/bus_stop_change_view.ex
**Asana Ticket:** [Set up initial page structure](https://app.asana.com/0/385363666817452/1203811157466553/f)
The new draft  page is set up at `/bus-stop-changes`, hidden behind a new feature flag accessible at `/_flags` (will redirect to /alerts if the flag is not enabled).
=> Setup bus change page feature flag + initial WIP

apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/test/site_web/controllers/schedule/line_controller_test.exs
**Asana Ticket:** [Google results should show short names instead of route IDs](https://app.asana.com/0/385363666817452/1202793084291449/f)
Just going through old tickets in the icebox.... this adjusts the description seen when searching Google or somesuch for certain routes that are better known by name rather than route id: CT2, SL4, etc.
=> fix: use bus name instead of id in meta description

apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/views/schedule_view_test.exs
**Asana Ticket:** [Logic: Station page vs. Bus Stop page](https://app.asana.com/0/385363666817452/1204099052193020/f)
Add is_station? that returns whether or not a given stop is a station
=> Logic: Station page vs. Bus Stop page

apps/site/assets/css/_stop-page.scss, apps/site/assets/ts/hooks/__tests__/useMapConfigTest.tsx, apps/site/assets/ts/hooks/useMapConfig.ts, apps/site/assets/ts/leaflet/components/__mapdata.d.ts, apps/site/assets/ts/stop/__tests__/StopMapRedesignTest.tsx, apps/site/assets/ts/stop/components/StopMapRedesign.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx, apps/site/lib/site_web/controllers/map_config_controller.ex, apps/site/lib/site_web/router.ex, apps/site/lib/site_web/templates/stop/show-redesign.html.eex, apps/site/test/site_web/controllers/map_config_controller_test.exs
Added the leaflet map to the new stop redesign page.
I decided to reuse the lowest level of wrappers we have for the leaflet map because it seemed really flexible and supportive for future requirements for the map, while having next to zero lift to include it in out page.
**Asana Ticket:** [Map | Display Map with Marker](https://app.asana.com/0/home/1201123880594717/1204099052193031)
---
=> feat(StopRedesign): Add map of stop to page

apps/site/assets/ts/app/global-navigation.ts
**Asana Ticket:** [Mobile menu placement affected by scrolling](https://app.asana.com/0/385363666817452/1204109811265850/f)
This PR sets the menu's CSS positioning right after clicking, before the menu is displayed, thereby circumventing the issue captured in the Asana ticket's video.
---
=> fix: adjust mobile menu placement on mobile after click

Dockerfile, apps/alerts/lib/supervisor.ex, apps/routes/lib/routes.ex, apps/routes/test/populate_caches_test.exs, apps/site/lib/site/application.ex, apps/site/test/green_line_test.exs, apps/site/test/site/lib/green_line/cache_test.exs, apps/site/test/site/lib/green_line/supervisor_test.exs, apps/site/test/site/trip_plan/itinerary_row_list_test.exs, apps/site/test/site_web/controllers/schedule/green_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/vehicles/lib/vehicles.ex, config/config.exs
This is a bit of a behind-the-scenes change I made while working on a different thing.
**Issue:** Dotcom runs lots of different processes in the background, mostly fetching and parsing data. But these processes always run, even during CI, producing occasional error messages such as this one:
Not technically failing test, but kind of annoying, intermittent, and unnecessary.
I eventually came across a pattern used in other projects, where we can configure certain processes to not be automatically started in every environment. [Skate uses it here](https://github.com/mbta/skate/blob/master/lib/skate/application.ex#L17) to omit certain modules from being added to the supervision tree in the test environment. So I decided to do something similar here!
**Approach:** 
* Set a single configuration …
=> Disable background data fetching processes during tests

apps/site/lib/site_web/plugs/cache_control.ex, apps/site/lib/site_web/router.ex, apps/site/test/site_web/plugs/cache_control_test.exs
No ticket. The loading time of our WIP stops redesign page was bugging me. Then I realized we can have the browser cache backend responses. So I added this to the `api/stop/:id`, `api/map-config` and `api/routes/by-stop/:stop_id` endpoints. These are tiny amounts of static information that we don't expect to change over the course of a day anyway.
- Creates a new plug that adds a specified cache-control max-age header to the response.
- Uses the plug on a few of our more recent endpoints, with a max-age of one day.
---
=> feat(SiteWeb.Plugs.CacheControl): cache some endpoints

apps/predictions/lib/parser.ex, apps/predictions/lib/prediction.ex, apps/predictions/lib/predictions.ex, apps/predictions/lib/predictions_pub_sub.ex, apps/predictions/lib/stream.ex, apps/predictions/lib/stream_parser.ex, apps/predictions/lib/stream_supervisor.ex, apps/predictions/mix.exs, apps/predictions/test/parser_test.exs, apps/predictions/test/predictions_pub_sub_test.exs, apps/predictions/test/repo_test.exs, apps/predictions/test/stream_parser_test.exs, apps/predictions/test/stream_supervisor_test.exs, apps/predictions/test/stream_test.exs, apps/routes/lib/parser.ex, apps/site/lib/site_web/channels/predictions_channel.ex, apps/site/lib/site_web/channels/user_socket.ex, apps/site/test/site/realtime_schedule_test.exs, apps/site/test/site_web/channels/predictions_channel_test.exs, apps/site/test/support/env_helpers.ex, apps/v3_api/lib/stream.ex
**Asana Ticket:** [Subscribe to streaming updates by routeId and stopId](https://app.asana.com/0/385363666817452/1203082255397801/f)
> **Warning**
> This was substantially reworked Dec 14! Description has been updated below.
This builds upon the work done in #1421. To that end, the first three commits are directly from Matt's branch there. The fourth commit (`fixup: feat: Parse and save prediction arrival and departure times`) conceptually goes with the changes in the third commit. 
So, the fifth commit (`feat: get streaming predictions by route, stop, direction`) contains the bulk of the task to enable subscribing to a stream of predictions for a specified stop on a route, rather than all predictions for an entire route. This was further enhanced to add a direction argument. This mostly …
=> Subscribe to streaming updates by routeId and stopId

apps/alerts/lib/cache/store.ex, apps/alerts/test/cache/store_test.exs, apps/alerts/test/repo_test.exs, apps/site/assets/ts/hooks/__tests__/useAlertsForStopTest.tsx, apps/site/assets/ts/hooks/useAlertsForStop.ts, apps/site/lib/site_web/controllers/alert_controller.ex, apps/site/lib/site_web/router.ex
The alerts are first sorted into a table that stores which stop_ids map to which alert_ids
Create an endpoint that returns all the alerts for the given stop.
The bones of the logic was there this pull request fixes it.
**Asana Ticket:** [Departure Cards | Departure Display | Alerts Data](https://app.asana.com/0/home/1201123880594717/1204340687791888)
---
=> feat(StopAlerts): Fixed endpoint for getting all the alerts at a stop

apps/site/assets/ts/app/__tests__/channels-test.ts, apps/site/assets/ts/app/channels.ts, apps/site/assets/ts/helpers/__tests__/date-test.ts, apps/site/assets/ts/helpers/date.ts, apps/site/assets/ts/hooks/__tests__/usePredictionsChannelTest.tsx, apps/site/assets/ts/hooks/useChannel.ts, apps/site/assets/ts/hooks/usePredictionsChannel.ts, apps/site/assets/ts/stop/__tests__/DepartureCardTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageDeparturesTest.tsx, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageDeparturesTest.tsx.snap, apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/components/DepartureCard.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx, apps/site/assets/ts/stop/components/StopPageDepartures.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx
**Asana Ticket:** [[Spike] Using the predictions refactor work in departures](https://app.asana.com/0/385363666817452/1204099052193042/f)
> **Note**
> Dotcom is working on a redesign of the stops pages ([random example page](https://dev.mbtace.com/stops/1112)). As with the current version, the new version will show upcoming departures using data we get from the V3 API's predictions. This WIP can be viewed by enabling the feature flag to turn on the stops page redesign. You can enable the feature flag appending `active_flag=stops_redesign` to the URL, or by visiting `/_flags` and clicking the checkbox.
A few months ago the Dotcom team had put in substantial effort into reconsidering how we fetch and serve prediction data site-wide, culminating in **#1476 feat(Predictions): Subscribe to …
=> [Spike] Using the predictions refactor work in departures

apps/route_patterns/lib/repo.ex, apps/routes/lib/route.ex, apps/routes/test/repo_test.exs, apps/routes/test/route_test.exs, apps/site/assets/ts/hooks/__tests__/useRouteTest.tsx, apps/site/assets/ts/hooks/useRoute.ts, apps/site/assets/ts/jest.config.js, apps/site/assets/ts/schedule/components/Map.tsx, apps/site/assets/ts/stop/__tests__/DepartureCardTest.tsx, apps/site/assets/ts/stop/__tests__/StopMapRedesignTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx, apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/__tests__/helpers.ts, apps/site/assets/ts/stop/components/StopMapRedesign.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx, apps/site/assets/ts/tnm/__tests__/setupTests.ts, apps/site/assets/ts/trip-planner/__tests__/__snapshots__/VoteMapTest.tsx.snap, apps/site/lib/site_web/controllers/route_controller.ex, apps/site/test/site_web/controllers/route_controller_test.exs
**Asana Ticket:** [Landing Page | Map should show subway and commuter rail routes](https://app.asana.com/0/385363666817452/1204340687791882/f)
Adds subway/trolley/commuter rail routes to the map.
Since fetching shapes is dependent on the routes, I figured we may as well fetch routes and shapes together, so I added that data to the existing endpoint we have for fetching routes for this page.
> **Note**
> This is behind a feature flag – please visit a stop page via `/stops/:stop_id?active_flag=stops_redesign`
---
=> Stop Page Redesign Landing Page | Map should show subway and commuter rail routes

apps/schedules/lib/repo.ex, apps/schedules/test/repo_test.exs, apps/site/lib/site/transit_near_me.ex, apps/site/lib/site_web/controllers/schedule_controller.ex, apps/site/lib/site_web/controllers/stop_controller.ex, apps/site/lib/site_web/router.ex, apps/site/test/site_web/controllers/schedule_controller_test.exs
Broke out the stop redesign departure times into a backend only ticket.
I believe all of the feedback from the previous pull request has been addressed.
Basic idea create an endpoint to get all the schedules for a given stop for the new stop page to consume.
**Asana Ticket:** [Departure Card Times](https://app.asana.com/0/home/1201123880594717/1204305469426579)
---
=> feat(StopRedesign): Schedule endpoint to return schedules by stop

apps/trip_plan/lib/trip_plan/api/open_trip_planner/parser.ex
All IDs coming from OTP are prefixed with the feed_id as specified in feed_info.txt, this updates the values in the case statement to reflect the exact values, along with a wildcard match that treats any other IDs as MBTA ones (if this is deployed before the ID is added to GTFS, it will continue to function with the auto-generated ID of 1).
**Asana Ticket:** [Fix leg icons and colors](https://app.asana.com/0/1204355099788517/1204505865009728)
All IDs coming from OTP are prefixed with the feed_id as specified in feed_info.txt, this updates the values in the case statement to reflect the exact values, along with a wildcard match that treats any other IDs as MBTA ones (if this is deployed before the ID is added to GTFS, it will continue to function with the auto-generated ID of 1).
⚠️ This …
=> Add more explicit handling for feed_id

apps/predictions/lib/prediction.ex, apps/predictions/lib/repo.ex, apps/predictions/lib/stream_parser.ex, apps/predictions/test/repo_test.exs, apps/predictions/test/stream_parser_test.exs, apps/schedules/lib/repo.ex, apps/schedules/lib/schedule.ex, apps/schedules/test/repo_test.exs, apps/site/test/site/realtime_schedule_test.exs
**Asana Ticket:** [Support comparing scheduled and predicted platform stops](https://app.asana.com/0/555089885850811/1204552579091683/f)
This PR includes the original stop_id for predictions and schedules as `platform_stop_id` so that we are able to compare the  scheduled vs. predicted stop. 
---
=> feat: Keep original stop_id on prediction & schedule records

apps/route_patterns/lib/repo.ex, apps/route_patterns/test/repo_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs
… 
Fix to https://github.com/mbta/dotcom/pull/1590. Canonical route patterns aren't always separate reference patterns not scheduled to operate; they can be scheduled to operate, so we shouldn't filter them out by default.
Some 
---
=> fix(RoutePatterns.Repo): Don't filter out canonical route patterns by default

apps/site/assets/css/_spacing.scss, apps/site/assets/css/_utilities.scss, apps/site/assets/ts/components/Badge.tsx, apps/site/assets/ts/components/__tests__/BadgeTest.tsx, apps/site/assets/ts/hooks/usePredictionsChannel.ts, apps/site/assets/ts/models/__tests__/alert-test.ts, apps/site/assets/ts/models/__tests__/schedule-test.ts, apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/models/schedule.ts, apps/site/assets/ts/stop/__tests__/DepartureCardTest.tsx, apps/site/assets/ts/stop/__tests__/DeparturesAndMapTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageDeparturesTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx, apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/components/DepartureCard.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx, apps/site/assets/ts/stop/components/StopPageDepartures.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx, apps/site/assets/ts/stop/models/displayTimeConfig.ts
Adds a Badge to display alerts in the departure cards instead of the times if an alert is present.
The alerts effect types this works for are Suspensions, Shuttle Service, and Detours.
This pull request fetches route wide alerts for the new stop redesign page, merges them with the stop specific routes.
The alerts are then divided up by route, and then direction.  To be passed to the corresponding `DepartureTimes` component for the direction.  This is then processed to display the corresponding badge if eligible.
This also breaks out `DepartureInfo` into its own file to help readability.
NOTE: This pull request needs the alert date parsing pull request merged for the badges to display
**Asana Ticket:** [Alerts | Route Specific Badges on Departure …
=> feat(DepartureTimes): Add an alert badge to the departure row

apps/site/assets/webpack.config.export-headerfooter.js
Adding the larger site icons to the dotcomchrome script, so that sites using dotcomchrome can mirror the existing icon tags from mbta.com
=> Add larger site icons to dotcomchrome export script

apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/DailyScheduleSubway.tsx, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/DailyScheduleSubwayTest.tsx
When the `added_dates_notes` happens to be missing a value for a given date, fall back on the service name.
**Asana Ticket:** [Day of Week Not Showing](https://app.asana.com/0/385363666817452/1204633022300171/f)
**Before:**
**After:**
---
=> fix(DailyScheduleSubway): fallback to service name

apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/hooks/__tests__/usePredictionsChannelTest.tsx, apps/site/assets/ts/hooks/usePredictionsChannel.ts, apps/site/assets/ts/hooks/useSchedules.ts, apps/site/assets/ts/schedule/components/__trips.d.ts, apps/site/assets/ts/tnm/helpers/process-realtime-data.ts
**Asana Ticket:** [Tech Debt - support arrival and departure times in stops page redesign](https://app.asana.com/0/555089885850811/1204758731107223/f)
This is the frontend complement to the backend work supporting prediction and schedule arrival and departure times from #1620 
Edit to clarify: I haven't implemented any logic around it, or changed how any times are displayed yet. But now when we inspect the schedules or predictions used in these React components, they will have populated `arrival_time` and `departure_time` values.
=> feat(StopsPageRedesign): support arrival and departure times

apps/site/assets/ts/schedule/components/line-diagram/ExpandableBranch.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagramWithStops.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/LineDiagramWithStopsTest.tsx
**Asana Ticket:** [Line diagrams showing "shuttle" where regular service is running](https://app.asana.com/0/385363666817452/1203533488121919/f)
It turns out we were passing the entire route's alerts to every stop's `<StopCard />`, which led to some erroneous determinations. Most notably, certain stops would be labeled with a "Shuttle" or other diversion when that actually only applied to other stops along the route.
I haven't included any test changes in this because..well, technically the components and functions were working as designed, and it was a bit of a user error on our part to give each stop component more alerts than relevant. And maybe there's a more elegant approach to this, but I didn't want to overhaul things.
=> fix(LineDiagram): give `<StopCard />` alerts for that stop

apps/site/assets/ts/stop/stop-loader-redesign.tsx, apps/site/lib/site_web/templates/stop/show-redesign.html.eex
...and stop reading the stop ID from the window location.
The way our current loading worked, whatever URL params are on the page ended up getting captured in the stop ID, e.g. visiting `/stops/place-whatever?something=foo` would result in a `stopId` of `place-whatever?something=foo`, which caused multiple subsequent requests to fail.
This fixes that by passing in the stop ID via the HTML.
**Asana Ticket:** [Stop Page | Load page when directed from search result](https://app.asana.com/0/385363666817452/1204659277085822/f)
=> refactor: add stop_id directly to container element

apps/site/assets/ts/hooks/useSchedules.ts, apps/site/assets/ts/stop/components/StopPageDepartures.tsx, apps/site/lib/site_web/controllers/schedule_controller.ex, apps/site/test/site_web/controllers/schedule_controller_test.exs
I saw the comment `// This filtering should be done on the backend` for the listing current schedules, so I went ahead and did that, and added a condition to remove schedules with a `last_stop?` value of `true`.
**Asana Ticket:** [For terminal stops, don't list routes that end at that stop](https://app.asana.com/0/385363666817452/1204678909646879/f)
| Before      | After |
| ----------- | ----------- |
|  ![dev mbtace com_stops_place-wondl](https://github.com/mbta/dotcom/assets/2136286/43d4c9aa-f049-4c54-9e06-1537d8846b5c)   |  ![localhost_4001_stops_place-wondl (3)](https://github.com/mbta/dotcom/assets/2136286/bee2a1b0-be2b-4a84-aa50-02f5f7b4755d)   |
---
=> refactor(StopPageDepartures): filter schedules in backend

apps/alerts/test/cache/store_test.exs, apps/predictions/lib/parser.ex, apps/predictions/lib/stream_parser.ex, apps/predictions/test/stream_parser_test.exs, apps/route_patterns/test/repo_test.exs, apps/schedules/lib/parser.ex, apps/schedules/test/parser_test.exs, apps/site/assets/ts/hooks/__tests__/usePredictionsChannelTest.tsx, apps/site/assets/ts/hooks/usePredictionsChannel.ts, apps/site/test/site/lib/green_line/supervisor_test.exs, apps/site/test/site/lib/vehicle_helpers_test.exs, apps/site/test/site/transit_near_me_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs
**Asana Ticket:** [Retrofit Departure Cards + List To Show Arrivals](https://app.asana.com/0/385363666817452/1204795517302694/f)
In our predictions and schedules, we have a field called `time` that was meant to abstract the idea of which of departure or arrival time to send to the frontend, but this became murky so we added `departure_time` and `arrival_time` back into the predictions and schedules so that it was easier to understand what we're displaying. But alas, now came time to implement logic to:
- For subway and bus, prefer arrival times
- For everything else, prefer departure times
So I replaced `Predictions.Parser.first_time/1` with `Schedules.Parser.display_time/3`, which implements this mode-specific logic with a slightly more legible name and comment. And put the result in the …
=> Retrofit Departure Cards + List To Show Arrivals

apps/predictions/lib/predictions_pub_sub.ex, apps/predictions/lib/stream_supervisor.ex, apps/predictions/test/predictions_pub_sub_test.exs, apps/predictions/test/stream_supervisor_test.exs, apps/site/assets/ts/hooks/__tests__/usePredictionsChannelTest.tsx, apps/site/assets/ts/hooks/usePredictionsChannel.ts, apps/site/lib/site_web/channels/predictions_channel.ex, apps/site/test/site_web/channels/predictions_channel_test.exs
**Asana Ticket:** [Predictions Refactor | Flexible Subscription IDs](https://app.asana.com/0/1204716173461809/1204668141429887/f)
The goal of this PR was to make the backend changes needed to enable predictions streaming for more than a route-direction-stop triad. In total,
- Instead of managing lists of predictions in a `Map` keyed by `route:stop:direction`, predictions are put into an ETS table. The single ETS table is created on startup and each new subscription starts a new streaming connection to the API (same as before), each connection having the ability to remove/update/add entries to the table. Each entry is a tuple of `{prediction ID, route ID, stop ID, direction ID, trip ID, vehicle ID, prediction (the whole object)}` - making it easy to fetch predictions by any and all of …
=> Predictions Refactor | Flexible Subscription IDs

apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/ServiceOptGroup.tsx, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/ServiceOptGroupTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/__snapshots__/DailyScheduleTest.tsx.snap
Because of the way the backend logic works, if there's only one service available this rating, that service might get labelled as "today's", even if it's not within the valid service dates. To improve this, 
- actually check whether the service is in the current service before labelling with "(now)"
- if it's not in the current service, adjust the text to indicate start date
**Asana Ticket:** [Schedule finder should not present future services as current](https://app.asana.com/0/385363666817452/1204794505976013/f)
---
=> fix(ServiceOptGroup): improve (now) logic

apps/cms/test/repo_test.exs, apps/fares/lib/fare_info.ex, apps/fares/lib/fares.ex, apps/fares/lib/format.ex, apps/fares/test/fares_test.exs, apps/fares/test/format_test.exs, apps/location_service/test/aws_location/request_test.exs, apps/location_service/test/wrappers_test.exs, apps/routes/lib/mock_repo_api.ex, apps/routes/test/repo_test.exs, apps/schedules/test/hours_of_operation_test.exs, apps/services/test/service_test.exs, apps/site/lib/site/content_rewriters/liquid_objects/fare.ex, apps/site/test/detailed_stop_group_test.exs, apps/site/test/predicted_schedule_test.exs, apps/site/test/site/transit_near_me_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/controllers/stop_controller_test.exs
**Asana Ticket:** [Ferry Fares Page | Add fare cards for Lynn and Winthrop](https://app.asana.com/0/385363666817452/1204827964401105/f)
Gonna deploy this to dev-green and leave this as a draft while I test if this change works with the (sandbox-mbta) CMS. (edit: done, it works!)
I mostly followed the code changes used when we added the fares for the East Boston ferry in #1411 
The one missed opportunity for optimization here - East Boston, Lynn, and Winthrop have the same one-way fares, so potentially that code could be more streamlined. But I know one of them is increasing in price at the end of summer, and E Boston has reduced fare that might not be the same as the others... so I didn't want to consolidate those if they're not meant to be identical.
---
=> chore: add Lynn & Winthrop ferry fare info

apps/site/assets/css/_stop-page.scss, apps/site/assets/css/_utilities.scss, apps/site/assets/ts/components/Badge.tsx, apps/site/assets/ts/stop/__tests__/components/amenities/AmenityCardTest.tsx, apps/site/assets/ts/stop/components/amenities/AmenityCard.tsx
No ticket, just a few improvements on the original `AmenityCard` component we'll all use:
* Some CSS and layout improvements, mostly around the card's heading. This allows the badge to be on the same line as the header text, and wrap nicely without interfering with the width of the right arrow.
* Adds disabled state
* Grey background and black header text and black icon
* No click enabled / hides arrow
* Adjusts badge to support additional CSS class - e.g. you can do `<Badge bgClass="u-bg--gray-lighter" />` to replace the default red background with a grey one
* Added an `<AmenityLink />`, there isn't much to it but just standardizing our rendering of links
* Improves the typing used for children components
=> feat(AmenityCard): add badge prop, improve styles

apps/site/assets/css/_stop-card.scss, apps/site/assets/ts/helpers/media-breakpoints.ts, apps/site/assets/ts/stop/components/DepartureCard.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx, apps/site/assets/ts/stop/components/StopPageDepartures.tsx
**Asana Ticket:** [Bug: stop page mobile view realtime tracking body of page still scrolls](https://app.asana.com/0/385363666817452/1204770533473925/f)
Isza's `z-index` addition made the bug more bearable, but this PR implements some additional code to prevent scrolling on the background.
- via a `useEffect` hook, disable/enable body scrolling when toggling between the landing page and realtime tracking view
- Adjusted layout: When toggling between the landing page and realtime tracking view, we keep the same HTML layout and swap out inner components as needed, instead of constructing an alternate layout. Some CSS is used to toggle further layout changes when the `.selected-departure` class name is present.
- Change viewAllRoutes function to a simpler viewSelectedDeparture variable.
- …
=> Stops Page Redesign | Prevent page scrolling on mobile in realtime tracking view

apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/ts/stop/__tests__/helpers.ts, cypress/e2e/customer-support-form/support_form.cy.js
No ticket. Was just using Faker to help me with generating test data, and realized we're a version behind. Also ran `npm audit fix` to further update our `package-lock.json`.
=> deps(npm): upgrade faker to v8.0

apps/location_service/lib/aws_location/request.ex, apps/location_service/test/aws_location/request_test.exs
**Asana Ticket:** [Switch geocoding search from HERE to Esri](https://app.asana.com/0/385363666817452/1204974196349553/f)
AWS Location Services requests can use two different geodata sources. We were previously using a mix of the two for different purposes, but one of the sources, HERE, was giving incorrect results in many different cases (many based around incorrect zip codes). This switches all searches to instead use the other source, Esri. If we start seeing more problems, we can switch back, but for now, Esri looks more reliable.
---
=> Switch AWS Location Service provider to Esri

apps/site/lib/site_web/router.ex
> **Note**
> There's a corresponding open PR at https://github.com/mbta/devops/pull/1028 that will add an endpoint to our prod CDN to the news RSS feed via the `/news/rss.xml` URL. This was already done on our dev CDN a few weeks ago. What this means is this can be tested on dev now, but won't work on prod until the linked open PR is merged and applied.
Our router normally takes this request to the `NewsEntryController`, which predictably fails to fetch a news entry and leads to a 404 page. This one-line change redirects requests to `/news/rss.xml` to the CDN directly via our existing `StaticFileController`.
**Asana Ticket:** [Drupal News RSS Feed](https://app.asana.com/0/385363666817452/1204747418355403/f)
=> feat: route RSS path to StaticFileController

apps/fares/lib/format.ex, apps/fares/lib/repo.ex, apps/fares/test/repo_test.exs, apps/routes/lib/parser.ex, apps/routes/lib/route.ex, apps/routes/test/route_test.exs, apps/site/assets/ts/__v3api.d.ts, apps/site/lib/site_web/controllers/fare_controller.ex, apps/site/lib/site_web/controllers/route_controller.ex, apps/site/lib/site_web/router.ex, apps/site/test/site/realtime_schedule_test.exs, apps/site/test/site_web/controllers/fare_controller_test.exs, apps/site/test/site_web/controllers/route_controller_test.exs
The corresponding front-end work is in #1658 
**Asana Ticket:** [Amenity Modal | Fare Sales](https://app.asana.com/0/385363666817452/1204415037587451/f)
(There was no separate Asana ticket for the card content, but that work is in this PR too).
Inadvertently covers:
**Asana Ticket:** [Create list of all fare classes as shown in API](https://app.asana.com/0/385363666817452/1204827964810515/f)
* Adds support for parsing a route's `fare_class`. I deduced the valid values for this field by finding [the source code in `gtfs_creator`](https://github.com/mbta/gtfs_creator/blob/e031d3618840c4f33f62c7c4541140b621efa547/gtfs_creator2/validate.py#L504) 🙃 
* Adds support for this field in the front-end too, but makes it optional so that I don't have to change 40+ TypeScript files... looks like that's …
=> feat(FareSalesAmenityCard): add info and modal (backend)

apps/site/assets/css/_amenity.scss, apps/site/assets/ts/hooks/__tests__/useFetchTest.tsx, apps/site/assets/ts/hooks/useFetch.ts, apps/site/assets/ts/stop/__tests__/DeparturesAndMapTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx, apps/site/assets/ts/stop/__tests__/components/StationInformationTest.tsx, apps/site/assets/ts/stop/__tests__/components/amenities/FareSalesAmenityCardTest.tsx, apps/site/assets/ts/stop/__tests__/helpers.ts, apps/site/assets/ts/stop/components/StationInformation.tsx, apps/site/assets/ts/stop/components/amenities/AmenityCard.tsx, apps/site/assets/ts/stop/components/amenities/BikeStorageAmenityCard.tsx, apps/site/assets/ts/stop/components/amenities/FareSalesAmenityCard.tsx
The front-end piece of #1654 
**Asana Ticket:** [Amenity Modal | Fare Sales](https://app.asana.com/0/385363666817452/1204415037587451/f)
- Some refactoring to account for the changed data structure now including fares
- Made a helper method for scaffolding a Stop for our tests.
- Added the modal content and amenity card text. Shows either information about fare vending machines or a link to view retail sales locations.
- Used styling from `.responsive-table` as a reference for the CSS (but couldn't copy it outright... too many differences)
=> feat(FareSalesAmenityCard): add info and modal (frontend)

apps/site/assets/ts/stop/__tests__/DepartureListTest.tsx, apps/site/assets/ts/stop/__tests__/StopMapRedesignTest.tsx, apps/site/assets/ts/stop/components/DepartureCard.tsx, apps/site/assets/ts/stop/components/DepartureList.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx, apps/site/assets/ts/stop/components/StopMapRedesign.tsx, apps/site/assets/ts/stop/components/StopPageDepartures.tsx
Most of this PR is just renaming, but it fixes a major issue where, for directions having multiple destinations, clicking on each of them led to the same view (e.g. clicking Ashmont or Braintree each lead to a "Red Line to Ashmont" list with the same list of departures, instead of showing different lists).
**Asana Ticket**: [Departures | Different destinations lead to the same realtime tracking page](https://app.asana.com/0/385363666817452/1205084471790526/f)
- remove repetition by defining a type for the filter and the function that handles it
- use headsign to help filter departures
- pass in the headsign as a prop to DepartureList
- simplify the filter type a bit by having a null state instead of a state where each object key can have a null value.
=> fix(DeparturesAndMap): add headsign to departure filters

apps/site/assets/ts/hooks/__tests__/useSchedulesTest.tsx, apps/site/assets/ts/hooks/useSchedules.ts, apps/site/lib/site_web/router.ex
This PR is based on the changes from #1650, which is needed for this PR to update the displayed schedules as expected.
**Asana Ticket:** [Departure data refresh investigation](https://app.asana.com/0/385363666817452/1204573540717218/f)
* The `useSchedules` hook now has an internal state, that updates a timestamp every 15 seconds. The timestamp is used to re-filter the list of schedules to ensure no stale schedules are returned.
* I learned a lot about how timers in Jest work while trying to test this
* I adjusted the schedules endpoint to set a cache header with a `max_age` of an hour. This means the client will get a refreshed version after an hour has elapsed, and prevents the client from fetching the same ~1.35MB of schedules over and over whenever the component state updates.
* I felt …
=> feat(useSchedules): update time, filter schedules

apps/site/assets/ts/stop/__tests__/DisplayTimeTest.tsx, apps/site/assets/ts/stop/components/DisplayTime.tsx
**Asana Ticket:** [Subway delayed trips should not show originally scheduled time on realtime tracking page](https://app.asana.com/0/385363666817452/1205079845268819/f)
Added a mode check to hide showing the delayed information detail (crossed out schedule time) for subway departures.
---
=> fix(DisplayTime): hide delayed time for subway

apps/site/assets/css/_stop-card.scss, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx
Adjust the "Back to all routes" control so that it can wrap long test. While we're here, also change this element to a button. This enables keyboard navigability and is more accessible.
**Asana Ticket:** [Realtime Tracking Page | Text in navigation bar falls outside of container](https://app.asana.com/0/385363666817452/1205172693755923/f)
(normal view without wrapping, for reference):
---
=> fixup(DeparturesAndMap): allow text wrapping

apps/site/lib/site_web/channels/predictions_channel.ex, apps/site/test/site_web/channels/predictions_channel_test.exs
**Asana Ticket:** [Investigate why Terminal Predictions and Headsigns showing](https://app.asana.com/0/385363666817452/1205175614190107/f)
Basically, once we stopped filtering out all predictions having `nil` departure times, we resumed sending predictions arriving at terminals to the frontend. This PR takes them back out.
---
=> feat(PredictionsChannel): remove at terminal stops

apps/predictions/config/config.exs, apps/predictions/lib/predictions_pub_sub.ex, apps/site/assets/ts/app/__tests__/channels-test.ts, apps/site/assets/ts/app/channels.ts, apps/site/assets/ts/hooks/__tests__/useChannelTest.tsx, apps/site/assets/ts/hooks/useChannel.ts, apps/site/assets/ts/hooks/usePageVisibility.ts
**Asana Ticket:** [Data Refresh when Stop Page in Background](https://app.asana.com/0/385363666817452/1205161605826762/f)
The three commits do different things, but they're all in the realm of improving the client experience of receiving data from the predictions channel.
1. ### `feat(channels): add socket close event listener`
This is the fundamental commit that prevents stale predictions from sticking around. 
**The problem:** In our case, after leaving a tab open in the background for ~10 minutes, the browser closes the WebSocket connection. With no more predictions data being received until a user refreshes the page. 
> [!NOTE]
> [Phoenix.js](https://hexdocs.pm/phoenix/js/) is _supposed_ to handle this situation (it's not uncommon or unexpected, after all) and automatically reconnect, …
=> background data refresh improvements

apps/site/assets/ts/__jest-extended.d.ts, apps/site/assets/ts/hooks/__tests__/usePredictionsChannelTest.tsx, apps/site/assets/ts/hooks/usePredictionsChannel.ts, apps/site/assets/ts/stop/__tests__/DeparturesAndMapTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx
**Asana Ticket:** [Bubble up prediction fetching error](https://app.asana.com/0/385363666817452/1205144855393526/f) and [Departures | Predictions aren't loading consistently](https://app.asana.com/0/385363666817452/1205093855734953/f)
1. #### Bubble up prediction fetching error
Use a `null` return type of `usePredictionsChannel` to signify the error state. Makes use of the fact that the underlying `useChannel` function is designed to return the `initialState` argument if the `channelName` argument happens to be `null`.
2. #### Add error message to top of page if predictions aren't fetched
If predictions are `null`, show the message at top. This uses some of the styling of the Transit Near Me error banner, but (a) doesn't use heading styling, just bolds the top text, and (b) removes the …
=> feat(StopPageRedesign): surface error message if predictions aren't fetched

apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/stop/__tests__/DepartureListTest.tsx, apps/site/assets/ts/stop/components/DepartureList.tsx
Only suppress departures for shuttle alerts that are currently active.
**Asana Ticket:** [Realtime Tracking | When future alerts are present, real time page predictions/schedules are suppressed](https://app.asana.com/0/555089885850811/1205225444022092/f)
This PR also has some minor refactoring for better readability.
---
=> fix(DepartureList): use shuttle alert lifecycle

apps/site/assets/ts/models/__tests__/alert-test.ts, apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/stop/__tests__/DepartureCardTest.tsx, apps/site/assets/ts/stop/__tests__/DepartureListTest.tsx, apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/components/DepartureList.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx
**Asana Ticket:** [Departures | “No Service” badge is shown and predictions are being suppressed for Green Line routes that are only affected in one direction](https://app.asana.com/0/385363666817452/1205213256266703/f)
The main issue this PR was trying to solve involved a Suspension alert on the Green Line in Government Center/Haymarket/North Station from earlier this week. That alert did not specify an affected direction. 
Because the changes in this PR might affect the display of **all** alert badges (Detour, Suspension/No Service, Shuttle) I'm creating some test alerts for the reviewer to verify that several things display as expected on **dev-blue**:
- The suspension from the PR has been recreated in test Alerts UI, so can be seen at Government Center (stop ID place-gover) and North …
=> refactor(DepartureTimes): improved handling of Suspension and Shuttle alerts

apps/site/assets/ts/helpers/date.ts, apps/site/assets/ts/stop/__tests__/DisplayTimeTest.tsx, apps/site/assets/ts/stop/components/DisplayTime.tsx
Remove `Tomorrow` from showing up on the time on the departure cards, and departure list.
This only happens if the time is set to relative.
**Asana Ticket:** [Departure Times | Text Mis Aligned close to midnight](https://app.asana.com/0/555089885850811/1205225444022104)
---
=> fix(DepartureTimes): Hide tomorrow when the time is relative

apps/site/assets/ts/models/__tests__/alert-test.ts, apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/stop/components/AccessAmenitiesModal.tsx, apps/site/assets/ts/stop/components/amenities/access-amenities-helpers.tsx
**Asana Ticket:** [Elevator Status Affected by Upcoming Alerts](https://app.asana.com/0/385363666817452/1205268550058218/f)
The first commit fixes the table, the second fixes the badge, both should now display the correct number of current outages.
---
=> fix: check current lifecycle when counting out of order amenities

apps/site/assets/ts/models/__tests__/alert-test.ts, apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx
Stop displaying train times where there is a station closure alert
**Asana Ticket:** [Scheduled Trips Still Showing During Closure](https://app.asana.com/0/555089885850811/1205113827581160)
---
=> feat(DepartureTimes): Display badge when station closed

apps/predictions/lib/predictions_pub_sub.ex, apps/predictions/lib/stream.ex, apps/predictions/lib/stream_supervisor.ex, apps/predictions/lib/stream_worker.ex, apps/predictions/test/predictions_pub_sub_test.exs, apps/predictions/test/stream_supervisor_test.exs, apps/v3_api/lib/stream.ex
**Asana Ticket:** [Close open connections to the API when there are no longer subscriptions to the stream](https://app.asana.com/0/385363666817452/1205293745657616/f)
I ended up not implementing an explicit `unsubscribe` function as originally written in the attached Asana ticket, as I came to realize:
* Subscribers listed in the `:prediction_subscriptions_registry` were already being removed automatically,
* When subscribers were removed, this wasn't via an `:unsubscribe` event. The processes that were subscribed were simply being shut down whenever a channel was closed.
I considered adding some code to a `terminate/2` callback in `SiteWeb.PredictionsChannel`, but ran into some race conditions around handling its `pid` and lookup in the registry, then I came across this note in the …
=> feat: add mechanism for closing streams of prediction data

apps/trip_plan/lib/trip_plan/api/open_trip_planner/parser.ex
**Asana Ticket:** [Fix massport shuttle labels in the trip planner](https://app.asana.com/0/1204355099788517/1205378240957261/f)
OTP2 fixed an issue where underscores were removed from GTFS feed IDs, but dotcom was expecting the Massport ID to always be missing the underscore that it has in GTFS. This was resulting in Massport shuttles not being labeled as such and just appearing as regular buses. This adds another case with the underscore to mark IDs as Massport ones.
Broken:
(Yes, that 88 schedule link goes to the MBTA 88 😱)
Fixed:
---
=> Resolve an issue with Massport shuttle labels

apps/site/assets/ts/app/__tests__/channels-test.ts, apps/site/assets/ts/app/channels.ts, apps/site/assets/ts/helpers/socketTestHelpers.ts, apps/site/assets/ts/hooks/__tests__/usePredictionsChannelTest.tsx, apps/site/assets/ts/hooks/usePredictionsChannel.ts
Set the default value of the predictions channel to an empty array.  The channel helpers now return null if there are any errors.  Allowing the error banner to behave as originally intended.
**Asana Ticket:** [Loading error banner appears while loading](https://app.asana.com/0/555089885850811/1205250017202658)
---
=> feat(PredictionsBanner): Banner only shows when the socket errors out

apps/predictions/lib/predictions_pub_sub.ex, apps/predictions/lib/stream_supervisor.ex, apps/predictions/lib/stream_topic.ex, apps/predictions/lib/stream_worker.ex, apps/predictions/test/predictions_pub_sub_test.exs, apps/predictions/test/stream_supervisor_test.exs, apps/predictions/test/stream_topic_test.exs, apps/route_patterns/lib/repo.ex, apps/route_patterns/test/repo_test.exs, apps/site/assets/ts/hooks/__tests__/usePredictionsChannelTest.tsx, apps/site/assets/ts/hooks/usePredictionsChannel.ts, apps/site/lib/site_web/channels/predictions_channel.ex, apps/site/test/site_web/channels/predictions_channel_test.exs
**Asana Ticket:** [Refactor the predictions stream to always connect to predictions for a route+direction instead of allowing connections per-stop](https://app.asana.com/0/385363666817452/1205293745657620/f)
`SiteWeb.PredictionsChannel` defines a topic for a stop, and a new abstraction, `Predictions.StreamTopic`, translates this into one or more route/direction combinations, in accordance to the route patterns in service for each stop.
Each route/direction is associated with a distinct V3 API stream. Each stream is registered separately, so that we can handle leaving topics/closing streams in a granular way. For example, if both `stop:place-state` and `stop:place-wondl` are joined, then `stop:place-state` is left, the streams associated with predictions for the Orange line would be …
=> refactor: connect to predictions stream using route+direction

apps/site/assets/ts/components/ErrorPage.tsx, apps/site/assets/ts/jest.config.js, apps/site/assets/ts/stop/stop-redesign-loader.tsx
This PR adds an error boundary, because React Router highly recommends it, and their default display is super ugly! I used Sentry's built-in `ErrorBoundary` component for this, which has the bonus of automagically sending the error to Sentry.
- As the fallback display, I wrote a new React component, `ErrorPage`, that's meant to imitate our current error page.
> [!Note]
> There are some small deviations from our normal error pages:
- Our error pages typically show an error code at the top, but we don't technically know the error code as this error boundary could catch anything, so I've omitted that part.
- I couldn't use our current blinky bus SVG image because those have the error codes written on them. See?
But I found a cute GIF in our `/images/` folder with …
=> feat(StopPageRedesign): add an error boundary

apps/route_patterns/lib/repo.ex, apps/route_patterns/lib/route_pattern.ex, apps/route_patterns/test/repo_test.exs, apps/routes/test/parser_test.exs, apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/schedule/components/__tests__/ScheduleFinderTest.tsx, apps/site/assets/ts/schedule/components/__tests__/test-data/routePatternsByDirectionData.json, apps/site/assets/ts/schedule/components/direction/__tests__/BusMenuTest.tsx, apps/site/assets/ts/schedule/components/direction/__tests__/reducer-test.tsx, apps/site/lib/site_web/controllers/route_controller.ex, apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/lib/site_web/controllers/schedule/timetable_controller.ex, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/stops/lib/route_stop.ex
The line diagrams for all rail routes now display stops from the canonical route patterns! Because bus routes and ferry routes have no canonical information for the moment, those remain unchanged.
**Asana Ticket:** [Update the line diagram to use canonical route information](https://app.asana.com/0/385363666817452/1205263426482070/f), part of but not all of  [Actually finish removing the dependency on shape.stop_ids](https://app.asana.com/0/1203354074531980/1199671224586821/f)
So... in support of [Stops showing Headsign for Route Even if One Direction of Travel](https://app.asana.com/0/385363666817452/1205268760549362/f) I figured out how to parse the route pattern's stops directly **from the representative trip, as opposed to from the related _shape_** (which is technically deprecated …
=> refactor(RoutePattern): get `stop_ids` from trip ++ related improvements

apps/site/assets/static/robots.txt, apps/site/lib/site_web/templates/layout/app.html.eex
**Asana Ticket:** [Don't let Cubic payment URLs get indexed by Google during test phase](https://app.asana.com/0/385363666817452/1205542506645866/f)
---
update robots.txt to stop urls from being indexed
=> Don't let Cubic payment URLs get indexed by Google during test phase

apps/site/assets/ts/app/helpers/testUtils.ts, apps/site/assets/ts/schedule/components/ScheduleDirection.tsx, apps/site/assets/ts/schedule/components/ScheduleLoader.tsx, apps/site/assets/ts/schedule/components/__schedule.d.ts, apps/site/assets/ts/schedule/components/__tests__/ScheduleDirectionTest.tsx, apps/site/assets/ts/schedule/components/__tests__/ScheduleLoaderTest.tsx, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/ExpandableBranch.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagramWithStops.tsx, apps/site/assets/ts/schedule/components/line-diagram/StopCard.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/DiagramTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/LineDiagramTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/LineDiagramWithStopsTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/LineTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/StopCardTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/DiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/StopCardTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/graphics/Diagram.tsx, apps/site/assets/ts/schedule/components/line-diagram/graphics/Line.tsx, apps/site/assets/ts/schedule/components/line-diagram/graphics/Merges.tsx, apps/site/assets/ts/schedule/components/line-diagram/graphics/useTreeStopPositions.ts, apps/site/lib/site_web/controllers/schedule/line.ex, apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/lib/site_web/controllers/schedule/line_api.ex, apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/test/site_web/controllers/line_api_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs
No ticket - fixing a bug on dev with the 217 & 120 bus route schedule pages.
- #1755 
The recent PR updated how stops were being fetched for the line diagram, but came with corrected data that broke the line diagram code on at least two pages. It turns out the recursive code that parses the stops to draw the branches on the line diagram assumes that each stop ID is unique, which is assuredly not the case for the 217 and 120 routes, each of which repeat at least one stop along its route.
The approach I took here was to just not compute the stop tree for pages for a ferry or bus route. We don't need it - these either don't have line diagrams or have simple lines that won't branch.
- Consolidated the two places that were computing a stop tree into one function
- Adjusted that function to …
=> hotfix(ScheduleDirection): fix line diagram for routes with repeated stops

apps/site/assets/css/_stop-card.scss, apps/site/assets/ts/helpers/departureInfo.tsx, apps/site/assets/ts/hooks/__tests__/useRouteTest.tsx, apps/site/assets/ts/hooks/useRoute.ts, apps/site/assets/ts/stop/__tests__/DepartureCardTest.tsx, apps/site/assets/ts/stop/__tests__/DeparturesAndMapTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageDeparturesTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageDeparturesTest.tsx.snap, apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/__tests__/helpers.tsx, apps/site/assets/ts/stop/components/DepartureCard.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx, apps/site/assets/ts/stop/components/DeparturesWithBadge.tsx, apps/site/assets/ts/stop/components/StopPageDepartures.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx, apps/site/assets/ts/stop/stop-redesign-loader.tsx, apps/site/lib/site_web/controllers/route_controller.ex, apps/site/lib/site_web/controllers/stop_controller.ex, apps/site/lib/site_web/router.ex, apps/site/test/site_web/controllers/route_controller_test.exs, apps/site/test/site_web/controllers/stop_controller_test.exs
**Asana Ticket:** [Stops showing Headsign for Route Even if One Direction of Travel](https://app.asana.com/0/385363666817452/1205268760549362/f)
- Adds `/api/stop/:stop_id/route-patterns` to get a JSON object of augmented route patterns grouped by headsign and route ID.
- Replaces the `/routes/by-stop/:stop_id` with `/routes/:route_ids` that returns a JSON response containing a simple list of routes.
- The polyline information continues to be computed in the backend, but is now part of the route pattern response as opposed to appending the routes response.
- Adds a `loader` to the React Router's configuration to fetch the route patterns, which will be available from within child components via React Router's `useLoaderData()` hook. Disables revalidation because this data is not going to …
=> refactor(StopPageRedesign): use route patterns

apps/site/lib/site_web/controllers/schedule/timetable_controller.ex, apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs
**Asana Ticket:** [Timetable | Add "via Fairmount line" note to more Franklin/Foxboro trains](https://app.asana.com/0/385363666817452/1205632277310611/f)
I basically followed the approach of [this prior state of code](https://github.com/mbta/dotcom/commit/f3747d824254fdf9988d36d58cdf0f4486e7106c). The "Via Fair- Mount Line" messages shows in the timetable for CR-Franklin for 4-5 trains in each direction, spanning 5 or 4 cells between Reading and Back Bay stations (the difference accounts for Hyde Park being omitted in one direction).
---
=> fix(TimetableController): update via-Fairmount trains

apps/route_patterns/lib/route_pattern.ex, apps/services/lib/repo.ex, apps/services/lib/service.ex, apps/services/test/repo_test.exs, apps/services/test/service_test.exs, apps/site/lib/site_web/controllers/stop_controller.ex, apps/v3_api/lib/services.ex, apps/v3_api/test/services_test.exs
Instead of using all route patterns from the whole rating, this PR adjusts the stop page's backend response for route patterns to remove those associated with services that aren't applicable today. 
On the stop page, this removes headsigns associated with route patterns for this weekend's shuttle service, later disruptions, and so on.
---
=> fix(SiteWeb.StopController): don't show route patterns for services that aren't running today

.github/workflows/deploy-auto.yml, .github/workflows/deploy-manual.yml, .github/workflows/deploy-pr.yml, .github/workflows/deploy-release.yml, .github/workflows/use-deploy-ecs.yml
**Asana Ticket:** [Update workflows repo to point to V2 actions and use assumed role instead of keys](https://app.asana.com/0/0/1205570959197530/f)
This PR updates the `use-deploy-ecs` workflow to use v2 of the shared `build-push-ecr` and `deploy-ecs` actions. These updated actions assume an IAM role instead of relying on long-lasting AWS keys for an IAM user. 
Note: Other workflows that rely on the `deploy-ecs` [workflow](https://github.com/mbta/workflows/blob/main/.github/workflows/deploy-ecs.yml) will be updated at a later date.
=> Chore: Update GitHub actions to use assumed role

apps/stops/test/api_test.exs, apps/stops/test/repo_test.exs, apps/v3_api/lib/v3_api.ex, apps/v3_api/test/services_test.exs, apps/v3_api/test/v3_api_test.exs
We discovered sometimes a service ID might contain a space character. And we were not able to get that service information from the API because we weren't encoding the URL. This fixes that, along with updating related tests.
It also appears the V3 API now doesn't allow for fetching all services without any filter parameters, so another test has been updated to account for that.
---
=> fix(V3Api): encode url for v3 api requests

apps/algolia/lib/algolia/api.ex, apps/algolia/lib/algolia/application.ex, apps/algolia/mix.exs, apps/algolia/test/api_test.exs
While working on the autocomplete widget I noticed an opportunity for us to cache our requests to the Algolia REST API!
This PR uses our existing `RepoCache` module to cache the POST requests we make to Algolia, based on two parameters
1. The **request `body`**. It's a gnarly string of text looking something like this (yes it's a query for the letter `r`).
```
"{\"requests\":[{\"query\":\"r\",\"params\":\"analytics=false&clickAnalytics=true&facetFilters=%5B%5B%5D%5D&facets=%5B%22*%22%5D&hitsPerPage=5\",\"indexName\":\"routes\"},{\"query\":\"r\",\"params\":\"analytics=false&clickAnalytics=true&facetFilters=%5B%5B%5D%5D&facets=%5B%22*%22%5D&hitsPerPage=2\",\"indexName\":\"stops\"},{\"query\":\"r\",\"params\":\"analytics=false&clickAnalytics=true&facetFilters=%5B%5 …
```
=> feat(Algolia.Api): cache requests

apps/stops/lib/route_stop.ex, apps/stops/test/route_stop_test.exs
**Asana Ticket:** [Omit shuttles as connections on schedule page line map](https://app.asana.com/0/385363666817452/1205743983345585/f)
**Before:** (Mattapan Line)
This PR removes references to shuttle routes from the line diagram.
**After:**
---
=> fix(Stops.RouteStop): omit shuttle connections

apps/site/assets/ts/ui/__tests__/autocomplete-templates-test.tsx, apps/site/assets/ts/ui/autocomplete/templates/algolia.tsx
**Asana Ticket:** [🔍  Search | Flex Pass Search Bug](https://app.asana.com/0/385363666817452/1204551723865238/f)
Making use of a browser feature called **Text Fragments** in order to have the search box navigate to a section of arbitrary text on the page. See the Asana issue for context behind why I decided to take that approach.
More resources around the browser feature:
- [Boldly link where no one has linked before: Text Fragments (web.dev)](https://web.dev/articles/text-fragments)
- [Text fragments (MDN reference)](https://developer.mozilla.org/en-US/docs/Web/Text_fragments)
- [URL Scroll-To-Text Fragment (Can I use...)](https://caniuse.com/url-scroll-to-text-fragment)
---
=> feat(autocomplete): link to text fragment

apps/site/lib/site_web/router.ex, apps/site/lib/site_web/www_redirector.ex, apps/site/test/site/lib/www_redirector_test.exs
Asana Ticket: [Redirect requests to /charlie](https://app.asana.com/0/385363666817452/1205692575718677/f)
Added a couple features to the existing `SiteWeb.WwwRedirector` module, to support redirecting to an external host, and to support using the path that's matched by the router's `/*path` declaration. The latter was needed to prevent `mbta.com/charlie/something` from redirecting to `charlie.mbta.com/charlie/something`.
---
=> feat(SiteWeb.Router): add /charlie/* redirects

apps/site/lib/site_web/controllers/schedule_controller.ex, apps/site/test/site_web/controllers/schedule_controller_test.exs
**Asana Ticket:** [Stop pages intermittently missing Commuter Rail schedules](https://app.asana.com/0/385363666817452/1205814823003719/f)
I happened to be able to consistently reproduce the problem for a particular bus route on a particular stop on prod... but ultimately I never figured out a definitive cause for this. Splunk didn't reveal any errors. No network problems or console errors. I suspect that caching _might_ exacerbate the problem and cause the backend to return `[]` instead of re-trying within the cache `max_age` window. But still, ideally it wouldn't erroneously return `[]` in the first place.
This PR does 3 things:
1. Returns an error response if the `Schedules.Repo.schedules_for_stop/2` call returns `{:error, error}` value. An error will be logged in Splunk and the …
=> feat(ScheduleController): smaller schedules_for_stop response + logging

apps/site/assets/css/_global-navigation.scss, apps/site/assets/ts/app/global-navigation.ts
**Asana Ticket:** [Address keyboard navigation issues with header navigation bar](https://app.asana.com/0/385363666817452/1205380245423065/f)
**Asana Ticket:** [Opening navbar dropdowns shifts whole page](https://app.asana.com/0/385363666817452/1205466554569829/f)
The first was addressed by changing a CSS property; setting `display: none` takes the element out of the accessibility tree, thus it's not reachable via tab key. 
The second needed the addition of `{ reserveScrollBarGap: true }` to the `disableBodyScroll` call, along with some CSS and JS hackery to get the expanded menu and the background grey cover to look decent.
=> fix(navigation): fix tab order and layout shift

apps/trip_plan/lib/trip_plan/api/open_trip_planner.ex, apps/trip_plan/lib/trip_plan/api/open_trip_planner/parser.ex
Noticed the itineraries were no longer linking to intermediate stops, and that that was from the `%NamedPosition{}` always having a `nil` `stop_id`. 
Left is #1791 , right is on current dev - note hyperlinked stop names, attached alert icons.
This PR repopulates that value and fixes the result to show links and alert icons as before.
=> feat(OpenTripPlanner): add stop ID to response

apps/site/assets/css/_autocomplete-theme.scss, apps/site/assets/ts/ui/__tests__/__snapshots__/autocomplete-test.ts.snap, apps/site/assets/ts/ui/__tests__/autocomplete-test.ts, apps/site/assets/ts/ui/autocomplete/index.ts, apps/site/lib/site_web/components.ex, apps/site/test/site_web/components_test.exs
this fixes a Safari bug where the tab order traps keyboard focus in between the autocomplete input and submit buttons. the bug only happened on Safari, when using the React renderer instead of the default Preact renderer.
some CSS refactoring was needed to target elements that are inside the new panelContainer element.
Asana Ticket: [Can't tab past navbar search on macOS/Safari](https://app.asana.com/0/385363666817452/1205862370279606/f)
=> hotfix(autocomplete): use separate panelContainer

apps/site/assets/css/_stop-card.scss, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx
Let the fixed positioning maintain the boundaries of this section, but give it a grid display and lay out the scrollable section as a scrollable grid item. This does end up moving the scrollable functionality from `.stop-departures--realtime` to its parent element.
I tested this out using the MacOS built-in Simulator application for an iPhone 14 Plus and iPhone 14 Pro. To me it looks like it no longer sliiiightly truncates the end of the departures list.
**Asana Ticket:** [Stop page | long departure lists should not be cut short on mobile](https://app.asana.com/0/385363666817452/1205822245998059/f)
=> fix(DepartureList): better mobile fullheight view

apps/route_patterns/lib/route_pattern.ex, apps/routes/test/parser_test.exs, apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/helpers/departureInfo.tsx, apps/site/assets/ts/models/route-patterns.ts, apps/site/assets/ts/schedule/components/__tests__/ScheduleFinderTest.tsx, apps/site/assets/ts/schedule/components/__tests__/test-data/routePatternsByDirectionData.json, apps/site/assets/ts/schedule/components/direction/__tests__/BusMenuTest.tsx, apps/site/assets/ts/schedule/components/direction/__tests__/reducer-test.tsx, apps/site/assets/ts/stop/__tests__/DepartureCardTest.tsx, apps/site/assets/ts/stop/__tests__/DeparturesAndMapShuttleTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageDeparturesTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx, apps/site/assets/ts/stop/__tests__/helpers.tsx, apps/site/assets/ts/stop/components/DepartureCard.tsx, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx, apps/site/assets/ts/stop/components/StopPageDepartures.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx, apps/site/assets/ts/stop/stop-redesign-loader.tsx
**Asana Ticket:** [Omit uncommon Green Line branches/headsigns with no upcoming service](https://app.asana.com/0/385363666817452/1205743915866207/f)
There are a couple extra commits because our code wasn't using the V3 API's `canonical` attribute for route patterns. Most of this PR's file changes are due to this.
The main part of this PR, in the final commit, checks the `canonical` value for subway route patterns against the list of departures to determine whether to hide a specific headsign. Additionally, if all the headsigns for a given route card end up hidden, the route card itself will also be hidden.
**Before and After:**
In the early morning when the other Green Line branches run trains this way, those schedules/predictions _should_ show up on this page, though I haven't captured a …
=> feat(StopPageDepartures): Omit uncommon Green Line branches/headsigns with no upcoming service

apps/site/assets/js/trip-planner-location-controls.js, apps/site/lib/site/trip_plan/location.ex, apps/site/lib/site_web/templates/partial/_trip_planner_widget.html.eex, apps/site/lib/site_web/templates/trip_plan/_to_from_inputs.html.eex, apps/site/test/site/trip_plan/location_test.exs, apps/trip_plan/lib/trip_plan/api/open_trip_planner.ex, apps/trip_plan/lib/trip_plan/api/open_trip_planner/builder.ex, apps/trip_plan/test/api/open_trip_planner/builder_test.exs
This pull request allows us to query OTP using stop ids.  This is supposed to remove walking directions to get to the initial stop if the user is already assumed at the stop.
**Asana Ticket:** [Fix Trip planner origin and destinations](https://app.asana.com/0/home/1201123880594717/1205711841709226)
---
=> feat(TripPlanner): Use Stop ID to query OTP

apps/predictions/lib/predictions_pub_sub.ex
**Asana Ticket:** [Stop page loads predictions and schedules slowly (Predictions)](https://app.asana.com/0/555089885850811/1205902724791995/f)
By adding immediate broadcasting of the `:reset` events coming from the predictions stream, I was able to decrease the time-to-first-predictions on the Haymarket page in Chrome desktop from 11145 ms to 715 ms (-93.6%). (This was measured using `console.time` and `console.timeEnd` on the predictions being output from the `usePredictionsChannel` hook). Similar decreases were seen at other stops.
My understanding is that reset events are generally the first event after subscribing to a stream, though they can happen at other points during the stream as well. :) So that seemed like a reasonable place to immediately send the predictions to subscribing …
=> feat(PredictionsPubSub): immediately broadcast resets

apps/routes/lib/route.ex
No Asana ticket. Just a drive-by change I noticed while copying API files out.
fix: Remove unused `combined_route?` function
This was added in PR #1099. The rest of the code added in that PR was later removed in PR #1146, but this function was missed.
---
=> fix: Remove unused `combined_route?` function

rel/vm.args
No ticket.
I was observing how our redesigned stop page increased our memory usage noticeably. One thing our stop page does that's new is maintain a connection to streaming predictions from the V3 API, and publish the streaming updates to subscribed channels via Phoenix PubSub.
Eventually I found a blog post[0] suggesting that maintaining long-lived connections to Phoenix Channels can result in higher memory usage than necessary, and that setting a smaller value for `ERL_FULLSWEEP_AFTER` can force the system to do a full-sweep garbage collection sooner. 
I do have some other optimizations planned in the next couple days, but I wanted to deploy this change in isolation so I can observe its effect.
[0]: [Using Phoenix Channels? High Memory Usage? Save Money With …
=> chore: add custom `ERL_FULLSWEEP_AFTER` value

apps/predictions/lib/store.ex
Currently, it doesn't like we have any way of knowing whether or not remove prediction events are being sent. This will log all remove prediction events so we can tell whether or not they're sent...
=> Log when a remove prediction event occurs

apps/site/assets/ts/stop/components/DisplayTime.tsx
Add the trip id to departures on a stop page so that we can more easily debug problems with schedules and predictions.
=> Add a trip id data attribute

apps/holiday/lib/repo.ex, apps/holiday/test/repo_test.exs
No ticket, just updating the list of dates so that holidays show in the timetable's date picker again.
=> fix(Holidays): Add recent and near-future dates

.tool-versions, Dockerfile
I can finally compile this with [wxWidgets](https://formulae.brew.sh/formula/wxwidgets) and run `:observer` woohoo!!!
=> chore: upgrade erlang to OTP 24

apps/predictions/lib/store.ex
Instead of collecting predictions indefinitely, delete old predictions from the ETS table every so often.
- Out of concern for removing visibility of predictions that're still being shown on the page, I added a buffer of a minute. So this'll just delete predictions for times earlier than that minute.
- It was an arbitrary choice of 5 minute intervals to run this, open to other suggestions.
=> feat(Predictions.Store): clear old predictions

apps/predictions/lib/predictions_pub_sub.ex, apps/predictions/test/predictions_pub_sub_test.exs, apps/site/lib/site_web/channels/predictions_channel.ex
**Asana Ticket:** [Investigate high memory usage from streaming predictions on stop page](https://app.asana.com/0/555089885850811/1206184081297463/f)
I was able to achieve lower sustained memory usage on `Predictions.PredictionsPubSub` by:
- Removing map-based state, because the reference to the old states are kept in memory. This uses ETS tables instead
- Removing overhead of `Process.monitor` by sending a custom message on channel `terminate/2`.
- Setting `:hibernate` on various calls in `Predictions.PredictionsPubSub`
---
=> refactor(PredictionsPubSub): change state, reduce memory

apps/location_service/lib/aws_location/aws_location.ex, apps/site/assets/css/_autocomplete-theme.scss, apps/site/assets/js/algolia-result.js, apps/site/assets/js/trip-planner-location-controls.js, apps/site/assets/ts/ui/__tests__/autocomplete-helpers-test.ts, apps/site/assets/ts/ui/__tests__/autocomplete-plugins-test.ts, apps/site/assets/ts/ui/autocomplete/__autocomplete.d.ts, apps/site/assets/ts/ui/autocomplete/helpers.ts, apps/site/assets/ts/ui/autocomplete/index.ts, apps/site/assets/ts/ui/autocomplete/plugins.ts, apps/site/assets/ts/ui/autocomplete/plugins/geolocation.ts, apps/site/assets/ts/ui/autocomplete/plugins/locations.ts, apps/site/assets/ts/ui/autocomplete/plugins/popular.ts, apps/site/assets/ts/ui/autocomplete/templates/geolocation.tsx, apps/site/assets/ts/ui/autocomplete/templates/location.tsx, apps/site/assets/ts/ui/autocomplete/templates/popular.tsx, apps/site/lib/site_web/components.ex, apps/site/lib/site_web/controllers/fare_controller.ex, apps/site/lib/site_web/controllers/places_controller.ex, apps/site/lib/site_web/router.ex, apps/site/lib/site_web/templates/error/error_layout.html.heex, apps/site/lib/site_web/templates/fare/proposed_sales_locations.html.heex, apps/site/lib/site_web/templates/fare/retail_sales_locations.html.heex, apps/site/lib/site_web/templates/layout/_new_header.html.heex, apps/site/lib/site_web/templates/layout/_new_nav_mobile.html.heex, apps/site/test/site_web/components_test.exs, apps/site/test/site_web/controllers/places_controller_test.exs
**Asana Ticket:** [AutocompleteJS v1.0 | Sales locations pages](https://app.asana.com/0/385363666817452/1205902725457090/f)
- /fares/retail-sales-locations
- /fare-transformation/proposed-sales-locations
Updates the big search input on these two pages to upgrade the underlying AutocompleteJS library to version 1 by adopting our custom functional component, `<.algolia_autocomplete />`.
In the dropdown, clicking a location is supposed to take you to a relevant URL for that location. Before, we had this hard-coded to link to Transit Near Me. But that won't work for these two pages, as they're supposed to keep you on the same page! I got tired of stringing together URLs and moved over the URL-creating to the backend (so that I could use Phoenix's route helpers to just create the right URL, …
=> AutocompleteJS v1.0 | Sales locations pages

apps/predictions/lib/predictions_pub_sub.ex, apps/predictions/lib/store.ex, apps/predictions/lib/stream.ex, apps/predictions/lib/stream_supervisor.ex, apps/predictions/lib/stream_topic.ex, apps/predictions/lib/stream_worker.ex, apps/predictions/test/predictions_pub_sub_test.exs, apps/predictions/test/store_test.exs, apps/predictions/test/stream_supervisor_test.exs, apps/predictions/test/stream_test.exs, apps/predictions/test/stream_topic_test.exs, apps/site/lib/site_web/channels/predictions_channel.ex
**Asana Ticket:** [Predictions.Store | remove predictions on :reset event](https://app.asana.com/0/385363666817452/1206160446331599/f) 
- Handles reset events by removing the relevant predictions before adding new predictions to `Predictions.Store`
- Fixes parsing to correctly handle the `:remove` event, as discovered during  [Stop page displaying mystery extra Red Line prediction](https://app.asana.com/0/385363666817452/1205862370279611/f)
---
=> fix(Predictions.Stream): handle reset and remove events better

config/runtime.exs
Looks like the REDIS_HOST can be set to an empty string in prod. So, we need to check for that at the application level.
=> Change configuration to deal with empty string

cypress/e2e/smoke.cy.js, lib/stops/route_stop.ex
[Link to relevant error source in Splunk](https://mbta.splunkcloud.com/en-US/app/search/show_source?sid=1705519178.13357441&offset=0&latest_time=), which is fairly reproducible when visiting `/schedules/CR-Fairmount/line?schedule_direction%5Bdirection_id%5D=1` - viewing the Fairmount Line's `/line` page initialized to the `1` `direction_id` results in a 500 error because of a function assuming that a shape with a name referencing the Foxboro line exists. This might be something that changed names when the rating changed recently and all the underlying data was updated. 
I suspect this logic was originally put in place due to side effects of our system's somewhat confusing routing of _some_ trains on the Franklin/Foxboro line going "via Fairmount line" (as seen …
=> fix(Stops.RouteStop): remove Fairmount/Foxboro logic

assets/js/cr-timetable-train-icons.js, assets/js/cr-timetable-trains.js, assets/ts/stop/components/StopMap.tsx, lib/dotcom_web/controllers/event_controller.ex, mix.exs
**Asana Ticket:** [Timetable | TypeError: Cannot read properties of undefined (reading 'stop_sequence')](https://app.asana.com/0/385363666817452/1205750830454329/f) and [Timetable | TypeError: undefined is not an object (evaluating 'e.forEach')](https://app.asana.com/0/385363666817452/1205750617538734/f)
Just helps these two errors from Sentry, along with fixing another problem I spotted on Splunk. With an extra commit to hopefully fix the problem devs have seen where SVG icons are not in the expected place.
=> fix: some small things

lib/dotcom_web/controllers/cms_controller.ex, lib/dotcom_web/router.ex, test/dotcom_web/controllers/cms_controller_test.exs
Deleting from the cache is failing for paths with > 2 component parts /one/two/three. This fix makes it so the path can be of any length.
=> Take an arbitrary path for delete cache

lib/dotcom_web/templates/event/_event_teaser.html.eex
**Asana Ticket:** [Events page should show all events in a day](https://app.asana.com/0/385363666817452/1206330231992947/f)
Shows today's events instead of hiding them.
=> fix: more forgiving event page date comparison

assets/ts/models/alert.ts
No ticket, was suggested by @shantigonzales to improve schedule page presentation of the Green Line suspensions happening this month.
| Before | After |
| --- | --- |
| ![green-b-before](https://github.com/mbta/dotcom/assets/2136286/2872afe4-d53d-4a16-9728-bed551638baa) | ![green-b-after](https://github.com/mbta/dotcom/assets/2136286/bd1fd350-d933-43a8-b772-4c0c0a834137) |
=> fix(alert): show suspensions as diversion

assets/ts/components/Alerts.tsx, assets/ts/components/__tests__/__snapshots__/AlertsTest.tsx.snap, lib/alerts/parser.ex, lib/dotcom_web/views/alert_view.ex
No ticket, based on our discussion this morning. Added the time zone abbreviation to the displayed `updated_at` timestamps, for each the backend and frontend renderings of alerts. Converts the parsed alerts to use the `America/New_York` time zone. Updates the snapshot. This'll probably work?
=> feat(Alerts): display updated_at timezone

deploy/monitor/Dockerfile, integration/monitor/ecosystem.config.js
The scenarios script keeps crashing and failing to restart. Running it locally, it doesn't look like it gets anywhere near the memory limit of the task. But, we should set a memory limit anyway. When it reaches the limit, the process will just be restarted. I think the crashes might be related to log rotation. So, I set up some log rotation configuration.
=> Add memory limits on processes and setup log rotation

lib/dotcom_web/controllers/schedule/timetable_controller.ex
skip fetching data for dates outside the rating
it turns out we already had the pieces in place (`conn.assigns.date_in_rating?` is set to true or false using a plug), we just had to use it...
The extra function clause passes along some empty values so the page still renders the same as before. It looks like this.
=> hotfix(TimetableController): check for date in rating

deploy/monitor/Dockerfile, integration/monitor/worker.js, integration/scenarios/search-for-a-subway-line.js
We are seeing issues with Playwright where the browser becomes inaccessible. PM2 will continue to try to restart the process and fail. We don't know the root cause, but we should be closing the page and browser context before we close the browser. This *might* be the issue...causing some kind of memory leak. I've deployed this branch and we'll see if we have any issues.
=> Close the context in Playwright to avoid crashes

.envrc.template, config/config.exs, config/runtime.exs, config/test.exs, lib/cms/repo.ex, lib/dotcom/cache/multilevel.ex, lib/dotcom/cache/publisher.ex, lib/dotcom/cache/subscriber.ex, lib/dotcom/redis/behaviour.ex, lib/dotcom/redix/behaviour.ex, lib/dotcom/redix/pub_sub/behaviour.ex, lib/dotcom_web/controllers/cache_controller.ex, lib/dotcom_web/controllers/cms_controller.ex, lib/dotcom_web/router.ex, test/dotcom/cache/multilevel_test.exs, test/dotcom/cache/publisher_test.exs, test/dotcom/cache/subscriber_test.exs, test/dotcom_web/controllers/cache_controller_test.exs, test/dotcom_web/controllers/cms_controller_test.exs, test/support/mocks.ex
https://app.asana.com/0/555089885850811/1206042318802989/f
Adds the ability to flush the cache according to a given pattern (which could just be one key) by sending an HTTP request with Basic Auth.
=> Flush caches by key

lib/dotcom/realtime_schedule.ex, lib/predictions/repo.ex, test/dotcom/realtime_schedule_test.exs
More specifically, this is a partial revert of 8a50295235a40c7f8b7b9e77d72770a8af36cfaf
This takes `Dotcom.RealtimeSchedule` (used in Transit Near Me) back to the original request parameters for fetching predictions at a frequent interval. We're hoping it improves performance by (1) requesting less data from the V3 API and (2) having less data to parse through on our end.
=> fix(RealtimeSchedule): partial revert of #1915

.github/workflows/push-monitor.yml, deploy/monitor/Dockerfile, integration/health_checks/otp.js
We need to actually call `dumb-init`. We can try redeploying the monitor every 12 hours until we can figure out how to run it somewhere where it won't crash. Maybe using dumb-init will solve the problem...probably not.
=> Use dumb init

lib/dotcom_web/controllers/schedule/line_api.ex
We are getting empty headsigns in predictions. This will log if that happens so that we a) know and b) can see when and where it is happening.
=> log empty headsigns

lib/predictions/repo.ex
We don't want to cache empty predictions. Sometimes, when a node comes online the API informs us that predictions haven't changed. It looks in the cache, sees that it is empty, and returns an error which then gets converted to an empty list.
=> Match that a list of predictions isnt empty

lib/dotcom/transit_near_me.ex, lib/dotcom_web/controllers/schedule/line_api.ex, lib/predictions/repo.ex
We are narrowing down the issues with blank predictions. There is really no point in caching predictions because the TTL is only 10 seconds. And, we don't want to cache realtime responses because they can hold bad data for even longer: 1 minute.
=> Dont cache predictions

lib/routes/repo.ex
Just another tiny change. I'm not sure if this was already caching error responses, but at least this way it's written clearer and also logs errors.
=> fix(Routes.Repo): log errors in by_stop_route_route_pattern

lib/cms/repo.ex
We were a little off on the cache keys that get sent. They are downcase even if our route_id is mixed case. Also, it's `route-pdfs` and not `route_pdfs`.
=> Change keys to use downcase because that is what gets sent to bust

lib/dotcom_web/controllers/schedule/timetable_controller.ex, test/dotcom_web/controllers/schedule/timetable_controller_test.exs, test/support/factory.ex
**Asana Ticket:** [Fix incorrectly ordered timetable stops](https://app.asana.com/0/555089885850811/1206815695536344/f)
The primary change: Ensure stop sorting is consistent with each stop's `zone` number and schedule's `stop_sequence` values
So the simplest sorting that worked consitently across all commuter rail lines involved comparing the `stop_sequence` across all trips. Technically sorting initially by `zone` wasn't needed to show stops in a sensible order, but I found that adding it improved the legibility of a few timetables by placing certain termini stops more proximate to its adjacent stops.
This came with a slight caveat - for Newburyport/Rockport, having two branches which reach similar distances, the branched stops end up displaying interlined instead of clustering by …
=> feat(TimetableController): revised stop sorting

lib/dotcom/cache/multilevel.ex, test/dotcom/cache/multilevel_test.exs
It seems possible for L1 (ETS) and L2 (Redis) to get out of sync. When that happens, we can't flush the cache effectively if the key doesn't exist in Redis but does in ETS. We have to wait for the TTL. This PR makes it so that flushing a single key won't scan Redis for keys and will just send the command to delete it.
=> When only given a key, we dont need to scan redis

README.md, assets/ts/ui/autocomplete/index.ts, integration/scenarios/search-for-a-static-page.js, integration/scenarios/search-for-a-station.js, integration/scenarios/search-for-a-subway-line.js
https://app.asana.com/0/555089885850811/1206695418505883/f
I added a sensible default that when no container id is given, the term 'search' is used to construct ids.
I changed the search for a subway scenario to use the search page so now we have multiple search pathways covered.
=> Add more information to input id and change integration tests

deploy/dev.yml, deploy/dotcom/dev/1/Dockerfile, deploy/dotcom/dev/2/Dockerfile
Adds in dependencies between services so that multiple versions of dotcom don't have to compile the same things. This makes it slow and error prone. Instead, one version of the app launches and then a second one uses the work of the first one.
=> Chain service launch to reduce conflicts

lib/dotcom/content_rewriter.ex
This just handles the case where no pattern can be matched. We log the content and return a safe empty string.
=> Log and render empty string when content cant be rewritten

.github/dependabot.yml, mix.exs
This will get dependabot to stop bothering us about dependencies that we already know we can't upgrade. When we fix the dependency, we'll remove it from the ignore list.
=> Add ignores and comments

.github/workflows/crawler.yml, .github/workflows/deploy-auto.yml, .github/workflows/tests.yml, README.md, assets/package.json, docs/DEPLOYMENT.md, docs/TESTING.md, package.json
Finally renamed `master` branch to `main`.
On your local machines, you can do the following:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
=> chore: reference main branch name

lib/dotcom_web/views/trip_plan_view.ex, lib/trip_plan/transfer.ex, test/dotcom_web/views/trip_plan_view_test.exs
Currently, for a subway -> bus transfer the fare for the first leg is $2.40 which covers the transfer. But, for bus -> subway the fare for the first leg is $1.70. So, we need to add the extra $0.70 transfer fee.
=> Charge a transfer fee for bus to subway transfers

.github/workflows/push-monitor.yml, .github/workflows/use-deploy-ecs.yml
This might not be the desired strategy - maybe we want to deploy the monitor as soon as any changes are merged into master, instead of tying it to deploys this way?
This will not work until the `dorny/paths-filter@v3` action is whitelisted by the org.
=> feat: re-deploy the monitor 

lib/dotcom_web/views/page_view.ex
No ticket, I just noticed this code was probably written before we started parsing route `sort_order` from the V3 API.
=> fix: route sort_order to sort homepage alert route

lib/dotcom_web/plugs/schedule_redirector.ex, lib/dotcom_web/router.ex, lib/dotcom_web/www_redirector.ex, test/dotcom_web/plugs/schedule_redirector_test.exs
No ticket. I'm just tired of seeing tons of failed visits to `/schedules/:route_id/schedule` (e.g. the prior pattern for a schedule page, likely linked from many old pages across the Internet) constantly.
I wrote this plug, inspired by `Www.Redirector`, to redirect those to the appropriate place (`/schedules/:route_id`).
=> feat: redirect bad schedules URLs

assets/ts/ui/autocomplete/templates/algolia.tsx
https://app.asana.com/0/home/1204957179328166/1206833764807735
Super simple. The links sometimes have two forward slashes. When that is the case, we need to remove the first one so the link stays relative to the current domain.
=> Fix broken search links

lib/dotcom_web/controllers/schedule/timetable_controller.ex, test/dotcom_web/controllers/schedule/timetable_controller_test.exs
Back by popular demand (requested by stakeholders to tide us over until a better sorting algorithm has been, well, sorted)
=> hotfix(TimetableController): reinstate earlier sorting

assets/ts/hooks/useRoute.ts, assets/ts/hooks/useStop.ts, cypress/e2e/smoke.cy.js
No ticket, 
1. fixes the persistently failing smoke test by using the correct selector.
2. returns error in addition to `FetchStatus.Error`
=> fix failing test, return error

lib/mbta/api/stream.ex, test/mbta/api/stream_test.exs, test/predictions/stream_supervisor_test.exs
Sorry for breaking this in my earlier commit. This should reinstate the `"Missing required configuration for MBTA API"` error message under the expected conditions.
=> tests: fix tests using :mbta_api config

assets/css/_spacing.scss, assets/css/_stop-bubbles.scss, assets/css/_trip-plan.scss, assets/css/_typography.scss, assets/js/stop-bubbles.js, lib/dotcom/trip_plan/itinerary_row.ex, lib/dotcom_web/templates/partial/_stop_bubble_container.html.eex, lib/dotcom_web/templates/schedule/_stop_list_expand_link.html.eex, lib/dotcom_web/templates/trip_plan/_itinerary.html.eex, lib/dotcom_web/templates/trip_plan/_itinerary_row.html.eex, lib/dotcom_web/templates/trip_plan/_itinerary_row_personal.html.eex, lib/dotcom_web/templates/trip_plan/_itinerary_row_step.html.eex, lib/dotcom_web/templates/trip_plan/_itinerary_stop.html.eex, lib/dotcom_web/templates/trip_plan/_itinerary_transfer_stop.html.eex, lib/dotcom_web/templates/trip_plan/_walk_list_expand_link.html.eex, lib/dotcom_web/views/trip_plan_view.ex, lib/mix/tasks/header_footer.ex, lib/trip_plan/api/open_trip_planner.ex, lib/trip_plan/leg.ex, test/dotcom_web/views/schedule/stop_list_view_test.exs, test/dotcom_web/views/trip_plan_view_test.exs
Adds the walking collapse link, minutes, and distance to the trip planner experience.
**Asana Ticket:** [Walking Directions UX](https://app.asana.com/0/home/1201123880594717/1206991818623256)
---
=> feat(TripPlanner): Walking directions UX update

lib/schedules/hours_of_operation.ex
https://app.asana.com/0/555089885850811/1207183265103207/f
=> Remove redundant with

assets/js/app.js, lib/dotcom_web/templates/partial/_trip_planner_widget.html.eex, lib/dotcom_web/templates/trip_plan/_sidebar.html.eex, lib/dotcom_web/templates/trip_plan/index.html.eex
**Asana Ticket:** [Trip planner 500 error](https://app.asana.com/0/555089885850811/1207250103476225/f)
Rendering the trip planner results requires parsing the form's selections via query params. We had a bug where, when specific modes are requested, the selected modes were not being resolved as query params cleanly because of our use of an anchor link (we send users to a certain spot in the DOM by appending `#plan_result_focus` to the URL), so we'd end up with this as the mode:
```elixir
%{
"bus" => "true",
"commuter_rail" => "true",
"ferry" => "true#plan_result_focus",
"subway" => "true"
}
```
I decided to take an alternate approach and abstain from using an anchor link in this case. Here we use a tiny bit of JS to scroll to the trip planner result. I wanted to use `JS.dispatch` (which …
=> refactor: don't use anchor link in form action

lib/cms/api.ex
These were recently removed in #1999, and probably need to stay in there.
=> hotfix(CMS.Api): restore preview URL params

lib/predictions/repo.ex, test/predictions/repo_test.exs
This fixes the start point of a shuttle disruption from showing predictions and showing the effect title instead
https://app.asana.com/0/home/1201123880594717/1206362494901588
---
=> fix(Schedules): Fix alerts not showing up for stops with inbound trains

assets/ts/schedule/components/RapidTransitHoursOfOperation.tsx
**Asana Ticket:** [Sentry Error: RangeError: Invalid time value](https://app.asana.com/0/555089885850811/1207115579685725/f)
Avoids potentially passing invalid dates to the underlying `formatToBostonTime`.
=> refactor(RapidTransitHoursOfOperation): check date before formatting

config/config.exs, config/test.exs, lib/dotcom_web/controllers/fare_controller.ex, lib/dotcom_web/controllers/places_controller.ex, lib/dotcom_web/controllers/transit_near_me/location.ex, lib/dotcom_web/controllers/transit_near_me_controller.ex, lib/dotcom_web/controllers/trip_plan_controller.ex, lib/location_service/address.ex, lib/location_service/aws_location/request.ex, lib/location_service/behaviour.ex, lib/location_service/location_service.ex, lib/location_service/result.ex, lib/location_service/suggestion.ex, lib/location_service/utils.ex, test/dotcom_web/controllers/places_controller_test.exs, test/dotcom_web/controllers/transit_near_me/location_test.exs, test/location_service/location_service_test.exs, test/support/factory/location_service.ex, test/support/mocks.ex
No ticket, just refactoring and a bunch of test rewriting.
Since `LocationService` uses `ExAws`, and `ExAws` comes with its own behaviour module, I went ahead and setup mocking for that as well, and used that to rewrite the `LocationService` tests.
=> refactor: create `LocationService` behaviour

lib/dotcom_web/controllers/schedule/timetable_controller.ex, lib/routes/route.ex, test/routes/route_test.exs
1. Ferry timetables are all out of order! It turns out using route patterns as a basis for ferry stops does not work well at all, because two of our ferry routes have many route patterns and many possible combinations of stops. I'm adding a separate clause here to handle those more simply.
2. Just threw this in... we'll want to start showing the CapeFlyer route soon, so I've removed it from hidden routes. Note we won't see it yet, because Transit Data still has to expose that route in the V3 API.
=> hotfix(TimetableController): don't sort ferry stops by route pattern

lib/dotcom_web/controllers/schedule/timetable_controller.ex, test/dotcom_web/controllers/schedule/timetable_controller_test.exs
A few more late-coming timetable-related changes arising from the service changes which started this week.
1. Enabled the "via Fairmount line" message for the 752 train.
2. Manually added the Readville stop to the Providence Line timetable (this stop isn't part of any of the Providence Line's canonical route patterns, but is still desired in this table).
3. Removed the 734 train from the Fairmount Line timetable (prior/current state shown below). This involved adding some logic which identifies trips that only make one stop in the timetable (in this train's case, its other stops are part of _another_ route).
=> fix(TimetableController): better reflect new service changes

lib/dotcom_web/controllers/transit_near_me_controller.ex, test/dotcom_web/controllers/transit_near_me_controller_test.exs
Quick followup to https://github.com/mbta/dotcom/commit/aa9f9915f4ecaf4e5f7e220a54dc8fc9ce7b5ddd
- Removes the dependency injection from `TransitNearMeController`
- Refactors test to reflect changes
The rest of this test suite could use some more work... but I have reviews to do. ;)
=> refactor(TransitNearMeControllerTest): update mocks

lib/schedules/repo.ex
Instead of returning `{:ok, nil}`, let the error propagate in `Schedules.Repo.fetch_trip/2`. That way the response isn't cached.
The caller function, `Schedules.Repo.trip/2`, happens to match the error and return `nil`. So downstream nothing actually changes :tada:
=> fix(Schedules.Repo): stop caching unfound trips

lib/dotcom/map_helpers.ex
I confirmed this works on Chrome, Vivaldi, and Safari. If someone can check on Firefox, I think we're good.
=> Use the ferry-map vanity url

assets/css/_stop-card.scss, assets/ts/helpers/__tests__/departureInfoTest.tsx, assets/ts/helpers/departureInfo.tsx, assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, assets/ts/stop/components/DepartureCard.tsx, assets/ts/stop/components/DepartureList.tsx, assets/ts/stop/components/DepartureTimes.tsx, integration/scenarios/view-subway-schedule.js
https://app.asana.com/0/555089885850811/1207376931845116/f
The best way I found to test this with no predictions is to comment out the `PredictionsSupervisor` in `application.ex`.
=> Show "No real-time data" when no predictions

lib/dotcom/map_helpers.ex
Calling static_url in prod gives us a different (and wrong) URL for the ferry map. We can just not call it and use the relative URL.
=> Remove static url wrapper for ferry map link

lib/dotcom_web/controllers/schedule/line.ex, lib/dotcom_web/controllers/schedule_controller.ex, lib/dotcom_web/controllers/trip_plan_controller.ex, lib/dotcom_web/views/page_content_view.ex, lib/mix/tasks/header_footer.ex, lib/stops/nearby.ex
https://app.asana.com/0/home/1201123880594717/1207286684779746
Refactor to reduce function nesting
=> fix(Credo): Reduce function nesting

assets/css/_alerts.scss, assets/ts/components/Alerts.tsx, assets/ts/components/__tests__/AlertsTest.tsx, assets/ts/components/__tests__/__snapshots__/AlertsTest.tsx.snap, lib/alerts/alert.ex, lib/dotcom_web/banneralert.ex, lib/dotcom_web/templates/alert/_banner.html.eex, lib/dotcom_web/templates/alert/_item.html.eex, lib/dotcom_web/views/alert_view.ex, test/alerts/alerts_test.exs, test/dotcom_web/banneralert_test.exs
https://app.asana.com/0/555089885850811/1207270019179507
Add back the alert lifecycle label
Reverts some of the changes found here:
https://github.com/mbta/dotcom/pull/1962/files
=> feat(Alerts): Added back the lifecycle labels

lib/dotcom_web/controllers/customer_support_controller.ex
https://mbta.slack.com/archives/C911LQH2N/p1718310447661849
We got a complaint about the customer support form not working, but no errors were logged. This will log errors whenever the user sees there was an error so that we know what they are.
=> Log all customer support errors when rendering so we know what they are

lib/dotcom/cache/key_generator.ex, lib/dotcom/cache/trip_plan_feedback/key_generator.ex, lib/dotcom/trip_plan/map.ex, lib/dotcom_web/controllers/schedule/schedule_api.ex, lib/trip_info.ex, test/dotcom_web/controllers/helpers_test.exs
https://app.asana.com/0/555089885850811/1207647461641385/f
=> Avoid piping into anonymous functions

lib/dotcom_web/controllers/schedule/finder_api.ex, lib/dotcom_web/controllers/schedule/schedule_api.ex, lib/dotcom_web/controllers/trip_plan_controller.ex, lib/fares/fares.ex, lib/fares/month.ex, lib/fares/one_way.ex, lib/trip_info.ex, test/fares/fares_test.exs, test/fares/month_test.exs, test/fares/one_way_test.exs
While cleaning up code from my (ongoing) trip planner refactoring, I realized there was some fare-calculating logic involved in `Fares.fare_for_stops/4` that is no longer relevant
- The Foxboro pilot logic is from 2019, I'm pretty sure there's no pilot effort involved anymore...
- The combo zones that were introduced in 2020 (PR #601) are no longer relevant, as there are no more `1A-2` or such zones.
This made the `trip` argument no longer needed, so I got to remove it from way too many function calls.
In the meantime I also removed the `:external` tag from a bunch of related tests to stop skipping them, and added the necessary mocks to make those tests work.
=> chore(Fares): remove obsolete logic

lib/location_service/location_service.ex
https://app.asana.com/0/555089885850811/1207746606618659/f
A previous ticket made it simple to change options for AWS locations. This ticket just makes bias the default option for autocomplete while retaining bounding box as the default option for geocode and reverse geocode.
=> Use bias options for autocomplete

lib/dotcom_web/channels/predictions_channel.ex, test/dotcom_web/channels/predictions_channel_test.exs, test/support/factories/predictions/prediction.ex
https://app.asana.com/0/555089885850811/1207779834092092/f
Note, I am rewriting tests, but we want to get this out before this weekend's Red Line issues.
=> Remove predictions that don't have a departure time

assets/css/_autocomplete-theme.scss, assets/js/app.js, assets/package-lock.json, assets/package.json, assets/ts/jest.config.js, assets/ts/phoenix-hooks/algolia-autocomplete.ts, assets/ts/phoenix-hooks/index.ts, assets/ts/phoenix-hooks/leaflet-map.ts, assets/ts/phoenix-hooks/scroll-into-view.ts, assets/ts/phoenix-hooks/trip-planner-form.ts, assets/ts/ui/autocomplete/index.ts, lib/dotcom_web/live/trip_planner/index.ex, lib/dotcom_web/router.ex, lib/dotcom_web/templates/layout/preview.html.heex
**Asana Ticket:** [Set up dev preview page for Trip Planner WIP](https://app.asana.com/0/385363666817452/1207763166362686/f)
Instead of hacking at the current trip planner incrementally, we'll use a fresh view to start implementing the desired UX/UI changes. This page will be shared across the team for iterative feedback while we explore new ways of grouping and displaying itineraries.
> [!Tip]
>
> Visit `/preview/trip-planner` using the basic auth username/password (this is in 1Password under "Dotcom Basic Auth" in the Website Dev vault for prod/dev/dev-blue/dev-green, or locally with `BASIC_AUTH_USERNAME` and `BASIC_AUTH_PASSWORD` environment variables)
=> Set up dev preview page for Trip Planner WIP

assets/js/trip-planner-form.js
**Asana Ticket:** [Shorten trip planner date/time format on input](https://app.asana.com/0/555089885850811/1207666884802652/f)
---
=> fix: use short date format on trip planner

lib/dotcom/content_rewriters/liquid_objects/fare.ex, lib/dotcom/content_rewriters/liquid_objects/route.ex, lib/fares/fare_info.ex, test/dotcom/content_rewriters/liquid_objects/fare_test.exs, test/dotcom/content_rewriters/liquid_objects_test.exs
**Asana Ticket:** [Update RIDE fare cards](https://app.asana.com/0/555089885850811/1207881146339795/f)
This requires adjusting the logic for fetching The RIDE fares, which had assumed they were always reduced value and paid using senior cards... neither of which are true.
=> feat(LiquidObjects): support reduced fares for the RIDE

lib/alerts/repo.ex
Comparison operators don't work with date times.
=> Fix date sorting using timex

assets/ts/stop/__tests__/components/icons/AccessibilityIconTest.tsx, assets/ts/stop/components/icons/AccessibilityIcon.tsx, assets/ts/stop/components/icons/StopFeatures.tsx
**Asana Ticket:** [Inaccurate accessibility icon for station pages](https://app.asana.com/0/385363666817452/1208024340326629/f)
- Removes extra logic in `<AccessibilityIcon />` in favor of reading from the stop's `accessible` attribute, which looks pretty correct to me. Some stops I checked and verified:
- Concord, the offending stop cited in the ticket
- Holbrook/Randolph, a commuter rail stop that's actually served by buses and is marked as accessible on the commuter rail map
- Washington St opp Ruggles St, a bus stop, to verify that it's still being marked as accessible
- note: as far as I can tell, there are no commuter rail + bus stations which are marked inaccessible on the map
- Added logic to remove the shuttle routes from being assessed in `<ModeIcons />`. Still not great (these …
=> fix(StopPageHeader): improve mode and accessibility icons

lib/dotcom/trip_plan/related_link.ex, test/dotcom/trip_plan/related_link_test.exs
https://app.asana.com/0/555089885850811/1208024961726077/f
=> Fix related link text for all modes

config/runtime.exs
*This affects only local dev, or any environment that uses `MIX_ENV=dev`.*
The CSP was preventing a wide variety of images from being loaded when running locally. The local-dev CSP doesn't protect us from anything, since it's not used in prod, and it doesn't make use of any re-usable config either, so it's really not serving any purpose aside from creating some challenging local-only issues that are tough to debug.
---
=> feat: Remove local-dev Content Security Policy

README.md, deploy/dev.yml, deploy/dotcom/dev/1/Dockerfile, deploy/dotcom/dev/2/Dockerfile
By mounting `..` into `/app`, we were overwriting the `deps/` directory in the containers with whatever was in the repository when running `docker-compose`. That means that the results from the build steps in the dockerfiles were being overwritten. A particularly annoying effect is that if you run `docker-compose -f deploy/dev.yml up` on a fresh clone, then even though the build step does fetch and build dependencies, `/app/deps` is missing, and the app doesn't start.
This fixes that by explicitly re-mounting the image's `/app/deps` folder into the container, regardless of what's in `..:/app`
---
=> fix: Don't overwrite dep directories in `docker-compose`'ed containers

config/deps/endpoint.exs, test/cms/paragraph_test.exs, test/cms/partial/banner_test.exs, test/cms/partial/whats_happening_item_test.exs
Start `DotcomWeb.Endpoint` without the `server: true` flag in tests.
Starting `DotcomeWeb.Endpoint` with `server: true` causes the tests to fail if anything is already running on the port supplied (in this case `4002`). That conflicts with the docker config, which runs `dotcom-1` on the same port, so if you try to run `mix test` while the docker setup is running, they will reliably fail.
Completely removing `DotcomWeb.Endpoint` runs afoul of [one test][0], which has `localhost:4002` hard-coded in its assertion, which is why I didn't completely obliterate it the `DotcomWeb.Endpoint` invocation. Another option, which I'm open to, would be to remove the hard-coded `localhost:4002` from that test.
[0]: https://github.com/mbta/dotcom/blob/6ba2846bf84efcf545d42b51d08f3860d8ec9d64/test/cms/paragr …
=> tests: Don't start DotcomWeb.Endpoint as a server in tests

deploy/dotcom/dev/Dockerfile
Without this change, if a dependency is updated, then you have to fully rebuild the dotcom docker images. This change allows you to simply restart the containers, which will then pick up updated dependencies.
Depends on:
- #2185
- Dependency is to avoid git conflicts, since the Dockerfile(s) got moved in ☝️.
Note:
- Having `mix deps.get` and `mix deps.compile` in the Dockerfile as well is still helpful because having the dependencies cached in the image allows `mix deps.get` to run much more quickly, and won't need to rebuild the dependencies when restarting a container.
---
=> feat(docker): Add `mix deps.get` to Dockerfile CMD

deploy/dev.yml
The current setup has `dotcom-2` wait for `dotcom-1` to finish starting up before it even starts trying. This PR speeds up `docker compose` startup time, since it doesn't force `dotcom-2` to wait anymore.
```mermaid
flowchart LR
dotcom-1 --> dotcom-2 --> nginx
```
```mermaid
flowchart LR
dotcom-1 --> nginx
dotcom-2 --> nginx
```
- Looks like the chaining was added in https://github.com/mbta/dotcom/pull/1951 in order to keep the parallel `elixir ... mix phx.server` processes from stepping on each other. That's because they were both (under the hood) running `mix deps.compile` and writing to the same `_build` directory, which was mounted in by docker-compose.
- But with the changes introduced in https://github.com/mbta/dotcom/pull/2182, `dotcom-1` and `dotcom-2` aren't sharing the same …
=> feat(docker): Allow dotcom-1 and dotcom-2 start in parallel in docker compose

lib/dotcom/trip_plan/input_form.ex, lib/dotcom_web/components/live_components/trip_planner_form.ex, lib/dotcom_web/live/trip_planner.ex, test/dotcom/trip_plan/input_form_test.exs, test/dotcom_web/live/trip_planner_test.exs
While polishing up the mode selector I struggled to reconcile the current form field values (for modes, initially a list of atoms, e.g. `[:RAIL, :BUS]`) with how the default checkboxes work (each setting a true/false value). Rather than devise some new checkbox group component, I decided to keep the traditional checkboxes and change the form schema. So now modes is a map, where each key is a mode and each value is a boolean. It works great.
I also moved some display logic outside of the form live component. This let me render the selected modes summary outside the form like so :) 
Finally added some missing tests around form validation mostly.
=> chore(TripPlan.InputForm): change modes type from enum to map

assets/css/app.scss, lib/dotcom_web/components/live_components/trip_planner_form.ex, lib/dotcom_web/live/trip_planner.ex
I wasn't quite satisfied with the current experience of waiting for results. This change simplies the form code a bit, and lets us show the submitted form details immediately (black text), while showing a spinner until the results are retrieved (status of this is shown below the black text).
It can also show the error code.
The formatting is also adjusted to be closer to the desired output from the Figma mock, though I couldn't figure out how to format dates with suffixes (e.g. October 11**th** instead of October 11)..
=> refactor(Live.TripPlanner): show form submission while waiting for trips

lib/location_service/location_service.ex
This removes these warnings, which show up any time we run any test
```ex
warning: module attribute @ttl was set but never used
│
10 │   @ttl :timer.hours(24)
│   ~~~~~~~~~~~~~~~~~~~~~
│
└─ lib/location_service/location_service.ex:10: LocationService (module)
warning: module attribute @cache was set but never used
│
9 │   @cache Application.compile_env!(:dotcom, :cache)
│   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
│
└─ lib/location_service/location_service.ex:9: LocationService (module)
```
=> fix: Restore cache calls in LocationService, fixing some warnings

.github/workflows/tests.yml
I've had a few PR's recently that got stuck in a state where there was a build that was required, but that was configured not to run. That has prevented those PR's from being merge-able (Cristen was able to merge them using her ~magic~ admin powers, but it's not good to rely on that).
[Documentation on required status checks](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks) suggests that it's not a good idea to use `paths-ignore` for required checks.
Impacted PR's:
- https://github.com/mbta/dotcom/pull/2177
- https://github.com/mbta/dotcom/pull/2199
=> fix: Remove `paths-ignore` from CI Github Action config

.github/workflows/docs.yml
The `Publish docs` action has been failing consistently for a few weeks with this message:
```
** (Mix) You're trying to run :dotcom on Elixir v1.16.1 but it has declared in its mix.exs file it supports only Elixir ~> 1.17
Error: Process completed with exit code 1.
```
This should fix that.
Example: https://github.com/mbta/dotcom/actions/runs/11371895399/job/31634982030
=> fix: Failing "publish docs" build

mix.exs
In https://github.com/mbta/dotcom/pull/2173, we renamed a bunch of files, but didn't update the `docs` mix task to reflect the new location in the filesystem of the T logo. That was causing the docs task to fail.
This should fix that, and hopefully get the docs task publishing again.
=> fix: Icon location for docs

lib/dotcom/map_helpers.ex
This should fix this problem 👇 on https://www.mbta.com/schedules/subway.
=> fix: Have vanity links point to dotcom, rather than CDN

assets/package-lock.json
I ran `npm --prefix assets install` and got some updates in the package-lock.json! Does this seem legit?
=> update package-lock to reflect metro deps

lib/dotcom_web/channels/predictions_channel.ex, test/dotcom_web/channels/predictions_channel_test.exs
**Asana Ticket:** [Fix: Extraneous <1 minute predictions appearing on Stop Pages](https://app.asana.com/0/555089885850811/1208505215613687/f)
Some facts:
- because the backend endpoint that gives the stop page its schedules is cached, the frontend component refreshes every 15s, filtering out the past schedules. 
- these get merged with the predictions. but plenty of predictions have no corresponding schedule. 
- and apparently there's no frontend mechanism to filter out stale predictions
- in the backend, past predictions get culled out of our in-memory storage every 5 minutes (gotta keep the ETS table size low)
- the streaming connection we have to the V3 API tells us when to add/remove/update/reset our predictions
Filtering the predictions here in `DotcomWeb.PredictionsChannel`, right …
=> fix(PredictionsChannel): filter out past predictions

test/dotcom_web/components/route_symbols_test.exs
This makes assertions less picky. For instance:
```elixir
"Massport Route 55" |> Regex.compile!("i") |> Regex.match?("Massport")
```
is `false`, but
```elixir
"Massport" |> Regex.compile!("i") |> Regex.match?("Massport Route 55")
```
is `true`.
This should hopefully fix the [build that's currently failing](https://github.com/mbta/dotcom/actions/runs/11939144123/job/33279345358).
=> fix: Swap the sense of the Regex.match? call in route_symbols_test

lib/dotcom_web/components/live_components/trip_planner_results_section.ex, lib/dotcom_web/components/trip_planner/itinerary_group.ex, lib/dotcom_web/live/trip_planner.ex, test/dotcom_web/live/trip_planner_test.exs, test/support/factories/trip_planner/trip_planner.ex
https://github.com/user-attachments/assets/a3551943-cac9-4cf2-9590-56bd80954239
**Asana Ticket:** [Trip Planner Preview | Toggle between list and details views](https://app.asana.com/0/555089885850811/1208788271277295/f)
=> feat: Toggle between summary and details view in itinerary panel

lib/dotcom_web/components/live_components/trip_planner_results_section.ex, lib/dotcom_web/components/trip_planner/itinerary_group.ex, lib/dotcom_web/components/trip_planner/itinerary_summary.ex
Extract 👇 to a re-usable component called `<.itinerary_summary />` and re-use it in the details view.
=> feat(trip_planner): Use <.itinerary_summary /> in the details panel

assets/css/_events.scss, lib/dotcom_web/components/live_components/trip_planner_results_section.ex
Looks pretty much the same
---
**Asana Ticket:** [Trip Planner Preview | Scaffold out the responsive mobile/desktop layout](https://app.asana.com/0/555089885850811/1208788271277297/f)
=> feat: Arrange map and plan results correctly on desktop and mobile

assets/ts/stop/__tests__/components/icons/AccessibilityIconTest.tsx, assets/ts/stop/components/icons/AccessibilityIcon.tsx
**[Slack Thread](https://mbta.slack.com/archives/C076FBBC21K/p1733238074242899)**
**[Notion Doc](https://www.notion.so/mbta-downtown-crossing/Accessibility-Inconsistencies-151f5d8d11ea8097ac79d213a592d635?pvs=4)**
=> fix: Remove wheelchair icon from non-accessible stop pages

lib/services/service.ex, test/dotcom_web/controllers/stop_controller_test.exs, test/services/service_test.exs
This accommodates a very specific type of GTFS service, which looks like
%Services.Service{
added_dates: ["2024-12-05"],
added_dates_notes: %{"2024-12-05" => nil},
description: "Weekday schedule",
end_date: ~D[2024-12-04],
name: "Weekday",
id: "LRV42024-hlb44011-Weekday-01",
removed_dates: [],
removed_dates_notes: %{},
start_date: ~D[2024-11-27],
type: :weekday,
typicality: :typical_service,
valid_days: [1, 2, 3, 5],
rating_start_date: ~D[2024-08-25],
rating_end_date: nil,
rating_description: "Fall"
}
The edge case is when the `valid_days` doesn't include the day of the week for the `added_date(s)`. When that happens, the added dates should still be considered served, but the previous version was only handling that correctly if `valid_days` was `[]`.
=> fix: Make Service.serves_date?/2 use added_stops as a full override

lib/dotcom_web/components/live_components/trip_planner_results_section.ex, lib/dotcom_web/components/trip_planner/itinerary_detail.ex
It was bugging me that `expanded_itinerary_index` and `selected_itinerary_detail_index` were separate assigns in `TripPlannerResultsSection` (eventually will get bumped up to `TripPlanner` itself), since in reality, they're more like two parts of the same state. So I decided to try combining them into a single `itinerary_panel_view` assign instead.
Things I like: 
- It's clearer that those two bits of state are in fact related
- It's impossible to accidentally change `expanded_itinerary_index` without also resetting `selected_itinerary_detail_index` (note how those two assigns basically always have to go together in the "before" side of the diff)
Things I'm not sure about:
- With `itinerary_panel_view`, updating which specific itinerary is selected is more of a pain, because we need to …
=> refactor: Change itinerary-panel-view state for TripPlannerResultsSection

lib/dotcom_web/components/trip_planner/itinerary_detail.ex, lib/dotcom_web/components/trip_planner/trip_planner_results_section.ex, lib/dotcom_web/live/trip_planner.ex
Follow up to [this comment](https://github.com/mbta/dotcom/pull/2238#pullrequestreview-2472824039), which suggested biasing much more strongly towards function components, and [this PR](https://github.com/mbta/dotcom/pull/2242), which consolidated the `TripPlannerResultsSection` state into a single variable.
User-facing-wise, this should be a pure refactor, so no visible changes.
No ticket.
=> refactor: Convert TripPlannerResultsSection to a function component

assets/css/_schedule.scss
No ticket.
I happened to notice that the layout looked funky, especially on mobile, with what seemed like a huge amount of dead space above the route pill. And sure enough, the Figma showed 28 pixels, while reality showed 44.
=> fix(layout): Shrink margin-top for schedule headers

assets/ts/stop/__tests__/components/icons/AccessibilityIconTest.tsx
No ticket.
I was so excited to [fix this bug](https://github.com/mbta/dotcom/pull/2244) that I missed that I had [named this test incorrectly](https://github.com/mbta/dotcom/pull/2244/files/9fd27fbcf0c09818f00d233e1d101164cba9b7fb#r1868430770).
=> test: Update inaccurate test name

lib/dotcom_web/components/trip_planner/itinerary_detail.ex, test/dotcom_web/live/trip_planner_test.exs
**Asana Ticket:** [Trip Planner Preview | Suppress "Depart At" buttons if only one itinerary is surfaced in an itinerary group](https://app.asana.com/0/555089885850811/1208923455785213/f)
=> feat: Suppress "Depart at" buttons when there's only one itinerary

lib/dotcom_web/components/trip_planner/itinerary_detail.ex
No ticket.
Maybe the Right™ answer here is to limit to show no more than some reasonable number of "Depart at" buttons, but I also think we should wrap responsibly, in case whatever limiting we try to do still leads to an overflow.
=> fix: Make "Depart at" buttons wrap rather than overflow

test/fares/fares_test.exs
No ticket. Just happened to notice that we were _really_ making sure that we imported the `PersonalDetail` module.
=> cleanup: We only need to alias PersonalDetail once

lib/dotcom_web/components/trip_planner/itinerary_detail.ex
The build is currently failing because of this, and trip planner is broken in dev, so this would be good to merge, assuming that it fixes the problem! 😅 
The change in this PR was missed in [this change](https://github.com/mbta/dotcom/pull/2252/files#diff-305f62bdf1a6c169554d660ab991cb2351a808186609f2fdf0acfe1281b59290)
No ticket.
=> fix: Remove invocation of @target from <.itinerary_detail />

lib/dotcom/trip_plan/map.ex, lib/dotcom_web/components/trip_planner/trip_planner_results_section.ex
=> Itinerary detail map

lib/dotcom/trip_plan/leg_to_segment_helper.ex, test/dotcom/trip_plan/leg_to_segment_helper_test.exs
---
**Asana Ticket:** [🐞 Trip Planner Preview | Details: Duplicate end-location if there's no walking leg at the beginning or end of an itinerary](https://app.asana.com/0/555089885850811/1208939733320494/f)
=> fix: De-duplicate start and end locations when they're next to transit segments

.env.template, README.md, config/runtime.exs, docs/RedisClustering.md
This makes it much easier to run locally, as you can run a single instance of Redis.
=> chore: allow running Redis standalone

lib/dotcom_web/templates/customer_support/index.html.eex
---
**Asana Ticket:** [Update Customer Support feedback message](https://app.asana.com/0/555089885850811/1208960915233452/f)
=> feat: Update confirmation message for the customer support feedback form

assets/ts/schedule/components/__tests__/ScheduleDirectionTest.tsx, assets/ts/schedule/components/__tests__/test-data/lineDiagramData.json, assets/ts/schedule/components/line-diagram/__tests__/DiagramTest.tsx, assets/ts/schedule/components/line-diagram/__tests__/LineDiagramTest.tsx, assets/ts/schedule/components/line-diagram/__tests__/LineDiagramWithStopsTest.tsx, assets/ts/schedule/components/schedule-finder/__tests__/test-data/departures.json, assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/DailyScheduleTest.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/test-data/serviceData.json, assets/ts/schedule/components/schedule-finder/upcoming-departures/__tests__/test-data/enhancedBusJourneys.json, assets/ts/stop/__tests__/stopData.json, assets/ts/ui/autocomplete/__tests__/templates-test.tsx, lib/dotcom_web/controllers/helpers.ex, lib/dotcom_web/controllers/schedule/cms.ex, lib/routes/parser.ex, lib/routes/route.ex, priv/cms/cms/teasers_project.json, test/dotcom_web/controllers/helpers_test.exs, test/dotcom_web/controllers/transit_near_me_controller_test.exs, test/dotcom_web/views/schedule_view_test.exs, test/routes/parser_test.exs, test/routes/repo_test.exs, test/routes/route_test.exs, test/support/factories/routes/route.ex
**Asana Ticket:** [Update bus on schedule summary page](https://app.asana.com/0/555089885850811/1208990226294680/f)
Fixes the missing list of ~key~ frequent buses on the schedules page.
=> chore: completely remove key bus route designation

lib/dotcom_web/views/schedule_view.ex
=> fix: Make the "Service every 15 minutes or better" text black

assets/ts/helpers/service.ts, assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/DailySchedule.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/ServiceOptGroup.tsx
**Asana Ticket:** [Schedule finder "Daily Schedule" selection doesn't match current date](https://app.asana.com/0/555089885850811/1208990596026312/f)
- The logic for "is this service current?" founders in the face of this rating's weekday schedule, which features added dates which are outside of the start/end date range. We improve this by disentangling the added date check from the start/end date check
- The current logic picked the first of today's valid services as the 'default' selection. We improve this by first checking for the `"default_service?"` flag on the service.
=> fix(DailySchedule): improve identification of today's service

lib/dotcom_web/components/trip_planner/results.ex, lib/dotcom_web/live/trip_planner.ex
<details>
<summary>Screenshots</summary>
(Note: The fact that the route is drawn on the map is because of an unrelated bug and has to do with the order in which I took the screenshots, and has nothing to do with this PR)
</details>
**Asana Ticket:** [Fix margins, padding, and borders for the panel to the left of the map](https://app.asana.com/0/555089885850811/1209002105863143/f)
Changes:
- Removed border and margins around the results panel
- Removed a border at the bottom of itinerary details
- Replaced `grid` with `flex` as an implementation for arranging the results panel next to the map
- Made the results panel grow to no more than 500px on desktop
---
=> ui(TripPlanner): Fix margins, paddings, and borders for results panel

lib/dotcom_web/components/trip_planner/start_or_end_place.ex
No ticket.
Added [here](https://github.com/mbta/dotcom/pull/2275/files#diff-7cdebfe6554316ff59636ce0c4ed299e9e2cc8104f7a823992c1196a9f5dfe28R10-R11), but I guess I forgot to remove them when they become unnecessary.
=> cleanup: Remove unused aliases

lib/dotcom_web/components/route_symbols.ex, lib/dotcom_web/components/trip_planner/transit_leg.ex
**Asana Ticket:** [Bus icon should be smaller in itinerary-detail/transit-leg](https://app.asana.com/0/555089885850811/1209018563871717/f)
=> ui(TripPlanner): Use small bus icons in trip planner transit legs

lib/dotcom/trip_plan/input_form.ex, lib/dotcom/trip_plan/itinerary_groups.ex, test/dotcom/trip_plan/itinerary_groups_test.exs
**Before**
- We retrieved 5 itineraries from OTP, then grouped them, and returned them however they were grouped.
- This sometimes led to all of the itineraries being shown as one group, or two groups, and sometimes left out certain itineraries.
- For instance, Logan Airport to North Station can easily be done with the Back Bay Logan Express shuttle, followed by an OL transfer, but if that wasn't in the next 5 trips, then it wouldn't show up.
**After**
- We retrieve 100 itineraries from OTP, group those, and then within each group, surface the next five itineraries (so as not to overwhelm).
**Asana Ticket:** [Increase number of itineraries returned from 5 ](https://app.asana.com/0/555089885850811/1208975267675615/f)
=> feat(TripPlanner): Show more itineraries

lib/dotcom_web/live/trip_planner.ex
- Plan a trip
- Select a specific itinerary
- Return to summary (By clicking "View all options")
---
**Asana Ticket:** [When navigating from details to summary view, the route diagram doesn't vanish from the map](https://app.asana.com/0/555089885850811/1208999575515975/f)
=> fix(TripPlanner): Clear the map when switching back to summary view

lib/dotcom_web/components/trip_planner/input_form.ex
No ticket, but this fixes [a bug that prevents upgrading to phoenix_live_view 1.0.1](https://github.com/phoenixframework/phoenix_live_view/blob/main/CHANGELOG.md#bug-fixes), which is necessary for https://github.com/mbta/dotcom/pull/2283.
The bug is that phoenix_live_view now raises an error if it detects duplicate DOM ID's in tests. These ID's were duplciated, [thus causing the Trip Planner tests to fail](https://github.com/mbta/dotcom/actions/runs/12421971500/job/34682970311?pr=2280).
Blocks:
- https://github.com/mbta/dotcom/pull/2283
=> fix: Make DOM ID's unique for trip planner search boxes

lib/dotcom_web/components/trip_planner/transit_leg.ex
Screenshots above include the walking directions in order to highlight the fact that the route symbol is supposed to be aligned with the walk symbol.
**Asana Ticket:** [Route icon is slightly mis-aligned in itinerary-detail/transit-leg](https://app.asana.com/0/555089885850811/1209018563871715/f)
=> ui(TripPlanner): Fix alignment of route symbol icon in transit leg

lib/dotcom_web/live/trip_planner.ex
---
**Asana Ticket:** [Itinerary detail should show active state on first "Depart at" button](https://app.asana.com/0/555089885850811/1209016991115335/f)
=> fix: Make the first "Depart at" button active when selecting an itinerary group

test/dotcom_web/router_test.exs
Most tests rely on the `HOST` environment variable to be set to `nil`, so that it defaults to `localhost`. If `HOST` is set to `www.mbta.com`, that causes a redirect. `router_test.exs` has a test that validates that redirect, by setting `HOST` to `www.mbta.com`, validating the redirect, and then setting it back to `nil`.
This is what that normally looks like in context:
```mermaid
sequenceDiagram
RouterTest->>Env: set_env("HOST", "www.mbta.com")
RouterTest->>Env: get_env("HOST")
Env-->>RouterTest: "www.mbta.com"
RouterTest->>Env: set_env("HOST", nil)
OtherTest->>Env: get_env("HOST")
Env-->>OtherTest: nil
```
(Note the existence of `OtherTest`, which also retrieves `HOST`, and relies on `HOST` being `nil`.)
BUT, when `router_test.exs`'s execution is interleaved with other tests, then …
=> fix(tests): Prevent router_test.exs from running async

lib/dotcom_web/components/trip_planner/results_summary.ex, test/dotcom_web/live/trip_planner_test.exs
---
**Asana Ticket:** [Remove duplicate "no trips" state](https://app.asana.com/0/555089885850811/1209016991115315/f)
=> fix: Don't show "No trips found" message when there are other errors

.env.template, config/runtime.exs, lib/dotcom_web/router.ex, test/dotcom_web/live/trip_planner_test.exs
Goes with https://github.com/mbta/devops/pull/2400
There might be a better way to organize it? Anyways, this keeps the existing credential for the `/cache` scope but changes the environment variables for the others.
=> feat: add another basic auth credential

assets/ts/ui/autocomplete/__tests__/config-test.ts, assets/ts/ui/autocomplete/config.ts, assets/ts/ui/autocomplete/sources.ts, lib/dotcom/trip_plan/input_form.ex
**Asana Ticket:** [No modes selected should display "Walking only" in the select box](https://app.asana.com/0/555089885850811/1209037564056787/f) and [The special Logan result is not surfaced as a search result, only in zero state](https://app.asana.com/0/555089885850811/1209037564056804/f)
=> cleanup(Live.TripPlanner): even more UI polish

lib/dotcom_web/components/trip_planner/transit_leg.ex
**Asana Ticket:** [Transit legs with 2 stops should be collapsed](https://app.asana.com/0/555089885850811/1209037564056803/f)
(noting here the leg `intermediate_stops` is just the stops between start and end, so it shows "take X for 2 stops" for 1 intermediate stop + the end stop)
=> fix(TransitLeg): collapse for any non-zero number of intermediate stops

lib/dotcom/trip_plan/alerts.ex, test/dotcom/trip_plan/alerts_test.exs
Accessibility not selected:
Accessibility selected:
=> Dont show irrelevant alerts

.env.template
This causes an error if `.env.template` is copied directly into `.env`.
=> fix: Comment out comment explaining readonly basic auth creds

lib/dotcom/trip_plan/anti_corruption_layer.ex, lib/dotcom_web/live/trip_planner.ex, lib/dotcom_web/router.ex, test/dotcom/trip_plan/anti_corruption_layer_test.exs
Last week we discussed whether to port over the old trip planner's feature of geocoding and pre-filling a "From" or "To" destination using the `/to/` and `/from/` URLs. I wanted to see if this could potentially be a quick thing, and this is what I came up with.
=> feat(Live.TripPlanner): support /from and /to shortcuts

lib/dotcom_web/live/admin.ex
No ticket. Just a silly little thing I noticed.
=> cleanup: Use Tailwind classes on admin page instead of inline styles

lib/dotcom_web/live/trip_planner.ex
In https://github.com/mbta/dotcom/pull/2309, we got rid of the `&maybe_round_datetime/1` function, which was the only caller of `&standardize_datetime/1`. This removes that function as well.
Follow-up to:
- https://github.com/mbta/dotcom/pull/2309
---
No ticket, but this does clean up a warning.
=> cleanup: Remove `&standardize_datetime/1` function that's now unused

integration/monitor/all-scenarios.js, integration/monitor/ecosystem.config.js, integration/monitor/worker.js, playwright.config.js
https://app.asana.com/0/555089885850811/1208924776345287/f
I made some small efficiency changes to the monitor and made it so that every night at midnight the all-scenarios script restarts. I couldn't find any correlation between CPU usage or memory usage and degradation of performance. So, I'm hoping simply restarting the script every night works. We already don't run it during off-service hours so no data will be missed.
=> small changes and restart at midnight

lib/dotcom/trip_plan/input_form.ex, lib/dotcom_web/components/trip_planner/input_form.ex, lib/dotcom_web/live/trip_planner.ex, test/dotcom/trip_plan/input_form_test.exs, test/dotcom_web/live/trip_planner_test.exs
This fixes a bug introduced in https://github.com/mbta/dotcom/pull/2309 (oops!)
(Note the lack of error message, but also the lack of actually doing a trip plan)
---
**Asana Ticket:** [Trip Planner | Restore error state for origin == destination](https://app.asana.com/0/555089885850811/1209091204225425/f)
Follow-up to:
- https://github.com/mbta/dotcom/pull/2309
=> fix(tripPlanner): Restore error message if from and to are the same

lib/dotcom_web/live/trip_planner.ex
(Note that the selected itinerary uses the Orange Line, but the line on the map is the Green Line color)
---
No Ticket.
=> fix: Have the map show the selected itinerary, rather than a random member of the group

assets/css/_autocomplete-theme.scss, assets/tailwind.config.js, assets/ts/ui/autocomplete/config.ts, lib/dotcom_web/components/trip_planner/input_form.ex
**Asana Ticket:** [Cannot scroll through location results on mobile (menu disappears when input loses focus)](https://app.asana.com/0/555089885850811/1209037564056799/f)
Trying out this library's [full-screen search experience on mobile](https://www.algolia.com/doc/ui-libraries/autocomplete/core-concepts/detached-mode/), enabled only for the trip planner for now.
=> feat(autocomplete): on mobile for trip planner, use detached experience

assets/css/_autocomplete-theme.scss
=> fix(TripPlanner): Restore A and B on desktop in search boxes

lib/dotcom_web/components/trip_planner/input_form.ex
=> fix(TripPlanner/ui): Decrease padding on the input form for tiny screens

config/config.exs, config/dotcom/dotcom.exs
**Asana Ticket:** [Map tiles should load on production environment](https://app.asana.com/0/555089885850811/1209117947602740/f)
Possible fix! I'm not sure we'll really know til we try it in prod.
=> fix: change metro map config tile URL for prod

config/config.exs
A `minZoom` of 12 doesn't allow riders to zoom out very far at all, which means that trips over a certain distance won't fit on the screen. 
(Lower zoom corresponds to a bigger map - a zoom level of 1 is the entire planet)
---
No ticket.
=> fix: Decrease min zoom on the map to allow riders to zoom out further

lib/dotcom/timetable_blocking.ex, lib/dotcom_web/controllers/schedule/timetable_controller.ex, lib/dotcom_web/templates/alert/_item.html.eex, lib/dotcom_web/templates/schedule/_timetable.html.eex, lib/dotcom_web/templates/schedule/_timetable_blocked.html.eex, lib/dotcom_web/views/alert_view.ex, test/dotcom/timetable_blocking_test.exs, test/dotcom_web/controllers/schedule/timetable_controller_test.exs, test/dotcom_web/views/alert_view_test.exs, test/dotcom_web/views/schedule/timetable_view_test.exs
**Asana Ticket:** [CR disruption timetable improvements](https://app.asana.com/0/116562505129567/1208217281866205/f)
This adds special-case handling for two types of alerts where we want to hide the timetable from view. One case is expected to have a PDF as the URL for the alert, and the other does not. In the PDF case, we hide the timetable and provide the link to the PDF. In the other, we hide the timetable and say "PDF upcoming."
This also changes the rendering of the alert to drop the special-case text, and to say "View PDF schedule" if the PDF link is available.
---
=> feat: hide CR timetable in the presence of special alerts

lib/dotcom_web/components/trip_planner/results_summary.ex
**Asana Ticket:** [TP Accessibility | When results update on page, screenreader should know](https://app.asana.com/0/555089885850811/1209108724880496/f)
I included comments in the code and tried it out using MacOS VoiceOver to hear the changes!
=> feat(TripPlanner.ResultsSummary): make it a live region

assets/js/test/trip-plan_test.js, assets/ts/phoenix-hooks/algolia-autocomplete.ts, assets/ts/ui/autocomplete/__autocomplete.d.ts, assets/ts/ui/autocomplete/index.ts, assets/ts/ui/autocomplete/sources.ts, lib/dotcom_web/components/trip_planner/input_form.ex, lib/dotcom_web/components/trip_planner/results_summary.ex, lib/dotcom_web/live/trip_planner.ex
**Asana Ticket:** [Add switch origin/destination button](https://app.asana.com/0/555089885850811/1208603342838393/f)
Building off of Josh's earlier work in #2231 and elsewhere, implements switching the locations on the form, thus switching the displayed markers on the map, and rerunning the trip planner with new results.
This also includes some cleanup on the `AlgoliaAutocomplete` Phoenix JS hook. Now instead of triggering 4 "change" events for each location input change, we more elegantly fire off _one_ (1) event for the LiveView to handle (just another `"input_form_change"` event, transmitting data selected from the location dropdown).
=> feat(Live.TripPlanner): Add switch origin/destination button

lib/dotcom_web/plugs/secure_headers.ex, lib/dotcom_web/templates/layout/root.html.eex
**Asana Ticket:** [Add Soundcloud to CSP list so we can embed it](https://app.asana.com/0/555089885850811/1209117971448504/f) and [Map tiles should load on production environment](https://app.asana.com/0/555089885850811/1209117947602740/f)
- After #2322 the map tiles couldn't load as they were blocked by the CSP! So the first commit should fix that.
- The second commit adds a missing Google Tag Manager URL that I noticed logged in the console on mbta.com
- The third commit removes an old link from the root template that I only noticed because the CSP yelled about it 😅 The flatpickr library code is distributed with Metro now anyway.
- The fourth commit goes ahead and adds the Soundcloud URL.
=> fix: assorted CSP issues

lib/dotcom_web/live/trip_planner.ex
https://app.asana.com/0/555089885850811/1209110864370903/f
I just changed the order of the elements in the DOM.
=> Change the tab order of itineraries and the map

lib/dotcom_web/live/trip_planner.ex
No ticket. We noticed the map was only taking up part of the page. This is due to the fact that we were calling submit changeset on mount and it was setting loading to true. Now we only try to load itineraries if the changeset is valid.
=> only submit if valid

lib/util/util.ex
=> docs: Fix formatting so that examples render nicely

lib/dotcom_web/components/route_symbols.ex, lib/dotcom_web/components/trip_planner/itinerary_summary.ex
https://app.asana.com/0/555089885850811/1209110864370905/f
=> Add aria labels for itinerary group summaries

lib/util/util.ex
No ticket, but is sort of a blocker for some other PR's out there. 
Blocks:
- https://github.com/mbta/dotcom/pull/2327
---
=> chore: Add `&Util.end_of_service/1`

lib/dotcom/system_status/alerts.ex
Elixir docs will add a link to a function's docs if it's referenced like `active_on_day?/2`, but not if it's referenced like `&active_on_day?/2`. Thus, what I had thought was a link wasn't. This fixes that.
No ticket.
=> docs: Update function name in SystemStatus.Alerts docs to be linkable

lib/dotcom_web/plugs/secure_headers.ex
No ticket
Technically our existing tile server URLs are already in the Content Security Policy directives, via cdn.mbta.com and *.s3.amazonaws.com. But I found this approach helpful when testing out a different URL here.
=> feat: add tile server URL to CSP

assets/css/_autocomplete-theme.scss
No ticket, just a very minor repositioning of the "x" icon to clear the input. This regressed in #2300
Before
After
=> fix(autocomplete): adjust clear button width only in detached mode

assets/ts/stop/__tests__/components/StationInformationTest.tsx, assets/ts/stop/components/StationInformation.tsx
**Asana Ticket:** [Stop pages missing facility information](https://app.asana.com/0/555089885850811/1208613560085954/f)
Before, parking info and bike facility info would be suppressed on stop pages representing bus stops or other "not station" stops. Adjusted the logic so this is no longer the case.
Now we can see...
- Parking and bike storage at ferry docks such as Hingham
- Parking and bike storage at this bus stop near Watertown Yard
- Covered bike racks at Arlington Heights Busway
=> fix(StationInformation): show bike/parking info even for non-stations

lib/dotcom/trip_plan/anti_corruption_layer.ex, test/dotcom/trip_plan/anti_corruption_layer_test.exs
Even though the timezone information is in the ISO8601 string, it doesn't get decoded by DateTime.
```
DATETIME: #DateTime<2025-01-30 18:01:34.508539-05:00 EST America/New_York>
ENCODED: "2025-01-30T18:01:34.508539-05:00"
DECODED: ~U[2025-01-30 23:01:34.508539Z]
```
So, we have to convert it to a datetime with Timex and specify the timezone.
=> When we decode a datetime, we have to cast it to the timezone

lib/dotcom_web/templates/layout/root.html.eex
https://app.asana.com/0/555089885850811/1209320056067616/f
Go to dev-green and you'll see the meta tag in the html head.
=> Tell robots to ignore all pages when the domain is mbtace

assets/ts/ui/autocomplete/sources.ts
Related to [TP | Add an error state when location isn't selected](https://app.asana.com/0/555089885850811/1209320056067619) but not technically that! Chase and I decided to split this into two parts, here's one of those parts.
This PR both:
1. Changes the behavior of this input to keep the dropdown open until an item is selected (or the input is cleared).
2. Adds a display for when there're no results.
Both changes apply to this input generally, not just in the trip planner.
=> feat(autocomplete): add zero state

lib/dotcom_web/plugs/canonical_hostname.ex, test/dotcom_web/plugs/canonical_hostname_test.exs
**Asana Ticket:** Related to [Get rid of mticket.mbtace.com](https://app.asana.com/0/555089885850811/1209322293648193)
This lets mticket.mbtace.com-based visitors get a 301 response and get redirected to mbta.com.
=> chore(Plugs.CanonicalHostname): remove mTicket exception

lib/dotcom_web/live/trip_planner.ex, test/dotcom_web/live/trip_planner_test.exs
It turns out we weren't pattern matching to handle the `%Req.TransportError{reason: :timeout}` we were receiving.
=> feat(Live.TripPlanner): handle OTP timeouts

assets/ts/ui/autocomplete/config.ts
Inspired by [this thread](https://mbta.slack.com/archives/C911LQH2N/p1738766422999089). This PR will simulate selecting the first result if a user presses enter in a location search box. This actually replicates old Trip Planner behavior, which [searches AWS Location Service using the name](https://github.com/mbta/dotcom/blob/main/lib/dotcom/trip_plan/location.ex#L118) in cases when geographic coordinates weren't already provided.
We don't necessarily want this exact same configuration in other usages of the autocomplete component, since some have implemented different behavior. For example, pressing `Enter` in the top nav search bar actually takes you to the search page. :) So this change only affects trip planner as written here.
=> feat(autocomplete): in trip planner, auto-select first result on enter

assets/css/_autocomplete-theme.scss, assets/ts/ui/autocomplete/config.ts, lib/dotcom/trip_plan/anti_corruption_layer.ex, lib/dotcom/trip_plan/input_form.ex, lib/dotcom_web/components/trip_planner/input_form.ex, test/dotcom/trip_plan/input_form_test.exs, test/dotcom_web/live/trip_planner_test.exs
**Asana Ticket:** mostly [TP | Add an error state when location isn't selected](https://app.asana.com/0/1209151500209207/1209320056067619) with some [UI/UX | Trip Planner location input error state](https://app.asana.com/0/1209151500209207/1208726277099892), should fix [TP Bugs | Trip planner input location bug](https://app.asana.com/0/1209151500209207/1208025102649692) 
Will be even better with #2364 and #2361 in the mix.
- Validation of the `:to` and `:from` fields has been overhauled, and adds the error where needed
- The location inputs are technically themable now, and we use that to change to the error styling when that form field has errors
- Text that's pasted into the location inputs now gets sent to LiveView (as a pseudo-"selection" that's a name with no lat/lon) and proceeds …
=> fix(TripPlan.InputForm): improve location validation + add visual error state

lib/dotcom_web/components/route_pills.ex, lib/dotcom_web/components/system_status/status_label.ex, lib/dotcom_web/components/system_status/subway_status.ex, lib/dotcom_web/components/system_status/widget.ex, lib/dotcom_web/live/system_status.ex
---
**Asana Ticket:** [System Status | [Hi-Fi] Component that renders grouped statuses/alerts](https://app.asana.com/0/555089885850811/1209091199210570)
=> feat: Add Hi-Fi system status widget

lib/dotcom_web/components/components.ex, lib/dotcom_web/components/layouts/alerts_layout.html.heex, lib/dotcom_web/templates/alert/inline.html.eex, lib/dotcom_web/templates/alert/show.html.heex, lib/dotcom_web/templates/alert/tooltip.html.eex, lib/dotcom_web/views/alert_view.ex, test/dotcom_web/views/alert_view_test.exs
**Asana Ticket:** Precursor to [Service Alerts page | Refine Station and Service Alerts section](https://app.asana.com/0/555089885850811/1209323323089304)
Refactored the alerts "show" template into a layout. I used named slots to control what goes into the sidebar, since this will change for the subway service alerts (the timeframe filters will be removed). Anyways, I'm hoping it'll make it easier to swap in/out the differing content between subway and the other modes (which will remain the same). Visually, this should be a no-op.
=> refactor: alerts page layout

lib/dotcom_web/controllers/event_controller.ex
File downloads with a comma were not working. `URI.encode` doesn't encode commas, but `URI.encode_www_form` does.
=> fix file download link

test/dotcom/system_status/subway_test.exs, test/support/factories/alerts/alert.ex
Follow-up to:
- https://github.com/mbta/dotcom/pull/2330
=> cleanup: Add more alert factories for use in SystemStatus.SubwayTests

lib/dotcom/system_status/subway.ex, lib/dotcom_web/live/system_status.ex, test/dotcom/system_status/subway_test.exs, test/support/factories/alerts/alert.ex
Changes the way that green line statuses get grouped, so that they line up more closely with the alerts themselves. Previously, branches would only be grouped together if their full set of alerts was the same. Now, branches will be grouped together if they're impacted by the same alert, even if they also have other statuses.
---
**Asana Ticket:** [System Status | 🐞 Green line grouping bug](https://app.asana.com/0/555089885850811/1209323504575454)
---
Depends on:
- #2347
=> fix: Green line grouping bug

lib/dotcom/content_rewriters/links.ex
https://mbtace.sentry.io/issues/6268836106/?environment=prod&project=4507102206820352&referrer=project-issue-stream
=> String match bug cause 'href' can be a list.

lib/dotcom/alerts/disruptions/subway.ex, lib/dotcom/utils/service_date_time.ex, test/dotcom/alerts/disruptions/subway_test.exs
No ticket, found alerts missing under `todays_disruptions/0` and uncovered a problem which manifests for any alert which spans many service ranges. So instead of only using the service ranges for the `:active_period` starts and stops, this PR will have it also interpolate any ranges in between.
=> fix(Alerts.Disruptions.Subway): add missing service ranges

lib/dotcom_web/components/alerts.ex, lib/dotcom_web/components/components.ex, lib/dotcom_web/components/planned_disruptions.ex, lib/dotcom_web/components/route_symbols.ex, lib/dotcom_web/views/alert_view.ex
- Update the (unreleased) Planned Disruption UI to be consistent with the Current Status UI
- Fix `<.subway_route_pill />` to prevent translation
- Improvement to `<.embedded_alerts />` for the (unreleased) Planned Disruption UI
=> refactor: some UI improvements

lib/dotcom/routes.ex, lib/dotcom_web/components/planned_disruptions.ex
No ticket. 
Example can be seen with the test Station Closure alert below: 
| Before | After |
|--------|--------|
| (slightly outdated UI) <img width="569" alt="image" src="https://github.com/user-attachments/assets/88d2037b-9b35-435c-ad6b-e8e38c1ad9fc" /> | <img width="541" alt="image" src="https://github.com/user-attachments/assets/6a5fe08e-67b3-4a0d-a739-b6bb7ce00000" /> |
=> fix(Components.PlannedDisruptions): render separate accordion for each subway line

assets/css/_alerts.scss, lib/dotcom_web/templates/alert/show.html.heex, lib/dotcom_web/views/alert_view.ex
No ticket, just a UI improvement that Chase was cool with, that'll make it easier to implement the upcoming UI change for subway alert display (since we'll have a consistent layout for each).
The route header above each group of alerts now has icon placed on left and text on right. This also fixes a regression in the text size of bus route names.
---
=> fixup(DotcomWeb.AlertView): remove too-big bus text

lib/dotcom_web/components/alerts.ex
**Asana Ticket:** [[PW/SS] Alert details changes](https://app.asana.com/0/555089885850811/1209437138451267)
- Removes icon from inside alert details
- Makes image clickable to open in a new tab. 
I adjusted a Red Line shuttle alert with an image, so we can test this out on` /preview/subway-status` in the planned disruptions section at bottom.
=> feedback(Components.Alerts): remove icon, make image clickable

lib/dotcom_web/components/planned_disruptions.ex, lib/dotcom_web/components/system_status/status_label.ex, lib/dotcom_web/components/system_status/subway_status.ex, lib/util/util.ex
In order:
1. **Asana Ticket:** [[PW/SS] Fix text wrapping](https://app.asana.com/0/555089885850811/1209437138451266)
2. Hiding the status icon from screen readers, as the text alone is sufficient
3. _Part_ of [Tweaks to delay handling, homepage + /alerts/subway system status](https://app.asana.com/0/555089885850811/1209498039973244)
- Add "Expect " to all future delays (`Expect Delay`)
- For all future alerts, adjust time display:
- Capitalize AM/PM 
- Add space between time & AM/PM
- Hide :00 if even hour
- `8:00pm → 8 PM`
=> fix: `SystemStatus` QA improvements 

lib/dotcom/alerts/disruptions/subway.ex, lib/dotcom/utils/service_date_time.ex, lib/dotcom_web/components/planned_disruptions.ex, test/dotcom/utils/service_date_time_test.exs
I _think_ this is everything needed to handle alerts configured as "until further notice", but I didn't want to recreate that alert and break dev-green/blue while people were using it to review :)
- `service_range_range` has been updated to gracefully handle `nil`, and tests have been added for that
- More creative formatting has been added to handle active periods with missing start or stop times.
=> hotfix(Alerts.Disruptions.Subway): process alerts with no end datetime

lib/alerts/repo.ex, lib/alerts/repo/behaviour.ex, lib/dotcom/alerts/disruptions/subway.ex, lib/dotcom/utils/service_date_time.ex, lib/dotcom_web/components/alerts.ex, lib/dotcom_web/components/layouts/alerts_layout.html.heex, lib/dotcom_web/components/layouts/alerts_page_content_layout.html.heex, lib/dotcom_web/components/planned_disruptions.ex, lib/dotcom_web/components/system_status/subway_status.ex, lib/dotcom_web/controllers/alert_controller.ex, lib/dotcom_web/live/system_status.ex, lib/dotcom_web/templates/alert/show.html.heex, lib/dotcom_web/templates/page/_tabbed_nav.html.heex, lib/dotcom_web/views/alert_view.ex, test/dotcom/utils/service_date_time_test.exs, test/dotcom_web/controllers/alert_controller_test.exs
**Asana Ticket:** [Service Alerts page | Refine Station and Service Alerts section](https://app.asana.com/0/555089885850811/1209323323089304) and [Service Alerts page | Add "Current Status" section for subway](https://app.asana.com/0/555089885850811/1209323323089299)
Most of the changes here were adding an additional sub-layout for the content of the alert page. Everything's the same between modes except for: 
- the icon shown next to each route (for subway it's the `subway_route_pill`, all others `route_icon`)
- the `<h2>` shown above the list of alerts, as there's no heading shown for non-subway
- I changed the verbiage of the "no alerts here" message for subway to read more like "no other alerts here", since there might be other alerts covered by the Current Status or Planned …
=> feat(AlertController): put new features on the subway alerts page

lib/dotcom_web/channels/predictions_channel.ex, test/dotcom_web/channels/predictions_channel_test.exs, test/dotcom_web/controllers/alert_controller_test.exs
**Asana Ticket:** [Stop Pages don't display cancelled trips with strikethrough](https://app.asana.com/0/555089885850811/1207956121805040)
...it turns out that skipped/cancelled predictions without departure times (e.g. probably all of them) were never making it to the stops page in the first place (on account of we were rejecting every prediction having `nil` departure_time). This PR should fix that. 
And this should be enough to resolve the cited issue, as everything's in place in the frontend to give skipped/cancelled trips the strikethrough treatment they deserve.
=> fix(DotcomWeb.PredictionsChannel): let skipped/cancelled with no departure times through

test/alerts/cache/bus_stop_change_s3_test.exs
[This build](https://github.com/mbta/dotcom/actions/runs/13660799318/job/38191538311?pr=2411) failed due to this test flaking.
=> tests: Mark "copy_alerts_to_s3/2 works" test as flaky

lib/dotcom_web/components/planned_disruptions.ex, lib/dotcom_web/components/system_status/status_label.ex, test/dotcom_web/components/planned_disruptions_test.exs
Three main changes, grouped by commit:
1. Add tests for planned disruptions
2. Refactor so that the planned disruptions component passes around alert `Date`'s rather than alert `DateTime`'s
3. Fix the bug (in a way that's a lot easier given 2 ☝️ than it would have been without, hence the refactor)
---
**Asana Ticket:** [Handle single day diversions in Planned Work](https://app.asana.com/0/555089885850811/1209557314856998)
=> fix: Handle single day diversions in Planned Work

lib/dotcom_web/components/route_symbols.ex, lib/dotcom_web/components/system_status/status_label.ex, lib/dotcom_web/components/system_status/subway_status.ex, test/dotcom_web/components/route_symbols_test.exs, test/dotcom_web/components/system_status/subway_status_test.exs, test/support/factories/alerts/alert.ex
[This PR](https://github.com/mbta/dotcom/pull/2385) was introduced without tests for the homepage component, but upon further reflection, there's enough non-trivial stuff going on in there, that it does deserve some tests.
I'm doing this for two reasons:
- It's better to have this test coverage late than never
- There are tickets that I'm about to work on that affect how to collapse [Mattapan trolley status](https://app.asana.com/0/555089885850811/1209412979464965) and [green line status](https://app.asana.com/0/555089885850811/1209412979464963), which I think will involve substantially changing the collapsing logic, so I want to reduce the risk of introducing a regression.
---
No ticket.
---
Follow-up to:
- https://github.com/mbta/dotcom/pull/2385
Blocking:
- …
=> tests: Add tests validating homepage-subway-status collapsing behavior

lib/dotcom_web/components/system_status/subway_status.ex, lib/dotcom_web/live/system_status.ex, test/dotcom_web/components/system_status/subway_status_test.exs
This PR fixes a few edge cases in the homepage subway status component where it was unnecessarily collapsing green line rows together, or collapsing Mattapan alerts into Red line (which we decided it should never do).
- [System Status | 🐞 Don't needlessly collapse Mattapan alerts into Red](https://app.asana.com/0/555089885850811/1209412979464965)
- [System Status | 🐞 Don't needlessly collapse GL alerts](https://app.asana.com/0/555089885850811/1209412979464963)
Blocked by:
- https://github.com/mbta/dotcom/pull/2404
=> fix: Avoid collapsing green line and Mattapan line rows unless needed

assets/ts/components/Alerts.tsx
[Live example right now](https://www.mbta.com/stops/place-nqncy?route=Red&direction_id=1&headsign=Alewife) (to see the bug, or the fix, expand the shuttle alert).
---
The bug was originally introduced in [this PR](https://github.com/mbta/dotcom/pull/2181). Turns out, there is no `w-100` tailwind utility; [the correct utility](https://v3.tailwindcss.com/docs/width#percentage-widths) to set the width to 100% is `w-full`.
---
**Asana Ticket:** [Fix dimensions for alert images on stop pages](https://app.asana.com/1/15492006741476/project/555089885850811/task/1209229373348286)
=> fix: Fix image width in alerts

lib/dotcom_web/live/trip_planner.ex
[Example Trip](https://www.mbta.com/trip-planner?plan=hsQSX3VudXNlZF93aGVlbGNoYWlyxADECGRhdGV0aW1lxBkyMDI1LTA0LTAxVDEyOjAwOjAwLTA0OjAwxA1kYXRldGltZV90eXBlxAhsZWF2ZV9hdMQEZnJvbYTECGxhdGl0dWRlxAk0Mi4zNjUzOTbECWxvbmdpdHVkZcQKLTcxLjAxNzU0N8QEbmFtZcQUQm9zdG9uIExvZ2FuIEFpcnBvcnTEB3N0b3BfaWTEAMQFbW9kZXOJxANCVVPEBHRydWXEBUZFUlJZxAR0cnVlxARSQUlMxAR0cnVlxAZTVUJXQVnEBHRydWXEDl9wZXJzaXN0ZW50X2lkxAEwxAtfdW51c2VkX0JVU8QAxA1fdW51c2VkX0ZFUlJZxADEDF91bnVzZWRfUkFJTMQAxA5fdW51c2VkX1NVQldBWcQAxAJ0b4TECGxhdGl0dWRlxAk0Mi4zNjU1NzfECWxvbmdpdHVkZcQJLTcxLjA2MTI5xARuYW1lxA1Ob3J0aCBTdGF0aW9uxAdzdG9wX2lkxAtwbGFjZS1ub3J0aA==) (this link will be valid until April 1)
(Note the mismatch between what's in the datepicker and what's in the results summary - the trip is planned based on the time in the URL, which is …
=> fix(trip-planner): Datepicker bug on mount

lib/dotcom_web/templates/alert/show.html.heex
This will allow a URL like https://www.mbta.com/alerts/subway#planned to take you directly to the planned work section.
Test locally: http://localhost:4001/alerts/subway#planned
**Asana Ticket:** [QF | PW | Add id/anchor to planned work section](https://app.asana.com/0/1205718271156548/1209703382141195/f)
=> chore: Add `#planned` anchor tag for alerts page planned work section

config/config.exs
This only affects local dev, since deployed environments were already using cdn.mbta.com for this.
---
No ticket
=> fix: Use cdn.mbta.com as the tileserver for MapLibre maps for all envs

assets/css/_icons.scss, assets/css/_schedule-page-line-diagram.scss, assets/react_app.js, assets/ts/models/__tests__/vehicle-test.ts, assets/ts/models/vehicle.ts, assets/ts/schedule/components/line-diagram/LiveCrowdingIcon.tsx, assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LiveCrowdingIconTest.tsx.snap, lib/dotcom_web/components/components.ex, lib/dotcom_web/templates/schedule/_timetable.html.heex, lib/dotcom_web/views/schedule/timetable.ex, lib/dotcom_web/views/schedule_view.ex, test/dotcom_web/components_test.exs, test/dotcom_web/views/schedule/timetable_view_test.exs
**Asana Ticket:** [Uncaught exit - {:timeout, {Task, :await, [%Task{mfa: {:erlang, :apply, 2}, owner: #PID<0.26396768.0>, pid: #PID<0.26396822.0>, ref: #Reference<0.0.425996307.1154070796.3517251586.135124>}, 5000]}}](https://app.asana.com/0/555089885850811/1209703855878428/f) (links to [this Sentry issue](https://mbtace.sentry.io/issues/5767367004/))
Since the crowding icon was initially made in React, it was later added to the timetable via `Dotcom.React.render/2`... which was cool and all but turns out performs terribly, and also contributes to many of the 500 errors we were seeing post-deploy. This PR removes that.
Also:
- Adds a simple functional component for rendering tooltips
- Refactors the React component to remove the commuter rail-specific logic that's no longer needed
=> refactor: remove React component from timetable

lib/dotcom/transit_near_me.ex
We've known it was broken for a long time. Everything else about the code behind that functionality made sure to account for the `"Green"` route ID, _except_ for fetching predictions. The MBTA API won't give you predictions for `route: "Green"`! But it will for `route: "Green-B,Green-C,Green-D,Green-E"` :)
=> fix: enable predictions on the Green Line schedule page

lib/dotcom_web/plugs/content_security_policy.ex, lib/dotcom_web/router.ex
Right now on dev, images hosted on Drupal are being blocked by the content security policy. It's likely non-obvious things are also being blocked!
I'm giving up on using the `plug/2` macro to involve the `ContentSecurityPolicy` dependency. In this PR I am instead calling the various plugs directly via their `call/2` methods.
=> hotfix(ContentSecurityPolicy): implement as a Plug

assets/ts/schedule/components/direction/BusMenu.tsx
=> fix: Don't call `item.focus()` for all variants in dropdown

deploy/monitor/Dockerfile, package-lock.json, package.json
This is thanks to Artillery's Playwright plugin versioning.
Note: There is an even newer version of Artillery available, but it requires upgrading our version of Node, which is a more involved effort (I tried... a Cypress dependency broke).
This got the monitor testing scenarios again when I ran it locally.
=> deps(npm): sync Playwright version to 1.48.0

assets/ts/schedule/components/schedule-finder/daily-schedule/ServiceOptGroup.tsx
Schedule finder crashes the page for certain bus routes, including [Route 111](https://www.mbta.com/schedules/111/line), [Route 61](https://www.mbta.com/schedules/61/line), [Route 96](https://www.mbta.com/schedules/96/line) and several others.
The current code checks `service.added_dates` for truthiness before pulling the first item out as `addedDate`. Javascript treats `[]` as truthy, so that check still passes even if `service.added_dates` is `[]`. This PR fixes that by also checking to make sure that `service.added_dates` isn't empty.
---
No Ticket.
=> hotfix(schedule-finder): Check whether `added_dates` has more than 0 elements

lib/dotcom_web/plugs/content_security_policy.ex
Well, I'm hoping that works -- will deploy and test.
Also adds a missing directive for Fullstory, and fixes the Sentry URL (which was broken :()
=> hotfix(ContentSecurityPolicy): corrected websocket host for iOS15

assets/ts/leaflet/components/Map.tsx, assets/ts/schedule/components/__tests__/__snapshots__/MapTest.tsx.snap
Moves the tooltip down 40px so that it sits on top of the marker. I'm not sure why this is necessary. My guess is that it has something to do with the map's CSS positioning within the page.
https://app.asana.com/0/555089885850811/1209641407424374/f
=> Tooltip offset

assets/ts/schedule/components/ScheduleDirection.tsx, assets/ts/schedule/components/line-diagram/LineDiagram.tsx, assets/ts/schedule/components/line-diagram/LineDiagramWithStops.tsx, assets/ts/schedule/components/line-diagram/StopCard.tsx, assets/ts/schedule/components/line-diagram/__tests__/LineDiagramWithStopsTest.tsx, assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap
This is a code-cosmetic change that I'm intending to merge _before_ https://github.com/mbta/dotcom/pull/2454. 
As I was working on https://github.com/mbta/dotcom/pull/2454, I noticed that a bunch of components had props that weren't sorted, which made it a bit confusing to decide where to put the new props that I was adding. For some of those prop-lists, I sorted them while working on it, but that expands the diff and makes it harder to see what the real change is, versus just the cosmetic prop-ordering. Also I missed some.
This change is a more systematic run-through of all of the prop-lists in the files touched by https://github.com/mbta/dotcom/pull/2454 in order to get all of those lists into sorted order. Once this is merged, then https://github.com/mbta/dotcom/pull/2454 can be …
=> cleanup: Sort props in LineDiagram code

lib/dotcom_web/controllers/page_controller.ex, test/dotcom_web/live/trip_planner_test.exs
**Asana Ticket:** [Only currently-active accessibility alerts should show up on alerts tab](https://app.asana.com/0/555089885850811/1209539521192559/f)
This will affect other things consuming `@alerts` on the index.html page... which as far as I can tell is only the recently visited buttons (to determine whether to show the exclamation triangle).
=> fix(PageController): filter index alerts to active on datetime

lib/dotcom_web/components/system_status/subway_status.ex, test/dotcom_web/components/system_status/subway_status_test.exs
Change the `Subway Status` header to be a link that directs to `/alerts/subway`.
This change also includes a small change to the `subway_status` component tests, because, those tests were assuming that the only `<a>` tags in the component would be the status rows, but that's not true anymore.
**Asana Ticket:** [QF | Homepage subway status goes to /alerts/subway](https://app.asana.com/0/555089885850811/1209601118457610/f)
=> feat: Have the subway-status header link to /alerts/subway

assets/ts/schedule/components/line-diagram/StopCard.tsx, assets/ts/schedule/components/line-diagram/StopConnections.tsx, assets/ts/schedule/components/line-diagram/__tests__/StopConnectionsTest.tsx, assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap, assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/StopCardTest.tsx.snap
Just a minor code-cleanup thing that I noticed while working on https://github.com/mbta/dotcom/pull/2454 - `<StopConnections />` wasn't using its first argument (called `route_id`, though the value that was passed in was actually a stop ID), and also that it was defined in a way that made it impossible to invoke as a normal React component.
=> cleanup: Make `<StopConnections />` a real component and remove unused prop

assets/ts/hooks/useMobileAppBanner.ts, assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/DailyScheduleSubway.tsx, integration/e2e_tests/mobile-app-banner.spec.js, playwright.config.js
- moves rendering the banner into the `<ScheduleModalContent />` component so it could potentially render in any mode (instead of just subway)
- instead of hard-coding the banner in the React component, copies it from the DOM (thus leveraging the logic used in `js/mobile-app-banner.js`). Thereby, if the banner isn't on the schedule page anyway, it doesn't get copied and rendered in the schedule finder, either.
- adds a new Playwright test! This tests against our expectations, and also runs the tests in triplicate - on desktop, iPhone, and Android - so we can verify presence on mobile and absence on desktop.
=> fix: show mobile app banner in schedule finder for additional modes

assets/ts/schedule/components/line-diagram/StopCard.tsx, assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap, assets/ts/schedule/components/schedule-finder/OriginListItem.tsx, assets/ts/schedule/components/schedule-finder/OriginModalContent.tsx, assets/ts/schedule/components/schedule-finder/__tests__/OriginListItemTest.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/TripDetails.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/__snapshots__/TripDetailsTest.tsx.snap, lib/trip_info.ex, test/dotcom_web/trip_info_test.exs
(*Context: Route 39, Outbound. Note the lack of a `View Schedule` link for Forest Hills, the terminal station for this variant.*)
(*Before-ish: This is why the `View Schedule` link is suppressed - expanding the trip produces an error rather than a table.*)
---
- This doesn't change the display for subway pages - only bus and commuter rail.
- No ticket explicitly, but it's closely related to (and blocking) https://github.com/mbta/dotcom/pull/2454.
---
Blocking:
- https://github.com/mbta/dotcom/pull/2454
=> feat: Allow schedule finder to load (short) trips for terminals

assets/js/mobile-app-banner.js, assets/ts/ui/autocomplete/sources.ts, assets/ts/ui/autocomplete/templates/algolia.tsx, assets/ts/ui/autocomplete/templates/helpers.tsx
**Asana Ticket:** [Search results takes you to node instead of actual page when you hit enter](https://app.asana.com/0/555089885850811/1207505625020797/f)
We already have good logic for figuring out the URL you go to when you click the result. Now this PR applies this same logic to the source's `getItemUrl` property, which is what autocomplete.js uses to identify the URL that _keyboard navigation_ takes you to.
=> refactor(autocomplete): consistent URL handling for source.getItemUrl

lib/dotcom_web/templates/event/show.html.eex
**Asana Ticket:** [Before 4/17, Allow Vimeo embeds to be full width on event pages](https://app.asana.com/0/555089885850811/1209459897950318/f)
Per discussion described in the ticket, we can already add a code embed to events... and now with this PR we can actually show them too.
Now here's the thing, I think we had a flawed bit of Vimeo embed code. This one didn't work:
```html
<div style="padding:56.25% 0 0 0;position:relative;"><iframe src="https://vimeo.com/event/4867722/embed" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;"></iframe></div>
```
But this one did (while super similar, there's a difference!):
```html
<div style="padding:56.25% 0 0 0;position:relative;"><iframe …
```
=> fix: show paragraphs on events

lib/alerts/alert.ex, lib/alerts/repo.ex, lib/dotcom/alerts.ex, test/alerts/alerts_test.exs, test/alerts/repo_test.exs, test/dotcom/alerts_test.exs
I thought that diversions were drawing from the same place as service impacting alerts, but they are subtly different. This makes it so that diversions also look at service changes where the severity >= 3.
=> Hotfix: forgot to add service change to diversions

lib/dotcom_web/templates/partial/_accordion_ui.html.eex, lib/dotcom_web/templates/partial/_accordion_ui_no_bootstrap.html.eex
This has effects in two places that I was able to find:
(In both screenshots below, **before** is on the left, and **after** is on the right)
(The font size is the change. The fact that seat availability is missing is a data discrepancy between local and prod.)
---
**Asana Ticket:** [Style issues | Text size](https://app.asana.com/0/555089885850811/1209162421069228/f)
(This only addresses the second issue - text size getting larger on accordions)
=> fix: Shrink font sizes on accordions

assets/tailwind.config.js
**Asana Ticket:** [Style issues | Link bolding](https://app.asana.com/0/555089885850811/1209237709550402/f)
This reverts the Tailwind-related change.
I feel like this might unbold some links that we might want more weight on, but I figure we can find and fix those on a case-by-case basis.
=> fix: don't set default fontWeight on links

lib/dotcom_web/templates/bus_stop_change/index.html.eex, lib/dotcom_web/templates/news_entry/show.html.eex, lib/dotcom_web/templates/search/index.html.eex
A few more font-size fixes (follow-up to https://github.com/mbta/dotcom/pull/2477)
(**Before** is on the left. **After** is on the right.)
---
On [news pages](https://www.mbta.com/news/2025-04-01/mbta-offers-increased-service-ma250-celebrations-april-19-20)
---
On [bus stop changes pages](https://www.mbta.com/bus-stop-changes?alerts_timeframe=current)
---
On the [search page](https://www.mbta.com/search)
---
No ticket, or maybe this is part of [Style issues | Text size](https://app.asana.com/0/555089885850811/1209162421069228/f).
=> fix: Three more instances of expanding `text-2xl`'s

lib/dotcom/cache/key_generator.ex
Minor note: this changes handling of a single argument which _isn't_ a binary - instead of hashing it directly it'll be wrapped in a list (e.g. `:erlang.phash2([arg])` instead of `:erlang.phash2(arg)`)
But I also took the suggestion to increase the range via the second argument of `:erlang.phash2/2`
=> hotfix(Cache.KeyGenerator): don't hash single binaries

test/dotcom_web/live/trip_planner_test.exs, test/test_helper.exs
We get a lot of build failures (e.g. [this one](https://github.com/mbta/dotcom/actions/runs/14314431748/job/40117527243?pr=2484#step:5:86)) where `render_async` times out because it can't finish rendering in 100ms.  These are otherwise valuable tests, so it would be nice to not need to mark them as `@flaky`. `render_async` [respects the ExUnit setting](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveViewTest.html#render_async/2), so this should allow `render_async` more time to finish its rendering.
Hopefully this will improve test reliability.
=> fix: Bump `assert_receive_timeout` to 500ms

assets/css/_schedule-page-line-diagram.scss
**Asana Ticket:** [Style issues | Icons misaligned](https://app.asana.com/0/555089885850811/1209237709550399/f)
This is for the line diagram, where connections show a mix of round icons + pills.
=> fix alignment of icons on Safari

assets/ts/stop/__tests__/StopPageTest.tsx, assets/ts/stop/components/StopPage.tsx
New alert banners at the tops of stop pages, such as:
*if they're active or will be within the next 7 days*
*only if they're active now*
---
... and a few other types.
Notice that none of these new alert types show up in the departures-and-map section - only as banners at the top of the page.
---
This is organized as four (base) commits, and may be easier to review commit-by-commit:
1. [refactor: Tease apart stop-page banner versus departure-and-map alerts](https://github.com/mbta/dotcom/pull/2480/commits/955cc0a122f7b56ef67d3ea663a8c675a3319fb1)
2. [feat: Add new alert types to the top of the stop page (but not the departures section)](https://github.com/mbta/dotcom/pull/2480/commits/365af26594b5107bf4aa2c2028df53274227de92)
3. [feat: Add active elevator alert banners to the stop …
=> feat: Add new alert types on the stop page

lib/dotcom_web/controllers/schedule/timetable_controller.ex
This is for data on dev-green, for a shuttle between Mansfield and Foxboro. See it at `/schedules/CR-Franklin/timetable?date=2025-04-11`
=> feat(TimetableController): show the Foxboro-Mansfield shuttle stops

lib/feedback/mock_aws.ex
No ticket, just noticed that submitting the customer support was broken when developing locally.
=> fix(Feedback.MockAws): use right decoder

lib/dotcom/trip_plan/map.ex
Follow-up to:
- https://github.com/mbta/dotcom/pull/2495
I had forgotten to update the line color on the map. But this is slightly complicated from the fact that we get color for the map from GTFS (while the other places we use color come from [the Rider Design System](https://github.com/mbta/rider-design-system/blob/c9589af1a5c1b6734ffb786f5f8b9ba993662f9c/dist/variables.Light.css#L62-L72)), and our GTFS sets rail-replacement-shuttles as having the bus color.
This is a _very_ inelegant solution for now. If there's a better way to do this, I am so eager for it.
---
**Asana Ticket:** [QF | TP | Fix shuttle icon size, line color, map color in details view](https://app.asana.com/0/555089885850811/1209501772392193/f)
=> fix(trip-planner): Fix rail-replacement-shuttle colors on the map

lib/dotcom/trip_plan/itinerary_groups.ex, test/dotcom/trip_plan/itinerary_groups_test.exs
- avoid grouping rail replacement shuttles with buses
- avoid grouping itineraries with different `accessibility?` values together
- while that is very unlikely to be needed, it covers the case where we have a type of itinerary which is _usually_ accessible, with the exception of perhaps one trip that's affected by some sort of accessibility-impacting-outage (maybe planned work, maybe something else)
=> fix(TripPlan.ItineraryGroups): enhanced grouping logic

lib/dotcom_web/components/trip_planner/results.ex
This is a no-op. This'll make things easier once we start rendering several groups like so:
The reason the new component takes already-indexed groups, instead of handling the indexing itself, is so that we don't run into collisions based on index (e.g. if we're showing multiple groups of itinerary summaries, the first item in each shouldn't open the same view).
=> refactor(TripPlanner.Results): component for a group of summaries

lib/dotcom_web/controllers/schedule/timetable_controller.ex, lib/schedules/sort.ex, test/schedules/sort_test.exs
https://app.asana.com/1/15492006741476/project/555089885850811/task/1209963100947971?focus=true
Turns out we want two different types of ordering. One for ferry and one for all other modes.
=> Shared stop sort for non-ferry timetables

lib/dotcom/trip_plan/itinerary_groups.ex
For the "arrive by" situation, actually chooses the representative itinerary correctly (after limiting the itineraries in the group).
=> fix(TripPlan.ItineraryGroups): correct representative itinerary

test/dotcom_web/controllers/schedule_controller_test.exs
Fix warning associated with calling a non-existent function in `ScheduleControllerTest`. This wasn't causing the build to fail because those tests were already marked as `external`, which means they're not getting run.
---
No ticket.
=> fix: Don't call non-existent function in `ScheduleControllerTest`

assets/ts/schedule/components/line-diagram/LineDiagram.tsx
(Before on the left; After on the right)
[Route 217](https://www.mbta.com/schedules/217/line?schedule_direction%5Bdirection_id%5D=0&schedule_direction%5Bvariant%5D=217-1-0)
[Route 37](https://www.mbta.com/schedules/37/line?schedule_direction%5Bdirection_id%5D=1&schedule_direction%5Bvariant%5D=37-3-1)
Turns out: Both of these bugs are examples of some of the bizarre non-deterministic behavior that React does when child elements have duplicate `key` values.
**Asana Ticket:** [Inaccurate stop search results for routes which visit a stop twice ](https://app.asana.com/1/15492006741476/project/555089885850811/task/1206537132113542?focus=true)
**Asana Ticket 2:** [Weird stop search results for "Lagrange St @ Vermont St"](https://app.asana.com/1/15492006741476/project/385363666817452/task/12096467 …
=> fix: Extra duplication of duplicate stops when filtered

lib/dotcom_web/components/alerts/subway.ex
Update the alert-table line height sizes so that on mobile, they're the same height on subway pages as on bus pages.
---
Below is a before/after comparison on mobile (Before is on the left; after is on the right)
---
This also slightly shrinks the line height on desktop
(Before on the left; after on the right)
---
But on desktop, they're still slightly bigger on subway pages than on bus pages.
---
**Asana Ticket:** [QF | Adjust subway alerts tab link height on mobile](https://app.asana.com/1/15492006741476/project/1204352509486278/task/1209775659080578?focus=true)
=> fix: Alert-table line height sizes on mobile

lib/dotcom/trip_plan/input_form.ex, lib/dotcom_web/components/trip_planner/results.ex, lib/dotcom_web/live/trip_planner.ex, test/dotcom/trip_plan/itinerary_groups_test.exs, test/dotcom_web/live/trip_planner_test.exs, test/support/factories/trip_planner/trip_planner.ex
**Asana Ticket:** [Trip Planner: group results based on newly fixed accessibility score](https://app.asana.com/1/15492006741476/project/555089885850811/task/1209939784083536?focus=true) (last task in [TP | Update trip accessibility display](https://app.asana.com/1/15492006741476/project/555089885850811/task/1209572743277407?focus=true))
Mainly UI changes here:
- "Prefer accessible trips" is unchecked - show itinerary summaries grouped by "Accessible Routes" follow by "Inaccessible Routes"
- "Prefer accessible trips" is checked - show itinerary summaries in a flat list (like now), limited only to those which are accessible (this was already done in #2501)
Backend change: 
- When requesting plans from OTP, always pass `wheelchair: true` to that, regardless of what's chosen in the form. This …
=> feat(Live.TripPlanner): wheelchair checkbox toggles groupings

README.md
[The command to install homebrew has changed](https://brew.sh/), so we might as well include the correct one in the README.
---
No ticket.
=> chore: Update Homebrew installation command in the README

assets/ts/components/Modal.tsx
[Local link](http://localhost:4001/schedules/39/line?schedule_finder%5Bdirection_id%5D=0&schedule_finder%5Borigin%5D=41391)
[Prod link](https://www.mbta.com/schedules/39/line?schedule_finder%5Bdirection_id%5D=0&schedule_finder%5Borigin%5D=41391)
The current behavior is that whenever there is a `Modal` present in the DOM on page-load, it adds a listener that closes the modal as soon as the DOM's content is loaded. You can see this if you copy the prod link above into a browser - you'll see the modal flicker briefly before vanishing. This leads to a few annoying UX'es:
- If you refresh with schedule finder open, it won't be open anymore.
- If you copy a schedule page link with the schedule finder query params and open that link in another browser window, those query params will erase …
=> fix: Don't have `<Modal />` component auto-close itself

lib/dotcom_web/components/planned_disruptions.ex, lib/dotcom_web/components/system_status/status_row_heading.ex, lib/dotcom_web/components/system_status/subway_status.ex, test/dotcom_web/components/system_status/subway_status_test.exs
No ticket, but it's been bugging me for a while that there were three (slightly different, but fundamentally the same) implementations of the same route-pill-plus-status-label concept. So I extracted that to a component that's shared between the various subway status components.
~There may be an opportunity here to re-use this for planned work as well and extracting this further (if we do that, we'll want to clean up the interface a bit more 😅). I'm open to doing that as part of this PR, or as a follow-up.~ *I did it as part of this PR 😇*
=> refactor: Consolidate code for subway status row headers

lib/dotcom_web/controllers/schedule/alerts_controller.ex
Having the `alerts_timeframe=` URL parameter present was still filtering away alerts on pages where we've taken away from timeframe filtering from the UI! This PR avoids that from happening on subway schedule pages.
Before at https://dev.mbtace.com/schedules/Red/alerts?alerts_timeframe=current - No service alerts
Now with this PR - Upcoming service alerts visible
=> fix(AlertsController): don't filter by timeframe

lib/dotcom_web/components/planned_disruptions.ex, lib/dotcom_web/components/system_status/status_row_heading.ex, lib/dotcom_web/components/system_status/subway_status.ex
I noticed that [this PR](https://github.com/mbta/dotcom/pull/2525) messed up some styles for when system status isn't 100% normal, with some border lines not quite lining up, and some things not being centered properly.
Screenshots below (before on the left; after on the right)
---
No ticket.
=> fix: Styling for consolidated subway statuses

lib/dotcom_web/controllers/schedule/timetable_controller.ex
When iterating through canonical route patterns and their associated trips/stops, sometimes we need to help it pick the right route pattern to look through first. Here we add the Foxboro route to this logic!
[Before](https://dev.mbtace.com/schedules/CR-Foxboro/timetable?date=2025-05-04&schedule_direction[direction_id]=0#direction-filter)
After
=> fix(TimetableController): Foxboro route pattern sorting

lib/dotcom_web/components/system_status/status_icon.ex, lib/dotcom_web/components/system_status/status_label.ex, lib/dotcom_web/components/system_status/status_row_heading.ex, lib/dotcom_web/components/system_status/subway_status.ex
Re-implement the `<.status_row_heading />` component as a CSS `grid` instead of its previous `flex` implementation. This is in order to support the kind of layout where there is sub-heading text directly below the status description (**Shuttle** or **Station Closure** or whatever). 
This was intended to be a pure refactor, but while working on this, I noticed a few small details that I got wrong when originally implementing the subway status feature, so I went ahead and fixed those.
- The font size for disrupted statuses is now slightly larger, as well as being bold.
- The padding to the left of the root pills is now 4px rather than 8px.
---
**Asana Subtask:** [[Endpoints] Refactor status row heading to use grid instead of flex](https://app.asana.com/1/15492006741476/project/12057182711565 …
=> refactor: Change status row header from flex to grid

lib/dotcom_web/components/components.ex, lib/dotcom_web/components/planned_disruptions.ex, lib/dotcom_web/components/system_status/subway_status.ex, test/dotcom_web/components_test.exs
Oops - [missed these](https://github.com/mbta/dotcom/pull/2534).
These were actually the last usages of `lined_list`, so we could, in theory, remove that entire component as well. Thoughts?
=> cleanup: Remove unused `lined_list` imports

lib/dotcom/alerts.ex, lib/dotcom/alerts/commuter_rail.ex, lib/dotcom/alerts/group.ex, lib/dotcom/alerts/subway.ex, lib/dotcom_web/components/alerts/grouped.ex, lib/dotcom_web/controllers/schedule/alerts_controller.ex, lib/dotcom_web/templates/schedule/_alerts.html.heex, test/dotcom/alerts/group_test.exs
Group commuter rail alerts nearly like subway, but with some small differences. I pulled the logic from subway into a behaviour module and now you just have to define the grouping and sorting and it just works.
https://app.asana.com/1/15492006741476/project/555089885850811/task/1210070462275466?focus=true
=> Group commuter rail alerts

assets/ts/sentry.ts
No ticket, but I'm trying to see if I can collect more info for that [one persistent stop page error](https://mbtace.sentry.io/issues/5255754689/?project=194344&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&stream_index=0) that Sentry logs. It linked to some [guidance](https://sentry.io/answers/load-failed-javascript/) suggesting that adding this integration might help!
While I'm here I also figured I'd increase the sample rate and maybe collect more errors.
=> sentry: add console integration

lib/dotcom_web/components/stops/header.ex, lib/dotcom_web/components/transit_icons.ex
---
- The addition of `text-nowrap` forces `Zone 1A` to stay on one line.
- The addition of `flex-wrap` prevents that from pushing the parking icon off the edge of the screen, and allows the mode icons to give the station name some breathing room.
---
No ticket.
=> fix: Wrapping behavior for stop feature icons

lib/dotcom_web/components/stops/header.ex, lib/dotcom_web/controllers/stop_controller.ex, lib/dotcom_web/templates/stop/show.html.heex, test/dotcom_web/components/stops/header_test.exs
Don't include `connecting_stops` when considering whether a stop/station is accessible.
This was leading to an issue where stations were being given a ♿ icon if they were connected to a bus stop (which is always considered accessible), even if the station itself is not accessible. This was impacting some Commuter Rail stations as well as a few inaccessible Green Line stations, including Hynes Convention Center and Boylston.
(Before on the left; After on the right)
[Belmont](https://www.mbta.com/stops/place-FR-0064)
[Boylston](https://﻿﻿www.mbta.com/stops/place-boyls)
(This also works for stations whose names start with letters other than `B`)
---
It also fixes the `Accessibility` amenity card for affected stations.
---
No ticket.
=> fix: Don't include connecting stops when determining station accessibility

lib/cms/api/static.ex, test/dotcom_web/controllers/cms_controller_test.exs, test/dotcom_web/controllers/event_controller_test.exs, test/dotcom_web/controllers/news_entry_controller_test.exs, test/dotcom_web/controllers/project_controller_test.exs
No ticket.
When we did [the Elixir 1.18 upgrade](https://github.com/mbta/dotcom/pull/2539), that introduced a new type of warning to alert us to certain types of unused code. One of the offenders was this:
```
warning: this clause of defp handle_revision/1 is never used
│
287 │   defp handle_revision({:error, err}), do: {:error, err}
│        ~
│
└─ lib/cms/repo.ex:287:8: CMS.Repo.handle_revision/1
```
Triggered by [this code here](https://github.com/mbta/dotcom/blob/bf440f87f575faba294b9f68263abb955715e36f/lib/cms/repo.ex#L286-L287).
The wacky thing is - that code actually is used! `handle_revision/1` is called [here](https://github.com/mbta/dotcom/blob/bf440f87f575faba294b9f68263abb955715e36f/lib/cms/repo.ex#L265-L266), with the value [returned …
=> fix: Warning about unused `handle_revision/1` clause in tests

lib/dotcom_web/channels/vehicle_map_marker_channel.ex, lib/vehicle_helpers.ex, test/dotcom_web/channels/vehicle_map_marker_channel_test.exs
Looking at our excessive number of V3 API requests to `/predictions` in particular, I figured out we re-request predictions after every change in `/vehicles`... it's too much. Since we only use the prediction in that location to show tooltip text with commuter rail status and track, I added this `if` statement to only request the prediction if we're on a commuter rail route.
The whole everything should probably be rearchitected, really.
No ticket.
=> fix(VehicleMapMarkerChannel): prediction for rail only

lib/dotcom_web/components/system_status/subway_status.ex
Very small and subtle, but when I fixed the padding for subway status rows, I forgot to update the padding for the `Current Status` header on the [alerts page](https://www.mbta.com/alerts/subway). As a result, the header is a bit to the right of the content below it, which looks a bit wrong.
This change shifts it to be a bit to the left of the content below, and aligns it with `Planned Work` below.
(Before is to the left; After is to the right)
=> fix: Remove padding from `Current Status` title

lib/dotcom_web/controllers/schedule/line_api.ex
This fixes 👇 warning
```elixir
warning: variable "params" is unused (if the variable is not meant to be used, prefix it with an underscore)
│
59 │   def show(conn, params) do
│                  ~~~~~~
│
└─ lib/dotcom_web/controllers/schedule/line_api.ex:59:18: DotcomWeb.ScheduleController.LineApi.show/2
```
=> fix(warnings): Unused field `params` in `LineApi`

test/schedules/parser_test.exs
This fixes 👇 warning:
```elixir
warning: comparison between distinct types found:
left == right
given types:
dynamic(
{binary(), binary(), binary(), nil, term(), term(), true, true, false, integer(), integer()}
) ==
dynamic(
{term(), term(), term(), term(), term(), term(), boolean(), boolean(), boolean(), term(),
term(), term()}
)
where "left" (context ExUnit.Assertions) was given the type:
{binary(), binary(), binary(), nil, term(), term(), true, true, false, integer(), integer()}
)
left =
{"CR-Lowell", "31174458-CR_MAY2016-hxl16011-Weekday-01", "Lowell", nil,
Timex.to_datetime({{2016, 6, 8}, {5, 35, 0}}, "Etc/GMT-4"),
Timex.to_datetime({{2016, 6, 8}, {5, 35, 0}}, "Etc/GMT-4"), true, true, false, 0, 3}
where "right" (context ExUnit.Assertions) was given the type:
{term(), term(), term(), …
```
=> fix(warnings): Fix expect/assert mismatch that guaranteed test failure

test/schedules/repo_test.exs
This fixes 👇 warning
```elixir
warning: comparison between distinct types found:
left != right
given types:
dynamic(non_empty_list(term(), term())) != empty_list()
where "left" (context ExUnit.Assertions) was given the type:
left = response
where "right" (context ExUnit.Assertions) was given the type:
right = []
While Elixir can compare across all types, you are comparing across types which are always disjoint, and the result is either always true or always false
typing violation found at:
│
54 │       assert response != []
│                       ~
│
└─ test/schedules/repo_test.exs:54:23: Schedules.RepoTest."test by_route_ids/2 returns the parent station as the stop and keeps raw stop id"/1
```
=> fix(warnings): Change non-empty-list assertion to fix match warning

config/config.exs, config/test.exs, lib/dotcom/alerts/affected_stops.ex, lib/dotcom/alerts/affected_stops/behaviour.ex, lib/dotcom_web/components/planned_disruptions.ex, lib/dotcom_web/components/system_status/status_label.ex, lib/dotcom_web/components/system_status/status_row_heading.ex, lib/dotcom_web/components/system_status/subway_status.ex, test/dotcom/alerts/affected_stops_test.exs, test/dotcom_web/components/planned_disruptions_test.exs, test/dotcom_web/components/system_status/subway_status_test.exs, test/dotcom_web/controllers/alert_controller_test.exs, test/support/mocks.ex
---
**Asana Subtask:** [[Endpoints] Add affected stops subheadings to system status and planned work](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210239131757949?focus=true)
**Asana Parent Ticket:** [Add endpoints of disruption to system status and planned work](https://app.asana.com/1/15492006741476/project/1205718271156548/task/1209641123314696?focus=true)
=> feat: Add affected stops to system status and planned work

config/runtime.exs, lib/dotcom_web/controllers/mbta_go_deep_link_controller.ex, lib/dotcom_web/router.ex, test/dotcom_web/controllers/mbta_go_deep_link_controller_test.exs
**Asana Ticket:** [Create link that opens the app if you have it installed and the store otherwise](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209949928014406?focus=true)
As described in the ticket, sets `/go` to redirect to the App Store / Play Store / MBTA Go project page in the same way that #2437’s `/app-store` does, and creates the `/.well-known/` files that are needed to have MBTA Go open links under `/go` if it’s installed.
It’d be theoretically possible to have every instance of dotcom attached to every instance of the mobile app, which would let this be self-contained like #2437 is, but for people with multiple instances of the app installed, that’d make it difficult to control which instance of the mobile app is actually opened. Instead, per discussion …
=> feat: set up deep linking for MBTA Go

lib/cms/api.ex, lib/dotcom/application.ex, lib/dotcom_web/controllers/helpers.ex, lib/mbta/api.ex
No ticket.
We saw some issues that included error messages like
```
** (RuntimeError) Finch was unable to provide a connection
within the timeout due to excess queuing for connections.
Consider adjusting the pool size, count, timeout or reducing
the rate of requests if it is possible that the downstream
service is unable to keep up with the current rate.
```
So we figured we would bump the Finch pool size from its default of 50 up to 200.
[Finch docs.](https://hexdocs.pm/finch/Finch.html#module-usage)
=> hotfix: Increase default Finch connection pool size

lib/dotcom_web/controllers/mbta_go_feedback_controller.ex, lib/dotcom_web/router.ex, test/dotcom_web/controllers/mbta_go_feedback_controller_test.exs
**Asana Ticket:** [Redirect feedback form URLs](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209950590972399?focus=true)
Add new endpoints which replace our old vanity URLs that redirected to Microsoft forms. This replaces those URLs (which are hardcoded into the app) and redirects them instead to airtable, which prefills the language and OS.
Question for dotcom eng: Will the vanities be overridden automatically when this is deployed, or do we need to remove the vanities before this will go into effect?
---
~* [ ] **Have we load-tested** any new pages or internal API endpoints that will receive significant traffic? [See load testing docs](./../load_tests/README.md)~
=> feat: MBTA Go feedback form redirect endpoint

lib/dotcom_web/controllers/schedule_controller.ex, lib/dotcom_web/router.ex, test/dotcom_web/controllers/schedule_controller_test.exs
**Asana Ticket:** [Create dotcom schedule redirect URLs](https://app.asana.com/1/15492006741476/project/1205732265579288/task/1209949928014410?focus=true)
This adds a `/route/{id}` endpoint which will be used in T-Alerts texts as a shortcut to the schedule page. This is done partly to conserve characters, and partly so that we can use the redirect to include a GA campaign so that we know that the requests are coming from the alerts.
Instead of using the Route plug, this passes through whatever URL param is provided as the route id, so that it can handle cases like the Green line schedule page.
---
~* [ ] **Have we load-tested** any new pages or internal API endpoints that will receive significant traffic? [See load testing docs](./../load_tests/README.md)~
=> feat: Add /route/{id} endpoint for T-Alerts texts

lib/dotcom_web/templates/news_entry/show.html.eex
This clears up 👇 warning (and fixes a typo).
```
warning: <%# is deprecated, use <%!-- or add a space between <% and # instead
│
42 │               <%# This emails is hardcoded on purpose; the email can differ from the #{email} value. %>
│               ~
│
└─ lib/dotcom_web/templates/news_entry/show.html.eex:42: (file)
```
=> fix(warnings): Format EEx comment correctly

lib/dotcom/alerts.ex, lib/dotcom/system_status/commuter_rail.ex, lib/dotcom_web/controllers/alert_controller.ex
Hotfix to only reject service impacting alerts that are in effect today.
=> Only reject service impacting alerts from today

lib/dotcom_web/components/system_status/commuter_rail_status.ex
In preparation for more commuter-rail status work, I noticed that there was a lot of similarity between how different types of rows were defined in the Commuter Rail Status component. 
This aims to reduce that duplication, with the eventual goal of extracting shared visual components to re-usable components (for instance, pulling the icon / bold-text combo out as a "status label" that's more generic than the current `<.status_label />` component, which is pretty much only suited for subway.
As far as I've been able to tell with visual testing, this is a pure refactor that leaves the end result completely unchanged.
=> refactor: Reduce duplication in CR status component

lib/dotcom_web/components/system_status/commuter_rail_status.ex
No ticket.
---
The design for the commuter rail system status component says that the "title row" should have "Width fixed at 32px wider than the longest line name", which suggests an implementation of a grid or table, with titles having a 32px padding. The previous implementation had the row widths hard-coded, and had each row as a separate grid. This worked well, since all of the column widths were hard-coded, but it's also somewhat brittle. This change makes the implementation more closely match the intent described in the Figma.
(Before is to the left; After is to the right)
(Notice that the padding after the line name is shorter now. Honestly, I'm not sure how I feel about that on wider screens)
We may decide not to move forward with this, or to tweak the layout based on design …
=> refactor(cr-status): Use a single CSS `grid` instead of a list of disconnected `grid`'s

lib/dotcom_web/components/system_status/status_row_heading.ex, test/dotcom_web/components/system_status/subway_status_test.exs
Before on the left; After on the right
---
**Asana Ticket:** [Show "Now: Delay" on homepage and /alerts/subway status](https://app.asana.com/1/15492006741476/project/555089885850811/task/1209634655431456?focus=true)
=> fix(subway-status): Don't show "Expect Delay" when the prefix is "Now"

lib/dotcom/utils/time.ex, test/dotcom/utils/time_test.exs, test/support/generators/date_time.ex
This ensures that the `Dotcom.Utils.Time` module is always paying attention to its `inclusive` opt, and that its test coverage is keeping it honest.
---
No ticket.
=> chore: Clean up `Dotcom.Utils.Time` module and improve test coverage

lib/alerts/priority.ex, lib/dotcom_web/templates/schedule/_timetable.html.heex, lib/dotcom_web/views/schedule_view.ex, test/alerts/priority_test.exs, test/dotcom_web/views/schedule_view_test.exs
**Asana Ticket:** [SS | Track Changes on CR /timetable pages](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210331726103787?focus=true)
Adjusted the priority logic to always make track change alerts low priority, which removes them from showing in the top banner on timetable pages.
=> feat(DotcomWeb.ScheduleView): add track changes

lib/dotcom_web/live/trip_planner.ex
**Asana Ticket:** [QF | TP | Update Trip Planner <title> and content](https://app.asana.com/1/15492006741476/project/385363666817452/task/1209294962719705?focus=true)
Turns out adding breadcrumbs gives you the right title for free, and that assigning `:meta_description` directly just works.
=> feat(Live.TripPlanner): custom meta description and title

lib/dotcom/alerts.ex, test/dotcom/system_status/commuter_rail_test.exs, test/dotcom_web/components/system_status/subway_status_test.exs
In order to avoid hiding useful subway status when there are system-wide low-severity alerts, for instance for today's heat wave.
=> hotfix: Only show delays in system status of severity 2 or higher

assets/package-lock.json, assets/package.json
**Asana Ticket:** [QF | LiveView asset version mismatch. JavaScript version 1.0.9 vs. server 1.0.17. To avoid issues, please ensure that your assets use the same version as the server.](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210618974840960?focus=true)
I keep forgetting to check for this whenever somebody updates the Elixir LiveView version...
=> deps(npm): update phoenix_live_view

assets/ts/app/__tests__/channels-test.ts, assets/ts/app/channels.ts, assets/ts/schedule/components/Map.tsx, assets/ts/schedule/components/__tests__/MapTest.tsx
We were emitting lots of `console.error` messages that don't translate into anything meaningful. This PR aims to reduce the noisy errors we get.
- removes the `channel.onError` that as far as I can tell has never registered an actual meaningful error, just creates new errors on page change 🙄 
- downgrades the `console.error` to `console.warn` when the Map's reducer type isn't one of the expected ones
- adjusts the `handleJoin` call to pass in something more meaningful than the usual `{}`
=> fix(Map): reduce spurious console messages

config/runtime.exs
No ticket, just noticed a lot of `Could not check origin for Phoenix.Socket transport.` errors logged in prod.
=> fix: add host to check_origin

lib/timetable_loader.ex
Show the weekend timetable for the Quincy and Winthrop Ferries on Friday, July 4.
---
No ticket.
=> fix: Consider July 4 a weekend for ferry timetables

lib/dotcom_web/controllers/schedule/timetable_controller.ex
Make select Franklin Line train numbers no longer show `via Fairmount Line`.
(Before on the left; After on the right)
---
**Asana Ticket:** [QF | Update via Fairmount line numbers](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210678262944572?focus=true)
=> chore: Remove train numbers from `via Fairmount Line` list

lib/dotcom_web/controllers/places_controller.ex, lib/location_service/location_service.ex, test/location_service/location_service_test.exs
**Asana Ticket:** https://app.asana.com/1/15492006741476/project/555089885850811/task/1210649423464213?focus=true
AWS will return an error when asked to search for a text string longer than 200 characters. Let's handle this directly!
=> fix(LocationService): limit autocomplete text to 200 chars

lib/alerts/alert.ex, lib/dotcom_web/components/system_status/status_row_heading.ex, test/dotcom_web/components/system_status/subway_status_test.exs
(Note that when delays of different severities exist and get collapsed together for the homepage, only the most severe severity is shown.)
**Asana Ticket:** [SS/PW/Alerts | Delays "up to N minutes"](https://app.asana.com/1/15492006741476/project/1205718271156548/task/1210699069005382?focus=true)
---
<details>
<summary>Livebook code that I used to populate the data for ☝️ screenshots</summary>
I put 👇 code into this [LiveBook](https://github.com/mbta/dotcom/blob/main/livebooks/reusable/alerts.livemd)
```elixir
import Dotcom.Utils.DateTime, only: [now: 0]
alias Test.Support.Factories.Alerts.{Alert, InformedEntity}
alerts =
[
Alert.build(:alert,
active_period: [
{
now() |> Timex.shift(hours: -4),
now() |> Timex.shift(hours: 8)
}
],
effect: :delay,
severity: 3,
informed_entity: …
```
=> feat: Show severity (e.g. `up to 20 min`) for delay statuses

lib/dotcom_web/components/trip_planner/results.ex
**Asana Ticket:** [QF | TP | Make itinerary cards show pointer cursor on hover](https://app.asana.com/1/15492006741476/project/385363666817452/task/1210744258068580?focus=true)
---
This is tough to screenshot because screenshots don't include the cursor, but imagine 👇 image with a 👆 cursor over it
=> feat: Use the pointer cursor over itinerary details, because they are clickable

lib/dotcom_web/controllers/schedule/timetable_controller.ex
---
**Asana Ticket:** [QF | Update the description of ferry timetable pages in search results](https://app.asana.com/1/15492006741476/project/385363666817452/task/1210117915242712?focus=true)
=> fix: Don't include `Commuter Rail` in the description of ferry pages

lib/dotcom_web/templates/schedule/_timetable.html.heex
This reverts commit 14d8714f5573c67438cd2bc19be7a01440a3af8c.
I tested it out on the [Quincy Timetable Page](https://dev.mbtace.com/schedules/Boat-F7/timetable) on dev before deploying, and it doesn't look quite right. 👇 screenshot is from a 1400px-wide Firefox window.
Let's revert for now and figure out a more Right™ way of doing this.
=> Revert "fix: Allow timetables to scroll all the way to the left (#2646)"

lib/alerts/repo.ex, lib/alerts/repo/behaviour.ex, lib/dotcom/alerts.ex, lib/dotcom_web/controllers/cms_controller.ex, test/alerts/repo_test.exs, test/dotcom/alerts_test.exs, test/dotcom_web/controllers/cms_controller_test.exs
**Asana Ticket:** [Everywhere we use   @diversion_effects replace with using  @service_impacting_effects  instead](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210824489259944?focus=true)
=> fix(CMSController): render diversions based on planned service-impacting alerts

lib/dotcom/locales.ex, lib/dotcom_web.ex, lib/dotcom_web/hooks/restore_locale.ex, lib/dotcom_web/plugs/set_locale.ex, lib/dotcom_web/router.ex, test/dotcom_web/hooks/restore_locale_test.exs, test/dotcom_web/plugs/set_locale_test.exs
This enables easy retrieval of the locale for LiveViews. If there were a more straightforward way of reading the longer-lasting cookie into the LiveView I probably wouldn't bother with the session, but it works ✨ .
- Extracted the function for setting a locale into `Dotcom.Locales`
- Used `on_mount` to read the locale in all live views, and set it
- Restructured such that setting/using the locale should be disabled on the live prod website, and enabled everywhere else (including the staging environments).
=> feat(Plugs.SetLocale): put locale in the session

assets/js/app.js, assets/js/storage.js, assets/ts/app/channels.ts
**Asana Ticket:** [QF | SecurityError: The operation is insecure.](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210755669845451?focus=true)
Reproducible if you make your browser block all cookies. This PR lets our JS instantiate a Phoenix `LiveSocket` and `Socket` without the uncaught error that hindered much of the rest of the website JS from loading.
The resulting website isn't _perfect_ mind you, but at least it restores basic functionality to the searchbar, homepage tabs, etc.
=> fix: use in-memory storage if session/localStorage is unavailable

lib/location_service/location_service.ex, test/location_service/location_service_test.exs
:( I failed at fixing https://app.asana.com/1/15492006741476/project/1204352509486278/task/1210649423464213?focus=true and this PR should actually fix it so it no longer errors when someone pastes way too much text (beyond the limit which AWS Location Service accepts) into the trip planner location inputs. I decided it to make it do "nothing" (return an empty list).
=> fix(LocationService): actually handle long text

lib/dotcom_web/templates/layout/_footer.html.heex, lib/dotcom_web/views/layout_view.ex, priv/gettext/dotcom.pot
Changes links from Press Releases to Media Relations in the header and footer.
=> Change press release to media relations

lib/dotcom_web/plugs/content_security_policy.ex, lib/dotcom_web/views/helpers.ex
**Asana Ticket:** [Investigate requests we can offload to the CDN](https://app.asana.com/1/15492006741476/project/555089885850811/task/1211036325896900?focus=true)
Can compare the network tab in dev-blue and in prod to see that assets at the `/js/` and `/css/` paths are now being retreived from `cdn.mbta.com` instead of from the application.
=> fix: include host in static URL

assets/ts/schedule/components/schedule-finder/daily-schedule/DailyScheduleSubway.tsx
=> hotfix: Don't select `Weekday` in schedule-finder menu on Fridays

lib/alerts/cache/bus_stop_change_s3.ex
While debugging for https://github.com/mbta/dotcom/pull/2721, I shortened the TTL from the default (24 hours) to 1 minute for the bus-stop-changes cache. I intended for that to be temporary, but I accidentally merged without reverting that change.
---
No ticket.
=> fix: Restore the previous TTL for bus stop changes cache

assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/DailyScheduleSubway.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/DailyScheduleSubwayTest.tsx
Before on the left; After on the right.
**Asana Ticket:** [QF | Can we un-hide orange line headways?](https://app.asana.com/1/15492006741476/project/385363666817452/task/1211185862826337?focus=true)
=> fix: Show Orange Line headways in Schedule Finder

lib/dotcom/alerts.ex, lib/dotcom_web/live/commuter_rail_alerts.ex, lib/dotcom_web/router.ex, livebooks/reusable/alerts.livemd, priv/gettext/dotcom.pot, priv/gettext/es/LC_MESSAGES/dotcom.po, test/dotcom/alerts_test.exs, test/support/factories/alerts/alert.ex
Two rider-facing benefits:
1. This removes the not-terribly-helpful `All Alerts` / `Current Alerts` / `Planned Service Alerts` tab group from [the commuter rail alerts page](https://www.mbta.com/alerts/commuter-rail).
2. This lays the groundwork for live-updating commuter rail status when alerts change without requiring a page refresh.
**Asana Ticket:** [Replace CR alerts page with a LiveView](https://app.asana.com/1/15492006741476/project/1205718271156548/task/1210893459312443?focus=true)
=> chore: Replace commuter-rail alerts page with a LiveView

lib/dotcom_web/components/alerts.ex
Fixes a bug where images (and `For more information` URL's and `Updated` times) don't load when the description is missing.
**Asana Ticket:** [QF | Alert images should show up on /alerts/subway status even  if they have no additional information](https://app.asana.com/1/15492006741476/project/555089885850811/task/1211374431638884?focus=true)
=> fix: Images in embedded alerts with no descriptions

lib/dotcom/system_status/commuter_rail.ex, livebooks/reusable/alerts.livemd, test/dotcom/system_status/commuter_rail_test.exs
The fix is deceptively simple, and also a bit inelegant. We already have `Dotcom.SystemStatus.CommuterRail.commuter_rail_route_status/1`, which figures out the correct delay/cancellation count, so we can just use the data from that to populate `commuter_rail_status/0` as well.
The inelegance comes from the fact that the `<.alerts_commuter_rail_status />` frontend component relies on the data structure returned from `commuter_rail_status/0` being structured a particular way, which is different from how `commuter_rail_route_status/1` does it. So I added a bit of "adapter" logic to `route_info/1` to convert the data structure `commuter_rail_route_status/1` presents to the data structure `<.alerts_commuter_rail_status /> expects.
(This is especially inelegant because …
=> fix: Alert counts for multi-trip alerts in commuter rail status

lib/dotcom/alerts/subway/disruptions.ex, test/dotcom/alerts/subway/disruptions_test.exs
While testing https://github.com/mbta/dotcom/pull/2675, we discovered that the `/alerts/subway` page was crashing on both [dev-blue](https://dev-blue.mbtace.com/alerts/subway) and [dev-green](https://dev-green.mbtace.com/alerts/subway). That's because there's an alert in the test environment that is recurring and also has an effect period of `until further notice`.
Our [logic to combine contiguous active periods](https://github.com/mbta/dotcom/blob/d5a4a370f08037acbda9f731d2cdfd572a58ecb3/lib/dotcom/alerts/subway/disruptions.ex#L83) croaks if the active period list looks like `[{date1, nil}, {date2, _}]`, because it tries to get the service date of `nil`, which isn't a sensible thing to do. This PR fixes that by just short-circuiting when it sees `nil` in that spot.
---
This is a scenario …
=> fix: Don't crash the planned disruptions page if an alert is recurring and "until further notice"
