mbta/dotcom

apps/algolia/lib/algolia/object.ex, apps/algolia/lib/mix/tasks/algolia/update.ex, apps/algolia/test/object_test.exs, apps/algolia/test/support/mock_routes_repo.ex, apps/routes/lib/route.ex
**Asana Ticket:** [🔧 Refresh Algolia search](https://app.asana.com/0/555089885850811/1125318347335591)
I'm going to add some instructions to the wiki about how to run this.
<br>
=> Add mix task for Algolia updates

README.md
Fix semaphore badge in README
<br>
=> Fix semaphore badge

.github/PULL_REQUEST_TEMPLATE.md
Remove checklist from PR template since these items now have good coverage in CI
<br>
=> Remove checklist from PR template

apps/site/lib/site_web/templates/schedule/_trip_info.html.eex
**Asana Ticket:** [CR Schedules | Communicate unlimited weekend fares](https://app.asana.com/0/555089885850811/1124053272506029)
<br>
=> show unlimited fare link on CR schedule

apps/site/assets/js/alert-item.js, apps/site/assets/js/app.js, apps/site/assets/js/trip-planner-results.js, apps/site/assets/ts/components/ExpandableBlock.tsx, apps/site/assets/ts/trip-plan-results/__tests__/TripPlannerResultsTest.tsx, apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx, apps/site/lib/site_web/templates/trip_plan/_itinerary_alert.html.eex
**Asana Ticket:** [🔍 OpenStreetMaps | Trip Planner - Hide Alerts behind a link](https://app.asana.com/0/555089885850811/1126250841147222)
<br>
Assigned to: @ingridpierre
=> OSM Trip Planner - hide alerts behind a link

apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/schedule/__tests__/ScheduleNoteTest.tsx, apps/site/assets/ts/schedule/__tests__/SchedulePageTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleNoteTest.tsx.snap, apps/site/assets/ts/schedule/components/ScheduleNote.tsx, apps/site/assets/ts/schedule/components/SchedulePage.tsx, apps/site/assets/ts/schedule/schedule-loader.tsx, apps/site/lib/site_web/templates/schedule/_line.html.eex, apps/site/react_renderer/app.js
**Asana Ticket:** [⏱Schedules | Sidebar - Move Subway notes on Mobile](https://app.asana.com/0/555089885850811/1126274812113033)
<br>
=> Move Schedule Notes on Mobile

apps/site/assets/ts/schedule/components/Map.tsx, apps/site/lib/site/stream/vehicles.ex, apps/site/lib/site_web/channels/vehicle_channel.ex
**Asana Ticket:** [Schedules | Map disappears on Green Line parent page](https://app.asana.com/0/555089885850811/1125936468243532)
This fixes the issue with the map disappearing, but the data we are sending doesn't seem valid. We shouldn't be receiving or sending "update" events with an empty array as the data. It seems like it might be problem on the API side but it could use a closer look.
<br>
=> Map on Green Line parent page

apps/site/assets/ts/components/Modal.tsx, apps/site/assets/ts/components/__tests__/ModalTest.tsx, apps/site/assets/ts/components/__tests__/__snapshots__/ModalTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleFinderTest.tsx.snap, apps/site/assets/ts/schedule/components/ScheduleFinder.tsx
**Asana Ticket:** [🔧 Refactor modal to open/closed based on props](https://app.asana.com/0/555089885850811/1127423631852512)
The modal component's open/close state used to be managed internally. It was changed to receive this state as props so it could be more easily integrated into stateful components.
<br>
=> modal refactor

apps/site/assets/ts/schedule/components/ScheduleFinder.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ErrorMessage.tsx, apps/site/assets/ts/schedule/components/schedule-finder/OriginListItem.tsx, apps/site/assets/ts/schedule/components/schedule-finder/OriginModalContents.tsx, apps/site/assets/ts/schedule/components/schedule-finder/RoutePill.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContents.tsx, apps/site/assets/ts/schedule/components/schedule-finder/SelectContainer.tsx, apps/site/assets/ts/schedule/components/schedule-finder/StopNameLink.tsx
No Ticket
Just a clean-up of a component that grew too big.
<br>
=> refactor schedule finder

apps/site/test/detailed_stop_group_test.exs
NO TICKET
Fix a failing test that is clogging up CI.
<br>
=> fix test on master

apps/site/assets/css/_modal-component.scss, apps/site/lib/predicted_schedule.ex, apps/site/lib/site_web/controllers/mode_controller.ex
**Asana Ticket:** [⭐ Polish | Departures in Schedule Finder Modal](https://app.asana.com/0/555089885850811/1128011416736859)
<br>
=> Upcoming Departures with 4 predictions and style polish

upload_assets.sh
**Asana Ticket:** [🔧 upload images/fonts to S3 when deploying](https://app.asana.com/0/555089885850811/1126315817877626)
<br>
Assigned to: @paulswartz
=> upload fonts/images with max_age

README.md
This bug was hit today during a new setup, I documented because I've seen in the past as well.
<br>
=> Update README about asdf install 2x bug

apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx, apps/site/mix.exs
**Asana Ticket:** [🔥 Investigate services app error](https://app.asana.com/0/555089885850811/1129548528928905)
This has been deployed to dev-green and it seems to be resolved, see: https://green.dev.mbtace.com/schedules/238/line?direction_id=1
<br>
=> add services site application

README.md
(no ticket, did this on my own initiative)
Added some advice re: API keys to the `README.md` that would have saved me a few hours yesterday.
<br>
=> Mention current compatible API version in README

apps/site/assets/ts/schedule/components/schedule-finder/ErrorMessage.tsx
**Asana Ticket:** [⏱Schedules | Finder Tool - error message](https://app.asana.com/0/555089885850811/1128792702946715)
Two words that are easy to confuse if you type them all day got confused. Fixed.
<br>
=> Correct copy

apps/schedules/lib/repo.ex
**Asana Ticket:** [🔧 Look into Green Controller performance issues](https://app.asana.com/0/555089885850811/1129115952715486)
Virtually all of the time that a request for the Green Line page takes is spent in `load_from_other_repos`. I'm not 100% clear on why, but changing that function to use `Task.async` as opposed to `Task.async_stream` improved the average performance on this page, from about 1200 ms to about 900 ms.
<br>
=> Optimize trouble spot in `load_from_other_repos`

apps/content/priv/landing_page_with_all_paragraphs.json
See mbta/cms#282 and notes on https://app.asana.com/0/555089885850811/1111016757369336.
=> :thumb is no longer a JSON property for photos

apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/test/site_web/controllers/schedule/line_test.exs
**Asana Ticket:** [Schedule Finder: dedup service list](https://app.asana.com/0/555089885850811/1132113075246837)
<br>
=> dedup services

apps/site/lib/site_web/controllers/project_controller.ex, apps/site/lib/site_web/templates/project/index.html.eex, apps/site/test/site_web/controllers/content_controller_test.exs, apps/site/test/site_web/controllers/project_controller_test.exs
**Asana Ticket:** [🗂️ Project index | Update title and body text of /projects](https://app.asana.com/0/555089885850811/1131027733468481)
<br>
=> Project index | Update title and body text of /projects

apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleTableTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/TableRow.tsx
Noticed a missing id for an `aria-controls` element when looking over my PR from last week.
<br>
=> Schedule Finder: aria-controls fix-up

apps/site/lib/site_web/views/helpers.ex, apps/site/test/site_web/views/schedule_view_test.exs
https://github.com/mbta/dotcom/pull/112 was somehow merged w/o CI passing, this fixes up the dialyzer warnings and a test
<br>
=> Dialyzer and test fixup

apps/site/lib/site_web/templates/project/show.html.eex
**Asana Ticket:** [⭐ Projects | Remove hardcoded updated on date](https://app.asana.com/0/555089885850811/1131928348122847)
Needs rebase after dialyzer PR is merged
<br>
=> Projects | Remove hardcoded updated on date

apps/v3_api/test/headers_test.exs
No ticket. In the process of changing around some env vars on CI to try to address the Trip Planner/Backstop issue, I broke some Elixir tests. This fixes them.
<br>
=> Fix Elixir tests to work with new CI env vars

apps/site/lib/site_web/controllers/project_controller.ex, apps/site/test/site_web/controllers/cms_controller_test.exs
**Asana Ticket:** [🗂️ Project Index |  💧 Update breadcrumbs](https://app.asana.com/0/555089885850811/1132578944478173)
<br>
=> Project Index |  Update breadcrumbs

apps/site/assets/ts/projects/__tests__/MoreProjectsTableTest.tsx, apps/site/assets/ts/projects/components/Image.tsx, apps/site/assets/ts/projects/components/MoreProjectsRow.tsx, apps/site/assets/ts/projects/components/MoreProjectsTable.tsx, apps/site/assets/ts/projects/components/Route.tsx, apps/site/assets/ts/projects/components/__projects.d.ts
=> Move typescript defs out of tsx file (no jsx)

apps/site/assets/js/fullstory.js
**Asana Ticket:** [Reduce throttling on FullStory to record more sessions](https://app.asana.com/0/555089885850811/1134349200859705)
<br>
=> capture more fullstory sessions

apps/site/assets/css/_project-update.scss, apps/site/assets/ts/projects/__tests__/MoreProjectsTableTest.tsx, apps/site/assets/ts/projects/__tests__/__snapshots__/MoreProjectsTableTest.tsx.snap, apps/site/assets/ts/projects/components/MoreProjectsTable.tsx, apps/site/lib/site_web/controllers/project_controller.ex, apps/site/lib/site_web/router.ex, apps/site/lib/site_web/templates/project/_all_projects.html.eex, apps/site/lib/site_web/templates/project/index.html.eex, apps/site/test/site_web/controllers/project_controller_test.exs
**Asana Ticket:** [🗂️ Project Index |  Project List - Pagination functionality](https://app.asana.com/0/555089885850811/1131928348122855)
Instead of displaying just the first 50 project teasers in the "More Projects" table, we display 10 to start out, and add a button to fetch more from the server.
<br>
=> Paginate project list

apps/fares/lib/fare.ex, apps/fares/lib/fare_info.ex, apps/fares/lib/format.ex, apps/site/lib/site/content_rewriters/liquid_objects/fare.ex, apps/site/lib/site_web/templates/cms/paragraph/_fare_card.html.eex, apps/site/test/site_web/views/helpers_test.exs
**Asana Ticket:** [💲⛴️ Fares | Fix fare card media line for one-way ferry](https://app.asana.com/0/555089885850811/1131969990767401)
<br>
=> correction to ferry ticket description

apps/predictions/lib/repo.ex, apps/routes/lib/parser.ex, apps/routes/lib/repo.ex, apps/site/lib/site/realtime_schedule.ex, apps/site/lib/site_web/controllers/realtime_schedule_api.ex, apps/site/lib/site_web/router.ex, apps/site/test/site/realtime_schedule_test.exs, apps/site/test/site_web/controllers/realtime_schedule_api_test.exs
**Asana Ticket:** [TNM Performance: Fetch fewer predictions](https://app.asana.com/0/555089885850811/1133112028153973)
New API end point for Realtime Schedule data to use in Transit Near Me.
<br>
=> Realtime Schedule API

apps/cms/lib/api/static.ex, apps/cms/lib/repo.ex, apps/cms/priv/_paragraph.json, apps/cms/test/api/static_test.exs, apps/cms/test/repo_test.exs, apps/site/lib/site_web/controllers/project_controller.ex, apps/site/lib/site_web/templates/project/index.html.eex, apps/site/lib/site_web/views/paragraph_view.ex, apps/site/lib/site_web/views/partial_view.ex, apps/site/lib/site_web/views/project_view.ex, apps/site/test/site_web/controllers/project_controller_test.exs, apps/site/test/site_web/views/partial_view_test.exs
**Asana Ticket:** [Projects Index | Text Partial](https://app.asana.com/0/555089885850811/1133902923804293)
Instead of hard coding the text intro to this page, use a CMS paragraph that authors have access to edit using the paragraph ("partial") system.
NOTE: Required an update to a few repo and view functions to work properly.
=> Projects Index | Text Partial

apps/site/assets/css/_banner.scss, apps/site/assets/ts/helpers/css.ts, apps/site/assets/ts/helpers/date.ts, apps/site/assets/ts/projects/__tests__/BannerTest.tsx, apps/site/assets/ts/projects/__tests__/MoreProjectsTableTest.tsx, apps/site/assets/ts/projects/__tests__/__snapshots__/BannerTest.tsx.snap, apps/site/assets/ts/projects/components/Banner.tsx, apps/site/assets/ts/projects/components/MoreProjectsRow.tsx, apps/site/assets/ts/projects/components/MoreProjectsTable.tsx, apps/site/assets/ts/projects/components/__projects.d.ts, apps/site/assets/ts/projects/projects-loader.tsx, apps/site/assets/ts/stop/components/RoutePillList.tsx, apps/site/lib/site_web/controllers/project_controller.ex, apps/site/lib/site_web/templates/page/_banner.html.eex, apps/site/lib/site_web/templates/project/_banner.html.eex, apps/site/lib/site_web/templates/project/_featured_project.html.eex, apps/site/lib/site_web/templates/project/index.html.eex, apps/site/lib/site_web/views/helpers/cms_router_helpers.ex, apps/site/lib/site_web/views/page_view.ex, apps/site/react_renderer/app.js
**Asana Ticket:** [🗂️ Project Index |  Project Banner](https://app.asana.com/0/555089885850811/1132297856215673)
<br>
=> Project Index |  Project Banner

apps/site/assets/css/_project-update.scss, apps/site/assets/ts/projects/__tests__/FeaturedProjectsList.tsx, apps/site/assets/ts/projects/__tests__/RoutePillListTest.tsx, apps/site/assets/ts/projects/__tests__/__snapshots__/FeaturedProjectsList.tsx.snap, apps/site/assets/ts/projects/components/FeaturedProject.tsx, apps/site/assets/ts/projects/components/FeaturedProjectsList.tsx, apps/site/assets/ts/projects/components/FeaturedProjectsRow.tsx, apps/site/assets/ts/projects/components/MoreProjectsRow.tsx, apps/site/assets/ts/projects/components/RouteIcon.tsx, apps/site/assets/ts/projects/components/RoutePill.tsx, apps/site/assets/ts/projects/components/RoutePillList.tsx, apps/site/assets/ts/projects/projects-loader.tsx, apps/site/lib/site_web/controllers/project_controller.ex, apps/site/lib/site_web/templates/project/_featured_projects.html.eex, apps/site/lib/site_web/templates/project/index.html.eex
**Asana Ticket:** [🗂️ Project Index |  Project Feature](https://app.asana.com/0/555089885850811/1132297856215674)
Added "Featured Projects" to the new project index page, i.e. those that have the `sticky` flag set except for the one being used for the banner.
<br>
=> Feature projects on new project index

apps/site/lib/site_web/templates/project/_featured_projects.html.eex, apps/site/react_renderer/app.js
No ticket. Was working on something else entirely when I realized I'd neglected to do this, so I did it.
<br>
=> Render featured-projects list server-side

apps/site/lib/site/realtime_schedule.ex, apps/site/lib/site/transit_near_me.ex, apps/site/test/site/realtime_schedule_test.exs
NO TICKET
These are changes that came up when I was adjusting Transit Near Me to use this API.
- add the header to the route struct
- format the prediction an schedule times
<br>
=> Realtime API | format prediction / schedule times, use enhanced route

apps/site/lib/site_web/controllers/schedule/schedule_api.ex
**Asana Ticket:** [⏱️ Schedules | train times on Lowell line are shown out of order](https://app.asana.com/0/555089885850811/1133934151259692)
Re-order the trips by the first schedule in the trip after the full schedules have been pruned by the selected stop. 
We prune the schedules after fetching them by route since querying the schedules API by stop doesn't include the downstream stops. We need the downstream schedules anyway and the cache hit ratio should be better when we query without stop. We might want to check on the memory load here in our performance meeting today though.
<br>
=> Schedules | Sort pruned schedules

apps/site/lib/site/transit_near_me.ex
No ticket. I accidentally merged a branch (https://github.com/mbta/dotcom/pull/152) with a typespec that had become outdated. Fixed.
<br>
=> Fix one typespec in TNM

apps/site/assets/css/_utilities.scss
**Asana Ticket:** [🐞 Invisible connection pills!](https://app.asana.com/0/555089885850811/1136301236383445)
Added some selectors so that pills for Green Line branches get the same styling as generic Green Line pills.
<br>
=> Cause green line branch pills to reappear in connections

apps/cms/lib/partial/teaser.ex, apps/site/assets/css/_project-update.scss, apps/site/assets/ts/projects/__tests__/MoreProjectsRow.tsx, apps/site/assets/ts/projects/__tests__/__snapshots__/MoreProjectsRow.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/MoreProjectsTableTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/ProjectsPageTest.tsx.snap, apps/site/assets/ts/projects/components/MoreProjectsRow.tsx, apps/site/assets/ts/projects/components/MoreProjectsTable.tsx
**Asana Ticket:** [Add status to project index more-projects table](https://app.asana.com/0/555089885850811/1135411616097675)
Added the "Status" field to the table, against the day when we have a significant number of them filled in.
<br>
=> Add status to more-projects table

apps/site/test/site_web/controllers/project_controller_test.exs, apps/stops/test/route_stops_test.exs
No ticket. Fixed some failures master has developed by removing one outdated test and updating another.
<br>
=> Make some Elixir tests pass again

apps/schedules/lib/repo_condensed.ex, apps/site/lib/site/realtime_schedule.ex
NO TICKET
Avoid 500 errors when cache is warming.
<br>
=> allow longer time for realtime cache to warm

apps/site/assets/ts/tnm/components/TransitNearMe.tsx
NO TICKET
increase polling interval to take some pressure off the API
<br>
=> increase TNM polling interval

apps/stops/test/route_stops_test.exs
**Asana Ticket:** [Fix failing route stops tests](https://app.asana.com/0/555089885850811/1138833128646979)
- "Harvard" -> "Harvard Square"
- "Dudley" -> "Dudley Station"
=> Update changed API stop names

apps/site/assets/ts/projects/__tests__/RoutePillListTest.tsx, apps/site/assets/ts/projects/components/RoutePillList.tsx
**Asana Ticket:** [🔥 Project Index | Another invisible pill!](https://app.asana.com/0/555089885850811/1138833128646984)
Updated:
<br>
=> fix project pill className for all subway lines

apps/site/assets/css/_transit-near-me.scss, apps/site/assets/css/_variables.scss
**Asana Ticket:** [🐞 TNM | scrolling content covers filters](https://app.asana.com/0/555089885850811/1138809250700914)
<br>
=> fix TNM z-index issue

apps/site/assets/css/core.scss
**Asana Ticket:** [🐞 Schedules | Finder Tool -  address persistent zoom on iOS ](https://app.asana.com/0/555089885850811/1137523575743817)
Tested on dev green and confirmed that it fixes the problem for iOS 10 / safari .
<br>
=> Schedules | Finder Tool -  address persistent zoom on iOS 

apps/site/assets/css/_transit-near-me.scss, apps/site/assets/css/project-page.scss, apps/site/assets/ts/components/FilterButton.tsx, apps/site/assets/ts/components/ModeFilter.tsx, apps/site/assets/ts/projects/__tests__/FilterAndSearchTest.tsx, apps/site/assets/ts/projects/__tests__/SubwayFilterTest.tsx, apps/site/assets/ts/projects/__tests__/__snapshots__/SubwayFilterTest.tsx.snap, apps/site/assets/ts/projects/components/FilterAndSearch.tsx, apps/site/assets/ts/projects/components/ProjectsPage.tsx, apps/site/assets/ts/projects/components/SubwayFilter.tsx, apps/site/assets/ts/tnm/components/ModeIcon.tsx, apps/site/lib/site_web/controllers/project_controller.ex, apps/site/test/backstop.json
**Asana Ticket:** [🗂️ Project Index |  Filter - Subway filters](https://app.asana.com/0/555089885850811/1136817875129091)
Implemented the subway line filter buttons for the project page.
<br>
=> Project page subway filters

apps/routes/test/repo_test.exs, apps/stops/test/nearby_test.exs, apps/stops/test/route_stops_test.exs
**Asana Ticket:** [Fix API test fails](https://app.asana.com/0/555089885850811/1140056503281250)
Fixed a few tests that fail due to updated API information.
<br>
=> Fix some API tests

apps/schedules/lib/hours_of_operation.ex, apps/schedules/lib/parser.ex, apps/schedules/lib/repo.ex, apps/v3_api/lib/route_patterns.ex
This came up in some route pattern selection work where it would be helpful to have the new format for the `RoutePattern.name`.
Also, it is probably good not to fall behind.
<br>
=> support latest v3 api version

apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageTest.tsx.snap, apps/site/assets/ts/stop/__tests__/sidebar/ParkingTest.tsx, apps/site/assets/ts/stop/__tests__/sidebar/__snapshots__/ParkingTest.tsx.snap, apps/site/assets/ts/stop/components/sidebar/Parking.tsx, apps/site/test/site_web/views/stop/parking_view_test.exs, apps/stops/lib/stop.ex
**Asana Ticket:** [🚙 Add overnight parking data](https://app.asana.com/0/555089885850811/1134739080933662)
- adds new elixir key to parking capacity struct
- mirrored changes in react components
- adjusted output according to asana for each overnight value in elixir prior to react
- prints "Unknown" if overnight data is not [yet] available in the api, or other invalid key is found.
=> capture and render overnight parking information

apps/schedules/lib/repo_condensed.ex
Missed this case on prior work to support latest v3 API.
Not sure why test were passing, but noticed them failing this AM.
<br>
=> get latest API version to work w/ Condensed Schedule

apps/site/assets/ts/helpers/fetch.ts, apps/site/assets/ts/leaflet/components/__mapdata.d.ts, apps/site/assets/ts/schedule/__tests__/MapTest.tsx, apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap, apps/site/assets/ts/schedule/components/Channel.ts, apps/site/assets/ts/schedule/components/Map.tsx, apps/site/assets/ts/schedule/components/ScheduleDirection.tsx, apps/site/assets/ts/schedule/components/direction/ScheduleDirectionButton.tsx, apps/site/assets/ts/schedule/components/direction/ScheduleDirectionMenu.tsx, apps/site/assets/ts/schedule/components/direction/reducer.ts, apps/site/assets/ts/schedule/schedule-loader.tsx, apps/site/lib/leaflet/map_data.ex, apps/site/lib/leaflet/map_data/marker.ex, apps/site/lib/site_web/channels/vehicle_channel.ex, apps/site/lib/site_web/controllers/schedule/line.ex, apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/lib/site_web/controllers/schedule/line/maps.ex, apps/site/lib/site_web/controllers/schedule/map_api.ex, apps/site/lib/site_web/router.ex, apps/site/lib/site_web/templates/schedule/_line.html.eex, apps/site/react_renderer/app.js, apps/site/test/site_web/controllers/schedule/line_test.exs, apps/v3_api/lib/shapes.ex
**Asana Ticket:** [⏱Schedule | Directionality - Update Map](https://app.asana.com/0/555089885850811/1134071785708804)
<br>
=> Schedule | Directionality - Update Map

apps/site/assets/ts/schedule/components/ScheduleDirection.tsx
=> Schedule | Map rebase bugfix, use state.directionId

apps/site/lib/site_web/controllers/schedule/timetable_controller.ex, apps/site/lib/site_web/templates/schedule/_timetable.html.eex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs
**Asana Ticket:** [Foxboro | Fairmount timetable needs FRANK](https://app.asana.com/0/555089885850811/1143031265509300)
Added FRANK notation to timetable for Foxboro pilot
<br>
=> Foxboro | Frank in CR-Fairmount timetable

apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/stops/test/route_stops_test.exs
**Asana Ticket:** [Red Line API Test Failures on Master](https://app.asana.com/0/555089885850811/1143246874225985)
Updated a few tests so that branch names and grouping of branches reflects our new conventions, un-breaking a number of tests in the process.
<br>
=> Fix some tests to agree with newest API version

apps/site/test/detailed_stop_group_test.exs
**Asana Ticket:** [Update stop test with new "Franklin Line/Foxboro Pilot" route name](https://app.asana.com/0/555089885850811/1145171364034021)
=> Test fix: "Franklin Line" -> "Franklin Line/Foxboro Pilot"

apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/schedule/__tests__/ScheduleNoteTest.tsx, apps/site/assets/ts/schedule/__tests__/SchedulePageTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleNoteTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/SchedulePageTest.tsx.snap, apps/site/assets/ts/schedule/components/LineDiagram.tsx, apps/site/assets/ts/schedule/components/ScheduleNote.tsx, apps/site/assets/ts/schedule/components/SchedulePage.tsx, apps/site/assets/ts/schedule/components/__schedule.d.ts, apps/site/assets/ts/schedule/schedule-loader.tsx, apps/site/lib/site/schedule_note.ex, apps/site/lib/site_web/templates/schedule/_direction_select.html.eex, apps/site/lib/site_web/templates/schedule/_line.html.eex, apps/site/lib/site_web/templates/schedule/_route_notes.html.eex, apps/site/lib/site_web/views/helpers/stop_helpers.ex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site/lib/schedule_note_test.exs, apps/site/test/site_web/views/schedule_view_test.exs
**Asana Ticket:** [Foxboro | Event Service | Add disclaimer/link to pilot](https://app.asana.com/0/555089885850811/1140493168430473)
<br>
=> Foxboro | Event Service | Add disclaimer/link to pilot

apps/site/test/site_web/controllers/fare_controller_test.exs, apps/stops/test/route_stop_test.exs
No ticket. Ferries only go to Georges Island in summer, so these tests have begun failing.
<br>
=> Fix two tests broken by winter ferry service changes

apps/site/assets/css/_schedule-direction.scss, apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap, apps/site/assets/ts/schedule/components/direction/BusMenu.tsx, apps/site/assets/ts/schedule/components/direction/GreenLineMenu.tsx, apps/site/assets/ts/schedule/components/direction/ScheduleDirectionMenu.tsx, apps/site/assets/ts/schedule/components/direction/menu-helpers.ts
**Asana Ticket:** [⏱Schedules | Green line special case for route selection](https://app.asana.com/0/555089885850811/1141160481766011)
Added Green line route switching capability
<br>
=> Green line route switcher

apps/site/test/site/lib/vehicle_helpers_test.exs
**Asana Ticket:** [Fall Rating | Update failing vehicle helpers tests](https://app.asana.com/0/555089885850811/1146862506834061)
Rating change. Fixing [failing tests](https://semaphoreci.com/mbta/dotcom/branches/master/builds/312) on master.
- trip #s don't parse on a non-current rating
=> Fall 2019 rating change | Test updates

apps/site/assets/css/_social.scss, apps/site/lib/site_web/templates/layout/_footer.html.eex
**Asana Ticket:** [Add Facebook icon to global footer](https://app.asana.com/0/555089885850811/1143200501721132)
Links to https://www.facebook.com/TheMBTA/
=> Add Facebook icon/link back to global footer

apps/site/assets/css/_shuttles-page.scss, apps/site/assets/ts/shuttles/__tests__/ShuttlesOverviewTest.tsx, apps/site/assets/ts/shuttles/__tests__/ShuttlesPageTest.tsx, apps/site/assets/ts/shuttles/__tests__/__snapshots__/ShuttlesOverviewTest.tsx.snap, apps/site/assets/ts/shuttles/__tests__/__snapshots__/ShuttlesPageTest.tsx.snap, apps/site/assets/ts/shuttles/components/ShuttlesOverview.tsx, apps/site/assets/ts/shuttles/components/ShuttlesPage.tsx, apps/site/assets/ts/shuttles/shuttles-loader.tsx, apps/site/lib/site_web/controllers/helpers.ex, apps/site/lib/site_web/controllers/schedule/shuttles_controller.ex, apps/site/lib/site_web/templates/schedule/_shuttles.html.eex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/controllers/helpers_test.exs
* Adds route data to the shuttles page React component
* Adds helper function to access JSON-safe route data
* Creates buttons dynamically from route direction_destinations and adds an event handler and initial effect
* Adds initial tests for ShuttlesPage and ShuttlesOverview
**Asana Ticket:** [Shuttles | Direction selector](https://app.asana.com/0/477545582537986/1148592031135784/f)
=> add initial shuttle page overview with direction buttons

apps/site/lib/site/shuttle_diversion.ex, apps/site/lib/site_web/controllers/helpers.ex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/views/schedule_view_test.exs
**Asana Ticket:** [Shuttles | Establish and wire up API dependencies](https://app.asana.com/0/477545582537986/1149842993086361/f)
I wanted to get this up as early as possible, so there are no tests of the new module yet 😓
It is intended as a one-stop shop for the Shuttles tab specifically. Lists of `shapes` and `stops` are returned, which correspond to polylines and markers we can draw on the map (and `stops` can also be used to build the stop selector for the detail view).
* The stop selector can be built from `stops` of type `rail_affected`
* The map markers can be drawn from `stops` of type `rail_unaffected` and `shuttle`
* The shuttle and rail lines can be drawn from `shapes` according to `is_shuttle_route`
<details>
<summary>Example data structure for the Red Line diversion</summary> …
=> Add shuttle data dependencies

apps/site/lib/site_web/templates/schedule/_shuttles.html.eex
**Asana Ticket:** [Shuttles | Show existing full alert component on this tab](https://app.asana.com/0/477545582537986/1148592031135794/f)
This is copied straight from the current alerts section in `schedule/_line.html.eex`, so it should show the same set of alerts.
=> Copy existing alerts section to Shuttles tab

apps/site/lib/site_web/templates/layout/_footer.html.eex
**Asana Ticket:** [Update Instrgram URL](https://app.asana.com/0/555089885850811/1153706298243970?du=1149164108974353&invite=575f3f3f994707d96407b76ff2caf727)
Changes the site footer link from https://www.instagram.com/mbtapics/ to https://www.instagram.com/thembta/
=> Update instagram URL

apps/site/lib/site_web/controllers/schedule/line.ex, apps/site/lib/site_web/controllers/schedule/line_controller.ex
The root of this issue is that the stop data for the line page is being filtered by which stops are associated with a shape, which we're using to determine which stops are on which "branch" of a line. However, this is not a supported way to use shapes (the `stops` relationship on shapes may be deprecated in the future), and we think this is why some of the stops were missing.
Luckily the Schedule Finder origin picker only requires a flat list of stops on all branches/variants of the line, so in this case we can just send it the list of stops on the route, prior to the shape filtering.
**Asana Ticket:** [🐞 Schedule Finder origin picker is missing stops](https://app.asana.com/0/477545582537986/1146873289023569/f)
=> Fix missing stops in Schedule Finder origin picker

apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/helpers/icon.tsx, apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/SchedulePageTest.tsx.snap, apps/site/assets/ts/schedule/components/LineDiagram.tsx
**Asana Ticket:** [Line Diagram | Connection Tooltips](https://app.asana.com/0/385363666817452/1141229989083703/f)
* Uses Bootstrap tooltip on connection link elements
* Adds method to output descriptive connection names
* Adds small spacing change to connection links to improve focus outline appearance
=> Add tooltip to Line Diagram connections

apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx, apps/site/assets/ts/schedule/components/direction/reducer.ts
This replicates the behavior of the old line diagram where the "reverse direction" button reloads the page with a new `direction_id` param.
**Asana Ticket:** [Line Diagram | Update direction_id in page URL when changing directions](https://app.asana.com/0/385363666817452/1155400692401305/f)
=> Update URL when line diagram direction changes

apps/site/assets/css/_schedule-page.scss
**Asana Ticket:** [Schedule Finder | Polish | Mobile table layout is cramped](https://app.asana.com/0/385363666817452/1156256290328825/f)
Increases width of table, tightens space all around.
=> Improve schedule finder mobile table layout

apps/site/assets/js/app-entry.js, apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/ts/components/ExpandableBlock.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/ExpandableBranch.tsx
**Asana Ticket:** [Line Diagram | Keep collapse control in place during interaction](https://app.asana.com/0/385363666817452/1157057043034644/f)
* Adds an optional prop to `<ExpandableBlock />` to specify the [`preventScroll` option](https://caniuse.com/#feat=mdn-api_htmlelement_focus_preventscroll_option) for element focusing -- and uses it for the `<ExpandableBranch />` in the line diagram.
* Adds [a polyfill](https://github.com/calvellido/focus-options-polyfill) to extend browser support for this beyond Chrome and Firefox
=> Line Diagram | Keep collapse control in place during interaction

apps/site/assets/css/_schedule-page-line-diagram.scss, apps/site/assets/ts/components/ExpandableBlock.tsx, apps/site/assets/ts/components/__tests__/ExpandableBlockTest.tsx, apps/site/assets/ts/helpers/icon.tsx, apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx, apps/site/assets/ts/schedule/__tests__/VehicleIconsTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/SingleStopTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/lineDiagramData/live-data.json, apps/site/assets/ts/schedule/components/__schedule.d.ts, apps/site/assets/ts/schedule/components/line-diagram/ExpandableBranch.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/assets/ts/schedule/components/line-diagram/SingleStop.tsx, apps/site/assets/ts/schedule/components/line-diagram/VehicleIcons.tsx, apps/site/lib/site_web/controllers/schedule/line_api.ex, apps/site/test/site_web/controllers/line_api_test.exs
Visualizing Green Line bunching in real-time! 🚀
=> Show real-time vehicles on new line diagram

apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
**Asana Ticket:** [Pull out the code about polling](https://app.asana.com/0/385363666817452/1160944420414808/f)
Deleted code relevant to fetching and setting our live data but left relevant dependencies installed and affected components as is, setting the affected variable to an empty object.
=> Deal with no live data for now.

apps/site/lib/site_web/templates/layout/_footer.html.eex
**Asana Ticket:** [Footer | Add link to Lost and Found page](https://app.asana.com/0/385363666817452/1141024896875052/f)
=> Add Lost and Found link to footer

apps/site/lib/predicted_schedule.ex, apps/site/test/predicted_schedule_test.exs
This addresses an issue where, on stop pages and Transit Near Me, delayed commuter rail departures would display as "On time" if the current time was between the scheduled and predicted times. This was because we requested schedules with a "from now onwards" filter, so the resulting PredictedSchedule had only a prediction with no schedule, and the frontend defaults to displaying "On time" in this case. A separate ticket has been opened regarding this fallback behavior.
**Asana Ticket:** [🐞 CR stop page predictions "On time" even when delayed](https://app.asana.com/0/385363666817452/1157737923029097/f)
=> Fix delayed CR trips showing as "On time"

apps/site/assets/ts/jest.config.js
This fixes the immediate issue of every new branch and statement needing to have 100% coverage or it fails the build, because we were so close to the current thresholds. Separately, we can discuss how to align our code coverage approaches and decide on a long-term solution.
Relevant Asana ticket: [🔧 Decide on a common approach to test coverage](https://app.asana.com/0/385363666817452/1162707544957701/f)
=> Adjust TS test coverage thresholds

apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/lib/site/application.ex, apps/site/lib/site_web/controllers/schedule/line_api.ex, apps/site/mix.exs
No ticket. Yanking polling again until we figure out the problem with the cache.
=> Re-revert polling

apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/ExpandableBranch.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
This is a small refactor extracted from Cristen's schedule finder inputs branch — since it seemed independent of those changes, I thought we could review it separately.
=> Simplify typing of stop click function

apps/site/lib/site_web/controllers/schedule/line_api.ex, apps/site/test/site_web/controllers/line_api_test.exs
This way, even old clients can't hammer the server.
=> fix: disable the realime LineAPI

apps/site/test/site_web/controllers/line_api_test.exs
=> Adjust one test to pass

.envrc.template, apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/config/config.exs, apps/site/config/test.exs, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/mix.exs, apps/site/test/site_web/controllers/customer_support_controller_test.exs, docs/ENVIRONMENT.md, mix.lock
**Asana Ticket:** [Address spam on feedback form](https://app.asana.com/0/385363666817452/1165373168335001/f)
=> Add reCAPTCHA protection to feedback form

docs/TESTING.md
I remembered some time ago reading a doc about our use of CBT, but couldn't find it. Turns out it was in an unfinished branch Cristen made and had shown me once. I added this helpful info to our `TESTING` doc, and did some reformatting and typo fixes while I was in there.
cc @alicia-mbta @beeuhtricks
=> Add docs for CrossBrowserTesting

.github/PULL_REQUEST_TEMPLATE.md
**Asana Ticket:** [Ops | Write a PR checklist](https://app.asana.com/0/555089885850811/1162467761333249)
Or, "Some Things We Learned The Hard Way". These are some things that have proven to be gotchas in the past. In an effort to prevent making the same mistakes again, let's systematically check these things whenever we open a PR.
=> Add PR checklist to PR template

docs/TESTING.md
=> Update location of CrossBrowserTesting AuthKey

apps/site/assets/ts/helpers/service.ts, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleModalContentTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx
**Asana Ticket:** ["Regular" bus weekday schedules show up in Schedule Finder during reduced service](https://app.asana.com/0/385363666817452/1167020753909113/f)
Adds logic to render an additional message to convey the absence of service.
Technically, it checks whether any of the passed in services have a date range containing the present day.
---
=> Show "no scheduled trips" text in schedule modal

apps/site/assets/css/_select-custom.scss, apps/site/assets/ts/schedule/__tests__/ServiceOptGroupTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ServiceOptGroup.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
**Asana Ticket:** [Services Picker | Highlight current service with "Now" label](https://app.asana.com/0/385363666817452/1170321197668881/f)
If there is a current service, this change adds a (Now) indicator to the relevant option in the services picker. 
---
=> Highlight current service with "Now" label

apps/site/assets/js/algolia-result.js, apps/site/assets/js/test/algolia-result_test.js, apps/site/assets/js/test/algolia-results_test.js, apps/stops/test/api_test.exs
**Asana Ticket:** [🐞 Search | Location icon is wrong](https://app.asana.com/0/555089885850811/1150683371563985)
The wrong icon is showing for locations in searches:
After:
=> Fix location icon

docs/TESTING.md
=> Add section on ExVCR to TESTING.md

apps/site/assets/ts/components/Loading.tsx, apps/site/assets/ts/components/__tests__/LoadingTest.tsx, apps/site/assets/ts/components/__tests__/__snapshots__/LoadingTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleTableTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx, apps/site/assets/ts/schedule/components/schedule-finder/TripDetails.tsx
No Asana ticket, just a quick refactor opportunity I spotted working on other things.
---
=> Refactor out a Loading component

apps/site/assets/ts/components/Modal.tsx
No Asana Ticket, just a small bit of cleanup I came across.
---
=> Remove an unused interface

apps/site/lib/site_web/controllers/schedule/cms.ex
**Asana Ticket:** [⏱️Schedules | Display news entries for the specific route AND its parent mode](https://app.asana.com/0/555089885850811/1169031641902619)
Besides retrieving news/teasers from the specific line, we also want to retrieve the ones tagged with its mode to make content editors' lives easier. The changes in this PR retrieve those, removes duplicates and sorts them by date descending as requested.
=> Get additional teasers from mode

apps/fares/lib/min_max_fare.ex, apps/fares/test/min_max_fare_test.exs, apps/site/lib/site_web/controllers/schedule/schedule_api.ex, apps/site/lib/trip_info.ex
Asana ticket: [🎫 Trip Planner | Determine highest and lowest fares in Fares app](https://app.asana.com/0/555089885850811/1175251002332392)
- Moved and renamed apps/site/lib/site/base_fare.ex -> apps/fares/lib/min_max_fare.ex
- Added the logic and tests to obtain the highest fare analogously as it is done for the lowest fare
=> Get highest and lowest fare

apps/site/assets/css/_trip-plan-results.scss, apps/site/assets/ts/components/Accordion.tsx, apps/site/assets/ts/components/__tests__/AccordionTest.tsx, apps/site/assets/ts/components/__tests__/__snapshots__/AccordionTest.tsx.snap, apps/site/assets/ts/trip-plan-results/__tests__/__snapshots__/TripPlannerResultsTest.tsx.snap, apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx, apps/site/lib/site_web/templates/trip_plan/_itinerary.html.eex, apps/site/lib/site_web/templates/trip_plan/_itinerary_tab.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [🎫 Style update | Map & trip details accordion](https://app.asana.com/0/385363666817452/1162903717356817/f) and [🎫 Style update | Add total itinerary time to summary section](https://app.asana.com/0/385363666817452/1169236529454065/f)
Updated itinerary styles to accommodate the upcoming fares display!
---
=> Map & trip details accordion with total itinerary times

apps/site/test/site_web/controllers/schedule_controller_test.exs
This test has broken due to bus replacement schedules in GTFS, but more
importantly it doesn't seem to be testing any logic in our application.
No Asana ticket, CI just started failing
---
=> Remove a test that isn't actually testing our code

apps/site/assets/ts/schedule/__tests__/UpcomingDeparturesTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/UpcomingDeparturesTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/UpcomingDepartures.tsx
**Asana Ticket:** [🚍Schedule Finder | Upcoming Departures | Add empty state when no predictions available](https://app.asana.com/0/555089885850811/1173752461829233)
---
=> Add empty state for <UpcomingDepartures />

apps/site/test/site/lib/vehicle_helpers_test.exs
No ticket, just fixing a test that started failing
---
=> Update test to use the current service

apps/fares/lib/one_way.ex, apps/fares/test/one_way_test.exs, apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/test/site_web/controllers/trip_plan_controller_test.exs, apps/trip_plan/lib/trip_plan/transit_detail.ex
**Asana Ticket:** [Fare Calculator Accordion | Data for reduced fares](https://app.asana.com/0/555089885850811/1177449860049777)
This PR contains the logic to retrieve the reduced fares per mode. Backend changes, no visual impact.
=> Obtain reduced fares

apps/site/lib/site_web/templates/schedule/_timetable_schedule.html.eex, apps/site/lib/site_web/views/helpers.ex, apps/site/lib/site_web/views/schedule/trip_list.ex, apps/site/test/predicted_schedule/display_test.exs, apps/site/test/site/lib/vehicle_helpers_test.exs, apps/site/test/site_web/controllers/stop_controller_test.exs, apps/site/test/site_web/views/alert_view_test.exs, apps/site/test/site_web/views/schedule/stop_list_view_test.exs, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [🎫 Trip Planner | Update timestamp formatting on trip plan steps to match our current style](https://app.asana.com/0/385363666817452/1178027883917561/f)
---
=> Update timestamp formatting

README.md
Fix the links to the environment variables docs
No ticket, just noticed these links in the README were broken.
---
=> Fix the links to the environment variables docs

apps/site/lib/site_web/templates/layout/_footer.html.eex, apps/site/lib/site_web/templates/static_page/about.html.eex
**Asana Ticket:** [Footer | Add Engineering Resources link](https://app.asana.com/0/385363666817452/1178114575319500/f)
---
=> Add Design Standards and Guidelines link to footer

README.md, apps/trip_plan/README.md
**Asana Ticket:** [🎫 Investigate | Elixir/OTP Boundaries](https://app.asana.com/0/1134952491130998/1169236529454069)
Add a TripPlan application Readme.
Include information on how we use OpenTripPlanner.
---
=> Add a TripPlan application Readme

apps/site/lib/site_web/templates/trip_plan/_itinerary_fares.html.eex
**Asana Ticket:** [Fare Calculator | Polish | "Monthly Pass" header](https://app.asana.com/0/555089885850811/1179944684136545)
Change "Monthly Pass Fare" header to "Monthly Pass"
---
=> Change "Monthly Pass Fare" header to "Monthly Pass"

apps/fares/test/one_way_test.exs, apps/site/assets/css/_trip-plan-fare-calculator.scss, apps/site/assets/css/_trip-plan-results.scss, apps/site/assets/css/app.scss, apps/site/assets/ts/components/Accordion.tsx, apps/site/assets/ts/components/__tests__/AccordionTest.tsx, apps/site/assets/ts/trip-plan-results/__tests__/TripPlannerResultsTest.tsx, apps/site/assets/ts/trip-plan-results/__tests__/__snapshots__/TripPlannerResultsTest.tsx.snap, apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx, apps/site/assets/ts/trip-plan-results/components/TripPlannerResults.tsx, apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [Fare Calculator Accordion | One-Way/Round Trip fares](https://app.asana.com/0/555089885850811/1162903717356813)
Replaces https://github.com/mbta/dotcom/pull/499
=> Logic for the Fare Calculator in the Trip Planner (2nd accordion)

apps/routes/test/repo_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/stops/test/nearby_test.exs
Update tests to reflect the summer rating
No ticket, the new rating is causing tests to break in CI.
---
=> Update tests to reflect the summer rating

docs/ENVIRONMENT.md
No ticket, just a few small notes in the readme to avoid confusion with the names for the Algolia keys vs MBTA's names for the same keys.
=> Add clarifications regarding Algolia key names

apps/site/lib/site_web/templates/fare/_deprecation_message.html.eex, apps/site/lib/site_web/templates/fare/origin_destination.html.eex
**Asana Ticket:** [🎫 Fare Finder | Add deprecation message to old tool](https://app.asana.com/0/555089885850811/1178030825627713)
For Commuter Rail and Ferry, we are adding a message to 'redirect' the rider to our revamped Trip Planner for fare information:
=> Add deprecation message

apps/site/assets/ts/leaflet/__tests__/MapTest.tsx, apps/site/assets/ts/leaflet/components/__mapdata.d.ts, apps/site/assets/ts/schedule/__tests__/CrowdingPillTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/CrowdingPillTest.tsx.snap, apps/site/assets/ts/schedule/components/Map.tsx, apps/site/lib/leaflet/map_data/marker.ex, apps/site/lib/site_web/channels/vehicle_channel.ex, apps/site/lib/site_web/controllers/schedule/line/maps.ex, apps/vehicles/test/parser_test.exs
**Asana Ticket:** [👩‍👩‍👧‍👦 Crowding | Map Tooltip](https://app.asana.com/0/385363666817452/1178899641126298/f)
Just like you saw in the demo.
Also added some tests I should have added with my previous update.
---
=> 👩‍👩‍👧‍👦 Crowding | Map Tooltip

apps/site/assets/css/_trip-plan-fare-calculator.scss, apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs
[Fare Calculator Accordion | Evergreen notations](https://app.asana.com/0/555089885850811/1169236529454071)
[Fare Calculator Accordion | Transfers notes](https://app.asana.com/0/555089885850811/1169236529454073)
**THIS NEEDS TO BE MERGED AFTER #504**
=> Notes and links on fare calculator

apps/fares/lib/fare.ex, apps/fares/lib/format.ex, apps/fares/lib/month.ex, apps/fares/test/fare_test.exs, apps/fares/test/format_test.exs, apps/fares/test/month_test.exs, apps/fares/test/one_way_test.exs, apps/site/assets/css/_trip-plan-fare-calculator.scss, apps/site/assets/css/_trip-plan-results.scss, apps/site/assets/css/app.scss, apps/site/assets/ts/components/Accordion.tsx, apps/site/assets/ts/components/__tests__/AccordionTest.tsx, apps/site/assets/ts/trip-plan-results/__tests__/TripPlannerResultsTest.tsx, apps/site/assets/ts/trip-plan-results/__tests__/__snapshots__/TripPlannerResultsTest.tsx.snap, apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx, apps/site/assets/ts/trip-plan-results/components/TripPlannerResults.tsx, apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/templates/fare/_deprecation_message.html.eex, apps/site/lib/site_web/templates/fare/origin_destination.html.eex, apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex, apps/site/lib/site_web/templates/trip_plan/_monthly_pass_row.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs, apps/trip_plan/lib/trip_plan/itinerary.ex
No ticket, merging in a feature branch.
Contains work for the following tickets:
[Fare Calculator Accordion | One-Way/Round Trip fares](https://app.asana.com/0/555089885850811/1162903717356813)
[Fare Calculator Accordion | Recommended Passes](https://app.asana.com/0/555089885850811/1169236529454075)
[Fare Calculator Accordion | Transfers notes](https://app.asana.com/0/555089885850811/1169236529454073)
[Fare Calculator Accordion | Evergreen notations](https://app.asana.com/0/555089885850811/1169236529454071)
[Fare Calculator Accordion | Shuttle Fare (free)](https://app.asana.com/0/555089885850811/1178333054166489)
[🎫 Fare Finder | Add deprecation message to old tool](https://app.asana.com/0/555089885850811/1178030825627713)
---
=> Feature: Fare calculator accordion

apps/routes/lib/route.ex, apps/routes/test/route_test.exs
**Asana Ticket:** [👩‍👩‍👧‍👦 Crowding | Route list](https://app.asana.com/0/555089885850811/1180639549267081)
Add a list of routes with occupancy/crowding data
and a function to check whether a route is in the list.
---
=> Add a list of routes with occupancy/crowding data

apps/site/test/site_web/controllers/fare_controller_test.exs, apps/stops/test/route_stop_test.exs
No ticket, fixing breaking tests.
---
=> Adjust ferry test data to match upcoming limited schedule

AUTHORS
Add Cristen to the Authors file
No ticket
---
=> Add Cristen to the Authors file

AUTHORS
Add Cora to Authors file
No ticket
---
=> Add Cora to Authors file

AUTHORS
Add Alicia to the Authors file
No ticket
---
=> Add Alicia to the Authors file

AUTHORS
Add Ian to Authors file
No ticket
---
=> Add Ian to Authors file

AUTHORS
Add Phil to Authors file 
No ticket
---
=> Add Phil to Authors file

apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx, apps/site/assets/ts/schedule/__tests__/lineDiagramData/live-data.json, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/assets/ts/schedule/components/line-diagram/StopPredictions.tsx, apps/site/lib/site/transit_near_me.ex, apps/site/lib/site_web/templates/schedule/_line_page_stop_prediction.html.eex, apps/site/test/site/transit_near_me_test.exs
=> Revert "Include crowding data in data from time_data_for_route_by_stop"

apps/routes/lib/route.ex
**Asana Ticket:** [9 new routes with crowding data](https://app.asana.com/0/555089885850811/1181885620584410)
Add new routes with crowding data
---
=> Add new routes with crowding data

apps/site/test/site/lib/vehicle_helpers_test.exs
No ticket, tests were broken.
Update test details to match the current schedule
---
=> Update test details to match the current schedule

AUTHORS
Add Beatrix to Authors file
No ticket
---
=> Add Beatrix to Authors file

apps/site/assets/js/algolia-result.js, apps/site/assets/js/test/algolia-result_test.js
**Asana Ticket:** [🔍 Algolia Search | Search Icon/Search results investigation](https://app.asana.com/0/555089885850811/1182827314393756)
Fix map marker icons for location search results
---
=> Fix map marker icons for location search results

apps/site/test/site/lib/vehicle_helpers_test.exs
Update test data to use the current rating
No ticket, tests were failing in CI.
---
=> Update test data to use the current rating

apps/site/assets/ts/components/__tests__/SearchBoxTest.tsx, apps/site/assets/ts/helpers/__tests__/keyboard-events-test.ts, apps/site/assets/ts/projects/__tests__/MoreProjectsTableTest.tsx, apps/site/assets/ts/schedule/__tests__/CrowdingPillTest.tsx, apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx, apps/site/assets/ts/schedule/__tests__/ScheduleFinderFormTest.tsx, apps/site/assets/ts/schedule/__tests__/ScheduleFinderModalTest.tsx, apps/site/assets/ts/schedule/__tests__/ScheduleLoaderTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleFinderModalTest.tsx.snap, apps/site/assets/ts/schedule/components/ScheduleLoader.tsx, apps/site/assets/ts/trip-plan-results/__tests__/TripPlannerResultsTest.tsx
**Asana Ticket:** [⏱️ Schedules | Uni-directional Routes ☹️](https://app.asana.com/0/555089885850811/1183808154398651)
On line pages where the route only has one direction, and that direction is "Inbound", the page is blank. We need to add a check for unidirectional routes.
Before:
After:
=> Check if a route is unidirectional

apps/site/assets/ts/schedule/components/direction/ScheduleDirectionMenu.tsx
**Asana Ticket:** [🔧 Refactor implementation of ScheduleDirectionMenu event listeners](https://app.asana.com/0/385363666817452/1188077420952242/f)
Currently every click anywhere on the schedule page causes unnecessary rerendering of many components. This change fixes that.
---
=> 🔧 Refactor implementation of ScheduleDirectionMenu event listeners

apps/site/assets/ts/schedule/schedule-loader.tsx, apps/site/lib/site_web/templates/schedule/_line.html.eex, apps/site/test/site_web/controllers/schedule/green_test.exs
**Asana Ticket:** [🔥 Schedules | Fix right rail on suspended routes](https://app.asana.com/0/555089885850811/1187736907832137)
Temporary fix for the upcoming rating.
=> Pin right rail on the right side for suspended routes

apps/stops/test/api_test.exs, apps/stops/test/nearby_test.exs
Adjust test data to fix broken tests
No ticket, tests started failing in CI with the latest GTFS updates.
---
=> Adjust test data to fix broken tests

apps/route_patterns/lib/route_pattern.ex, apps/routes/lib/route.ex, apps/routes/lib/shape.ex, apps/schedules/lib/schedule.ex, apps/stops/test/route_stop_test.exs, apps/v3_api/lib/routes.ex, apps/v3_api/test/route_patterns_test.exs, apps/v3_api/test/routes_test.exs
Improve typespecs, documentation, and tests
- Improve types in RoutePattern, Shape and Trip
- Add a moduledoc for Shape
- Fix and simplify V3Api.Routes tests
- Add typespecs to V3Api.Routes
- Add a test for V3Api.RoutePatterns
- Rearrange RouteStop tests to match implementation order
No functional changes.
No ticket, preliminary things I notice while working toward using route patterns.
---
=> Improve typespecs, documentation, and tests

apps/fares/lib/fares.ex, apps/fares/test/fares_test.exs, apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/controllers/trip_plan_controller_test.exs, apps/site/test/site_web/views/trip_plan_view_test.exs, apps/trip_plan/lib/trip_plan/leg.ex, apps/trip_plan/lib/trip_plan/transfer.ex, apps/trip_plan/test/leg_test.exs
**Asana Ticket:** [Trip Planner | SL Trips from Airport are Free](https://app.asana.com/0/555089885850811/1189794962366354)
Any subway legs that come after the Silver Line when leaving the airport will be marked as part of the free service.
Example from Logan with several transfers:
=> SL Trips from Airport are free

README.md, apps/algolia/lib/mix/tasks/algolia/update.ex
**Asana Ticket:** [🔧 Document Algolia re-index command](https://app.asana.com/0/385363666817452/1186487484243318)
Add documentation for the Algolia re-index command
Include documentation in the mix task itself. This enables it to show up
in the task list when you run `mix help`.
---
=> Add documentation for the Algolia re-index command

README.md, apps/site/assets/babel.config.js
**Asana Ticket:** [🔧 Documentation | Write up browser support policy in docs](https://app.asana.com/0/555089885850811/1166916510708289)
Added some words in the README about which browsers our codebase supports via .browserslistrc.
---
=> 🔧 Write up browser support policy in docs

apps/site/assets/css/_colors.scss, apps/site/assets/css/_crowding-pill.scss
**Asana Ticket:** [Update Crowding Color Values](https://app.asana.com/0/385363666817452/1187313467059937/f)
Updated to use the new green in the icon, also corrects background for the pill display. Not sure why it looks so bright to me compared to the mockup in zeroheight 😅 
---
=> Update Crowding Color Values

apps/feedback/lib/message.ex
**Asana Ticket:** [☎️ Add a new Compliment service option](https://app.asana.com/0/555089885850811/1188535657153256)
Add a "Compliment" service option
---
=> Add a "Compliment" service option

apps/site/lib/site_web/views/helpers.ex
Remove unused font_awesome_id helper function
No ticket, just something I stumbled on.
---
=> Remove unused font_awesome_id helper function

apps/site/lib/site_web/templates/layout/app.html.eex
**Asana Ticket:** [Associate MBTA.com domain with Facebook account](https://app.asana.com/0/555089885850811/1192988614433558)
Authenticate our domain for Facebook
[This can be removed as soon as we complete the verification process.](https://app.asana.com/0/385363666817452/1193278706153525)
---
=> Authenticate our domain for Facebook

.tool-versions
Upgrade node to the lastest 8.x version 8.17.0
No ticket
---
=> Upgrade node to the lastest 8.x version 8.17.0

apps/site/lib/predicted_schedule.ex, apps/site/test/predicted_schedule_test.exs
**Asana Ticket:** [🐞 Stations/Stops/TNM | False "No departures within 24 hours" language](https://app.asana.com/0/555089885850811/1188548382586302)
Added a fix to compare the dates of the predicted schedules so there's no "no departures within 24 hours" message.
Before:
After:
=> Get schedules for tomorrow if there are no schedules left for today

apps/site/assets/ts/schedule/components/line-diagram/graphics/Merge.tsx
**Asana Ticket:** [❌ Kingston Line page broken](https://app.asana.com/0/385363666817452/1195805969093134)
Skip any gaps that are missing critical data
Stop-gap measure to get the page to render while we figure out an actual
complete solution.
---
=> Skip any gaps that are missing critical data

apps/site/assets/ts/schedule/components/line-diagram/line-diagram-helpers.ts
No ticket, builds off #630. Existing code broke for branches that comprise of only a single terminus stop. :)
=> Consider "terminus" as "stop" in isStopOnMainLine()

README.md, apps/feedback/README.md
Document the feedback app and logging emails in dev
No ticket.
---
=> Document the feedback app and logging emails in dev

apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/stops/lib/route_stop.ex, apps/stops/test/route_stop_test.exs
**Asana Ticket:** [Shuttles | Handle Lechmere shuttle in line diagram](https://app.asana.com/0/555089885850811/1193209413433881)
Include the Lechmere shuttle in line diagram
Handle this as a special case for the short-term while developing a
more robust solution.
---
=> Include the Lechmere shuttle in line diagram

apps/site/assets/css/_customer-support.scss, apps/site/assets/css/_utilities.scss, apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/lib/site_web/templates/customer_support/index.html.eex, apps/site/lib/site_web/views/customer_support_view.ex
**Asana Ticket:** [🐞 Customer Support | Page looks broken after submitting customer feedback](https://app.asana.com/0/555089885850811/1196118115121841)
Fix for broken page and no confirmation message after submitting the form.
=> Restore layout work

apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/lib/site_web/views/customer_support_view.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs, apps/site/test/site_web/integration/support_form_test.exs
**Asana Ticket:** [☎️ Replace Full Name field with First Name and Last Name fields](https://app.asana.com/0/385363666817452/1188547161220117/f)
The page seems to break on form submit so there's an extra commit meant to address that as well...
---
=> ☎️ Replace Full Name field with First Name and Last Name fields

apps/site/lib/site_web/templates/layout/_desktop_menu_more.html.eex, apps/site/lib/site_web/templates/page/_important_links.html.eex, apps/site/lib/site_web/templates/static_page/about.html.eex
**Asana Ticket:** [Homepage | Change "Sustainability" to "Climate Change"](https://app.asana.com/0/555089885850811/1197617020314821)
Change "Sustainability" page title to "Climate Change"
---
=> Change "Sustainability" page title to "Climate Change"

apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex
**Asana Ticket:** [☎️ Add a new "CharlieCard or Ticket Number" field](https://app.asana.com/0/555089885850811/1188547161220084)
Adding field to the frontend. It's only visible when the subject is "CharlieCards & Tickets".
=> "CharlieCard or Ticket Number" frontend field

apps/site/assets/ts/trip-planner/components/VoteMap.tsx, apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/templates/layout/app.html.eex
**Asana Ticket:** [Update page metadata (for social)](https://app.asana.com/0/0/1198956725506887/f)
=> fix: set appropriate meta values for vote action

apps/site/lib/site_web/router.ex
=> fix: redirect /Vote to /vote

apps/site/test/site/lib/vehicle_helpers_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs
=> Update trip ID and branch name for outdated tests

apps/site/lib/site_web/views/customer_support_view.ex
**Asana Ticket:** [Customer Support | Change language re: SWA complaints](https://app.asana.com/0/555089885850811/1199143478731724)
Small change regarding language:<br/>
=> Modify paragraph

apps/site/assets/css/_colors.scss, apps/site/assets/css/_social.scss, apps/site/lib/site_web/templates/layout/_desktop_menu_more.html.eex, apps/site/lib/site_web/templates/layout/_footer.html.eex, apps/site/lib/site_web/templates/static_page/about.html.eex
**Asana Ticket:** [GLT | Include in "More" in site header](https://app.asana.com/0/116562505129567/1199077122782605)
**Asana Ticket:** [add LinkedIn to footer](https://app.asana.com/0/555089885850811/1198209369766344)
@katrinaml I put LinkedIn between Instagram and Twitter: let me know if you'd prefer it somewhere else.
---
=> fix: replace Green Line Extension links with Green Line Transformation

apps/feedback/lib/mailer.ex
**Asana Ticket:** [🐞 Service: "Complaint", Category: "TAlerts/Countdowns/Apps" should have a topic of "Other"](https://app.asana.com/0/385363666817452/1198956720242885/f)
Corrected the pattern matcher!
=> Service: "Complaint", Category: "TAlerts/Countdowns/Apps" should have a topic of "Other"

apps/site/assets/css/_customer-support.scss, apps/site/lib/site_web/templates/customer_support/index.html.eex
[Asana ticket](https://app.asana.com/0/385363666817452/1199084704611414/f)
The form should now show you the confirmation message after hitting submit (as opposed to having to scroll up to see it).
=> fix: form submit focuses on confirmation message

apps/site/lib/site_web/controllers/schedule/finder_api.ex, apps/site/test/site_web/controllers/schedule/finder_api_test.exs
**Asana Ticket:** [🐞 Elixir.UndefinedFunctionError: function nil.route/0 is undefined](https://app.asana.com/0/385363666817452/1185865721068541)
Another bug involving trip info. This fix avoids getting a `500` error
=> Account for non-existing schedule route id for the Green Line

apps/site/assets/js/support-form.js, apps/site/assets/package-lock.json, apps/site/assets/package.json
**Asana Ticket:** [New Customer Support form not submitting in IE](https://app.asana.com/0/555089885850811/1199361102542406)
Some properties and methods are not supported in IE so some workarounds are needed.
=> Adjust the javascript code so it works in IE

apps/site/test/site_web/controllers/schedule/finder_api_test.exs
Adjusts one test's trip params to fix a test failure.
=> fix for finder_api test

apps/site/test/site_web/controllers/schedule_controller_test.exs
=> Fix for Green Line test

apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
**Asana Ticket:** [☎️ Elixir.KeyError: key "date_time" not found in: %{...}](https://app.asana.com/0/555089885850811/1198712992208784)
Default to "now" if said fields are not submitted.
=> Add date and time fields if not present in the form

apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
**Asana Ticket:** [☎️ Make subject field required](https://app.asana.com/0/555089885850811/1188547161220081)
Do not allow submission if field is not filled:<br/>
=> Make subject field required

.github/dependabot.yml
It looks like the default configuration is only looking at updates for `react_renderer`.
---
=> chore: configured Dependabot

apps/site/test/site_web/controllers/schedule/line/helpers_test.exs
No ticket. Fix for a broken test.
=> Fix for CR test

apps/routes/lib/repo.ex, apps/routes/lib/repo_api.ex, apps/routes/lib/route.ex, apps/routes/test/repo_test.exs, apps/routes/test/route_test.exs, apps/site/lib/upcoming_route_departures.ex
**Asana Ticket:** [Define a RoutesApi behaviour for V3Api.Routes](https://app.asana.com/0/555089885850811/1189396929591660)
=> Implement `@behaviour` for `Routes.Repo`

apps/site/lib/site_web/router.ex
**Asana Ticket:** [Nubian stop page redirect](https://app.asana.com/0/555089885850811/1193766408698965)
---
=> Dudly redirect

apps/site/lib/site_web/controllers/helpers.ex, apps/site/lib/site_web/controllers/schedule/green.ex, apps/site/lib/site_web/controllers/schedule/trip_view_controller.ex, apps/site/lib/site_web/plugs/banner_message.ex, apps/site/lib/site_web/templates/schedule/_trip_view.html.eex, apps/site/lib/site_web/views/helpers.ex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/controllers/helpers_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/plugs/banner_message_test.exs, apps/site/test/site_web/router_test.exs, apps/stops/test/repo_test.exs
**Asana Ticket:** [⏱️Schedule Tab | Add retirement message](https://app.asana.com/0/555089885850811/1170822992031033)
Create a plug for a retirement message (for CR and bus) in the Schedule tab.
**Pending: specific date**
=> Retirement message

apps/site/lib/site_web/views/schedule_view.ex
No ticket but related to [⏱️Schedule Tab | Add retirement message](https://app.asana.com/0/555089885850811/1170822992031033)
=> Slight format corrections in the retirement message

apps/site/test/site/lib/vehicle_helpers_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs, apps/stops/test/api_test.exs, apps/stops/test/repo_test.exs
No ticket, just fixes for tests that were breaking.
=> Fixes for broken tests

apps/routes/config/config.exs, apps/routes/config/dev.exs, apps/routes/config/prod.exs, apps/routes/config/test.exs, apps/routes/lib/mock_repo_api.ex, apps/routes/lib/repo_api.ex, apps/routes/test/group_test.exs, apps/routes/test/repo_test.exs, apps/site/test/leaflet/map_data/polyline_test.exs, apps/site/test/site/content_rewriters/liquid_objects/route_test.exs, apps/site/test/site/content_rewriters/liquid_objects_test.exs, apps/site/test/site_web/controllers/old_site_redirect_controller_test.exs, apps/site/test/site_web/controllers/schedule/green_test.exs, apps/site/test/site_web/controllers/schedule/hours_of_operation_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/stops/test/nearby_test.exs, apps/stops/test/route_stops_test.exs
**Asana Ticket:** [Configure test env to use Routes.MockRepoApi anywhere we currently call Routes.Repo](https://app.asana.com/0/555089885850811/1189396929591667)
This way we have a mock repo for routes and we don't need to make unnecessary calls.
=> Use Routes.MockRepoApi when testing

apps/fares/lib/proposed_locations.ex, apps/fares/lib/proposed_locations/location.ex, apps/fares/test/proposed_locations_test.exs, apps/site/assets/css/_bootstrap.scss, apps/site/assets/css/_proposed-locations.scss, apps/site/assets/css/app.scss, apps/site/assets/js/app.js, apps/site/lib/site_web/controllers/fare_transformation_controller.ex, apps/site/lib/site_web/router.ex, apps/site/lib/site_web/templates/fare_transformation/_nearby_locations.html.eex, apps/site/lib/site_web/templates/fare_transformation/proposed_sales_locations.html.eex, apps/site/lib/site_web/views/fare_transformation_view.ex, apps/site/test/site_web/controllers/fare_transformation_controller_test.exs, apps/site/test/site_web/router_test.exs
[Upload new data source](https://app.asana.com/0/555089885850811/1199957984734799)
[Update the location cards](https://app.asana.com/0/555089885850811/1199957984734798)
[Duplicate the existing tool into a new, unique instance](https://app.asana.com/0/555089885850811/1199957984734796)
[Restyle the new tool](https://app.asana.com/0/555089885850811/1199957984734797)
Gets data from ArcGIS depending on location.
=> Proposed Sales Location page

apps/site/assets/js/test/view-previous-events__test.js, apps/site/assets/js/view-previous-events.js, apps/site/lib/site_web/templates/event/_event_list.html.eex
**Asana Ticket:** [View Previous Month button - fix accessibility](https://app.asana.com/0/555089885850811/1200032439670461)
Added button to tab order, and added an eventListener that translates the enter-key to button click.
I tried to test it with screen readers, and I think it works better than before, but I'm not super great at using a screen reader yet.
Update:  I feel like there should be a test for this, but I tried a number of approaches and couldn't get jQuery triggers and JS events to play nicely.
---
=> Button is keyboard navigable

apps/fares/lib/fares.ex, apps/fares/mix.exs, apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex, apps/site/lib/site_web/templates/trip_plan/_itinerary_fares.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [Elixir.UndefinedFunctionError: function nil.mode/0 is undefined](https://app.asana.com/0/555089885850811/1200069554962417)
Fares are not specified for the CapeFLYER, so these changes make sure the trip planner logic doesn't break in this scenario and displays an additional message for more information instead.
=> Account for trips including the CapeFLYER

apps/site/assets/css/_proposed-locations.scss, apps/site/lib/site_web/templates/fare_transformation/proposed_sales_locations.html.eex
**Asana Ticket:** [Add error message for location search](https://app.asana.com/0/555089885850811/1200068680318939)
---
=> PSL:  Adjusted search error msg copy, color, placement

apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/schedule/components/ScheduleNote.tsx, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/ScheduleNoteTest.tsx.snap
**Asana Ticket:** [Schedules | Update hardcoded headway times](https://app.asana.com/0/385363666817452/1199240215358550)
Just a small footer that will be subject to redesign down the road.
=> Add footer to schedule note for subway

apps/site/assets/css/_events.scss, apps/site/lib/site_web/templates/event/_calendar.html.eex, apps/site/lib/site_web/views/event_view.ex, apps/site/test/site_web/views/event_view_test.exs
**Asana Ticket:** [Add event listings to the grid](https://app.asana.com/0/555089885850811/1199915858612066)
One thing I noticed is that the select-a-month sidebar wasn't looking right in my branch in IE, but I think that should be resolved with merging?
---
=> Calendar populated with events

apps/site/assets/js/timetable-stick.js, apps/site/lib/site_web/controllers/schedule/timetable_controller.ex, apps/site/test/site_web/controllers/event_controller_test.exs, apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs
**Asana Ticket:** [Schedules | CR Timetable "via" information incorrect](https://app.asana.com/0/385363666817452/1200083404866511)
Adjustments to accommodate the new schedules.
Plus a JS fix to avoid a crash.
=> New spring 2021 CR timetables

apps/site/assets/css/_events.scss, apps/site/lib/site_web/controllers/event_controller.ex, apps/site/lib/site_web/templates/event/_event_list.html.eex, apps/site/lib/site_web/templates/event/_list_of_events.html.eex, apps/site/lib/site_web/templates/event/index.html.eex, apps/site/test/site_web/controllers/event_controller_test.exs
**Asana Ticket:** [Add toggle between views to navigation](https://app.asana.com/0/555089885850811/1199915858612067)
In desktop mode only, we can now switch between views:
=> Add a toggle to switch between list and calendar views

apps/site/lib/site_web/templates/event/_list_of_events.html.eex, apps/site/lib/site_web/templates/event/index.html.eex
**Asana Ticket:** [Hide months in left nav if they have no events](https://app.asana.com/0/555089885850811/1200112047631302)
Only months that have events will be displayed on the left selector.
=> Hide months without events

apps/site/test/detailed_stop_group_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs
Just adding this to address a few new very minor test fails that popped up.
=> tests: Adjust for CR-Kingston name change, & more

apps/site/test/site/lib/vehicle_helpers_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs
No ticket, just fixes for tests.
=> Fixes for tests

apps/routes/lib/mock_repo_api.ex, apps/site/test/site_web/controllers/schedule/green_test.exs, apps/stops/test/route_stops_test.exs
=> Fix for Green Line (B branch) test

apps/site/test/site/lib/vehicle_helpers_test.exs
No ticket, just your average occasional fix.
=> Fix for `vehicle_helpers_test.exs`

apps/cms/lib/page/event.ex, apps/cms/priv/cms/events.json, apps/cms/test/helpers_test.exs, apps/cms/test/page/event_test.exs
**Asana Ticket:** [Events | Support paragraph in Elixir (Struct update)](https://app.asana.com/0/553506286097126/1200235953717698)
Add support for upcoming paragraphs-on-events.
---
=> Update Event struct to support paragraphs

apps/cms/lib/page/event.ex, apps/cms/priv/cms/events.json, apps/cms/test/page/event_test.exs
**Asana Ticket:** [New Event fields for top half event redesign](https://app.asana.com/0/553506286097126/1199897989131025)
Adds support for new CMS API fields. See https://github.com/mbta/cms/pull/360 for more details.
---
=> Add support for new event link fields (CMS API)

apps/site/assets/js/event-page-setup.js, apps/site/assets/js/test/event-page-setup__test.js
**Asana Ticket:** [Add overlay tests to event-page-setup__test.js](https://app.asana.com/0/555089885850811/1200196372897037)
Just a couple of tests to show that overlays are opened and closed.
=> Add tests for overlay in calendar view

apps/site/assets/css/_event-overlay.scss, apps/site/assets/css/_events.scss, apps/site/lib/site_web/templates/event/_add_button.html.eex, apps/site/lib/site_web/templates/event/_event_teaser.html.eex, apps/site/lib/site_web/templates/event/_popup.html.eex
**Asana Ticket:** [Calendar popup/overlay styling](https://app.asana.com/0/555089885850811/1200196372897030)
Mainly fixed font sizes, colors, and spaces to better match the mocks.  Also replaced "Ended" with a disabled add-to-calendar button.
---
=> Calendar overlays re-styled to match mocks

apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/ScheduleFinderTest.tsx.snap, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/SchedulePageTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleFinderForm.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleFinderModal.tsx, apps/site/assets/ts/schedule/components/schedule-finder/SelectContainer.tsx, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/ScheduleFinderFormTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/__snapshots__/ScheduleFinderFormTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/__snapshots__/ScheduleFinderModalTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/__snapshots__/ScheduleModalContentTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/DailySchedule.tsx, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/ServiceOptGroup.tsx, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/__snapshots__/DailyScheduleTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/__snapshots__/ServiceOptGroupTest.tsx.snap
Asana ticket: https://app.asana.com/0/385363666817452/1200074880846056/f
~Hoping that a few improved labels will help things! We're testing on dev blue with our user.~ Testing was successful! Opening this PR up for code review here.
=> Schedule modal short-term accessibility improvements

apps/site/assets/css/_location-card.scss, apps/site/assets/css/_location-input.scss, apps/site/assets/css/_utilities.scss, apps/site/lib/site_web/templates/fare/retail_sales_locations.html.eex, apps/site/lib/site_web/templates/fare_transformation/proposed_sales_locations.html.eex
**Asana Ticket:** [Adjust spacing between sections of content](https://app.asana.com/0/385363666817452/1200068635956331)
Adjusted PSL to match updated layout of RSL.  This impacted spacing between components, content width, and grid layout.
=> Updated PSL layout:  grid position, spacing, content width

apps/site/lib/site_web/templates/event/_event_list.html.eex
**Asana Ticket:** [Clicking on the nav link on the left should expand the corresponding month](https://app.asana.com/0/555089885850811/1200312808499748)
A different approach in an attempt to achieve the desired behavior. Related to #940.
=> Expand and scroll to selected month

.github/workflows/tests.yml, apps/schedules/lib/repo.ex, apps/site/lib/predicted_schedule.ex, apps/site/lib/site/transit_near_me.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
Unreverts #982, and fixes the test failure introduced there.
Additionally, this updates the GitHub Actions workflow to calculate when Elixir files are changed, so that the tests run on those pull requests.
---
=> Unrevert #982

apps/site/assets/ts/ie-warning/__tests__/IEWarningTest.tsx
Minor tweaks related to #963 and #1008.
=> Augment code coverage for IE warning

apps/site/lib/site_web/templates/layout/app.html.eex
**Asana Ticket:** [Make it easier to track 400s/404s/500s error pages in Google Analytics](https://app.asana.com/0/385363666817452/1200311047451594)
Quick change to track 404 pages easier in Google Analytics.
=> Change page title when there is a 404 error

apps/site/lib/site_web/controllers/schedule/timetable_controller.ex
**Asana Ticket:** [🐞 Elixir.UndefinedFunctionError: function nil.id/0 is undefined](https://app.asana.com/0/385363666817452/1195676305098336/f)
Also returns a sensible value instead of erroring in Map.new so that the entry can still be added to the map that's being created. 
As far as I can tell it shouldn't cause issues downstream (where a template fetches information from that map).
=> logs: Add log for when schedules don't have trip

apps/site/lib/site_web/templates/event/_event_teaser.html.eex
**Asana Ticket:** [Show upcoming events the day of the event](https://app.asana.com/0/555089885850811/1200636541215449)
Just a small modification to make sure that only events from past days (in the current month) are hidden.
=> Check day for past events in the current month

apps/site/assets/css/_location-card.scss
**Asana Ticket:** [Update grid structure of location cards](https://app.asana.com/0/1200650448662357/1200068680318933)
Just some tweaks so the cards look better.
=> Fix location cards' layout

apps/feedback/config/test.exs, apps/site/assets/.stylelintrc, apps/site/assets/css/_event-details.scss, apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/webpack.config.base.js, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/event/show.html.eex, apps/site/test/site_web/controllers/schedule/green_test.exs
**Asana Ticket:** [[Elixir] Updated agenda display (CSS/HTML)](https://app.asana.com/0/385363666817452/1200184323508002/f)
Building upon @hannahpurcell's initial work, makes the agenda all pretty and stuff.
---
=> Updated Event Agenda Display

.github/PULL_REQUEST_TEMPLATE.md, apps/site/load_tests/README.md, apps/site/load_tests/linediagram.py, apps/site/load_tests/locustfile.py, apps/site/load_tests/requirements.txt
**Asana Ticket:** [Add docs/process around load testing](https://app.asana.com/0/385363666817452/1200761946703394/f)
Enhances our load testing script by
1. Linking to its docs in a relevant spot (in this case the PR template)
2. Updating the Locust dependency (it was very outdated!)
3. Adding additional tests on the line diagram page. 
Much of that script is adapted from the `locustfile.py` in the [API repo](https://github.com/mbta/api/blob/master/load_tests/locustfile.py). Additional logic is added to simulate the multiple JS-driven API calls that happen simultaneously on the page. There is also logic inspecting the request responses for certain values, as we expect to see not only a valid non-error HTTP response, also data! It's a little convoluted but it does okay ✨
=> Add load test for line diagrams

Dockerfile
No ticket. Trying to solve an error I'm seeing when running our Dockerfile:
I'm not sure if this is a valid solution so please advice.
=> Avoid Docker error

apps/site/lib/site_web/templates/layout/_desktop_menu_more.html.eex, apps/site/lib/site_web/templates/page/_important_links.html.eex, apps/site/lib/site_web/templates/static_page/about.html.eex, apps/site/test/leaflet/map_data/polyline_test.exs, apps/stops/test/nearby_test.exs
**Asana Ticket:** [Sustainability | update Climate Change in Important Links on homepage](https://app.asana.com/0/555089885850811/1200754434089045)
=> Replace "Climate Change" with "Sustainability"

apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/ScheduleModalContentTest.tsx
**Asana Ticket:** [Ferry redesign | Schedule Finder modal](https://app.asana.com/0/1200690266799825/1200758897524250)
Show only "Daily Schedule"
=> Do not show Upcoming Departures for Ferry

.github/CODEOWNERS.md
Asana task [Automatically add teammates as reviewers to pull requests](https://app.asana.com/0/385363666817452/1200335498182731/f)
=> feat: Add CODEOWNERS

apps/site/assets/webpack.config.base.js, apps/site/lib/site_web/templates/layout/app.html.eex
**Asana Ticket:** 
1. [Tech Debt | CSS changes not updating during live development](https://app.asana.com/0/385363666817452/1200624402983961/f)
2. [Upgrade | Update .scss files with new rule](https://app.asana.com/0/385363666817452/1200760793364273/f)
=> Some tiny dev environment improvements

apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/excluded_stops_test.exs, apps/site/test/site_web/views/partial_view_test.exs
**Asana Ticket:** [Fix tests to accommodate *fixed* GL page](https://app.asana.com/0/555089885850811/1201289560710299)
=> GL:  Fixed some tests, but skipped others that are way-broken

apps/site/lib/site/stream/vehicles.ex
No ticket. This mostly just affects the console on application startup.
Because `Site.Stream.Vehicles` starts before `Site.Endpoint`, but the broadcasted events work with ETS tables that are set up with the Endpoint, unhandled errors come up when broadcasting events while the application continues to start up. Here we catch those errors only, and discard the events that happen before the application finishes starting up.
Open to alternate ways of handling this, but this change can be a stopgap measure to perhaps a smarter change. One obvious alternative is starting `Site.Endpoint` _before_ `Site.Stream.Vehicles` in `Site.Application`, but I found this to degrade the user experience quite a lot (visiting a schedule page, vehicles take a noticeably long time to populate the map, since they …
=> refactor(Site.Stream.Vehicles): add rescue

apps/cms/lib/partial/paragraph/agenda_topic.ex, apps/site/assets/css/_event-details.scss, apps/site/lib/site_web/templates/event/_event_agenda.html.eex, apps/site/lib/site_web/templates/event/show.html.eex, apps/site/lib/site_web/views/event_view.ex, apps/site/test/site_web/views/event_view_test.exs
**Asana Ticket:** [Update Agenda Topic HTML+CSS](https://app.asana.com/0/385363666817452/1201218504169421/f)
Updating our implementation of the Agenda topics and subtopics to account for https://github.com/mbta/cms/pull/376, with some test data...
=> Update Agenda Topic HTML+CSS

apps/site/assets/css/_header.scss, apps/site/assets/css/_secondary-nav.scss, apps/site/assets/css/_svg.scss, apps/site/assets/css/core.scss, apps/site/lib/site_web/views/event_view.ex
No ticket.  Seemed easier to just set up the new breakpoint instead of setting up a bunch of temporary classes to feature-flag this in the navbar rework.
=> Adjust navbar breakpoint between mobile / desktop views

apps/schedules/lib/repo.ex, apps/site/assets/css/_icons.scss, apps/site/assets/css/_schedule-icon-key.scss, apps/site/assets/css/_schedule-page-line-diagram.scss, apps/site/assets/css/_timetable.scss, apps/site/assets/react_app.js, apps/site/assets/ts/models/vehicle.ts, apps/site/assets/ts/schedule/components/line-diagram/LiveCrowdingIcon.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LiveCrowdingIconTest.tsx.snap, apps/site/config/dev.exs, apps/site/lib/site_web/templates/schedule/_timetable.html.eex, apps/site/lib/site_web/templates/schedule/_timetable_icon_key.html.eex
**Asana Ticket:** [Display crowding info in CR timetable](https://app.asana.com/0/555089885850811/1201303796115903)
---
=> Commuter rail crowding icons and tooltips

apps/site/assets/js/algolia-result.js, apps/site/lib/site_web/templates/partial/_hidden_icons.html.eex, apps/site/lib/site_web/views/helpers.ex
**Asana Ticket:** [🐞 Inconsistency for South Station in search results](https://app.asana.com/0/385363666817452/1199926429840347/f)
=> Use Silver Line Icon in Search

apps/site/lib/site_web/templates/schedule/_timetable.html.eex, apps/site/lib/site_web/templates/schedule/_timetable_icon_key.html.eex
Updated wording of accordion icon key.
Don't render crowding icon when crowding data is nil.
=> CR crowding improvements

apps/predictions/lib/repo.ex, apps/schedules/lib/repo.ex, apps/schedules/lib/repo_condensed.ex, apps/site/lib/site_web/templates/schedule/_timetable_icon_key.html.eex
Also updated wording on crowding, after Keolis request.
=> Fetch occupancy every time a request includes "trip"

apps/site/assets/js/test/psl-page-setup_test.js, apps/site/assets/js/test/trip-plan_test.js
No ticket, but big testing fix!  The only still-failing test is trip-plan__test.js.  Not sure how to fix, but seems that there's an issue with displaying results because the site prompts location-sharing.
=> Unblock other mocha tests

apps/site/lib/site/map_helpers.ex, apps/site/lib/site_web/views/layout_view.ex
**Asana Ticket:** [🔧  Maps | update map preview photo](https://app.asana.com/0/555089885850811/1201417381255112)
I wish this image could be dynamically updated by the CMS, but that would take a lot more work.  Backlog idea?
=> Updated subway map

apps/site/lib/site_web/templates/layout/_new_nav_mobile.html.eex
**Asana Ticket:** [Accordion containers in mobile menu](https://app.asana.com/0/555089885850811/1201306740497115/f)
A draft pr for the mobile accordion. Currently this work wraps the mobile menu links within a toggle-able accordion. This doesn't include no javascript accordion(it is however built into the component) or accessibility checks
=> mobile accordion

apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/UpcomingDepartures.tsx
**Asana Ticket:** [Remove LIVE icon in Schedule Finder ](https://app.asana.com/0/385363666817452/1201493530809999/f)
Remove live icon from the upcoming departures modal in schedule finder.
=> Remove LIVE icon in Schedule Finder 

apps/site/assets/css/_header.scss
**Asana Ticket:** [Mobile menu | Expand col width of fare prices on larger devices](https://app.asana.com/0/555089885850811/1201529194279333/f)
Have column width of fare price box expand based on screen size.
=> Expand col width on larger devices

apps/site/lib/site_web/templates/event/show.html.eex
**Asana Ticket:** [Remove "Join the Virtual Meeting" section of new agenda](https://app.asana.com/0/385363666817452/1201638800796932/f)
Remove Join the virtual meeting section on the event show template.
500 error was being thrown at the rendering of the registration link.
=> remove join the virtual meeting section

apps/site/assets/css/_header.scss
**Asana Ticket:** [Mobile menu | Fix multiple styling issues](https://app.asana.com/0/385363666817452/1201613685853923/f)
Make Search button a square
Stop T logo on header from shifting when opening menu or search
Make submenu heading normal blue at all times
Couldn't recreate [white bar issue](https://app.asana.com/0/1154777277498386/1201529194279324/f)
=> Mobile Menu Styling Fixes

apps/site/assets/css/_header.scss, apps/site/assets/ts/app/mobile-menu.ts
**Asana Ticket:** [Mobile menu | When you scroll down quickly on Safari 15, mobile menu disappears](https://app.asana.com/0/385363666817452/1201529194279348/f)
Deploying to dev-blue so we can try out the fix...
=> fix for Mobile menu | When you scroll down quickly on Safari 15, mobile menu disappears

apps/site/assets/ts/app/global-navigation.ts, apps/site/lib/site_web/templates/layout/_desktop_menu_contact_us.html.eex
**Asana Ticket:** [Add RR crossing number to current desktop menu](https://app.asana.com/0/385363666817452/1201824241791485/f)
Add column to desktop menu with rail road crossing number
=> Add RR crossing number to current desktop menu

.envrc.template, README.md, apps/v3_api/test/stream_test.exs, docs/ENVIRONMENT.md
Update hardcode api-dev url where applicable
---
=> fix: Change api-dev url

.github/workflows/crawler.yml
**Asana Ticket:** n/a
The `api.mbtace.com` host points to the old dev EB instance. I'm not sure yet if we're going to maintain it, so this updates the crawler to use the new `api-dev.mbtace.com` host and ECS instances.
---
=> chore: Update API dev URL in crawler workflow

apps/site/assets/css/_global-navigation.scss, apps/site/lib/site_web/templates/layout/_new_nav_contact_numbers.html.eex, apps/site/lib/site_web/templates/layout/_new_nav_desktop.html.eex, apps/site/lib/site_web/views/helpers.ex, apps/site/lib/site_web/views/layout_view.ex, apps/site/test/site_web/views/helpers_test.exs
**Asana Ticket:** [Add RR crossing number to updated mobile and desktop menus](https://app.asana.com/0/385363666817452/1201824241791486/f)
Add the railroad crossing gate issue number to the new desktop and mobile menus.
=> feat: Add RR crossing number to updated mobile and desktop menus

apps/site/assets/css/_secondary-nav.scss
**Asana Ticket:** [Add vertical rule between main nav and secondary nav](https://app.asana.com/0/385363666817452/1201772094911991/f)
Border was being removed at larger resolutions due to a breakpoint inclusion. This allows border to show up at all resolutions.
---
=> add border to top of secondary nav bar

apps/site/assets/css/_header.scss
**Asana Ticket:** [Update Search button to square](https://app.asana.com/0/555089885850811/1201764117487421/f)
Some minor styling tweaks to ensure the header search button is square and the icon is centered inside
=> Make search button square

apps/site/assets/css/_header.scss
**Asana Ticket:** [🟩 Update border radius of search input field](https://app.asana.com/0/555089885850811/1201764117511335/f)
Update border radius of search input to 8px
=> Update border radius of search input field

apps/site/assets/css/_global-navigation.scss
**Asana Ticket:** [Update chevron icon to caret icon](https://app.asana.com/0/555089885850811/1201772094911997/f)
=> Use carets instead of chevrons for desktop dropdowns

apps/site/assets/css/_form.scss
**Asana Ticket:** [Update clear search input icon ("x") placement](https://app.asana.com/0/555089885850811/1201764117487449/f)
center (x) icon vertically within search box
=> Update clear search input icon ("x") placement

apps/site/assets/css/_header.scss, apps/site/assets/css/core.scss
**Asana Ticket:** [🛑 Mobile menu: Fix search alignment](https://app.asana.com/0/385363666817452/1201937782917570/f)
After a maddening amount of debugging, found that limiting the page width so that it doesn't exceed 100% fixes it.
Also noticed the logo was slightly off-center, so modified the width of the `Menu` button to match the width+margin-left of the search button.
Also unset the padding on the search button - this seems to make it truly square (it was a few pixels too wide on iOS 15).
=> Fix new navigation bugs

apps/site/lib/site_web/templates/layout/app.html.eex
A quick PR to make the polyfills load using the webpack path, instead of relying on the static build paths.
=> Use webpack path for loading polyfills

apps/site/assets/css/_glx-open.scss, apps/site/lib/site_web/templates/trip_plan/_glx_now_open.html.eex, apps/site/lib/site_web/templates/trip_plan/_itinerary_stop.html.eex
**Asana Ticket:** [GLX "NOW OPEN" in trip planner](https://app.asana.com/0/555089885850811/1201915536508566/f)
Added glx now open message + logo to trip planner results for relevant stops
=> add glx now open message to trip planner

apps/site/assets/ts/stop/__tests__/sidebar/AccessibilityTest.tsx, apps/site/assets/ts/stop/components/sidebar/Accessibility.tsx
**Asana Ticket:** [Update accessibility information for stops and stations](https://app.asana.com/0/385363666817452/1201979003649875/f)
Pretty small change to remove some special casing according to the linked ticket
=> Remove some special accessibility info cases

apps/site/assets/ts/components/GlxOpen.tsx, apps/site/assets/ts/schedule/components/direction/GreenLineMenu.tsx
**Asana Ticket:** [Update hard-coded endpoints for GL](https://app.asana.com/0/555089885850811/1201984535304521/f)
use getIsGlxOpen to determine stops to be used in green line picker.
=> WIP Update hard-coded endpoints for GL

apps/site/lib/site/map_helpers.ex
**Asana Ticket:** [Update subway map image](https://app.asana.com/0/555089885850811/1201999151092149/f)
New image here:
https://cdn.mbta.com/sites/default/files/media/2022-03/3-21-2022-subway-map-1.jpg
=> Update subway map image link

apps/site/lib/site_web/templates/layout/_new_nav_popular_fares.html.eex
**Asana Ticket:** [update Linkpass to LinkPass in header](https://app.asana.com/0/385363666817452/1202052100099014/f)
Capitalize the "P" in "LinkPass"
---
=> Capitalize LinkPass properly

apps/site/assets/js/app.js, apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/lib/site_web/templates/layout/app.html.eex
**Asana Ticket:** [Tech Debt | Add Sentry monitoring for our JS frontend](https://app.asana.com/0/385363666817452/1200329682137272/f)
This is a subset of #1270 for just the frontend piece. This follows closely with other applications under the CTD umbrella - for example [signs_ui](https://github.com/mbta/signs_ui/pull/525)
Will add support for multiple environments in a followup PR someday!
=> Tech Debt | Add Sentry monitoring for our JS frontend

apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/svgo.yml, apps/site/assets/webpack.config.base.js
Also consolidates the configuration into the Webpack config
=> chore: upgrade svgo

apps/site/assets/ts/components/Headsign.tsx, apps/site/assets/ts/components/__tests__/HeadsignTest.tsx, apps/site/assets/ts/components/__tests__/__snapshots__/HeadsignTest.tsx.snap
**Asana Ticket:** [Departure times out of order](https://app.asana.com/0/555089885850811/1201990508147605/f)
Put departure times in order by comparing prediction times.
=> Departure times out of order fix

apps/cms/lib/page/project.ex, apps/cms/lib/page/project_update.ex, apps/cms/priv/repo/project-updates.json, apps/cms/priv/repo/projects.json, apps/cms/test/page/project_test.exs, apps/cms/test/page/project_update_test.exs
**Asana Ticket:** [Add all project aliases to the existing project page response data](https://app.asana.com/0/553506286097126/1202178207539128/f)
Updated project and project_update structs to [support incoming API changes](https://github.com/mbta/cms/pull/386).
---
=> update structs to support incoming API changes

apps/site/assets/css/_mixins.scss
**Asana Ticket:** [Stops & Transit Near Me | Fix alert icon](https://app.asana.com/0/555089885850811/1202225536290333/f)
=> Stops & Transit Near Me | Fix alert icon

apps/site/assets/css/_alerts.scss, apps/site/lib/site_web/templates/alert/summary.html.eex, apps/site/lib/site_web/templates/cms/page/_alerts.html.eex
**Asana Ticket:** [Display alerts summary on project page](https://app.asana.com/0/385363666817452/1200671244979945/f)
Show summary of number of alerts on project page.
=> Display alerts summary on project page

apps/site/assets/css/_grid-button.scss, apps/site/lib/site_web/templates/page/_contact_us.html.eex, apps/site/lib/site_web/templates/page/index.html.eex
**Asana Ticket:** ["Contact Us" section](https://app.asana.com/0/385363666817452/1202227445728527/f)
I also updated some of the HTML / CSS styles to make them work across both sections
=> Add Contact Us section

apps/site/assets/css/_alerts.scss, apps/site/assets/css/_project.scss, apps/site/lib/site_web/controllers/cms_controller.ex, apps/site/lib/site_web/templates/alert/_item.html.eex, apps/site/lib/site_web/templates/alert/group.html.eex, apps/site/lib/site_web/templates/alert/summary.html.eex, apps/site/lib/site_web/templates/cms/page/_alerts.html.eex, apps/site/lib/site_web/templates/cms/page/_project.html.eex, apps/site/lib/site_web/views/page_content_view.ex, apps/site/test/site_web/views/page_content_view_test.exs, apps/site/test/site_web/views/project_contact_test.exs
=> Project Page Alerts

apps/site/lib/site_web/templates/trip_compare/index.html.eex
Adds a paragraph explaining that GLX Medford is not included in suggested itineraries
=> Add GLX note

apps/cms/priv/landing_page_with_all_paragraphs.json, apps/site/assets/css/_content.scss, apps/site/assets/css/_fare-card.scss, apps/site/lib/site_web/templates/cms/paragraph/_fare_card.html.eex, apps/site/lib/site_web/templates/page/_fares_passes.html.eex
**Asana Ticket:** ["Standard One-Way Fares" updates](https://app.asana.com/0/555089885850811/1202125833856565/f)
create a breakpoint for standard one way fares section on xs small screens
Note: see fares overview link changes have to be made in CMS and should happen before merging this ticket as it removes the current fares link.
=> Standard One-Way Fares updates

apps/alerts/lib/accessibility.ex, apps/site/assets/css/_homepage.scss, apps/site/lib/site_web/templates/page/_alerts.html.eex, apps/site/lib/site_web/views/page_view.ex
**Asana Ticket:** [Alerts design updates](https://app.asana.com/0/555089885850811/1202384504606986/f)
Some things I noticed right off the jump:
- No spacing at the top of the container at the larger breakpoints (I think this will be solved by a later ticket maybe?)
- Some things are no longer possible if we want to rely on the container spacing. This mostly affects the footer section containing the buttons (e.g. the horizontal bar at the medium breakpoint and up can't span the full width of the container)
=> Homepage Alerts Section visual changes

apps/site/lib/site_web/templates/page/_important_links.html.eex
**Asana Ticket:** [Update homepage parking icon to match style](https://app.asana.com/0/385363666817452/1202110801136196/f)
=> update important links parking icon to font awesome version

apps/site/lib/site_web/views/trip_compare_view.ex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/trip_plan/lib/trip_plan/transfer.ex, apps/trip_plan/test/transfer_test.exs
**Asana Ticket:** [Make some additional transfers free in fare calculation](https://app.asana.com/0/555089885850811/1202313545967339/f)
update transfer calculations to accommodate:
express_bus -> express_bus
bus -> bus -> subway
subway -> bus -> bus
=> Update free transfer logic

apps/site/assets/css/_whats-happening.scss, apps/site/lib/site_web/templates/page/_whats_happening.html.eex
**Asana Ticket:** [Add "What's Happening at the MBTA" header](https://app.asana.com/0/555089885850811/1202075661172626/f)
[Please include a brief description of what was changed]
=> add header to non-promoted what's happening section

apps/site/assets/css/_homepage.scss, apps/site/assets/css/_news-entry.scss, apps/site/lib/site_web/controllers/page_controller.ex, apps/site/lib/site_web/templates/page/_news_and_updates.html.eex, apps/site/lib/site_web/views/helpers/cms_helpers.ex, apps/site/lib/site_web/views/page_view.ex, apps/site/lib/site_web/views/partial_view.ex, apps/site/lib/site_web/views/teaser_view.ex, apps/site/test/site_web/views/helpers/cms_helpers_test.exs, apps/site/test/site_web/views/page_view_test.exs
**Asana Ticket:** ["News" section > "Press Releases" section](https://app.asana.com/0/555089885850811/1202075661172628/f)
=> "News" section > "Press Releases" section

apps/site/assets/css/_tabbed-nav.scss
**Asana Ticket:** [Tab button design updates](https://app.asana.com/0/555089885850811/1202414279322440/f)
* Corrected the font family in smallest breakpoint
* Adjusted tab bar padding so that the buttons are left-aligned with the content
* Adjusted the padding of individual buttons
=> Tab button design updates

.github/workflows/algolia-update.yml
**Asana Ticket:** [Update Algolia for new Franklin/Foxboro name](https://app.asana.com/0/385363666817452/1202421859282539/f)
The ticket implied we might want to automate this... so here's my first attempt at that.
I've gone ahead and created a new write API key in Algolia for usage with GitHub Actions, and added that key and the app ID to the repository secrets.
=> feat(ci): update Algolia index periodically

apps/site/assets/css/_homepage.scss, apps/site/assets/css/_icons.scss, apps/site/assets/css/_schedule-page-line-diagram.scss, apps/site/assets/css/_stop-page.scss, apps/site/assets/css/_stops-v1.scss, apps/site/assets/css/_timetable.scss, apps/site/assets/js/trip-planner-location-controls.js, apps/site/assets/ts/__tests__/helpers/icon-test.tsx, apps/site/assets/ts/components/ExpandableBlock.tsx, apps/site/assets/ts/helpers/icon.tsx, apps/site/assets/ts/helpers/render-fa.tsx, apps/site/assets/ts/leaflet/__tests__/__snapshots__/MapTooltipTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/StopFeatures.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/useStopPositionsTest.tsx, apps/site/assets/ts/stop/__tests__/__snapshots__/HeaderTest.tsx.snap, apps/site/assets/ts/stop/__tests__/__snapshots__/StopCardTest.tsx.snap, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageTest.tsx.snap, apps/site/assets/ts/stop/__tests__/sidebar/__snapshots__/ParkingTest.tsx.snap, apps/site/assets/ts/stop/components/Header.tsx, apps/site/assets/ts/stop/components/sidebar/Parking.tsx, apps/site/lib/site_web/views/partial/svg_icon_with_circle.ex, apps/site/lib/site_web/views/schedule/timetable.ex, apps/site/lib/site_web/views/stop_view.ex
**Asana Ticket:** [Update parking icon anywhere else it's in use](https://app.asana.com/0/385363666817452/1202125833856552/f)
=> use fa parking icon everywhere

apps/site/assets/css/_grid-button.scss
**Asana Ticket:** [Schedules hover states](https://app.asana.com/0/555089885850811/1202570650180354/f)
Hover state for recently visited buttons
.
=> Schedules hover states

apps/site/assets/css/_homepage.scss, apps/site/lib/site_web/templates/page/_homepage-events.html.eex, apps/site/lib/site_web/views/page_view.ex
**Asana Ticket:** [Commuter Rail icon placement / label](https://app.asana.com/0/555089885850811/1202570650180359/f)
=> Homepage shortcut order change

apps/site/assets/css/_homepage.scss
**Asana Ticket:** [Alerts sizing/spacing tweaks](https://app.asana.com/0/555089885850811/1202570650180351/f)
=> Homepage alerts sizing/spacing tweaks

apps/site/lib/site_web/templates/trip_compare/index.html.eex
**Asana Ticket:** [Add note to /trip-compare](https://app.asana.com/0/385363666817452/1202617920075247/f)
Adds a disclaimer about travel time and transfers alongside the GLX disclaimer. I haven't tested it locally (because I can't), but I did mock it up in dev tools to make sure the class name and layout were OK.
=> Add time/transfer disclaimer note

apps/site/assets/css/_page.scss
**Asana Ticket:** [.page-section margin issues outside homepage](https://app.asana.com/0/385363666817452/1202638732046337/f)
update page-section margins so homepage styling is only for homepage.
=> page-section margin issues outside homepage

apps/v3_api/config/prod.exs
**Asana Ticket:** n/a
Adjusting timeout for api requests to match api side to avoid timeouts especially during service day switch over.
https://github.com/mbta/api/blob/master/apps/api_web/lib/api_web/api_controller_helpers.ex#L19
=> adjust api timeout duration to match api side

apps/site/assets/css/_recently-visited.scss
**Asana Ticket:** [Recently visited schedules heading margin ](https://app.asana.com/0/385363666817452/1202644949290864/f)
=> Limit "Recently Visited Schedules" margin removal to homepage tab

apps/cms/lib/partial/route_pdf.ex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/views/schedule_view_test.exs
**Asana Ticket:** [Elixir integration](https://app.asana.com/0/385363666817452/1202623240995537/f)
=> Schedule pdf labelling

apps/site/assets/ts/schedule/components/line-diagram/LineDiagramWithStops.tsx, apps/site/assets/ts/schedule/components/line-diagram/StopListWithBranches.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/MergeTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/line-diagram-helpers-test.ts, apps/site/assets/ts/schedule/components/line-diagram/__tests__/lineDiagramData/northStationBidiTest.json, apps/site/assets/ts/schedule/components/line-diagram/graphics/Merge.tsx, apps/site/assets/ts/schedule/components/line-diagram/line-diagram-helpers.ts
**Asana Ticket:** [allow <Merge> component to be able to merge in both directions within the same line diagram](https://app.asana.com/0/555089885850811/1201936157420489/f)
Builds on the work from #1204, mostly just adding a unit test based off of the previous test data and doing some clean up. I've tested it locally with some additional stops / branching and all seems fine as well.
=> allow <Merge> component to be able to merge in both directions within the same line diagram

.tool-versions, Dockerfile
No ticket, I needed to update erlang in order to get it to build on my machine and figured I'd get the others while I was in there.
• erlang 22.3.4.26
• elixir 1.10.4-otp-22
• nodejs 14.20.0
[Successful docker build](https://github.com/mbta/dotcom/runs/7861031139?check_suite_focus=true)
---
=> build: Minor level language updates

apps/site/lib/site_web/views/trip_compare_view.ex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [Restore transfer logic to Trip Planner](https://app.asana.com/0/555089885850811/1202802897881979)
This reverts commit 04fe81a11ebbf26475e8bd107ca89bc7b1d2727b.
---
=> Revert "Remove transfer logic from fare calculation (#1340)"

apps/site/lib/site_web/templates/schedule/_timetable.html.eex
**Asana Ticket:** [Copy edits on combined CR timetable page](https://app.asana.com/0/555089885850811/1202802897882007)
* Adds a sentence to the end of intro copy
* Adds a standalone Haverhill link under North Side Alternatives paragraph
* Adds and updates paragraphs under South Side Alternatives
---
=> Update copy for OL surge CR alternatives

apps/fares/lib/fare_info.ex, apps/site/lib/site_web/templates/trip_compare/_fare_calculator.html.eex, apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex
Asana ticket: [Revert CR fare calculation changes](https://app.asana.com/0/555089885850811/1202832059153476/f)
Reverts mbta/dotcom#1385
=> Revert "Calculate some CR legs as $0 during OL shutdown"

apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/lib/site_web/views/schedule_view.ex
**Asana Ticket:** [Clean up OL shuttle pages](https://app.asana.com/0/555089885850811/1202824647488162/f)
set OL shuttle fares to $0.00 and remove OL from connections section.
=> Clean up OL shuttle pages

apps/site/assets/ts/schedule/components/line-diagram/StopCard.tsx, apps/site/assets/ts/schedule/components/line-diagram/StopConnections.tsx
**Asana Ticket:** [Clean up OL shuttle pages followup](https://app.asana.com/0/555089885850811/1202824647488162/f)
Remove OL as a connection on line diagrams for shuttle pages.
=> Clean up OL shuttle pages followup

apps/site/assets/js/google-translate.js
**Asana Ticket:** [Remove Nepali and Somali translation options](https://app.asana.com/0/555089885850811/1202824647488178)
The google translate plugin we use doesn't support Nepali and Somali, so they need to be removed.
---
=> fix(Localization): Remove the unsupported localizations

apps/site/assets/ts/schedule/components/ScheduleNote.tsx, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/ScheduleNoteTest.tsx.snap, apps/site/lib/site/schedule_note.ex
**Asana Ticket:** [Update subway schedule notes](https://app.asana.com/0/555089885850811/1202824647488160)
The Schedule Note sections of subway pages matches the values provided
in the fall subway schedule.
The headings are changed to reflect lack of peak/off peak distinctions.
Use Weekdays and Weekends instead.
Time values are updated.
---
=> content: Update subway schedule notes

apps/fares/test/format_test.exs, apps/predictions/test/repo_test.exs, apps/site/test/green_line_test.exs, apps/site/test/site_web/controllers/schedule/green_termini_api_test.exs, apps/site/test/site_web/controllers/schedule/line/diagram_helpers_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/excluded_stops_test.exs, apps/site/test/site_web/views/helpers_test.exs
No ticket, fixes test that are currently breaking in CI.
- fix(test): Fix tests to account for latest GTFS data updates
- fix(test): Update expectation for new ferry route fare
---
=> fix(test): Fix tests to account for latest GTFS data updates

apps/site/assets/ts/stop/components/sidebar/Accessibility.tsx
**Asana Ticket:** [Manually remove elevator from Lynn station accessibility features](https://app.asana.com/0/385363666817452/1203005769296539/f)
Remove elevator for list of accessibility features on sidebar on Lynn stop page
=> Manually remove elevator from Lynn station accessibility features

apps/routes/lib/mock_repo_api.ex, apps/routes/lib/route.ex, apps/routes/test/repo_test.exs, apps/routes/test/route_test.exs, apps/site/lib/site_web/router.ex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/router_test.exs, apps/site/test/site_web/views/schedule_view_test.exs
**Asana Ticket:** [Add Silver Line Way link to bus hub](https://app.asana.com/0/385363666817452/1121899302297930/f)
Silver Line way added to bus hub page, search results, etc. update v3_url to dev blue to view changes locally
Search
Customer Support
Stop Page
=> Add Silver Line Way link to bus hub

apps/site/lib/site/map_helpers.ex, apps/site/test/site/map_helpers_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs
**Asana Ticket:** [Update source URL for ferry map](https://app.asana.com/0/555089885850811/1202974987514982)
[[Please include a brief description of what was changed]](feat: Updated ferry map)
---
=> feat: Updated ferry map

apps/alerts/lib/parser.ex, apps/alerts/lib/url_parsing_helpers.ex, apps/alerts/test/url_parsing_helpers_test.exs, apps/cms/lib/partial/paragraph.ex, apps/location_service/lib/aws_location/request.ex, apps/site/lib/site_web/views/alert_view.ex, apps/site/lib/site_web/views/helpers/cms_helpers.ex, apps/site/lib/site_web/views/partial/svg_icon_with_circle.ex
No ticket, just a handful of initial things I came across as I started looking into upgrading Elixir.
- fix: Remove duplicate docs
- fix: This parsing helper shouldn't be a view
- fix: Fix typespec
- fix: Remove function definition that is never reached
---
=> fix: Miscellaneous small fixes

apps/site/assets/ts/tnm/components/RouteCard.tsx
**Asana Ticket:** [Transit Near Me does not render nearby locations](https://app.asana.com/0/555089885850811/1203202409417379)
---
=> fix: Ensure that alerts exists before checking the length

apps/site/assets/ts/tnm/components/RouteCard.tsx
No ticket.
Follow-up to https://github.com/mbta/dotcom/pull/1445 based on a suggestion from @i0sea.
---
=> refactor: Use the optional syntax for a cleaner line

requirements.txt, scripts/POLLING_PLACES.md, scripts/combine_geocoded_addresses_with_shapes.py, scripts/geocode_addresses.py, scripts/shp_to_geojson.sh
**Asana Ticket:** [Update precincts.json](https://app.asana.com/0/555089885850811/1203042792164454/f)
feat: Script to combine polling places with geo shapes
Add documentation on all three scripts.
Depends on https://github.com/mbta/dotcom/pull/1446 and https://github.com/mbta/dotcom/pull/1448. These could be combine into 1 PR if that seemed better.
---
=> feat: Script to combine polling places with geo shapes

apps/site/assets/ts/hooks/__tests__/useDirectionChangeEventTest.tsx, apps/site/assets/ts/hooks/useDirectionChangeEvent.ts, apps/site/assets/ts/schedule/components/ScheduleFinder.tsx, apps/site/assets/ts/schedule/components/direction/reducer.ts
**Asana Ticket:** [Schedules | Schedule Finder default direction doesn't match user selection](https://app.asana.com/0/385363666817452/1200234754629197/f)
Establishes a new custom event.
Adds a helper function for dispatching this event to communicate the changed direction across disparate react trees. 
The `useDirectionChangeEvent` hook sets up the event listener on the document and outputs the updated direction after said custom event is fired.
---
=> feat: add custom event ‘changeddirection’

apps/site/assets/ts/trip-planner/components/VoteMap.tsx
**Asana Ticket:** [Update /vote error message](https://app.asana.com/0/385363666817452/1203272636155446/f)
Changes "nearby polling location" to "polling place" and clarifies that only voters registered in MA can use the link to find their polling place.
---
=> Update error message on /vote

apps/site/assets/ts/trip-planner/components/VoteMap.tsx
fix: Fix formatting for eslint
No ticket, just addresses a check that was failing for me after rebasing against master.
---
=> fix: Fix formatting for eslint

apps/site/assets/ts/schedule/components/direction/__tests__/GreenLineMenuTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/OriginListItemTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/OriginModalContentTest.tsx, apps/site/assets/ts/trip-planner/__tests__/VoteMapTest.tsx, apps/site/assets/ts/trip-planner/__tests__/__snapshots__/VoteMapTest.tsx.snap, apps/site/assets/ts/trip-planner/components/VoteMap.tsx
No ticket, just bringing the Jest coverage tests back to 90+% by adding basic tests for the VoteMap component
---
=> tests: add tests for `<VoteMap />`

apps/site/lib/site_web/templates/layout/_footer.html.eex, apps/site/lib/site_web/templates/page/_important_links.html.eex
**Asana Ticket:** [OPMI | add performance metrics to main navigation + update homepage link](https://app.asana.com/0/385363666817452/1202406729586828/f)
=> OPMI | add performance metrics to main navigation + update homepage link

apps/schedules/lib/hours_of_operation.ex, apps/schedules/test/hours_of_operation_test.exs
**Asana Ticket:** [Green-E missing Lechmere](https://app.asana.com/0/385363666817452/1203389014503052/f)
---
=> fix(HoursOfOperation): Fix stations not showing up for Green-E

apps/schedules/lib/hours_of_operation.ex, apps/schedules/lib/repo.ex, apps/schedules/test/hours_of_operation_test.exs, apps/site/assets/ts/hooks/useHoursOfOperation.ts, apps/site/lib/site_web/controllers/schedule/hours_controller.ex, mix.lock
**Asana Ticket:** [🔺 GL-E displaying Medford/Tufts times even though service hasn't started](https://app.asana.com/0/555089885850811/1203484100934127/f)
* **First commit** basically does what the ticket asks. It checks whether the current day of the week is a weekday (value of 1 through 5) before using either it or next Monday (as it was before) as the "weekday" date for the API request.
* **Second commit** is some cleanup I found while testing the first commit. That specific test was failing for me, and rather than muck around with `Pollution.VG` internals, it seemed like a better idea to me to make that dependency redundant.
* **Third commit** Enables using `date=YYYY-MM-DD` in the URL to select the base date for requesting the Hours of Operation. It's admittedly mostly there to help me …
=> Hours of Operation: use current weekday, and make date configurable

apps/site/assets/css/_accordion-ui.scss, apps/site/assets/css/_alerts.scss, apps/site/assets/css/_global-navigation.scss
**Asana Ticket:** [Ignore more pointer events](https://app.asana.com/0/385363666817452/1203202409417409/f)
remove pointer events from specified classes
=> Ignore more pointer events

apps/site/assets/ts/stop/components/LocationBlock.tsx
**Asana Ticket:** ["Get directions" link broken for stops with slashes](https://app.asana.com/0/385363666817452/1202323182981930/f)
Removes slashes from stop name in get directions link.
=> remove slashes from stop name in direction url

apps/site/lib/site/map_helpers.ex
**Asana Ticket:** [Update subway map preview image](https://app.asana.com/0/385363666817452/1203535674021122/f)
update preview map
=> Update subway map preview image

apps/site/assets/css/_stop-page.scss, apps/site/assets/css/_utilities.scss, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/ConnectionsTest.tsx.snap, apps/site/assets/ts/stop/__tests__/SidebarTest.tsx, apps/site/assets/ts/stop/__tests__/__snapshots__/LocationBlockTest.tsx.snap, apps/site/assets/ts/stop/__tests__/__snapshots__/RoutePillListTest.tsx.snap, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageTest.tsx.snap, apps/site/assets/ts/stop/components/ExternalRiptaConnection.tsx, apps/site/assets/ts/stop/components/LocationBlock.tsx, apps/site/assets/ts/stop/components/PillLink.tsx, apps/site/assets/ts/stop/components/RoutePillList.tsx, apps/site/assets/ts/stop/components/Sidebar.tsx, apps/site/lib/site_web/controllers/schedule/line/helpers.ex
Add a pill to the 4 RIPTA stop pages that links to the external RIPTA page resource
**Asana Ticket:** [Hard Code External RIPTA Information](https://app.asana.com/0/555089885850811/1203642123973340)
---
=> feat(RIPTA): Add an external link to the RIPTA page on certain stops

apps/site/assets/js/address-search.js, apps/site/assets/js/test/address-search_test.js, apps/site/assets/js/test/algolia-search-with-geo_test.js, apps/site/assets/js/test/datepicker-input_test.js
**Asana Ticket:** [Increase unit test coverage (JavaScript)](https://app.asana.com/0/385363666817452/1203608818912887/f)
A few unit test for js
=> Js test coverage

apps/site/assets/css/leaflet.scss
Removed the attribution flag from leaflet displays
**Asana Ticket:** [Remove the Flag from Leaflet Map](https://app.asana.com/0/385363666817452/1203675196112409/f)
---
=> feat(Leaflet): Remove flag from leaflet contribution

apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/ts/components/__tests__/GlxOpenTest.tsx, apps/site/assets/ts/helpers/__tests__/icon-test.ts, apps/site/assets/ts/helpers/__tests__/query-test.ts, apps/site/assets/ts/hooks/__tests__/useIsGlxOpenTest.tsx, apps/site/assets/ts/hooks/__tests__/useRealtimeTest.tsx, apps/site/assets/ts/jest-setup.ts, apps/site/assets/ts/jest.config.js, apps/site/assets/ts/models/__tests__/alert-test.ts, apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/schedule/components/line-diagram/StopConnections.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/LineDiagramTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/MergesTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/StopCardTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/StopConnectionsTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/MergesTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/graphics/Merges.tsx, apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/__tests__/TripDetailsTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/__tests__/TripStopTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/__tests__/UpcomingDeparturesTest.tsx, apps/site/assets/ts/stop/__tests__/RoutePillListTest.tsx, apps/site/assets/ts/tnm/__tests__/MarkerWrapperTest.tsx, apps/site/assets/ts/tnm/__tests__/TransitNearMeMapTest.tsx, apps/site/assets/ts/tnm/helpers/__tests__/process-realtime-data-tests.tsx, apps/site/assets/ts/tnm/helpers/process-realtime-data.ts
Increased the code coverage of the typescript.
**Asana Ticket:** [Increase unit test coverage (Typescript)](https://app.asana.com/0/home/1201123880594717/1203608818912871)
---
=>  chore(TS Coverage): Update the typescript coverage above our threshold

apps/site/assets/ts/stop/__tests__/LocationBlockTest.tsx, apps/site/assets/ts/stop/__tests__/__snapshots__/LocationBlockTest.tsx.snap, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageTest.tsx.snap, apps/site/assets/ts/stop/components/LocationBlock.tsx
Update Button Copy
**Asana Ticket:** [Clearer Link To Trip Planner](https://app.asana.com/0/385363666817452/1203803183465618/f)
---
=> feat(Location): Update Directions Button Copy

apps/site/assets/js/algolia-result.js, apps/site/assets/js/test/algolia-result_test.js
**Asana Ticket:** [Search | Project results might display too many icons](https://app.asana.com/0/385363666817452/1202238959861594/f)
remove duplicate icons from search results
=> Search | Project results might display too many icons

apps/site/assets/.eslintrc.js, apps/site/assets/js/address-search.js, apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/ts/.eslintrc.js, apps/site/assets/ts/helpers/render-fa.tsx, apps/site/assets/ts/helpers/render-svg.tsx, apps/site/assets/ts/schedule/components/Map.tsx, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/MapTest.tsx.snap, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/ScheduleFinderTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/graphics/Merges.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleFinderForm.tsx, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/__snapshots__/ScheduleFinderModalTest.tsx.snap, apps/site/assets/ts/stop/components/StopAccessibilityIcon.tsx, apps/site/assets/ts/stop/components/StopMap.tsx, apps/site/assets/ts/stop/components/StopPage.tsx, apps/site/assets/ts/stop/components/StopPageHeader.tsx, apps/site/assets/ts/stop/components/SuggestedTransfers.tsx
Initially went to add `eslint-plugin-jsx-a11y` then realized we already had it. Then realized we hadn't enabled many of the recommended rules that come from the many ESLint plugins we're using, so went ahead and updated that. Made some minor updates to existing files as a result.
---
=> Add ESLint recommended configurations

apps/site/assets/css/_link-block.scss, apps/site/assets/css/_transit-near-me.scss, apps/site/assets/css/_utilities.scss, apps/site/assets/ts/components/RouteCardHeader.tsx, apps/site/assets/ts/stop/components/RouteCard.tsx
**Asana Ticket:** [Clearer link to alerts](https://app.asana.com/0/555089885850811/1203803183465619/f)
Make it clearer that alerts link is a link
=> Clearer link to alerts

apps/site/assets/ts/components/RouteCardHeader.tsx
Check if alerts exists in `routeCardHeader`. 
Update: this is a fix for the tnm map disappearing. Going to https://dev-blue.mbtace.com/transit-near-me to confirm it functions as expected should suffice.
=> Check if alerts exists

apps/fares/lib/fare.ex, apps/fares/lib/fare_info.ex, apps/fares/lib/format.ex, apps/fares/lib/month.ex, apps/fares/lib/one_way.ex, apps/fares/test/fare_info_test.exs, apps/fares/test/one_way_test.exs, apps/routes/lib/repo.ex, apps/routes/test/repo_test.exs
Hard coded in costs for the Logan Express Massport Shuttles.
Now the trip planner correctly displays the estimated cost of the trip
**Asana Ticket:** [Fare Calculator Treatment for Logan Express](https://app.asana.com/0/home/1201123880594717/1203838985467086)
---
=> feat(TripPlanner): Add fare estimations for the logan express routes

apps/site/assets/css/_timetable.scss, apps/site/lib/site_web/templates/schedule/_timetable_schedule.html.eex
**Asana Ticket:** [UI Bug | CR Timetable Realtime Train Arrival Icon](https://app.asana.com/0/385363666817452/1203869376953056/f)
styling changes so that train icon doesn't overlap time text
=> UI Bug | CR Timetable Realtime Train Arrival Icon

apps/site/lib/site_web/templates/layout/_footer.html.eex
**Asana Ticket:** [Footer | update link to MBTA YouTube channel](https://app.asana.com/0/385363666817452/1204015513754176/f)
---
Update youtube footer link to new channel name.
=> Footer | update link to MBTA YouTube channel

apps/site/assets/ts/tnm/__tests__/__snapshots__/RouteCardTest.tsx.snap, apps/site/assets/ts/tnm/__tests__/__snapshots__/RoutesSidebarTest.tsx.snap, apps/site/assets/ts/tnm/components/RouteCard.tsx, apps/site/assets/ts/tnm/components/RoutesSidebar.tsx
**Asana Ticket:** [Transit Near Me | Alerts not Showing](https://app.asana.com/0/385363666817452/1203879636893634/f)
Add alerts button to transit near me results
=> Transit Near Me | Alerts not Showing

apps/site/lib/site_web/views/layout_view.ex
**Asana Ticket:** [add pages to website header nav](https://app.asana.com/0/385363666817452/1203684095820928/f)
Add link to About us section for Quality, Compliance and oversight.
Note: page not live till 2/24 so merge after
=> add pages to website header nav

apps/site/assets/css/_stop-page.scss, apps/site/assets/ts/stop/components/StationInformation.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx
**Asana Ticket:** [Implement responsive layout](https://app.asana.com/0/385363666817452/1204099052193014/f)
desktop
tablet
mobile
Placeholder containers to show responsive layout across screen sizes
=> Implement responsive layout

apps/site/assets/css/_stop-page.scss, apps/site/assets/ts/stop/components/StationInformation.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx
**Asana Ticket:** [Refine headings](https://app.asana.com/0/385363666817452/1204099052193019/f)
Style headings for redesign
=> Refine headings

apps/site/lib/site_web/views/customer_support_view.ex
**Asana Ticket:** [☎️ Customer Support Form | Change Copy at top of Page](https://app.asana.com/0/0/1204179585884121/f)
Update copy on customer support form.
=> ☎️ Customer Support Form | Change Copy at top of Page

apps/site/assets/js/trip-planner-location-controls.js
No ticket fixes bug of reverse trips not working on trip planner
=> reverse stopid

apps/site/assets/js/trip-planner-location-controls.js, apps/site/lib/site/trip_plan/location.ex, apps/site/lib/site_web/templates/partial/_trip_planner_widget.html.eex, apps/site/lib/site_web/templates/trip_plan/_to_from_inputs.html.eex, apps/trip_plan/lib/trip_plan/api/open_trip_planner.ex
rollback recent trip planner changes
=> revert trip planner changes

apps/site/assets/js/algolia-autocomplete.js
**Asana Ticket:** [AlgoliaAutocomplete | Handle undefined result](https://app.asana.com/0/555089885850811/1204091647610829/f)
Attempting to fix this bug cited on [Sentry](https://mbtace.sentry.io/issues/3453396395/?project=194344). 🤷🏻‍♀️
=> feat(AlgoliaAutocomplete): Handle undefined result

apps/site/assets/ts/stop/components/ExternalMapLink.tsx
**Asana Ticket:** [Use "block quote" style links](https://app.asana.com/0/555089885850811/1204282335537369/f)
Changed the external map link to use styling similar to uses elsewhere
---
=> fix(ExternalMapLink): Change the styling to match other block links

apps/services/test/repo_test.exs
**Asana Ticket:** [CI: fix failing test](https://app.asana.com/0/555089885850811/1204309811592854)
Remove the `async:true` configuration from the test in order to get it passing.
https://github.com/mbta/dotcom/actions/runs/4607693209/jobs/8142539416?pr=1560
---
=> fix(ServicesTest): Fix a failing services elixir test

apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_accessibility.html.eex
**Asana Ticket:** [☎️ Customer Support Form | Create Accordion for ADA/Accessibility Complaints ](https://app.asana.com/0/555089885850811/1204179435047330/f)
---
Add accessibility accordion to contact support page.
awaiting final copy
=> ☎️ Customer Support Form | Create Accordion for ADA/Accessibility Complaints 

apps/fares/lib/fares.ex
Remove Bus Route 351 from the express route list as it is currently operating in local bus mode.
**Asana Ticket:** [Incorrect Fare Estimate for Bus Route 351](https://app.asana.com/0/home/1201123880594717/1204321529580855)
---
=> feat(Bus351): Changed Route 351 from express service to regular bus

apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx
**Asana Ticket:** [Alerts | Stop-Level](https://app.asana.com/0/385363666817452/1204305469426563/f)
Add alerts banner of alerts related to stop
---
=> Alerts | Stop-Level

apps/site/assets/css/_schedule-page-line-diagram.scss
**Asana Ticket:** [Line diagram | Text overflow on mobile](https://app.asana.com/0/385363666817452/1203792853001603/f)
---
Wrap text details on line diagram for mobile
=> Line diagram | Text overflow on mobile

apps/site/assets/css/_alerts.scss, apps/site/lib/site_web/ambiguous_alert.ex, apps/site/lib/site_web/templates/bus_stop_change/index.html.eex
**Asana Ticket:** [Complete Design Changes from Bus Change Tool](https://app.asana.com/0/385363666817452/1204131036282688/f)
CSS updates for bus change tool
=> Complete Design Changes from Bus Change Tool

apps/site/assets/ts/hooks/__tests__/useAlertsTest.tsx, apps/site/assets/ts/hooks/useAlerts.ts
If an alert is set at the route it is not surfaced via the current `useAlertsByStop` hook.
This adds a new hook `useAlertsByRoute` to get the alerts for the routes.
This will surface route wide alerts that affect all stops.
**Asana Ticket:** No Ticket
---
=> feat(useAlerts): Create a hook to fetch alerts by route id

apps/site/assets/ts/hooks/__tests__/usePredictionsChannelTest.tsx, apps/site/assets/ts/hooks/usePredictionsChannel.ts, apps/site/assets/ts/models/perdictions.d.ts
**Asana Ticket:** [TICKET_NAME](TICKET_LINK)
---
=> feat: Add vehicle_id field to predictions returned by usePredictionChannel

apps/site/assets/ts/models/__tests__/alert-test.ts, apps/site/assets/ts/models/alert.ts
Found a bug while working on alert badges for the stop redesign.
During one of the tech sprints how parsing date strings of alerts was changed.
Unfortunately this change was breaking how current alerts work.
This pull request unifies the change to use standard ISO date format parsing, and out custom format.
**Asana Ticket:** None
---
=> fix(Alert): Fixed how we parsed alert active period dates

apps/site/assets/ts/app/__tests__/channels-test.ts, apps/site/assets/ts/app/channels.ts, apps/site/assets/ts/hooks/__tests__/useVehiclesChannelTest.tsx, apps/site/assets/ts/hooks/useVehiclesChannel.ts
**Asana Ticket:** [Real-Time Tracking Page | Map](https://app.asana.com/0/385363666817452/1204506670061542/f)
This hook will be used for surfacing live vehicle data on the new stop page map. The structure of this hook is largely based on the `usePredictionsChannel` hook.
---
=> feat(useVehiclesChannel): New hook for getting live vehicle data

apps/site/assets/css/_stop-card.scss, apps/site/assets/ts/stop/__tests__/DepartureCardTest.tsx, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageDeparturesTest.tsx.snap, apps/site/assets/ts/stop/components/DepartureCard.tsx
**Asana Ticket:** [Departure Cards | Make route headers clickable](https://app.asana.com/0/385363666817452/1204525851385626/f)
---
=> feat(DepartureCard): Link to route page from header

apps/site/assets/ts/stop/__tests__/DepartureCardTest.tsx
It looks like a test was broken with a merge conflict.
This addresses it.
=> fix(DepartureCardTest): Fix test from merge

apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx, apps/site/assets/ts/stop/models/displayTimeConfig.ts
Noticed a bunch of console errors about no keys being specified in the `DepartureTimes` component.   I thought that it had gotten dealt with, but I guess not.
This fixes the console errors from showing up about no keys on the departure times rendered.
**Asana Ticket:** No Ticket
---
=> fix(DepartureTimes): Added key to generated time row to remove errors

apps/site/assets/css/_stop-card.scss, apps/site/assets/ts/helpers/route-headers.tsx, apps/site/assets/ts/stop/__tests__/DepartureListTest.tsx, apps/site/assets/ts/stop/components/DepartureCard.tsx, apps/site/assets/ts/stop/components/DepartureList.tsx, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx
**Asana Ticket:** [Stop Page | Real Time View Departure List Header](https://app.asana.com/0/385363666817452/1204591650723156/f)
Add route header to `departureList`
---
=> Stop Page | Real Time View Departure List Header

apps/site/lib/site_web/templates/customer_support/_report.html.eex
Update the report fraud waste abuse link.
**Asana Ticket:** [Replace Fraud Waste Abuse Link](https://app.asana.com/0/555089885850811/1204637987824085)
---
=> fix(ReportFraud): Update the url to learn how to report fraud

apps/site/assets/ts/stop/components/DepartureList.tsx
in https://github.com/mbta/dotcom/pull/1608 I accidentally removed the `<div/>` surrounding the mode + route name pill in the departure list header. That is causing a styling issue. This reverts that accidental change so that the mode + route name pill are part of one flex box child, not two separate ones.
---
=> fix(DepartureList): Add back in div around mode icon + route name

apps/stops/lib/repo.ex
I noticed this test started[ unexpectedly failing ](https://github.com/mbta/dotcom/actions/runs/5015450754/jobs/8994160406) and was able to reproduce locally on master prior to merging that PR. It seems that the intended behavior is for the stops returned by this endpoint to be unique, so adding a call to `Enum.uniq` to ensure that is the case.
---
=> fix(Stops.Repo): Deduplicate stops by_route_type

apps/site/assets/ts/hooks/__tests__/useAlertsTest.tsx, apps/site/assets/ts/hooks/__tests__/useRouteTest.tsx, apps/site/assets/ts/hooks/__tests__/useSchedulesTest.tsx, apps/site/assets/ts/hooks/__tests__/useStopTest.tsx, apps/site/assets/ts/hooks/useAlerts.ts, apps/site/assets/ts/hooks/useRoute.ts, apps/site/assets/ts/hooks/useSchedules.ts, apps/site/assets/ts/hooks/useStop.ts, apps/site/assets/ts/stop/__tests__/DeparturesAndMapTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx
**Asana Ticket:** [Stop Page | Show helpful message when there's an error fetching page-level data](https://app.asana.com/0/385363666817452/1204541822486710/f)
This PR makes use of the existing `FetchState` type to record if an error is returned from calls to `useSWR`. That type is defined for use with a different and less used hook `useFetch`. It seemed like the simplest starting point to reuse that type, but open to feedback on whether a new type should be defined!
---
=> feat(StopPageRedesign): Return error message if key data fails to load

apps/site/assets/ts/components/__tests__/BadgeTest.tsx, apps/site/assets/ts/stop/__tests__/DepartureCardTest.tsx, apps/site/assets/ts/stop/__tests__/DeparturesAndMapTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx
Inspired by [this comment](https://github.com/mbta/dotcom/pull/1617/files#r1206765323)!
Updates a handful of tests to use `getBy*` and `toBeInTheDocument` to test for an elements presence as recommended in [this article](https://kentcdodds.com/blog/common-mistakes-with-react-testing-library#using-query-variants-for-anything-except-checking-for-non-existence).
Most of these tests continued to pass as-is, only a few needed some minor tweaks.
---
=> Update some stop page redesign tests that could give false positives

apps/site/assets/css/_stop-card.scss, apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/stop/__tests__/DepartureListTest.tsx, apps/site/assets/ts/stop/components/DepartureCard.tsx, apps/site/assets/ts/stop/components/DepartureList.tsx, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx
**Asana Ticket:** [Alerts | Route-Specific Alerts on Real-Time Tracking Page](https://app.asana.com/0/385363666817452/1204570522422001/f)
---
Render route specific alerts above departures schedule
=> Alerts | Route-Specific Alerts on Real-Time Tracking Page

apps/alerts/lib/alert.ex, apps/alerts/lib/parser.ex, apps/alerts/test/parser_test.exs, apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/components/__tests__/AlertsTest.tsx, apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/stop/__tests__/AlertsTabTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageTest.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx, apps/site/lib/site_web/templates/alert/_banner.html.eex
**Asana Ticket:** [Filter Global Banner Alerts from showing Twice](https://app.asana.com/0/385363666817452/1204573844060266/f)
---
If a stop page alert has the same header as a global banner alert don't show that stop page alert.
=> Filter Global Banner Alerts from showing Twice

apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/models/displayTimeConfig.ts
**Asana Ticket:** [Route Cards | Change “Arriving” to “<1 minute away”](https://app.asana.com/0/385363666817452/1204818862216360/f)
---
Change text in departureCards to be <1 minute away instead of arriving
=> Route Cards | Change “Arriving” to “<1 minute away”

apps/site/assets/ts/helpers/__tests__/date-test.ts, apps/site/assets/ts/helpers/__tests__/departureInfoTest.ts, apps/site/assets/ts/helpers/departureInfo.ts, apps/site/assets/ts/models/departureInfo.d.ts, apps/site/assets/ts/stop/__tests__/DisplayTimeTest.tsx, apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx, apps/site/assets/ts/stop/models/displayTimeConfig.ts
Cancelled and Delayed formatting should only happen on the Commuter Rail, Ferry, and Bus.
For subway if it is cancelled or delayed only show the next time.
**Asana Ticket:** [Departure Cards Cancelled and Delayed Times](https://app.asana.com/0/home/1201123880594717/1204554128687100)
---
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1204554128687100
=> feat(DepartureTimes): Show certain formats based of mode type

apps/site/assets/ts/stop/__tests__/DepartureListTest.tsx, apps/site/assets/ts/stop/components/DepartureList.tsx, apps/site/assets/ts/stop/components/DisplayTime.tsx
This ticket adds styling to the display times of the departure list.  It changes the text to red, crosses out the time, and has the word cancelled next to it.
**Asana Ticket:** [Departure List | Cancelled Times](https://app.asana.com/0/555089885850811/1204591650723177)
---
=> feat(DepartureList): Add styling to cancelled trip times

apps/site/lib/site_web/templates/schedule/_empty.html.eex
**Asana Ticket:** [Lynn Ferry Timetable Page | Modify text to show service start date](https://app.asana.com/0/385363666817452/1204827964401085/f)
Added the hard-coded note for when we see the timetable before the Lynn ferry goes into service.
=> feat(timetable): add message for upcoming Lynn ferry

apps/site/assets/js/algolia-facets.js, apps/site/assets/js/algolia-results.js
**Asana Ticket:** [Global Search | Reorder search result sections](https://app.asana.com/0/385363666817452/1204827964401093/f)
---
Change order of search result sections on search page
=> Global Search | Reorder search result sections

apps/site/assets/css/_stop-page.scss, apps/site/assets/css/_utilities.scss, apps/site/assets/ts/models/__tests__/alert-test.ts, apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/stop/__tests__/components/StationInformationTest.tsx, apps/site/assets/ts/stop/__tests__/components/amenities/BikeStorageAmenityCardTest.tsx, apps/site/assets/ts/stop/components/StationInformation.tsx, apps/site/assets/ts/stop/components/amenities/BikeStorageAmenityCard.tsx
**Asana Ticket:** [Amenity Modal | Bike Storage](https://app.asana.com/0/385363666817452/1204415037587409/f)
**Asana Ticket:** [Alerts | Amenity | Bike Storage](https://app.asana.com/0/385363666817452/1204310331755190/f)
Adds everything for displaying bike storage.
* An optional badge denotes "temporarily closed" or "not available"
* The modal describes the different types of bike storage available
For previewing, here are some expected outputs for certain stations:
* **South Station** should show as "temporarily closed"
* **State St** should show as "not available"
* Most stations will have at least a bike rack
* **Braintree** is a station that has a Pedal & Park
---
=> add Bike Storage amenity card & modal

apps/site/assets/ts/stop/__tests__/components/StationInformationTest.tsx, apps/site/assets/ts/stop/__tests__/components/amenities/AccessibilityAmenityCardTest.tsx, apps/site/assets/ts/stop/__tests__/components/amenities/AmenityCardTest.tsx, apps/site/assets/ts/stop/components/StationInformation.tsx, apps/site/assets/ts/stop/components/amenities/AccessibilityAmenityCard.tsx
**Asana Ticket:** [Amenity Modal | Accessibility](https://app.asana.com/0/385363666817452/1204415037587432/f)
**Asana Ticket:** [Alerts | Amenity | Accessibility ](https://app.asana.com/0/385363666817452/1204415037587418/f)
Adds the information and modal for the Accessibility stop amenity, based on the values from the stop's `accessibility` property.
---
=> feat(AccessibilityAmenityCard): add info and modal

apps/site/assets/css/_spacing.scss, apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/stop/__tests__/components/ExternalMapLinkTest.tsx, apps/site/assets/ts/stop/__tests__/components/amenities/ParkingAmenityCardTest.tsx, apps/site/assets/ts/stop/components/ExternalMapLink.tsx, apps/site/assets/ts/stop/components/StationInformation.tsx, apps/site/assets/ts/stop/components/amenities/ParkingAmenityCard.tsx
This adds the parking amenity modal.
List all the parking available at the given stop with the rates, payment information, and other statistics.
**Asana Ticket:** [Amenity Modal | Parking](https://app.asana.com/0/555089885850811/1204415037586238)
---
=> feat(ParkingAmenity): Added the parking amenity modal

apps/site/assets/ts/stop/__tests__/DepartureCardTest.tsx, apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx
**Asana Ticket:** ["Track" label adjustments](https://app.asana.com/0/385363666817452/1204807074953512/f)
---
Render "Track" before track number and only show for commuter rail
=> "Track" label adjustments

apps/site/assets/ts/helpers/departureInfo.ts, apps/site/assets/ts/hooks/__tests__/usePredictionsChannelTest.tsx, apps/site/assets/ts/hooks/usePredictionsChannel.ts, apps/site/assets/ts/models/departureInfo.d.ts, apps/site/assets/ts/stop/__tests__/DepartureCardTest.tsx, apps/site/assets/ts/stop/__tests__/DepartureListTest.tsx, apps/site/assets/ts/stop/__tests__/DeparturesAndMapTest.tsx, apps/site/assets/ts/stop/__tests__/DisplayTimeTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageDeparturesTest.tsx, apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/components/DepartureCard.tsx, apps/site/assets/ts/stop/components/DepartureList.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx, apps/site/assets/ts/stop/components/DisplayTime.tsx, apps/site/assets/ts/stop/components/StopPageDepartures.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx
No ticket. It moves our call to predictions higher up in the tree, making one websocket connection for all the predictions, instead of one per route/direction.
---
=> feat(StopPageDepartures): fetch predictions at top level

apps/site/assets/ts/helpers/departureInfo.ts, apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/models/displayTimeConfig.ts
**Asana Ticket:** [Commuter Rail Specific Time Format](https://app.asana.com/0/385363666817452/1204570525176322/f)
---
Show commuter rail time in hh:mm format regardless of arrival time
=> Commuter Rail Specific Time Format

apps/site/assets/ts/stop/__tests__/components/DepartureTimesTest.tsx, apps/site/assets/ts/stop/models/displayTimeConfig.ts
This ticket removes the filtering of delay subway times from the departure times.
**Asana Ticket:** [Departure Subway times aren't consistent](https://app.asana.com/0/555089885850811/1205093855734951)
---
=> fix(DepartureTimes): Don't skip delayed subway times

apps/site/assets/ts/stop/components/DepartureTimes.tsx
**Asana Ticket:** [Departure Cards | Content falls outside of container](https://app.asana.com/0/385363666817452/1204570525176332/f)
---
Add white space after slash in headsign
=> Departure Cards | Content falls outside of container

apps/site/lib/site_web/controllers/stop_controller.ex, apps/site/test/site_web/controllers/stop_controller_test.exs
Add the standard title to the top of the redesign page.
Also add the old stops description to the meta data of the page
**Asana Ticket:** [HTML Title and Meta Tags](https://app.asana.com/0/home/1201123880594717/1205113827737597)
---
=> feat(StopsRedesign): Added the title and meta description to the page

apps/site/assets/css/_amenity.scss
**Asana Ticket:** [Stop overflows over close button in modal](https://app.asana.com/0/385363666817452/1205113827737603/f)
---
Added padding to modal header since the close button is positioned absolute text wrapping wasn't going to work. If the button text changes the padding will need to be adjusted.
=> Stop overflows over close button in modal

apps/site/assets/ts/helpers/departureInfo.ts
**Asana Ticket:** [Terminal Bound Routes Still showing up ](https://app.asana.com/0/385363666817452/1205113827581166/f)
---
put spaces around or check so places like n**OR**th station don't render at destination
=> Terminal Bound Routes Still showing up 

apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/stop/__tests__/DepartureListTest.tsx, apps/site/assets/ts/stop/__tests__/DeparturesAndMapTest.tsx, apps/site/assets/ts/stop/components/DepartureList.tsx, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx, apps/site/assets/ts/stop/components/StopPageDepartures.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx
Alert types to show on real time tracking page: "Detour", "Shuttle Service", "Suspension"
This pull request changes logic to ensure all the alert types above are shown for both upcoming and ongoing if they affect the current stop.  It only shows the above alert types for other stops along the route if they are ongoing/new.
**Asana Ticket:** [Alerts not appearing on the realtime tracking page](https://app.asana.com/0/555089885850811/1204819585744771)
---
=> feat(RealTimeAlerts): Display only stop and ongoing route alerts

apps/site/assets/ts/leaflet/components/Map.tsx
when DOM stuff happens, trigger [invalidateSize()](https://leafletjs.com/reference-1.4.0.html#map-invalidatesize) in order to redraw the map.
**Asana Ticket:** [Realtime Tracking | Map does not load on mobile ](https://app.asana.com/0/385363666817452/1205093855734947/f)
---
=> fix(Map): run `invalidateSize()` in `useLayoutEffect`

apps/site/assets/ts/stop/components/DisplayTime.tsx
**Asana Ticket:** [Departure List | Change Time Format](https://app.asana.com/0/385363666817452/1205040060480944/f)
Updates cancelled display to black small text... here's what the revision will look like (cancellations hard-coded here at random):
- Simplified display, showing "Delayed ~~hh:mm~~" regardless of whether the time is <1 hour away or >=1 hour away.
| Before  | After |
| ------- | ----- |
| <img height="300" src="https://user-images.githubusercontent.com/2136286/255985025-48fda113-9aba-4a76-aff1-21f071b8230e.png" />  | <img height="300" src="https://user-images.githubusercontent.com/2136286/255986180-6922558a-573e-431c-a0c7-ad4af94b770a.png" /> |
---
=> Departure List | Change Time Format

apps/site/assets/ts/stop/components/amenities/BikeStorageAmenityCard.tsx
**Asana Ticket:** [Amenity Modal | Bike Content Changes](https://app.asana.com/0/385363666817452/1205040060480950/f)
---
Add free to modal copy and charlieCard link
=> Amenity Modal | Bike Content Changes

apps/site/assets/ts/stop/components/amenities/EscalatorsAmenityCard.tsx
Replace the elevator icon with the escalator icon on the escalator amenity card
**Asana Ticket:** [Escalator Icon Fix](https://app.asana.com/0/555089885850811/1205172693755928)
---
=> fix(EscalatorAmenityCard): Show correct icon on card

apps/site/assets/ts/stop/components/DeparturesAndMap.tsx
Remove the vehicles from the real time map on the stop page redesign
**Asana Ticket:** [Hide All Vehicles from Real time Map](https://app.asana.com/0/555089885850811/1205175614190131)
---
=> feat(RealTimeStopPage): Remove vehicles from map

apps/site/assets/ts/stop/__tests__/DepartureListTest.tsx, apps/site/assets/ts/stop/components/DepartureList.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx
**Asana Ticket:** [Suppress Predictions when Shuttles in Service](https://app.asana.com/0/385363666817452/1205175609527218/f)
---
Don't show schedules or predictions if shuttle alert. Also don't show "See alternatives" when no alert badge
=> Suppress Predictions when Shuttles in Service

apps/site/assets/css/_stop-card.scss, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageDeparturesTest.tsx.snap, apps/site/assets/ts/stop/components/DepartureCard.tsx, apps/site/assets/ts/stop/components/DepartureTimes.tsx
Part of accessibility involves interactive parts being keyboard navigable - ideally, anything accessed via mouse click can also be accessed via keyboard `Enter`. This PR updates `<DepartureTimes />` to enable access via keyboard - can tab to it and click into the realtime tracking page. 
---
=> refactor(DepartureTimes): make row keyboard operable

apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx, apps/site/assets/ts/stop/components/StopPageRedesign.tsx
**Asana Ticket:** [Alerts | No information about stop moves](https://app.asana.com/0/385363666817452/1205250017202664/f)
---
Add `stop_moved` effect to list of effects filtered on stop page
=> Alerts | No information about stop moves

apps/site/assets/css/_stop-card.scss
**Asana Ticket:** [Realtime Tracking Page | Text cut off in departure list header](https://app.asana.com/0/385363666817452/1205241402306294/f)
---
=> Realtime Tracking Page | Text cut off in departure list header

apps/site/assets/ts/stop/__tests__/components/amenities/ParkingAmenityCardTest.tsx, apps/site/assets/ts/stop/components/amenities/ParkingAmenityCard.tsx
**Asana Ticket:** [Parking Modal | Update content and layout](https://app.asana.com/0/385363666817452/1205293725975719/f)
---
Reorder parking modal content and add management info.
=> Parking Modal | Update content and layout

apps/site/assets/css/_stop-card.scss
Increased the max height realtime departure list
**Asana Ticket:** [Increase Departure List Container Height](https://app.asana.com/0/555089885850811/1205268368932689)
---
=> feat(RealTimeList): Increase max height of real time list

apps/site/lib/site_web/templates/trip_plan/_itinerary_tab.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex
This removes the code about the Fare Note on the Sumner Tunnel closures.
The notes should automatically hide after Aug 31st.
This change removes all code about the notice.
**Asana Ticket:** [Remove Fare Change Note](https://app.asana.com/0/home/1201123880594717/1205301549499018)
---
=> feat(SumnerTunnel): Remove fare note from itinerary about closure

apps/site/assets/css/_amenity.scss, apps/site/assets/ts/stop/components/AccessAmenitiesModal.tsx
This ticket addresses the discussed padding changes in the ticket.
The padding is now on every row, and the fixed height of the table rows is removed.
Follow up to this ticket as the first attempt didn't fully address the padding
**Asana Ticket:** [Elevator/Escalator Modal | Add padding around text in table and row colors](https://app.asana.com/0/555089885850811/1205276830613117/f)
---
=> feat(AccessAmenitiesTable): Fixed padding on table

apps/site/assets/css/_stop-card.scss, apps/site/assets/ts/stop/components/DeparturesAndMap.tsx
Move the height change to just affect the realtime list
**Asana Ticket:** [Realtime Tracking Page | Increase departure list container height](https://app.asana.com/0/555089885850811/1205268368932689)
---
=> fix(RealtimeList): Height changes now only affect the realtime list

apps/fares/lib/fare_info.ex, apps/fares/lib/format.ex, apps/site/lib/site_web/templates/cms/paragraph/_fare_card.html.eex
This updates the East Boston Ferry card to say: `with mTicket App or paper ferry ticket`
Also lowercases the `paper ferry ticket` and `cash` lines on the site
**Asana Ticket:** [Update East Boston Ferry & other ferry cards](https://app.asana.com/0/555089885850811/1205435687611946)
---
=> feat(FerryCopy): Update the ferry card fare copy

apps/fares/test/format_test.exs, apps/site/test/site_web/views/helpers_test.exs, apps/site/test/site_web/views/paragraph_view_test.exs
This fixes some tests that were failing from a previous ticket that were missed.
**Asana Ticket:** None
---
=> fix(Fares): Fix tests to change the casing on cash.

apps/alerts/lib/alert.ex, apps/fares/test/format_test.exs, apps/site/assets/ts/models/__tests__/alert-test.ts, apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/stop/__tests__/StopPageRedesignTest.tsx
Update the active period of alerts returned by the dotcom backend to be in ISO format (therefore include the timezone)
**Asana Ticket:** [Alerts | Make Active Alerts Timestamp ISO Standard](https://app.asana.com/0/555089885850811/1204603996089768)
---
=> feat(Alert) Format the alert active period to ISO standard

apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/TripDetails.tsx, apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/TripDetails.tsx, apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/__tests__/TripDetailsTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/__tests__/__snapshots__/TripDetailsTest.tsx.snap
This stops the Schedule Finder modal from crashing when expanding the row of the Upcoming Trips.
The issue was skipped trips had a null time that the modal was not expecting and could not handle.  These are filtered out for skipped trips, so they will not show on the modal.
**Asana Ticket:** [Schedule Finder Upcoming Trip row opening crashes modal](https://app.asana.com/0/555089885850811/1205501402709150)
---
=> fix(ScheduleFinder): Upcoming Departure rows doesn't show skipped trips

apps/algolia/config/prod.exs
**Asana Ticket:** [Turn Algolia Click Tracking Back On](https://app.asana.com/0/385363666817452/1180498998795793/f)
---
Turn Algolia click tracking back on
=> Turn Algolia Click Tracking Back On

apps/site/lib/site_web/views/schedule/timetable.ex
**Asana Ticket:** [Track change tooltip includes markup](https://app.asana.com/0/385363666817452/1205494675199866/f)
---
=> Track change tooltip includes markup

apps/site/assets/ts/stop/components/amenities/ParkingAmenityCard.tsx
Parking amenity modal now only shows phone number and website link if data is populated
**Asana Ticket:** [Missing Link and Phone Number](https://app.asana.com/0/555089885850811/1205631015693371)
---
=> fix(ParkingAmenity): Phone number and website only show if available

apps/site/lib/site_web/views/layout_view.ex
**Asana Ticket:** [Update MBTA gifts navbar link](https://app.asana.com/0/385363666817452/1205492445611497/f)
---
=> Update MBTA gifts navbar link

apps/site/assets/css/_flex.scss, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageDeparturesTest.tsx.snap, apps/site/assets/ts/stop/components/StopPageHeaderRedesign.tsx
Right align the stop feature icons to line up with the stop name for bus stops
**Asana Ticket:** [Fix Stop ID Alignment](https://app.asana.com/0/555089885850811/1205145475592952)
---
=> feat(StopName): Right Align Stop Features

apps/site/lib/site_web/views/trip_compare_view.ex, apps/site/lib/site_web/views/trip_plan_view.ex
The error returned from OTP doesn't have anything to do with handicap accessibility.
None of the error codes [from otp docs](https://github.com/opentripplanner/OpenTripPlanner/blob/2df233d2ead2c2b04b70d33db0b6445facdde5b8/src/main/resources/Message.properties#L13) have information regarding handicap accessibility.  This updates the error message we display to reflect the intent of the error message from OTP
**Asana Ticket:** [Trip Planner Has Mis Leading Error Message](https://app.asana.com/0/555089885850811/1205556420824882)
---
=> fix(TripPlanner): Update the error message to match intent from OTP

apps/site/lib/site/map_helpers.ex
Updated the Ferry Map to reflect the current service
**Asana Ticket:** [Update Ferry Map](https://app.asana.com/0/555089885850811/1205874339374879)
---
=> feat(FerryMap): Update the ferry map to reflect the current service

apps/site/assets/css/_timetable.scss
=> Add width to icon

apps/site/assets/js/trip-planner-location-controls.js, apps/site/lib/site/trip_plan/location.ex, apps/site/lib/site_web/templates/partial/_trip_planner_widget.html.eex, apps/site/lib/site_web/templates/trip_plan/_to_from_inputs.html.eex, apps/site/test/site/trip_plan/location_test.exs, apps/trip_plan/lib/trip_plan/api/open_trip_planner.ex, apps/trip_plan/lib/trip_plan/api/open_trip_planner/builder.ex, apps/trip_plan/test/api/open_trip_planner/builder_test.exs
This fixes using addresses on the trip planner.
Stop ID is only used if a value exists.
**Asana Ticket:** [TICKET](https://app.asana.com/0/home/1201123880594717/1205711841709226)
---
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205711841709226
=> feat(TripPlanner): Use Stop ID to query OTP

apps/algolia/lib/algolia/api.ex, apps/algolia/test/api_test.exs
https://app.asana.com/0/555089885850811/1206042318802985/f
=> Check the status code of an algolia response to determine success

apps/algolia/lib/algolia/api.ex, apps/algolia/lib/algolia/update.ex, apps/algolia/test/api_test.exs, apps/algolia/test/update_test.exs, apps/site/lib/site_web/controllers/search_controller.ex
This affects both stops and routes.
This pull request adds a support for a `GET`  request to query the algolia endpoint during the update.
The order of operations
1. Grab all of the current objects off of Algolia
2. Generate a list of new objects to send to Algolia
3. Compare the current object list and new object list to get a list of no longer supported ids
4. Send a `batch` request job off to Algolia to delete the no longer supported objects
5. Send a `batch` request job off to Algolia to upload the new objects
**Asana Ticket:** [Update Algolia Scripts to remove stops](https://app.asana.com/0/home/1201123880594717/1204170419316251)
---
=> feat(Algolia): Clear old stops and routes on upload

apps/site/lib/site/schedule_note.ex
Update the train frequency to match the pdf schedule as outlined in the asana ticket.
**Asana Ticket:** [Dev | update schedule headways to match new rating](https://app.asana.com/0/555089885850811/1205890135793726)
---
=> feat(Schedules): Update the train frequency to match Winter 2023 ratings

apps/site/assets/ts/schedule/components/PDFSchedules.tsx, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/AdditionalLineInfoTest.tsx.snap, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/PDFSchedulesTest.tsx.snap, apps/site/assets/ts/schedule/helpers/__tests__/hoursOfOperationHelpersTest.tsx, apps/site/assets/ts/schedule/helpers/hoursOfOperationHelpers.tsx, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/views/schedule_view_test.exs
Update the titles and link wording to indicate that the PDFs contain maps
**Asana Ticket:** [Update references to PDF schedule to clarify that it also contains a map](https://app.asana.com/0/555089885850811/1205131053703829)
---
=> feat(PDFSchedules): Update workding to indate pdfs contain maps

docs/DEPLOYMENT.md
No ticket.
The documentation on creating a release felt a little unclear.  Added steps on how to create a tag, to use in the create a release step.
---
=> doc(DEPLOYMENT): Add tagging information to the deployment documentation

apps/site/assets/js/trip-planner-location-controls.js
**Asana Ticket:** [Trip Planner swap button doesn't update map](https://app.asana.com/0/385363666817452/1206190818412902/f) and [Trip Planner shows nonsensical results when origin/destination are updated after initial search](https://app.asana.com/0/385363666817452/1206190818412904/f)
---
=> fix(TripPlannerLocControls): fix stop ID swaps

apps/site/lib/site/map_helpers.ex
Update ferry map for new rating
**Asana Ticket:** [Ferry Map Update](https://app.asana.com/0/385363666817452/1206205746306567)
---
=> feat(FerryMap): Update the map for the winter rating

apps/site/lib/site_web/controllers/customer_support_controller.ex
No Ticket.
Noticed some unhandled errors on the customer support tool when users submit.
This should correctly log the error, and hopefully fail more gracefully for the end user.
---
=> fix(CustomerSupport): Catch misc errors from HTTPoison

lib/cms/page/event.ex, lib/util/util.ex
**Asana Ticket:** [[extra] Events showing as "ended" prematurely](https://app.asana.com/0/555089885850811/1206444920940594/f)
=> feat(CMS.Page.Event): better teaser started_status logic

assets/ts/schedule/components/AdditionalLineInfo.tsx, assets/ts/schedule/components/PDFSchedules.tsx, assets/ts/schedule/components/__tests__/PDFSchedulesTest.tsx, lib/dotcom_web/views/schedule_view.ex, lib/routes/route.ex, test/routes/route_test.exs
This pull request changes the wording the the pdf link for commuter rails to omit the word `map`
**Asana Ticket:** [Update CR PDF Link](https://app.asana.com/0/555089885850811/1206304591685791)
---
=> feat(ScheduleLink): Update wording on schedule link for commuter rail

lib/dotcom/phone_number.ex, lib/dotcom_web/templates/customer_support/_call_us.html.eex, lib/dotcom_web/templates/layout/_new_nav_contact_numbers.html.eex, test/dotcom/phone_number_test.exs
Updates the TTY number in the footer of the page
**Asana Ticket:** [TTY to Mass Relay Number](https://app.asana.com/0/555089885850811/1205391236227798)
---
=> feat(TTY): Updated the TTY number in the footer

assets/ts/components/Alerts.tsx, assets/ts/components/__tests__/AlertsTest.tsx, assets/ts/components/__tests__/__snapshots__/AlertsTest.tsx.snap
Format the timestamp and the description of the alerts on the stop page to match the formatting on the schedule page.
**Asana Ticket:** [Improve Alert Timestamp Presentation](https://app.asana.com/0/555089885850811/1205942612371910)
---
=> feat(Alerts): Update stop page alerts to match schedule alerts

e2e_tests/all-scenarios.spec.js, load_tests/all-scenarios.js, load_tests/all-scenarios.yml, monitor/all-scenarios.js, monitor/worker.js, playwright.config.js, scenarios/find-transit-near-me.js, scenarios/plan-a-trip-from-homepage.js, scenarios/plan-a-trip.js, scenarios/search-for-a-static-page.js, scenarios/search-for-a-station.js, scenarios/search-for-a-subway-line.js, scenarios/view-commuter-rail-schedule.js, scenarios/view-subway-schedule.js, scenarios/visit-a-static-page.js, scenarios/visit-the-homepage.js
https://app.asana.com/0/555089885850811/1206498102526465/f
All 10 critical user journeys. I removed the expectation that the test runs within a threshold because it was pretty unstable. And, it doesn't make sense to have thresholds that are so high they can handle that volatility. Instead, we just attach an annotation to the test for how long it took to complete.
=> Write Critical User Journeys

.github/workflows/push-monitor.yml
No ticket, just trying to fix the monitor.
=> fix: deploy after pushing new monitor image

integration/utils.js
Use the json logger for monitor errors.
=> use logger for monitor errors

integration/e2e_tests/all-scenarios.spec.js, integration/scenarios/search-for-a-subway-line.js, playwright.config.js
https://app.asana.com/0/555089885850811/1206777424770568/f
=> Increase expect timeout; remove map check that is failing; add tags

lib/dotcom_web/controllers/trip_plan/feedback.ex
We want to log when feedback is submitted so that we know how many submissions we have.
=> Log when action taken on feedback

assets/css/_typography.scss, assets/css/_utilities.scss, assets/ts/__v3api.d.ts, assets/ts/hooks/useHoursOfOperation.ts, assets/ts/schedule/components/HoursOfOperation.tsx, assets/ts/schedule/components/RapidTransitHoursOfOperation.tsx, assets/ts/schedule/components/__tests__/HoursOfOperationTest.tsx, assets/ts/schedule/components/__tests__/RapidTransitHoursOfOperationTest.tsx, assets/ts/schedule/components/__tests__/ScheduleFinderTest.tsx, assets/ts/schedule/components/__tests__/ScheduleLoaderTest.tsx, assets/ts/schedule/components/schedule-finder/__tests__/ScheduleFinderModalTest.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/DailyScheduleSubway.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/DailyScheduleSubwayTest.tsx, lib/dotcom/schedule_note.ex, lib/dotcom_web/controllers/schedule/hours_controller.ex, lib/dotcom_web/controllers/schedule/hours_of_operation.ex, lib/dotcom_web/router.ex, lib/schedules/departures.ex, lib/schedules/hours_of_operation.ex, lib/schedules/repo.ex, test/schedules/hours_of_operation_test.exs, test/schedules/repo_test.exs
This pull request removes the per head way times of the subway hours of operation display.
Instead it shows the time the first train leaves for the day, and the time the first train of the last trip leaves for the day.
Also some cleanup of logic and data around the existing hours of operation logic
**Asana Ticket:** [Rationalize Subway Card](https://app.asana.com/0/home/1201123880594717/1206558978794410)
---
=> feat(ScheduleCard): Overall Scehdule Card for Subway

lib/dotcom_web/controllers/schedule/predictions.ex, lib/dotcom_web/controllers/schedule/vehicle_locations.ex, lib/schedules/repo.ex
Just adding more logging for errors around schedules and predictions.
=> chore(ScheduleController.Predictions): log the errors

.github/workflows/changed-files.yml, .github/workflows/crawler.yml, .github/workflows/shellcheck.yml, .github/workflows/use-notify-slack.yml
Just fixing the Website crawler workflow, and updating the rest to use `ubuntu-latest` instead of an older version.
=> ci: update workflows

lib/dotcom_web/controllers/schedule/timetable_controller.ex
Followup to #1921 , fixes the ferry timetables.
=> fix(TimetableController): fix for stops without zones

lib/dotcom/phone_number.ex, lib/dotcom_web/views/helpers.ex, test/dotcom/phone_number_test.exs, test/dotcom_web/views/helpers_test.exs
No ticket.  Noticed the test was failing since the TTY update.  Fixes the test as we treat all telephone numbers as links now.
---
=> fix(tel_link): Fixed the tel link test

lib/dotcom_web/controllers/schedule/timetable_controller.ex
This adds the `Via Fairmount Line` note to the CR-Providence Outbound train
**Asana Ticket:** [Add Via Fairmount line on Train 893](https://app.asana.com/0/555089885850811/1206369501996341)
---
=> feat(ProvidenceTimetable): Update Time Table with Via Fairmount Line

lib/dotcom/map_helpers.ex
**Asana Ticket:** [Update Ferry map on Ferry Schedule page](https://app.asana.com/0/555089885850811/1206942681882973/f)
=> chore: update to latest ferry map

assets/ts/ui/autocomplete/plugins/algolia.ts, assets/ts/ui/autocomplete/plugins/geolocation.ts, assets/ts/ui/autocomplete/plugins/locations.ts, assets/ts/ui/autocomplete/plugins/popular.ts
Adding the `getItemUrl()` function enables keyboard navigation for the autocomplete library.
Allowing users to use the arrow and enter keys to interact with the search results.
**Asana Ticket:** [Search Bar Not Working on the top of the navigation](https://app.asana.com/0/home/1201123880594717/1206592383985332)
---
=> fix(AlgoliaSearch): Add support for keyboard navigation

assets/css/_alerts.scss, assets/ts/components/Alerts.tsx, assets/ts/components/__tests__/AlertsTest.tsx, assets/ts/components/__tests__/__snapshots__/AlertsTest.tsx.snap, lib/alerts/alert.ex, lib/dotcom_web/banneralert.ex, lib/dotcom_web/templates/alert/_banner.html.eex, lib/dotcom_web/templates/alert/_item.html.eex, lib/dotcom_web/views/alert_view.ex, test/alerts/alerts_test.exs, test/dotcom_web/banneralert_test.exs, test/dotcom_web/views/alert_view_test.exs
This removes the Delay time badge from the alerts (both Banner and regular Alerts)
**Asana Ticket:** [Remove Delay Time Badge from Alerts](https://app.asana.com/0/555089885850811/1206871686314363)
---
=> feat(Alert): Remove the human delay labels from alerts

lib/location_service/result.ex, test/location_service/result_test.exs
This change stops logging the `zero_results` message from AWS.
It appears the error was not being returned to the front end and an empty array was already being returned.
**Asana Ticket:** [Return an OK response from PlacesController when there are no results](https://app.asana.com/0/555089885850811/1206767478602193)
---
=> fix(PlacesController): Don't log zero results from AWS

README.md, deploy/dev.yml, deploy/dotcom/dev/1/Dockerfile, deploy/dotcom/dev/2/Dockerfile
This will start our development Phoenix apps in a way that they can be communicated with while running.
=> Allow for node connection and lower interval for faster startup

lib/dotcom/schedule_note.ex
Update the schedule note to align with the 2024 spring rating.
**Asana Ticket:** [Update Spring Rating Schedule Note](https://app.asana.com/0/555089885850811/1205890493113111)
---
=> feat(SpringRating): Update schedule note for spring 2024 rating

integration/monitor/all-scenarios.js
Also correct the comment. This was running from 5am to midnight UTC, not 6am.
=> feat(monitor): define timezone for cron job

config/deps/logger.exs
**Asana Ticket:** [[Credo] Warning.MissedMetadataKeyInLoggerConfig](https://app.asana.com/0/555089885850811/1207049863049664/f)
=> fix(Logger): add :ip to metadata

coveralls.json, test/alerts/alerts_test.exs, test/dotcom/lib/react_test.exs, test/dotcom_web/controllers/customer_support_controller_test.exs, test/dotcom_web/controllers/page_controller_test.exs, test/dotcom_web/plugs/cookies_test.exs, test/dotcom_web/plugs/recently_visited_test.exs, test/dotcom_web/views/helpers/cms_helpers_test.exs, test/fares/one_way_test.exs
No ticket, just a minor improvement in coverage, mostly by replacing a few `@moduletag :external` with more targeted `@tag :external`. It also didn't seem to make sense to me to expect coverage of both behaviors and implementations so I omitted one, open to alternate suggestions around that.
=> adjust covered files and tagged tests

lib/alerts/cache/bus_stop_change_s3.ex, lib/alerts/historical_alert.ex, lib/alerts/informed_entity.ex, lib/cms/repo.ex, lib/dotcom_web/ambiguous_alert.ex, lib/dotcom_web/controllers/event_controller.ex, lib/dotcom_web/controllers/schedule/line_controller.ex, lib/dotcom_web/controllers/search_controller.ex, lib/dotcom_web/views/bus_stop_change_view.ex, lib/dotcom_web/views/event_view.ex, lib/dotcom_web/views/partial/location_card.ex, lib/fares/proposed_locations.ex, lib/util/breadcrumb_html.ex
https://app.asana.com/0/555089885850811/1207049863049660
https://hexdocs.pm/credo/Credo.Check.Warning.SpecWithStruct.html
=> Change structs to types in specs

lib/dotcom_web/controllers/schedule/hours_controller.ex, lib/schedules/hours_of_operation.ex
No ticket, just noticing lots of errors in the backend in `DotcomWeb.ScheduleController.HoursController`, usually when the `route_id` does not correspond to a valid route. I wrote some logic that can account for this a bit more smoothly.
Locally, and a few times on dev, I also noticed errors in `Schedules.HoursOfOperation` when `departure(data, headsigns, :rapid_transit)` returns `:no_service`, so I wrote logic to accommodate this too.
=> chore: improve error handling in `DotcomWeb.ScheduleController.HoursController` and `Schedules.HoursOfOperation`

.github/workflows/deploy-release.yml, .github/workflows/use-deploy-ecs.yml, config/deps/sentry.exs, config/runtime.exs, lib/dotcom_web/templates/layout/root.html.eex
https://app.asana.com/0/home/1204957179328166/1206719459037546
Related Devops PR: https://github.com/mbta/devops/pull/1713
=> Update sentry configuration

assets/ts/components/Alerts.tsx, assets/ts/components/__tests__/AlertsTest.tsx, lib/alerts/url_parsing_helpers.ex, test/dotcom_web/views/alert_view_test.exs
This changes stops the domain part of emails in alert description bodies from being parsed out into links.
This affects all Alert descriptions.
**Asana Ticket:** [Pedal and Park Issue](https://app.asana.com/0/555089885850811/1204668860243821)
---
=> fix(AlertEmails): Disable url creation for emails in alert description

assets/ts/helpers/use-fetch.ts, assets/ts/hooks/useStop.ts, assets/ts/stop/components/StopPage.tsx
Add error message of failed feches to the error thrown by the stop page.
**Asana Ticket:** [https://app.asana.com/0/555089885850811/1206990740330709](https://app.asana.com/0/555089885850811/1206990740330709)
---
=> fix(StopPage): Log errors from fetching data

AUTHORS
No ticket adding myself as an Author
---
=> author: Added myself as an author

lib/cms/api/http_client.ex, lib/cms/repo.ex, test/cms/api/http_client_test.exs, test/cms/repo_test.exs
Parse the params of a map to a string for cache key generation
https://app.asana.com/0/555089885850811/1206990758684890
---
=> fix(CMSRepo): Support cache key generation for map params

lib/dotcom_web/views/schedule_view.ex, test/dotcom_web/views/schedule_view_test.exs
https://app.asana.com/0/555089885850811/1204958755227542/f
=> Show fare as free when the route says its a free fare

lib/dotcom_web/channels/predictions_channel.ex, lib/dotcom_web/controllers/schedule/line_controller.ex, lib/journey_list.ex, lib/predicted_schedule.ex, lib/services/service.ex, lib/stops/route_stop.ex
https://app.asana.com/0/385363666817452/1207115993391023/f
=> Removes calling reject multiple times in the same pipeline

lib/algolia/query.ex, lib/dotcom/cache/key_generator.ex, lib/dotcom/cache/telemetry/reporter.ex, lib/dotcom/cache/trip_plan_feedback/key_generator.ex, lib/dotcom/components/helpers.ex, lib/dotcom/phone_number.ex, lib/dotcom_web/controllers/static_page_controller.ex, lib/dotcom_web/controllers/trip_plan/feedback_csv.ex, lib/dotcom_web/views/helpers.ex, lib/mix/tasks/header_footer.ex, lib/predictions/stream_topic.ex, lib/routes/route.ex, lib/schedules/repo.ex, lib/schedules/repo_condensed.ex, test/dotcom_web/views/partial/location_card_test.exs
Replace `map |> join` with `map_join`
https://app.asana.com/0/555089885850811/1207115993391014
---
=> fix(Credo): Use map_join

lib/dotcom_web/controllers/schedule/timetable_controller.ex
Hoping this along with the metadata (node, IP, etc) might be able to shine some light...
=> chore(TimetableController): log sorted stop list

lib/dotcom_web/controllers/schedule/timetable_controller.ex
This is to address an intermittent issue on the Newburyport line, where Chelsea and North Station are switched.
This PR is a hack that ensures our beloved downtown terminal stops, North Station and South Station, will always be sorted such that they're before all the other zones.
Still working on creating a stable sorting function that'll work across all routes with or without disruptions. That will mostly likely not involve using zones to sort at all.
=> hotfix(TimetableController): ensure termini stops stay at the end

test/schedules/repo_condensed_test.exs, test/schedules/repo_test.exs
Removed uses of `filter |> count`
https://app.asana.com/0/555089885850811/1207115993391018
---
=> fix(Credo): Removed uses of filter |> count

lib/dotcom_web/controllers/schedule/line_api.ex
https://app.asana.com/0/555089885850811/1207183307398788/f
=> Handle nil returns when getting a stop parent

lib/fares/format.ex, test/fares/format_test.exs
Update Winthrop Ferry name to Winthrop/Quincy
https://app.asana.com/0/555089885850811/1207196747672723
---
=> feat(Ferry): Update the Winthrop/Quincy ferry name

lib/schedules/hours_of_operation.ex
https://app.asana.com/0/555089885850811/1207286684779740
=> fix(Credo): Remove negated check in if-else

lib/dotcom_web/templates/schedule/_stop_list_expand_link.html.eex
https://app.asana.com/0/555089885850811/1207286739672613/f
=> Make sure trip isnt nil before accessing it

lib/dotcom_web/controllers/search_controller.ex
https://app.asana.com/0/555089885850811/1207286741208406
=> fix(SearchController): Add case match for failed analytics click

package-lock.json, package.json
No ticket
Add lint-staged to the root of the pacakge.json
=> fix(LintStaged): Add Lint Staged to the root package

lib/dotcom_web/controllers/schedule/timetable_controller.ex
No ticket, I noticed this weekend's shuttle on the Newburyport/Rockport line was missing the stops from the local bus shuttle. And realized I had no mechanism for allowing the day's scheduled trips to add new stops to the timetable stops. So this PR does that (along with adding the positions for the two new stops, at Wonderland and Lynn).
=> hotfix(TimetableController): schedules can add new stops

README.md, bin/validate_fixtures.exs, config/runtime.exs, integration/health_checks/cms.js
https://app.asana.com/0/555089885850811/1207215129124865/f
Devops PR: https://github.com/mbta/devops/pull/1794
=> Remove unused env vars

lib/dotcom_web/controllers/schedule/timetable_controller.ex
**Asana Ticket:** [Ferry timetable](https://app.asana.com/0/555089885850811/1207363144361787/f) (continued)
Added custom sorting per stakeholder request. I don't _like_ hardcoding this, but there's no coherent way to piece together the stops-from-route-patterns to achieve the desired result.
=> feat(TimetableController): custom sort for ferries

lib/dotcom_web/controllers/schedule_controller.ex, lib/dotcom_web/router.ex
https://app.asana.com/0/555089885850811/1207382989831415
=> Redirect to external site

lib/alerts/cache/bus_stop_change_s3.ex, lib/dotcom_web/controllers/bus_stop_change_controller.ex, lib/dotcom_web/controllers/places_controller.ex, lib/dotcom_web/controllers/schedule/hours_controller.ex, lib/predictions/predictions_pub_sub.ex
https://app.asana.com/0/555089885850811/1207362707973005/f
=> Replace with with case

lib/dotcom_web/controllers/schedule/line_api.ex
https://app.asana.com/0/555089885850811/1207393006396493/f
=> Fallback when bad params are passed

lib/dotcom_web/controllers/schedule/timetable_controller.ex
Needed to accommodate next weekend's Needham Line's rail replacement bus which has a stop at Newton Highlands, at the very start of the route. The current shuttle stop placement logic was inadequate for this, as it assumed an existing stop _before_ the inserted stop. This PR enhances the logic by allowing specification of whether the shuttle stop is before or after a reference stop.
Made a minor correction for Anderson/Woburn while here. Other checks seem to come out ok.
=> feat(TimetableController): advanced override placement

lib/mbta/api.ex, lib/mbta/api/route_patterns.ex, lib/mbta/api/routes.ex, lib/mbta/api/services.ex, lib/mbta/api/shapes.ex, lib/mbta/api/stops.ex, lib/mbta/api/trips.ex, test/dotcom_web/controllers/trip_plan_controller_test.exs, test/mbta/api/route_patterns_test.exs, test/mbta/api/routes_test.exs, test/mbta/api/services_test.exs
No ticket, I noticed `Stops.Repo.get("")` returned a stop result and realized something needs fixing. For certain functions where we construct a URL, a value of `""` as our ID value risks producing an undesired result by, say, requesting `/stops/` instead of `/stops/123`. I wrote a guard function and applied it to the handful of places this would impact our usage of the V3 API.
---
=> feat(MBTA.Api): guard checking type and length

lib/algolia/request.ex, lib/dotcom_web/controllers/fare_controller.ex, test/algolia/request_test.exs
https://app.asana.com/0/555089885850811/1207362707973001
Snake Case Variable Names on Elixir
=> fix(Credo): Snake Case variable names

lib/alerts/cache/bus_stop_change_s3.ex, lib/algolia/query.ex, lib/cms/repo.ex, lib/dotcom_web/controllers/bus_stop_change_controller.ex, lib/dotcom_web/controllers/customer_support_controller.ex, lib/dotcom_web/controllers/places_controller.ex, lib/dotcom_web/stats.ex, lib/dotcom_web/views/customer_support_view.ex, lib/dotcom_web/views/page_view.ex, lib/green_line.ex, lib/mix/tasks/header_footer.ex, lib/predictions/store.ex, lib/req/stats.ex, lib/routes/mock_repo_api.ex, test/predictions/predictions_pub_sub_test.exs, test/support/conn_case.ex
https://app.asana.com/0/555089885850811/1207362707973009
Removed parentheses on functions with no arguments
=> cleanup(Credo): Remove parentheses from functions with no arguments

assets/ts/helpers/__tests__/departureInfoTest.tsx, assets/ts/helpers/departureInfo.tsx, assets/ts/stop/__tests__/components/DepartureTimesTest.tsx
https://app.asana.com/0/555089885850811/1207481893303699/f
=> predictions working

lib/dotcom/schedule_note.ex
Update the schedule note to match the summer rating
https://app.asana.com/0/555089885850811/1205890488165645
=> feat(ScheduleNote): Update the schedule note for the summer rating

lib/alerts/historical_alert.ex, lib/predictions/stream.ex
https://app.asana.com/0/555089885850811/1207647461641375/f
Closes out all `mix credo suggest --checks refactor`
=> Fix filter, filter and unnecessary use of apply

assets/ts/schedule/components/line-diagram/StopCard.tsx, assets/ts/schedule/components/line-diagram/__tests__/StopCardTest.tsx
https://app.asana.com/0/385363666817452/1207552218540036
Hide upcoming alert icon for upcoming alerts on the schedule page
=> feat(StopCards): Hide alerts that are upcoming

lib/dotcom_web/controllers/schedule/finder_api.ex
https://app.asana.com/0/385363666817452/1207393279013656
Sentry fix to handle bad params for the departures
=> fix(FinderApi): Handle bad params for the departures

assets/css/_icons.scss, assets/ts/schedule/components/schedule-finder/upcoming-departures/UpcomingDepartures.tsx, priv/static/icon-svg/icon-live-clock.svg
https://app.asana.com/0/555089885850811/1207383887369399
Remove clock icon
=> feat(UpcomingDepartures): Remove clock from live header

config/runtime.exs, lib/dotcom_web/router.ex
Re-Adding the CSP with more resources covered
https://app.asana.com/0/555089885850811/1207405407228256
=> feat(ContentSecurityPolicy): Add a content security policy (#2094)

lib/location_service/location_service.ex, test/location_service/location_service_test.exs
=> Filter location autocomplete results by USA and appropriate states

assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx
Increasing the rate so we can increase signups
=> Show to 100% of users with iphone

lib/dotcom/trip_plan/itinerary_row.ex, test/dotcom/trip_plan/itinerary_row_test.exs, test/dotcom_web/views/trip_plan_view_test.exs
https://app.asana.com/0/555089885850811/1207815145058284/f
=> Use long name for non agency routes too

lib/dotcom_web/templates/trip_plan/_itinerary.html.eex
https://app.asana.com/0/555089885850811/1207855317993512/f
=> When the destination has an id, render it as a link

config/runtime.exs, lib/dotcom_web/router.ex
https://app.asana.com/0/555089885850811/1207847119534941/f
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/connect-src
```
Note: connect-src 'self' does not resolve to websocket schemes in all browsers, more info in this [issue](https://github.com/w3c/webappsec-csp/issues/7).
```
=> Added websockets to prod content security policy

lib/dotcom/trip_plan/itinerary_row.ex
https://app.asana.com/0/555089885850811/1208022428056416/f
=> Use short name for bus in trip plan descriptions

assets/ts/schedule/components/__schedule.d.ts, lib/dotcom/schedule_note.ex, test/dotcom/lib/schedule_note_test.exs
https://app.asana.com/0/555089885850811/1205890385667025/f
=> Rearrange struct keys and update schedule

lib/dotcom_web/templates/trip_plan/_leg_summary.html.heex, test/dotcom_web/views/trip_plan_view_test.exs
https://app.asana.com/0/555089885850811/1208022428056403/f
=> Add train number

assets/js/trip-planner-form.js
https://app.asana.com/0/555089885850811/1207812778572977/f
=> Set default time to nearest 5 minutes

assets/css/app.scss
No ticket, just noticed that there are style issues with the new tailwind css.
=> Move tw up and override focus style

assets/js/app.js, assets/js/mobile-app-banner.js, lib/dotcom_web/templates/layout/root.html.eex
https://app.asana.com/0/555089885850811/1208403042873980/f
Took the approach of adding the HTML to every page, hiding it by default, and then showing it if the conditionals were true.
=> Show mobile app banner

assets/ts/__v3api.d.ts, assets/ts/components/Alerts.tsx
**Asana Ticket:** [Add associated images to alerts on stop pages](https://app.asana.com/0/555089885850811/1208003447130078/f)
---
=>  fix: Add images to alerts that are rendered on react pages

lib/dotcom/map_helpers.ex
Replace some hard-coded links to files in the CMS with vanity URL's.
This will allow those images to auto-update if content updates them, without the website itself needing to be updated.
**Asana Ticket:** [Update map images, PDFS to point to vanity links](https://app.asana.com/0/555089885850811/1207760168590049/f)
---
=> feat: Replace hard-coded image links with vanity URL's

lib/dotcom_web/templates/layout/root.html.eex
Remove negative margin from the mobile app banner, since that was making the banner hang off the edge of the screen.
---
=> fix: Remove negative margin from mobile app banner

AUTHORS
Adds Josh to the AUTHORS file.
No UI changes expected.
---
=> author: Add Josh to AUTHORS file

lib/dotcom_web/components/trip_planner/itinerary_group.ex, test/dotcom/trip_plan/itinerary_group_test.exs
https://app.asana.com/0/555089885850811/1208448201690703/f
=> Show alternative times and tests

config/runtime.exs
https://app.asana.com/0/555089885850811/1208600944175298/f
=> Add arcgis.com to the CSP

assets/ts/helpers/date.ts, assets/ts/stop/__tests__/DepartureListTest.tsx
https://app.asana.com/0/555089885850811/1208505215613679/f
=> Round predictions instead of flooring them

lib/dotcom/schedule_note.ex
**Asana Ticket:** [❄️ Dev | update schedule headways to match new rating](https://app.asana.com/0/555089885850811/1208827337326412/f)
---
=> feat: Update train schedule headways for Winter 2025 Rating

lib/dotcom_web/router.ex
**Asana Ticket:** [Redirect 117 pages to BNRD info page](https://app.asana.com/0/555089885850811/1208990226294678/f)
=> bnrd: add redirect for closed 117 route

lib/dotcom_web/controllers/schedule/timetable_controller.ex
=> chore(TimetableController): add busway stop to shuttle overrides

lib/dotcom_web/components/trip_planner/itinerary_summary.ex
=> cleanup: Replace if statement with :if directive in <.itinerary_summary />

lib/dotcom_web/components/trip_planner/transit_leg.ex
https://app.asana.com/0/555089885850811/1209140638282730/f
=> Fix missing bus line

lib/dotcom_web/live/trip_planner.ex
**Asana Ticket:** [TP Bugs | Inconsistency after using swap button](https://app.asana.com/0/385363666817452/1209230501426870/f)
Sometimes the solution lies in simplicity....
=> fix: simplify swap event & trigger input_form_change

assets/js/mobile-app-banner.js
turns out that matches most pages :)
=> fix(mobile-app-banner): remove not trip planner constraint

lib/dotcom_web/views/layout_view.ex
https://app.asana.com/0/555089885850811/1209272422683376/f
=> Change link text

lib/dotcom_web/templates/layout/root.html.eex
https://app.asana.com/0/555089885850811/1209151897411892/f
=> Remove the TP feedback banner

lib/dotcom/system_status/alerts.ex, lib/dotcom/system_status/subway.ex, test/dotcom/system_status/subway_test.exs
=> cleanup: Simplify module attributes in SystemStatus code and tests

lib/dotcom_web/router.ex
=> fix: Put system status preview back behind basic auth

lib/dotcom/system_status/subway.ex
Refactor to simplify some intermediate data in `Dotcom.SystemStatus.Subway`, and change some confusing names.
---
No ticket.
---
Depends on:
- #2347 
- #2381
=> cleanup: Remove branches_with_statuses and improve names

lib/schedules/parser.ex, lib/schedules/repo.ex, lib/schedules/schedule.ex, test/schedules/repo_test.exs
https://app.asana.com/0/555089885850811/1209276206078270/f
=> Get stop headsign values from schedules

lib/dotcom_web/controllers/schedule/timetable_controller.ex, test/dotcom_web/controllers/schedule/timetable_controller_test.exs
**Asana Ticket:** [SCR | Update "Via Fairmount line" message to match new train numbers](https://app.asana.com/0/555089885850811/1209144152994478)
Will show the "via Fairmount line" message for current and next rating's (after 3/24) trip numbers, visible on dev-green.
=> feat(TimetableController): support new rating trip messages

lib/location_service/address.ex
**Asana Ticket:** [ArgumentError: errors were found at the given arguments:](https://app.asana.com/0/555089885850811/1209702853813071/f) (links to [this Sentry issue](https://mbtace.sentry.io/issues/5872862606/events/5ef4b058d83d48ef8edc82b623b69831/))
It turns out `AddressUS.Parser.parse_address/1` isn't perfect, and completely breaks when given `"Rent Our Boxes, 6 Edgerly Place, Boston, MA, 02116, USA"` (which is one of the results AWS returns via searching for `'rent'` via `/places/search/rent/5`). This PR fixes that.
=> fix(LocationService.Address): improved label parsing

lib/dotcom_web/router.ex
**Asana Ticket:** [SCR | Redirect from CR-Middleborough to CR-NewBedford on 3/24/25](https://app.asana.com/0/555089885850811/1209206491597988/f)
---
Local: http://localhost:4001/schedules/CR-Middleborough
Prod: https://www.mbta.com/schedules/CR-Middleborough
Local: http://localhost:4001/schedules/CR-Middleborough/alerts
Prod: https://www.mbta.com/schedules/CR-Middleborough/alerts
---
Blocked by:
- https://github.com/mbta/dotcom/pull/2432
=> feat: Redirect CR-Middleborough to CR-NewBedford

assets/css/_schedule-direction.scss, assets/package.json, assets/ts/schedule/components/ScheduleDirection.tsx, assets/ts/schedule/components/__tests__/ScheduleDirectionTest.tsx, assets/ts/schedule/components/direction/BusMenu.tsx, assets/ts/schedule/components/direction/ScheduleDirectionMenu.tsx, assets/ts/schedule/components/direction/__tests__/BusMenuTest.tsx, assets/ts/schedule/components/direction/__tests__/__snapshots__/BusMenuTest.tsx.snap
https://app.asana.com/0/555089885850811/1209641407424367/f
=> Always show variants in dropdown

lib/dotcom/alerts.ex, lib/dotcom/alerts/subway.ex, test/dotcom/alerts/subway/disruptions_test.exs, test/dotcom/alerts/subway_test.exs, test/dotcom/alerts_test.exs, test/dotcom/system_status_test.exs, test/dotcom_web/components/system_status/subway_status_test.exs
https://app.asana.com/0/555089885850811/1209715928503652/f
=> Add service change to list of diversions if severity level greater than info

lib/dotcom/schedule_note.ex
**⚠️ Don't merge or deploy this until April 6 at the earliest**
**Asana Ticket:** [🌷 Dev | update schedule headways to match new rating](https://app.asana.com/0/555089885850811/1209336652481007/f)
=> feat: Update train schedule headways for Spring 2025 Rating

lib/dotcom_web/controllers/cms_controller.ex
https://app.asana.com/0/555089885850811/1209312811138607/f
=> Handle unfound pages with 404

lib/dotcom_web/controllers/schedule/line_api.ex
This should fix the fact that https://www.mbta.com/schedules/CR-Providence/line (and some other commuter rail line-diagram pages) aren't loading right now.
(Possibly supercedes https://github.com/mbta/dotcom/pull/2490)
---
No ticket.
=> hotfix: Only serve `other_route_stops` for bus routes

lib/schedules/sort.ex, test/schedules/sort_test.exs
https://app.asana.com/0/555089885850811/1209732356025278/f
=> Correctly order timetables

lib/dotcom/trip_plan/itinerary_groups.ex, test/dotcom/trip_plan/itinerary_groups_test.exs
- [Example Trip - Local](http://localhost:4001/trip-planner?plan=h8QVX3VudXNlZF9kYXRldGltZV90eXBlxADEEl91bnVzZWRfd2hlZWxjaGFpcsQAxAhkYXRldGltZcQZMjAyNS0wNC0wOVQxNzoyMDowMC0wNDowMMQNZGF0ZXRpbWVfdHlwZcQJYXJyaXZlX2J5xARmcm9thMQIbGF0aXR1ZGXEDzQyLjM1MTI5OTUwMDg1McQJbG9uZ2l0dWRlxBAtNzEuMDY3NzEzMzEyMzM0xARuYW1lxCIxMCBQYXJrIFBsLCBCb3N0b24sIE1BLCAwMjExNiwgVVNBxAdzdG9wX2lkxADEBW1vZGVzicQDQlVTxAR0cnVlxAVGRVJSWcQEdHJ1ZcQEUkFJTMQEdHJ1ZcQGU1VCV0FZxAR0cnVlxA5fcGVyc2lzdGVudF9pZMQBMMQLX3VudXNlZF9CVVPEAMQNX3VudXNlZF9GRVJSWcQAxAxfdW51c2VkX1JBSUzEAMQOX3VudXNlZF9TVUJXQVnEAMQCdG-ExAhsYXRpdHVkZcQKNDIuMzc1ODg3NMQJbG9uZ2l0dWRlxAstNzEuMDM4NjkxMsQEbmFtZcQ_Q2VudHJhbCBQYXJrIExhbmVzLCAxMCBTYXJhdG9nYSBTdCwgRWFzdCBCb3N0b24sIE1BLCAwMjEyOCwgVVNBxAdzdG9wX2lkxAA=)
- [Example Trip - …
=> fix(trip-planner): Show all possible routes in itinerary summary

lib/alerts/cache/fetcher.ex, test/alerts/cache/fetcher_test.exs
**Asana Ticket:** [Hide alert 636777 for the RL Ashmont Diamond disruption](https://app.asana.com/0/555089885850811/1209938689385280/f)
=> feat: Suppress a specific alert so that it doesn't show up anywhere

lib/dotcom_web/views/schedule_view.ex, test/dotcom_web/views/schedule_view_test.exs
Super simple.
https://app.asana.com/1/15492006741476/project/555089885850811/task/1209682019635461?focus=true
=> Downcase rating name

lib/dotcom_web/components/components.ex
https://app.asana.com/1/15492006741476/project/555089885850811/task/1209775659080578?focus=true
=> Alert count sizes on mobile

assets/ts/stop/components/amenities/AmenityCard.tsx, lib/dotcom_web/templates/cms/page/_diversions.html.eex, lib/dotcom_web/templates/cms/page/_page.html.eex, lib/dotcom_web/templates/mode/hub.html.eex, lib/dotcom_web/templates/schedule/_line_header.html.eex, test/dotcom_web/views/cms_view_test.exs
**Asana Ticket:** [Fix whitespace in H1 tags of CMS pages](https://app.asana.com/1/15492006741476/project/443102729541668/task/1209952731224339?focus=true)
SEO seems to be rejecting H1 contents due to carriage returns inside, caused by returns in the eex template. Moving to one line to remove whitespace and hopefully resolve issue of Google skipping H1 and using H2 contents for search results.
---
=> Remove whitespace from CMS page title H1

lib/journey_list.ex, test/journey_list_test.exs
**Asana Ticket:** [Fix schedule finder daily schedule to handle trips visiting the same stop multiple times](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210103449936938?focus=true)
It's a bit of a hack, but it works beautiful for the ferry case (as seen in the dev-green API data).
=> fix(JourneyList): don't overwrite schedule map entries with later schedules

lib/dotcom_web/templates/news_entry/show.html.eex
**Asana Ticket:** [Update default fields after press releases](https://app.asana.com/1/15492006741476/project/553506286097126/task/1210187480936083?focus=true)
---
=> text content updates to news entry footer

test/dotcom_web/controllers/mbta_go_feedback_controller_test.exs
=> fix(warnings): Remove unused `Test.Support.EnvHelpers` import

config/config.exs, config/test.exs, lib/dotcom/alerts/endpoint_stops.ex, lib/dotcom/alerts/endpoint_stops/behaviour.ex, lib/dotcom_web/components/system_status/status_label.ex, lib/dotcom_web/components/system_status/status_row_heading.ex, test/dotcom/alerts/endpoint_stops_test.exs, test/dotcom_web/components/planned_disruptions_test.exs, test/dotcom_web/components/system_status/subway_status_test.exs, test/dotcom_web/controllers/alert_controller_test.exs, test/support/mocks.ex
**Asana Subtask:** [[Endpoints] Add endpoints to system status and planned work](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210172306293799?focus=true)
**Asana Parent Ticket:** [Add endpoints of disruption to system status and planned work](https://app.asana.com/1/15492006741476/project/1205718271156548/task/1209641123314696?focus=true)
=> feat: Add endpoint stops to system status and planned work

lib/dotcom_web/components/system_status/status_row_heading.ex, test/dotcom_web/components/system_status/subway_status_test.exs
For this disruption:
Change the screen reader output from
```
"Orange Line Thu, May 29: Shuttles Jackson Square left-right-arrow Forest Hills"
```
to
```
"Orange Line Thu, May 29: Shuttles between Jackson Square and Forest Hills"
```
---
**Asana Ticket:** [QF | SS | Make endpoints read better on screenreaders](https://app.asana.com/1/15492006741476/project/385363666817452/task/1210402614532095?focus=true)
=> fix: Add aria label to endpoint-related subheadings

lib/dotcom_web/templates/news_entry/show.html.eex
**Asana Ticket:** [Update default fields after press releases](https://app.asana.com/1/15492006741476/project/553506286097126/task/1210187480936083?focus=true)
Adjust spacing for better readability using bootstrap utility classes. (revers the margins on this new, trailing paragraph)
BEFORE
AFTER
---
=> fixup! spacing / visual coherence on Media Contact block

lib/dotcom_web/templates/page/_find_a_location.html.eex, lib/dotcom_web/views/layout_view.ex
https://app.asana.com/1/15492006741476/project/555089885850811/task/1210316713180940?focus=true
=> Remove links to TNM

assets/css/_banner.scss
https://app.asana.com/1/15492006741476/project/385363666817452/task/1210451827267945?focus=true
=> Fix bottom margin of projects banner

assets/css/_timetable.scss
https://app.asana.com/1/15492006741476/project/555089885850811/task/1209646743059771?focus=true
Checked for Commuter Rail and Ferry across all widths.
=> Update widths for empty cells

assets/ts/models/alert.ts, assets/ts/stop/__tests__/components/amenities/BikeStorageAmenityCardTest.tsx, assets/ts/stop/__tests__/components/amenities/ParkingAmenityCardTest.tsx, assets/ts/stop/components/amenities/BikeStorageAmenityCard.tsx, assets/ts/stop/components/amenities/ParkingAmenityCard.tsx
https://app.asana.com/1/15492006741476/project/555089885850811/task/1208808770796970?focus=true
=> Filter out future alerts

lib/dotcom_web/templates/customer_support/_transit_police.html.eex, lib/dotcom_web/templates/layout/_new_nav_contact_numbers.html.eex, lib/dotcom_web/templates/layout/_new_nav_desktop.html.eex
https://app.asana.com/1/15492006741476/project/555089885850811/task/1210582061870711?focus=true
=> Change Transit Police phone

lib/dotcom_web/controllers/trip_plan_controller.ex, lib/dotcom_web/templates/fare/_nearby_locations.html.eex, test/dotcom_web/controllers/trip_plan_controller_test.exs
https://app.asana.com/1/15492006741476/project/555089885850811/task/1209332041135786?focus=true
Works from: https://dev-blue.mbtace.com/guides/get-outside-the-t
Works from: https://dev-blue.mbtace.com/fares/retail-sales-locations?address=10+Park+Plaza&latitude=42.351517603896&longitude=-71.066641738204
=> Handle lat,lon in from/to redirects

lib/dotcom_web/live/trip_planner.ex, test/dotcom_web/live/trip_planner_test.exs
This is so we can add `&locale=whatever` to the end of trip planner links and have it not get blasted away by the `AntiCorruptionLayer` tomfoolery.
=> fix(Live.TripPlanner): preserve additional params when encoding

lib/dotcom_web.ex, lib/dotcom_web/router.ex, lib/dotcom_web/templates/layout/app.html.eex, lib/dotcom_web/templates/layout/root.html.heex, priv/gettext/dotcom.pot, priv/gettext/es/LC_MESSAGES/dotcom.po
This is our first attempt at actually translating a few template files.
https://app.asana.com/1/15492006741476/project/1210709545912061/task/1210710191434522?focus=true
=> Translate the app and root layout templates

lib/dotcom_web/controllers/schedule/alerts_controller.ex
**Asana Ticket:** [Update CR, subway alerts summary + tab pages to avoid time filtering](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210732979952245?focus=true)
**Asana Subtask:** [Redirect /schedule/:route_id/alerts?alerts_timeframe=... to remove alerts_timeframe](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210893459312444?focus=true)
=> fix: Remove timeframe param from subway and CR schedule alerts pages

lib/dotcom_web/plugs/set_locale.ex, lib/dotcom_web/templates/layout/root.html.heex
**Asana Ticket:** [Add selected locale to HTML lang tag](https://app.asana.com/1/15492006741476/project/1210709545912061/task/1210862304119976?focus=true)
=> fix: use selected locale for lang attribute

.dialyzer_ignore.exs, lib/dotcom_web/controllers/fare_controller.ex
No ticket, but it sure is great to make Dialyzer happy!
=> fix: Alias Plug.Conn in FareController to fix Dialyzer error

.dialyzer_ignore.exs, lib/dotcom_web/controllers/search_controller.ex
=> fix: Typespec syntax error in SearchController

lib/dotcom_web/controllers/project_controller.ex, lib/dotcom_web/controllers/search_controller.ex, lib/dotcom_web/controllers/vote_controller.ex, lib/dotcom_web/live/usage.ex, priv/gettext/dotcom.pot, priv/gettext/es/LC_MESSAGES/dotcom.po
**Asana Ticket:** [DotcomWeb.ProjectController](https://app.asana.com/1/15492006741476/project/1210709545912061/task/1210709781286098?focus=true)
**Asana Ticket:** [DotcomWeb.SearchController](https://app.asana.com/1/15492006741476/project/1210709545912061/task/1210709781286100?focus=true)
**Asana Ticket:** [DotcomWeb.VoteController](https://app.asana.com/1/15492006741476/project/1210709545912061/task/1210709781286104?focus=true)
=> translation: vote, search, project controllers

lib/dotcom/content_rewriters/liquid_objects/fare.ex, lib/dotcom_web/templates/cms/paragraph/_fare_card.html.heex, lib/fares/fare.ex, lib/fares/fare_info.ex, priv/gettext/dotcom.pot, priv/gettext/es/LC_MESSAGES/dotcom.po, test/dotcom/content_rewriters/liquid_objects/fare_test.exs, test/dotcom_web/views/helpers_test.exs
(Before on the left; After on the right)
*Note: In order to see the change locally, you need to bust the cache. It's quite possible that we'll also need to do that in prod when we release this if we want it to be visible promptly.*
[Prod](https://www.mbta.com/); [Local](http://localhost:4001/)
[Prod](https://www.mbta.com/fares); [Local](http://localhost:4001/fares)
[Prod](https://www.mbta.com/schedules/ferry); [Local](http://localhost:4001/schedules/ferry)
[Prod](https://www.mbta.com/fares/ferry-fares); [Local](http://localhost:4001/fares/ferry-fares)
**Asana Ticket:** [Release on/after 8/1 | Update ferry payment methods to include contactless](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210813232481005?focus=true)
=> feat: Include contactless payment as a ferry payment type

test/dotcom/cache/inspector/publisher_test.exs
=> fix: Make sure different values are different in test

lib/dotcom_web/router.ex
https://app.asana.com/1/15492006741476/project/555089885850811/task/1210812969411073?focus=true
=> Redirect /schedules/627/*

assets/ts/__v3api.d.ts, assets/ts/jest.config.js, assets/ts/schedule/components/RapidTransitHoursOfOperation.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/DailyScheduleSubway.tsx, assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/DailyScheduleSubwayTest.tsx, lib/schedules/hours_of_operation.ex, test/schedules/hours_of_operation_test.exs
https://app.asana.com/1/15492006741476/project/555089885850811/task/1211137160631903?focus=true
=> Add Friday schedules to schedule finder

lib/dotcom_web/templates/alert/_item.html.heex
https://app.asana.com/1/15492006741476/project/555089885850811/task/1210989758929009?focus=true
=> Allow alert expansion with images

lib/dotcom_web/live/trip_planner.ex, priv/gettext/dotcom.pot, priv/gettext/es/LC_MESSAGES/dotcom.po
**Asana Ticket:** [DotcomWeb.Live.TripPlanner](https://app.asana.com/1/15492006741476/project/555089885850811/task/1210709781286142?focus=true)
=> translate(DotcomWeb.Live.TripPlanner)

lib/dotcom_web/plugs/cookies.ex, lib/dotcom_web/templates/alert/_banner.html.heex, lib/dotcom_web/templates/alert/_item.html.heex, lib/feedback/mailer.ex, lib/telemetry/helper.ex
No ticket, just noticed this command was a thing now
=> chore: run mix format --migrate

lib/dotcom/trip_plan/open_trip_planner.ex
Loops are broken. This just removes the call to merge them until we figure out what is wrong.
=> Remove call to merge

lib/dotcom_web/components/system_status/status_row_heading.ex, priv/gettext/dotcom.pot, priv/gettext/es/LC_MESSAGES/dotcom.po
https://app.asana.com/1/15492006741476/project/555089885850811/task/1210709781286124?focus=true
=> Translate status row heading

lib/dotcom_web/components/components.ex, lib/dotcom_web/templates/mode/hub.html.heex, lib/dotcom_web/templates/schedule/show.html.heex, priv/gettext/dotcom.pot, priv/gettext/es/LC_MESSAGES/dotcom.po
**Asana Ticket:** [Stand up banners for CR survey](https://app.asana.com/1/15492006741476/project/385363666817452/task/1211453626386948?focus=true)
=> feat(Components): CR survey banner
