mbta/dotcom

apps/site/lib/predicted_schedule.ex, apps/site/lib/site/transit_near_me.ex, apps/site/lib/site_web/controllers/stop_controller.ex, apps/site/test/site/transit_near_me_test.exs, apps/site/test/site_web/controllers/transit_near_me/stops_with_routes_test.exs, apps/site/test/site_web/controllers/transit_near_me_controller_test.exs
Updates the TransitNearMe methods to use PredictedSchedule to match schedules with predictions, which is generally more reliable.
<br>
=> use PredictedSchedule in TNM

apps/site/lib/site/content_rewriters/liquid_objects/fare.ex, apps/site/test/site/content_rewriters/liquid_objects/fare_test.exs
**Asana Ticket:** [Add CR Zones to Liquid Fare Replacement](https://app.asana.com/0/555089885850811/794989287876740)
Adds `zone:x` and `interzone:x` tokens to replacement system. Prices will use `cash` amount unless otherwise specified.
=> CR zone replacements

apps/schedules/test/repo_test.exs, apps/site/test/site/lib/vehicle_helpers_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs, apps/site/test/site_web/controllers/schedule/origin_destination_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/controllers/stop_controller_test.exs, apps/stops/test/api_test.exs, apps/stops/test/nearby_test.exs, apps/stops/test/repo_test.exs
Fix tests that failed due to some `Stop.id` changes in upstream GTFS / API.
<br>
=> fix tests with references to old stop ids

apps/site/lib/site_web/controllers/schedule/green.ex, apps/site/lib/site_web/controllers/schedule/line_controller.ex
**Asana Ticket:** [⏱ Schedules | /schedules/Green is not rendering React components](https://app.asana.com/0/477545582537986/1123858331590598/f)
Green line has it's own schedule-line controller because the data processing is significantly different than other routes. The React components were not showing on the Green page because `schedule_page_data` was not being assigned with all data values.
<br>
=> assign schedule_page_data in green line controller

apps/site/lib/site/transit_near_me.ex
Predictions sometimes don't have times, which causes the `Timex.diff` function to raise.
<br>
=> handle nil prediction time in TNM

apps/site/lib/site_web/views/page_view.ex
**Asana Ticket:** [⭐ Homepage Commuter Rail Lines icon link wrong URL](https://app.asana.com/0/555089885850811/1112126309976758)
<br>
=> don't redirect commuter_rail on homepage

apps/site/lib/site_web/templates/schedule/_line.html.eex
**Asana Ticket:** [⏱Schedules | Accordions - Connections](https://app.asana.com/0/555089885850811/1118913618186294)
Moves old connection list so that it's not shown with react content
<br>
=> don't render old connections template on new line page

apps/site/lib/site_web/views/content_view.ex, apps/site/test/site_web/views/content_view_test.exs
**Asana Ticket:** [⭐ Event time format should match content style guide](https://app.asana.com/0/555089885850811/1116681773922428)
<br>
=> use style guide time format for events

apps/site/assets/css/_stop-bubbles.scss, apps/site/lib/site_web/templates/schedule/_line_page_stop_info.html.eex, apps/site/lib/site_web/templates/schedule/_line_page_stop_prediction.html.eex, apps/site/lib/site_web/templates/schedule/_line_page_stop_prediction_cr.html.eex
**Asana Ticket:** [⏱ Schedules | Add ellipsis to long headsign names](https://app.asana.com/0/477545582537986/1124353435273956/f)
- This change has no effect to most headsigns, but now longer ones will not wrap.
- removed zone tag for all modes except CR
<br>
=> Add ellipsis to long headsign names

apps/site/assets/ts/leaflet/__tests__/icon-test.ts, apps/site/assets/ts/leaflet/icon.ts
Allow any one of the options to be provided, use default values when others are not.
Discovered this when looking at the commuter rail tooltips. The updates on the schedule page don't provide an icon anchor, so it was set as undefined and leaflet was throwing a console error when you tried to open a tooltip.
<br>
=> Fix schedule page tooltip having undefined anchor

apps/site/lib/site_web/templates/layout/_alert_announcement.html.eex
**Asana Ticket:** [🚒 Website Alert Banner - Use banner text field](https://app.asana.com/0/555089885850811/1126432560732675)
Previously, we had a separate struct for banners, which had different keys from the normal `%Alert{}` struct. When we redesigned the alerts page, we stopped using that banner struct directly -- we still kept it but we were only using it to store the ID of the alert it represented. The alert was parsed as a normal alert, and so it kept the text from the `header` attribute -- but banners are supposed to use the text from the `banner` attribute.
This refactor removes the `Banner` struct entirely, and updates how we select text for the `header` field for alerts. We store only the ID of the banner alert in the repo instead of storing the full alert separately.
<br> …
=> standardize alert banner parsing

apps/predictions/test/repo_test.exs
Red line is struggling today, and this test is failing because there are no predictions more than an hour away. This shift doesn't need to be so large for this test to be valid.
<br>
Assigned to: @name
=> shorten min_time shift in prediction test

apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/schedule/__tests__/ScheduleFinderTest.tsx, apps/site/assets/ts/schedule/__tests__/SchedulePageTest.tsx, apps/site/assets/ts/schedule/components/ScheduleFinder.tsx, apps/site/assets/ts/schedule/components/SchedulePage.tsx, apps/site/assets/ts/schedule/components/__schedule.d.ts, apps/site/lib/site_web/controllers/schedule/line_controller.ex
**Asana Ticket:** [⏱Schedules | Input box - Submit button opens schedule modal](https://app.asana.com/0/555089885850811/1122431599573151)
Adds a formatted header to the schedule finder modal.
<br>
=> add header to schedule finder modal

apps/site/assets/ts/leaflet/__tests__/MapTest.tsx, apps/site/assets/ts/leaflet/components/Map.tsx
**Asana Ticket:** [🔍 OpenStreetMaps | Map zoom reset](https://app.asana.com/0/555089885850811/1125936468243528)
Saves map zoom as state, so that the zoom does not get reset every time a vehicle location is updated.
<br>
=> save map zoom as state

apps/site/lib/site_web/templates/fare/_summary.html.eex, apps/site/lib/site_web/templates/layout/_desktop_menu_contact_us.html.eex, apps/site/lib/site_web/templates/layout/_desktop_menu_fares.html.eex, apps/site/lib/site_web/templates/layout/_desktop_menu_getting_around.html.eex, apps/site/lib/site_web/templates/layout/_desktop_menu_more.html.eex, apps/site/lib/site_web/views/fare_view.ex
**Asana Ticket:** [🔷 Tag Manager | Identify SubMenu Items](https://app.asana.com/0/555089885850811/1125801130709062)
Adds a class to every sub-link inside of the main navigation containers to enable us to track clicks in Google Analytics.
<br>
=> add google analytics class to nav sublinks

apps/site/assets/ts/stop/__tests__/sidebar/ParkingTest.tsx, apps/site/assets/ts/stop/components/sidebar/Parking.tsx
**Asana Ticket:** [🐞🚗 Station pages *sometimes* pull wrong parking data](https://app.asana.com/0/555089885850811/1122296944502350)
We were doing an unnecessary extra calculation to determine whether to show a note about arriving early for station parking. This changes to logic to simply show what the API gives us.
<br>
=> don't do extra calculation for parking note

apps/site/test/detailed_stop_group_test.exs, apps/site/test/site_web/controllers/stop_controller_test.exs
NO TICKET
fix some test fails that occurred after recent GTFS changes.
- inclusion of new CR-SouthShoreLtd route
- remove a reference to a decommissioned child stop
<br>
=> test fixes related to inclusion of SSR CR route

apps/site/test/site/trip_plan/related_link_test.exs
this trip id now includes a character that needs to be encoded
<br>
=> encode trip ids in test

apps/site/assets/css/core.scss, apps/site/lib/site_web/templates/layout/_alert_announcement.html.eex
**Asana Ticket:** [⭐ Alert Banner | Links look like plain text](https://app.asana.com/0/555089885850811/1126696422778125)
There were two problems causing this issue:
- it is not valid to nest and `a` tag inside another `a` tag
- there were styles intended for the outer tag that were being applied to the inner tag
<br>
=> show links in alert banner

apps/site/test/site/trip_plan/related_link_test.exs
`URI.encode` doesn't encode colons, so we have to replace it manually for this test to pass.
<br>
=> encode : in trip id test

apps/site/lib/site/transit_near_me.ex, apps/site/lib/site_web/controllers/transit_near_me_controller.ex, apps/site/load_tests/locustfile.py, apps/site/test/site_web/controllers/transit_near_me_controller_test.exs
**Asana Ticket:** [🔧 'Dotcom Error - Latency Too High' was triggered.](https://app.asana.com/0/555089885850811/910872860359331)
Handles timeouts without crashing; also updates the load tests since we turned off the flag on transit-near-me.
<br>
=> handle timeouts in TransitNearMe

apps/site/lib/site_web/views/content_view.ex, apps/site/test/site_web/views/content_view_test.exs
**Asana Ticket:** [🐞  Hide entire Content List ¶ if list of content is empty](https://app.asana.com/0/555089885850811/1122465604344968)
Prevents header of description lists from being rendered if the list has no contents.
<br>
=> don't render empty description lists

apps/site/assets/ts/leaflet/components/Map.tsx, apps/site/assets/ts/tnm/components/leaflet/MarkerWrapper.tsx
**Asana Ticket:** [♿  Map captures tab on schedule line page](https://app.asana.com/0/555089885850811/1126862660664679)
Prevents markers from being selectable by tabbing.
<br>
=> add keyboard:false to map markers

apps/site/lib/site_web/controllers/schedule/timetable_controller.ex
**Asana Ticket:** [🐞 'via lowell' and 'via haverhill' missing on CR timetable](https://app.asana.com/0/555089885850811/1126468415631687)
The `via` messages stopped working because they were using child stop ids, which no longer match our data. Updated to use parent stop ids.
<br>
=> use parent stop ids for via messages

apps/google_maps/lib/google_maps/place/prediction.ex
**Asana Ticket:** [Fix error w/ Google Places API](https://app.asana.com/0/555089885850811/1128769227442731)
This issue was clogging up our Sentry error log.
It seems that Google Places API is not always providing the `id` attribute. We weren't using this attribute, so I removed it from the struct altogether so it no longer matters if they provide it or not.
<br>
=> fix Google Places place parser

apps/site/lib/site_web/controllers/schedule/line_controller.ex
NO TICKET
This call was resulting in some crashes on dev/dev-green so I just want to remove this so it doesn't sneak into a deploy next week.  Also, we are not using this yet, so it is harmless to remove it for now.
@meagonqz
=> remove call to services.repo

apps/predictions/test/repo_test.exs, apps/site/lib/site/map_helpers.ex, apps/site/test/site/lib/react_test.exs, apps/site/test/site/map_helpers_test.exs, apps/site/test/site/transit_near_me_test.exs, apps/site/test/site_web/controllers/schedule/green_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs
**Asana Ticket:** [💲New fares | Update map targets](https://app.asana.com/0/555089885850811/1129270878312734)
- some tests were changed late last night to get a build to pass in CI, those changes are reverted here
- use vanity URLs for map PDFs so content can manage this fully without requiring code changes when maps are updated
<br>
=> Update URLs in map helper, remove temporary test changes

apps/route_patterns/.formatter.exs, apps/route_patterns/.gitignore, apps/route_patterns/README.md, apps/route_patterns/config/config.exs, apps/route_patterns/lib/application.ex, apps/route_patterns/lib/repo.ex, apps/route_patterns/lib/route_pattern.ex, apps/route_patterns/lib/route_patterns.ex, apps/route_patterns/mix.exs, apps/route_patterns/test/repo_test.exs, apps/route_patterns/test/route_patterns_test.exs, apps/route_patterns/test/test_helper.exs, apps/v3_api/lib/route_patterns.ex
**Asana Ticket:** support for [TICKET_NAME](https://app.asana.com/0/555089885850811/1127979261717805)
Adds a RoutePatterns app for fetching route patterns. Will be used by the route variation dropdown on the schedule page.
<br>
=> add route_patterns app

apps/site/lib/site/map_helpers.ex, apps/site/test/site/map_helpers_test.exs
Fix map URLS
I tested this locally to be sure and it's working with the vanity url -> redirect to static path.
<br>
Assigned to: @aayesha
=> Mh fixup maps

apps/site/assets/js/cookies.js, apps/site/assets/js/test/cookies_test.js
I ran into this issue running the Wallaby tests. I didn't have any cookies,
so this lookup crashed each test.
We also don't need to build the hash: once we've found the key we're looking
for we can stop.
<br>
=> feat: don't crash when there are no cookies

apps/site/lib/predicted_schedule.ex, apps/site/lib/site/transit_near_me.ex, apps/site/test/site/transit_near_me_test.exs, apps/site/test/site_web/controllers/transit_near_me/stops_with_routes_test.exs
Some quick code improvements to speed up Transit Near Me.
Some future work would also be filtering the fetched predictions based on the `route_type` Predictions filter, but I don't understand the TNM code well enough to do that yet.
Testing script:
`ab -c 5 -n 10 'http://localhost:4001/transit-near-me/api?from=search-route--bus&query=Bank%20of%20America%20Financial%20Center%2C%20Washington%20Street%2C%20Boston%2C%20MA%2C%20USA&location[latitude]=42.352191&location[longitude]=-71.06252239999999&location[address]=Bank%20of%20America%20Financial%20Center%2C%20Washington%20Street%2C%20Boston%2C%20MA%2C%20USA&filter=bus'`
before:
```
Percentage of the requests served within a certain time (ms)
50%   3400
66%   3465
75%   3481
80%   3506
90%   3534
95%   3534
98%   3534
99%   3534
100%   3534 …
```
=> speed up Transit Near Me

apps/site/mix.exs
**Asana Ticket:** [Look into schedule 500 error on dev](https://app.asana.com/0/555089885850811/1130522906709257)
The application build is crashing because `:route_patterns` was never added as a dependency to the `:site` application after the modules were referenced.
A similar issue happened recently with the `:services` application.
<br>
=> make :route_patterns a dependency of :site app

apps/content/lib/cms/http_client.ex, apps/content/test/cms/http_client_test.exs
**Asana Ticket:** [AFC 2.0 Charlie | TNM vanity and UTM params](https://app.asana.com/0/555089885850811/1122614077520942)
[Please include a brief description of what was changed]
When the CMS API calls `view/2` on a Drupal path that is actually a redirect, we lost some of the params (both top-level and nested) due to the redirect using a Map and Strings vs. a List and Atoms to define the params.
This PR adds clauses and guards for redirects where the params are in this alternate format, and continues to sanitize nested and non-nested params.
I've also confirmed the CMS merges normal params from the request with those of the redirect location (it just had trouble with nested param format).
**Test Link** (note: connect to the live CMS when testing): …
=> Keep redirect [sub] params [if whitelisted]

apps/predictions/lib/repo.ex
**Asana Ticket:** [🔧 Performance: Log cache/hit ratio for predictions repo](https://app.asana.com/0/555089885850811/1129115952715485)
Added two log messages. One gets logged every time `Predictions.Repo.all` gets called, the other gets logged only when that function has a cache miss. From this, we can calculate our cache miss (or hit) ratio via Splunk.
<br>
=> Log messages to calculate predictions cache miss ratio

apps/site/lib/site_web/templates/project/show.html.eex, apps/site/test/site_web/views/project_view_test.exs
**Asana Ticket:** [Project pages | Remove "About the project" H1 from template](https://app.asana.com/0/555089885850811/1128553720328271)
Self-explanatory.
=> Remove hard-coded H2 from project template

apps/site/lib/site_web/controllers/event_controller.ex, apps/site/lib/site_web/controllers/project_controller.ex, apps/site/lib/site_web/templates/event/_event_list.html.eex, apps/site/lib/site_web/views/teaser_view.ex, apps/site/test/site_web/controllers/project_controller_test.exs, apps/site/test/site_web/views/project_view_test.exs
**Asana Ticket:** [Use teaser request for Events](https://app.asana.com/0/555089885850811/958950737688914)
- dependent on #84 
- make event times naive once parsed to avoid double TZ shift
- we only have the start time at the moment, not the whole range
=> Use Repo.teasers for event index

apps/site/lib/site_web/controllers/project_controller.ex, apps/site/lib/site_web/templates/project/show.html.eex, apps/site/test/site_web/views/project_view_test.exs
**Asana Ticket:** [Remove hard-coded project sidebar](https://app.asana.com/0/555089885850811/1117410708814904)
When paragraphs are present, don't use the hard-coded sidebar; use the dynamic sidebar that generic pages use (includes ordered paragraphs of content lists).
- added comments
- simplified if/then logic/conditions
=> If ¶s are present, use dynamic sidebar content

apps/feedback/config/config.exs, apps/feedback/config/test.exs, apps/feedback/lib/fake_date_time.ex, apps/feedback/lib/mailer.ex, apps/feedback/test/mailer_test.exs
**Asana Ticket:** [ℹ️ Contact Us | Current Date and Time](https://app.asana.com/0/555089885850811/1129241877448150)
Messages to HEAT should make use of the `INCIDENTDATE` field, filling it in with a UTC timestamp in 24-hour format.
<br>
=> Include current date/time in HEAT messages

apps/site/assets/ts/schedule/schedule-loader.tsx
**Asana Ticket:** [🔧 Invariant Violation: Target container is not a DOM element.](https://app.asana.com/0/555089885850811/1131943808986522)
The root element for the new schedule loader stuff was only rendered if the direction-redesign flag was set, but the React code itself runs whether or not the flag is set, so that caused an error when the flag was unset. Fixed.
<br>
=> Only use new schedule loader if root element present

apps/site/assets/css/_variables.scss
**Asana Ticket:** [🐞 Trip Planner | map renders on top of nav dropdown](https://app.asana.com/0/555089885850811/1130270846783244)
Change `z-index` of desktop menu to ensure it is higher than leaflet `z-index`.
---
<br>
=> ensure desktop menu z-index above map

apps/site/lib/site_web/views/content_view.ex, apps/site/test/site_web/views/content_view_test.exs
**Asana Ticket:** [Hide entire Content List ¶ if list of content is empty](https://app.asana.com/0/477545582537986/1122465604344968/f)
Render NOTHING if **content list** has **no teaser results**
- Fixes #54 (wrong paragraph type / logic)
=> Corrected fix for empty content lists

apps/site/lib/site_web/controllers/schedule/schedule_api.ex
**Asana Ticket:** [🐞 Schedules | Saturday schedules appear to have incorrect time ranges for service](https://app.asana.com/0/555089885850811/1131960756153348)
`Enum.sort_by` with a DateTime was putting 09/01 before 08/31. I looked into the list of schedules and they are already in order by time, so I removed the sort.
```
pry(1)> a = [List.first(services), List.last(services)] |> Enum.sort_by(& &1.time)
[
%Schedules.Schedule{
early_departure?: false,
flag?: false,
last_stop?: true,
pickup_type: 1,
route: ...,
stop: ...,
stop_sequence: 4,
time: #DateTime<2019-09-01 01:01:00-04:00 -04 Etc/GMT+4>,
trip: %Schedules.Trip{
bikes_allowed?: true,
direction_id: 0,
headsign: "Silver Line Way",
id: "40673166",
name: "",
shape_id: "7460007"
}
},
%Schedules.Schedule{
early_departure?: false,
flag?: …
```
=> Schedules | Fix sorting for Saturday service

apps/site/assets/ts/schedule/components/Map.tsx
**Asana Ticket:** [🔍 OpenStreetMaps | Map zoom reset](https://app.asana.com/0/555089885850811/1125936468243528)
We were calculating the bounds based on the markers and since the markers are live updated, it would sometimes change the bounds if the markers changed enough in position on the map.
This sets the bound to whatever the initial bounds are from the initial markers. It doesn't update the bounds when vehicles move or are added/removed from the map.
<br>
=> OpenStreetMaps | Map zoom reset

apps/site/assets/ts/schedule/__tests__/ScheduleTableTest.tsx, apps/site/assets/ts/schedule/__tests__/ServiceSelectorTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleTableTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx, apps/site/lib/site_web/controllers/schedule/schedule_api.ex, apps/site/test/site_web/controllers/schedule/schedule_api_test.exs
**Asana Ticket:** [⏱Schedules | 🐞 Finder Tool - Trip details are incorrect](https://app.asana.com/0/555089885850811/1132361826199925)
Prune the schedules so that they are not the full trip but only the section of the trip from the selected origin.
It doesn't seem like there's an efficient way to query this from the api so I pruned the schedules after we request them.
<br>
=> Schedule Finder | Trip details from the selected origin

apps/site/lib/site_web/templates/schedule/_trip_info.html.eex
**Asana Ticket:** [Fares | 404 on "View fares" link from Schedule pages](https://app.asana.com/0/555089885850811/1131253174031033)
"View fares" link on the current page goes to the cms static pages as requested in the ticket. We'll be replacing this page soon enough so I didn't get too fancy.
<br>
=> Fix View Fares link on current schedule page

apps/content/lib/cms/static.ex, apps/content/lib/paragraph/content_list.ex, apps/site/lib/site_web/templates/content/_content_list.html.eex, apps/site/lib/site_web/templates/content/_teaser_list.html.eex, apps/site/lib/site_web/views/content_view.ex, apps/site/lib/site_web/views/teaser_view.ex, apps/site/test/site_web/views/content_view_test.exs
**Asana Ticket:** [Automatically add "View More" link to content lists](https://app.asana.com/0/555089885850811/1117410708814919)
**NOTE:** Depends on mbta/cms#283
Since we are no longer hard-coding sidebar lists like Project Updates and they now come direct from the CMS, we can parse new CTA-related fields from this paragraph type to generate a relevant "View all..." link below the list of teasers.
Authors are also able to override this behavior by either hiding the CTA all together, or overriding either or both the CTA text or CTA url.
This makes content lists much more powerful for teasing a subset of content that lives elsewhere on the website (or even on an external website).
=> Intelligent / overridable Content List CTAs

apps/site/lib/site_web/templates/schedule/_timetable_schedule.html.eex
**Asana Ticket:** [♿  CR Timetable | Add stop name to aria labels](https://app.asana.com/0/555089885850811/1130340429843891)
Added the stop name into the screen-reader only time wording of the CR timetable. The ticked mentions the train number, but that is already being read as it is the row header.
<br>
=> CR Timetable | add stop name to aria lable for each time

apps/site/config/config.exs
Tests were failing because `old.mbta.com` now expects to be called over `https`.
<br>
=> Legacy Support | old site requests should use https

apps/content/lib/cms/http_client.ex, apps/content/lib/cms/static.ex, apps/content/lib/helpers.ex, apps/content/lib/paragraph/content_list.ex, apps/content/lib/repo.ex, apps/content/test/cms/http_client_test.exs, apps/content/test/cms/static_test.exs, apps/content/test/paragraph/content_list_test.exs, apps/content/test/paragraph_test.exs, apps/content/test/repo_test.exs, apps/site/lib/css_helpers.ex, apps/site/lib/site_web/controllers/event_controller.ex, apps/site/lib/site_web/controllers/mode/hub_behavior.ex, apps/site/lib/site_web/controllers/news_entry_controller.ex, apps/site/lib/site_web/controllers/page_controller.ex, apps/site/lib/site_web/controllers/project_controller.ex, apps/site/lib/site_web/controllers/schedule/cms.ex, apps/site/lib/site_web/templates/content/_content_list.html.eex, apps/site/lib/site_web/views/content_view.ex, apps/site/test/site_web/controllers/project_controller_test.exs, apps/site/test/site_web/views/content_view_test.exs, apps/site/test/site_web/views/partial_view_test.exs
**Asana Ticket:** [Events are taking the place of projects](https://app.asana.com/0/555089885850811/1130887606820083)
Changes `Repo.teasers` `type` option from single atom to list of atoms.
- `type: [:project, :news_entry]` will be converted to `{"type[]", "project"}, {"type[]", "news_entry}`
NOTE: Must be deployed _first_, then mbta/cms#286 can be deployed.
=> Repo.teasers should support multiple `type` values

apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/helpers/__tests__/fetchTest.ts, apps/site/assets/ts/helpers/__tests__/service-test.ts, apps/site/assets/ts/helpers/fetch.ts, apps/site/assets/ts/helpers/service.ts, apps/site/assets/ts/schedule/__tests__/ScheduleModalTest.tsx, apps/site/assets/ts/schedule/__tests__/ServiceSelectorTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
**Asana Ticket:** [⏱Schedules | Finder Tool - Polish](https://app.asana.com/0/555089885850811/1131943808986526)
I ran the Modal flickering that can be see on LG devices (see ticket for an example) through the Chrome Performance tool that can take snapshots. It showed that the modal was going from old data -> spinner -> old data -> new data.
Since the modal went from big to small, the transition was more noticeable. This would be more noticeable on a 3G network on an older mobile device. I was able to emulate that scenario by using the Chrome Performance tool to add network and CPU throttling.
Looking at the code, 
the state was set to loading
-> a render to show the spinner happened,
the state was set to not loading
-> a render to hide the spinner happened and show the (still old) data, …
=> Schedule Finder | Polish

apps/site/lib/site_web/controllers/schedule/timetable_controller.ex, apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs
We are experiencing 500s on pages in the future where schedules did not have a stop. This occurred for Malden shuttles. Updating this processing to use the headsign if the stop is not available. This data does get processed for the tooltips to keep track of what the prior stop is, which might not apply to this data but is processed anyway. 
The ticket in the backlog to address this is to not build data for the vehicle tooltips if the date is not today.
<br>
=> Timetable | Use headsign for nil stops

apps/site/lib/site_web/controllers/schedule/timetable_controller.ex, apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs
There's a ticket in the backlog to make the Vehicle stream Phoenix channel to not start on days that are not today, which is a modular level change.
In this case, on a controller level, we are computing extra data specific to CR that is not provided in the Vehicle stream. We don't need this data if it's not the current service day.
<br>
=> Timetable | Don't calculate tooltip data when it's not today

apps/site/lib/site_web/views/page_content_view.ex, apps/site/test/site_web/views/page_content_view_test.exs
When there are only empty content list(s), don't render right sidebar. I noticed this on some projects where the layout was shifted over for a sidebar, yet there was no sidebar content.
=> Prevent empty sidebar right from rendering

apps/site/test/detailed_stop_group_test.exs
No ticket. Now that the API is exposing the Foxboro Line we have to update one test.
<br>
=> Add Foxboro Line to appropriate test

apps/site/lib/site_web/controllers/schedule/cms.ex
**Asana Ticket:** [Allow /schedules/*/line to promo basic pages with page type=Projects](https://app.asana.com/0/555089885850811/1133912070337208)
- on route pages, authors can now feature basic pages tagged with that route
- requires the content to be published (created date) more recent than any other competing, similarly-tagged content
- basic page content must be "Promoted to sidebar" as well
=> Allow basic pages tagged with route to appear in promo slot

apps/site/lib/site_web/controllers/schedule/line_controller.ex
**Asana Ticket:** [Schedule Finder | Duplicate stops](https://app.asana.com/0/555089885850811/1134882691751327)
The struct that we are using for this stops list is derived from the struct that creates the "stop bubbles" for the schedule page. I looked into deconstructing that data so we could be more deliberate about the order of stops, but I think that'd be more work than a 1. This solves for the problem for http://localhost:4001/schedules/39/line example in the ticket if you
`export V3_URL="https://green.dev.api.mbtace.com"` before running `mix phx.server`
<br>
=> Schedule Finder | Duplicate stops

apps/site/lib/site/content_rewriters/embedded_media.ex
**Asana Ticket:** [❗ 🚧 🔶 OL Cars | Embedded iframe has funky sizing](https://app.asana.com/0/555089885850811/1134554424225557)
This allows these iframes to be full width (break out of our columns). 
The scrollbars are due to the Knightlab/Juxtapose javascript in the iframe setting an explicit width/height on an element within it. I don't see any easy way around this. After this change, content authors could use option #2 on https://mbta.com/projects/orange-line-improvement-program/update/new-orange-line-cars?preview=&vid=28918&nid=4453. It seems to resize itself best in our flexbox layout.
The image may not break out of the column at certain viewpoints. If you inspect the element, you will see it has added padding (top or left) because Juxtapose is trying to retain the original aspect …
=> Add cdn.knightlab.com to EmbeddedMedia

apps/cms/lib/api/static.ex, apps/cms/lib/page/project_update.ex, apps/cms/priv/repo/project-updates.json, apps/cms/test/api/static_test.exs, apps/site/lib/site_web/controllers/cms_controller.ex, apps/site/lib/site_web/controllers/project_controller.ex, apps/site/lib/site_web/router.ex, apps/site/lib/site_web/templates/cms/page/_project_update.html.eex, apps/site/lib/site_web/views/page_content_view.ex, apps/site/test/site_web/controllers/cms_controller_test.exs, apps/site/test/site_web/controllers/project_controller_test.exs
**Asana Ticket:** [Project Update | Allow paragraphs on Project Update template](https://app.asana.com/0/555089885850811/1117427304689982)
- Passes project update requests through CMS controller
- Removes `:project_update` from router
- Adds unique template for project update due to inclusion of type-specific "Updated On" field
=> Support paragraphs on Project Update pages

apps/site/lib/site/transit_near_me.ex, apps/site/test/site/transit_near_me_test.exs
**Asana Ticket:** [🐞 Routes with high priority alerts aren't showing alert icon in TNM](https://app.asana.com/0/555089885850811/1135457050018732)
A bug in Transit Near Me was preventing routes with alerts from showing alert icons. Fixed.
<br>
=> Fix alert icons in Transit Near Me

apps/site/lib/site/realtime_schedule.ex, apps/site/test/site/realtime_schedule_test.exs
Address some realtime API bugs observed when testing Transit Near Me
- don't need to filter predictions by `min_time` when fetching from Repo
- don't fetch schedules for subway
- use a more detailed key for grouping schedules/predictions by route_pattern
- sort predictions by date when they are combined for similar route_patterns
<br>
=> realtime API bug fixes

apps/site/assets/js/app-entry.js, apps/site/assets/ts/projects/components/MoreProjectsTable.tsx, apps/site/assets/ts/stop/stop-loader.tsx, apps/site/assets/ts/tnm/transit-near-me-loader.tsx
**Asana Ticket:** [IE11: async/await and fetch should work via polyfill](https://app.asana.com/0/555089885850811/1135644534502577)
A problem that wasn't related to async/await is that response.body was always undefined with the whatwg-fetch polyfill. I think that does not exist in this polyfill: https://github.github.io/fetch/
The polyfill doesn't support the readable stream type of body but we don't use that, see more here: https://github.com/github/fetch/pull/32
We separate out vendor packages into vendor.js in production builds so moving this import doesn't make a difference in bundle size/composition.
This is deployed to green.dev.mbtace.com
<br>
=> IE11: add fetch polyfilll to app.js and fix up response.body

apps/fares/lib/fares.ex, apps/site/lib/site/base_fare.ex, apps/site/lib/site_web/templates/schedule/_trip_info.html.eex, apps/site/test/site/lib/base_fare_test.exs
**Asana Ticket:** [🐞 Incorrect pricing on CR for special events](https://app.asana.com/0/555089885850811/1135048817493698)
Looking at a schedule page for Foxboro with a special event, e.g. https://www.mbta.com/schedules/CR-Foxboro/schedule?date=2019-08-22&direction_id=0, you'll see prices appropriate for a Zone 1A trip, rather than the $20 flat round-trip fare. Also, it mentions the "Unlimited Weekends" deal that isn't valid for travel to Foxboro. Fixed.
<br>
=> Fix Foxboro fares

apps/site/lib/site/realtime_schedule.ex, apps/site/test/site/realtime_schedule_test.exs
**Asana Ticket:** [Realtime API | alert count per route](https://app.asana.com/0/555089885850811/1135263069483354)
The realtime API now includes, on a per-route basis, the `alert_count` attribute needed to make alert icons appear where appropriate in TNM.
Also fixed a pre-existing bug in the realtime API where it crashed on skipped predictions.
<br>
=> Add alert count per route to realtime API

apps/algolia/lib/algolia/routes.ex
**Asana Ticket:** [🚧 🔴 🔧 Wollaston | Add Wollaston back to stops index](https://app.asana.com/0/555089885850811/1135967865570354)
Wollaston is already showing in production as a stop in Algolia.
The algolia update wasn't completing due to a route being set to "Green" which isn't a valid route id.
<br>
=> Algolia Index update: Handle route id of Green

apps/cms/lib/helpers.ex, apps/site/test/site_web/views/cms_view_test.exs
**Asana Ticket:** [Event Start Time now includes TZ offset in CMS](https://app.asana.com/0/555089885850811/1135670866855626)
- Adds support for new datetime format w/TZ included
- Maintain support for original format during transition period
=> Support updated CMS API datetime RFC3339 format

apps/site/lib/site/content_rewriters/liquid_objects.ex, apps/site/lib/site/content_rewriters/liquid_objects/route.ex, apps/site/test/site/content_rewriters/liquid_objects/route_test.exs, apps/site/test/site/content_rewriters/liquid_objects_test.exs
**Asana Ticket:** [Create liquid replacements for route long name](https://app.asana.com/0/555089885850811/1135428663528491)
- **Input**: `{{ route:83 }}`
- **Output**: `Rindge Avenue - Central Square, Cambridge`
- Tolerant of missing route id and no route match found
- Compatible with error handling and reporting functions
=> support {{ route:x }} liquid replacements

apps/site/lib/site/base_fare.ex, apps/site/test/site/lib/base_fare_test.exs
**Asana Ticket:** [Fares | Users know bus shuttles are free](https://app.asana.com/0/555089885850811/1133954832480177)
- any route with `description: :rail_replacement_bus` will return a `:free_fare` base fare instead of a typical bus fare
- affects fare output on both old and new trip info components
=> Rail replacement shuttles should use :free_fare

apps/site/assets/css/_schedule.scss
**Asana Ticket:** [Schedules | selected date on the calendar hard to read](https://app.asana.com/0/555089885850811/1132719231879592)
Increases specificity of `.schedule-selected` selector so that selected weekend dates use dark blue styling, making the white text readable.
=> Fix readability of weekend-selected dates on calendar

apps/stops/test/api_test.exs
Fixes broken test due to API changes.
- addition of "South Station-S" for SS Stops
=> Fix broken Stops test due to API updates

apps/cms/lib/helpers.ex, apps/site/assets/css/_banner.scss, apps/site/assets/css/_content-teasers.scss, apps/site/assets/css/_utilities.scss, apps/site/assets/css/_whats-happening.scss, apps/site/lib/site_web/templates/page/_banner.html.eex, apps/site/lib/site_web/templates/page/_banner_content.html.eex, apps/site/lib/site_web/templates/page/_whats_happening.html.eex, apps/site/lib/site_web/views/helpers/cms_helpers.ex, apps/site/lib/site_web/views/page_view.ex, apps/site/lib/site_web/views/partial_view.ex
**Asana Ticket:** [Make Projects category headers link to /projects](https://app.asana.com/0/555089885850811/1134372917205057)
Create a nested utility class to render certain blocks of content as "cards" -- with a primary link covering the entire block, and secondary link(s) which can be clicked on for alternate navigation.
Applied to:
- Homepage: Main Banner
- Homepage: All primary and secondary "What's Happening" item blocks
- Hub and Line Schedule pages: sidebar project teasers
Bonus:
- ~When the secondary link is hovered, its `title` attribute text is shown for greater context~
=> Make Projects category headers link to /projects

apps/cms/lib/partial/paragraph/content_list.ex
**Asana Ticket:** [Diversions | On project pages, Elixir should NOT limit diversions to 2 max](https://app.asana.com/0/555089885850811/1136755693816401)
Release limit of `:diversion` content list results.
NOTE: The reusable list used on project pages in the CMS is currently set to 2, so I suggest authors adjust that to whatever they need (this is beyond the scope of this ticket).
=> Don't hard-limit diversion teasers in content lists

apps/site/assets/ts/helpers/date.ts
**Asana Ticket:** [🐞 Clientside project updated on date is sometimes parsed wrong](https://app.asana.com/0/555089885850811/1136806483144122)
Noticed this while working on my PC on another PR. My snapshots were failing on it because of a timezone issue.
<br>
=> Projects | correct date regardless of client timezone

apps/site/assets/ts/leaflet/__tests__/MapTest.tsx, apps/site/assets/ts/leaflet/components/Map.tsx
**Asana Ticket:** [🐞 Trip planner map issue w/ double clicking](https://app.asana.com/0/555089885850811/1135810086712490)
This reverts commit a8994a9750f07286c57d1b19a4027524ff022269, in order
to fix a bug it introduced where zooming on a map under certain
circumstances would reset its center to downtown Boston.
<br>
=> Revert "save map zoom as state (#37)"

apps/schedules/lib/repo_condensed.ex, apps/schedules/lib/schedule.ex, apps/schedules/lib/schedules.ex, apps/schedules/test/repo_condensed_test.exs, apps/site/lib/predicted_schedule.ex, apps/site/lib/site/realtime_schedule.ex, apps/site/test/site/realtime_schedule_test.exs
**Asana Ticket:** [Website Perf: Investigate more strategic schedule cache (by route_pattern / stop)](https://app.asana.com/0/555089885850811/1134294684192693)
- create a new schedule-like struct that only contains data needed to display a schedule without any nested structs
- cache the struct (the existing `Schedule.t()` caches the record, and re-builds the struct on every call)
<br>
=> use CondensedSchedule in Transit Near Me

apps/site/lib/site_web/router.ex, apps/site/test/site_web/router_test.exs
**Asana Ticket:** [❗🚍 Better Bus | Redirect eliminated routes Sept 1 onward](https://app.asana.com/0/555089885850811/1134934127605007)
Some bus routes are getting eliminated by the Better Bus Project. This PR redirects their schedule, etc. pages to the appropriate Better Bus Project page.
<br>
=> Redirect routes eliminated by Better Bus Project

apps/fares/lib/fares.ex
**Asana Ticket:** [❗🚍 Better Bus | Remove 424 from hard-coded list of express routes for Sept 1](https://app.asana.com/0/555089885850811/1133711653869789)
This changes the 424 from an inner express bus to a local. I considered making the code changes detailed in the ticket, but on investigation decided that it was more complex than I wanted to do for something with a hard deadline like this.
<br>
=> Change 424 bus from inner express to local

apps/cms/lib/partial/paragraph/fare_card.ex, apps/site/assets/css/_fare-card.scss, apps/site/assets/css/_utilities.scss, apps/site/lib/site_web/templates/cms/paragraph/_fare_card.html.eex, apps/site/lib/site_web/templates/cms/paragraph/_grouped_fare_card.html.eex, apps/site/lib/site_web/views/helpers/cms_helpers.ex, apps/site/lib/site_web/views/paragraph_view.ex
**Asana Ticket:** [For linked fare cards, strip/handle nested note links](https://app.asana.com/0/608870567064377/997300270214265)
Prevents broken HTML due to potential links-within-links on fare cards
- Uses data from newly added CMS field `field_card_link` for card link URL (see mbta/cms#300)
- Adjusts HTML output for fare card linkage (uses new `.u-linked-card` utility class)
- Tweaks to utility class to support wider range of linked card scenarios
- Abstract some of the link output logic within the fare card templates
=> Support CMS Fare Card links and nested links

apps/site/test/site_web/controllers/schedule_controller_test.exs
Holiday count needed to be updated in two tests.
<br>
=> update holiday count in tests

apps/site/assets/ts/tnm/components/TransitNearMe.tsx, apps/site/lib/site/application.ex, apps/site/lib/site/realtime_schedule.ex, apps/site/mix.exs, apps/site/test/site/realtime_schedule_test.exs
**Asana Ticket:** [TNM: cache result by stop for 30 seconds](https://app.asana.com/0/555089885850811/1138499454939089)
- use `RepoCache` to cache complete JSON response for stops for 30 seconds
- currently, we are only sending a single stop from TNM, so caching the list of stops should be fine for achieving re-use across separate requests.
- the JSON responses are currently anywhere from 1kb to 20kb, as such, I'm not expecting this cache to grow too large as it seems not span more than 1000 stops in a 30 second window
- also, we have recently doubled the dotcom memory and are still typically running at less than 50% of the available memory
- with this cache in place, I reduced the polling time of the frontend
---
Some local time measurements: …
=> cache realtime data, reduce TNM polling time

apps/site/assets/js/fullstory.js, apps/site/lib/site_web/plugs/cookies.ex
**Asana Ticket:** [🔧 FullStory and Informizely throttling investigation](https://app.asana.com/0/555089885850811/1134544942021189)
- fullstory and informizely stopped working properly because they need to read the mbta_id cookie value from Javascript
- we had previously set `http_only` for that cookie, making it impossible to read by modern browsers
- this changes `http_only` to false, now it can be read
- allowing this to be read is not a security issue because the value is meaningless, just unique to a session and not tied back to any user identifiable information
- fullstory's original throttling value was restored because this should make it go back to normal
I verified locally that making this change allows the value to be read and the fullstory code to be initiated.
<br>
Assigned …
=> fix fullstory and informizely, make mbta_id readable by JS

apps/schedules/lib/repo_condensed.ex, apps/site/lib/site/realtime_schedule.ex, apps/site/test/site/realtime_schedule_test.exs
This is an odd issue... basically, deploys have been failing because during the heath check stage of new servers instances, enough 500 errors are generated that the server instance fails the check and the deploy rolls back.
The odd thing about this is that it seems that the errors are not appearing in Splunk. The number of 500 errors recorded there vs the number of 500 responses I can see in the AWS Elastic Beanstalk Heath console do not correlate.
I found this issue by downloading a log file from Beanstalk directly. That should be investigated in . a separate ticket.
What is happening here is somehow a value that is not a valid stop_id is being passed and the application is crashing because that is an unhandled case.
<br>
=> fix issues causing 500 errors in realtime API

apps/cms/lib/api/static.ex, apps/cms/lib/partial/paragraph/content_list.ex, apps/cms/lib/repo.ex, apps/cms/priv/landing_page_with_all_paragraphs.json, apps/cms/test/paragraph/content_list_test.exs, apps/cms/test/paragraph_test.exs
**Asana Ticket:** [Teasers endpoint serving incorrect Content List results](https://app.asana.com/0/555089885850811/1137138645355009)
Prepare for changes in https://github.com/mbta/cms/pull/301 (**deploy this FIRST**)
- Always fill both slots for term arguments in request: `/cms/teasers/<tag>/<route>`
- If either argument is unnecessary, fill with default wildcard `"any"`
- Simplify logic for building this part of the content list recipe
=> Teaser endpoint argument changes

apps/site/assets/css/_stop-page.scss
**Asana Ticket:** [Stops Page | Filters overflow for XS breakpoint](https://app.asana.com/0/555089885850811/1137173248482867)
- Only affects stop page filters
- Bumps buttons to new line under FILTERS header
- Better margin alignment for wrapped buttons
=> Better rendering of stop filter buttons on XS

apps/site/assets/css/_utilities.scss
**Asana Ticket:** [Safari | Website doesn't render correctly](https://app.asana.com/0/555089885850811/1139044049600985)
Resolves iOS issue by scoping `position: relative` for links only when they are children of the `.u-linked-card` parent element.
=> Fix greedy SCSS selector in linked-card utility class

apps/site/lib/site_web/views/partial_view.ex, apps/site/test/site_web/views/partial_view_test.exs
**Asana Ticket:** [Fix missing link on Guide-tagged teaser images](https://app.asana.com/0/555089885850811/1139717823570505)
In #165 we moved where the link HTML appears to the `h3`, which is not rendered when content is tagged as `Guides`. This adds a clause to wrap that standalone image with a link.
=> Ensure teasers tagged as "Guides" have linked image

apps/site/lib/site/react/worker.ex
Reduce noise by reserving `node_logging` debug output for the `:test` env only. In all other envs, set it to the `info` level. Logging is preserved, and the test checking for this output continues to work.
=> De-escalate node logging

apps/site/assets/css/project-page.scss, apps/site/assets/ts/projects/__tests__/__snapshots__/BannerTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/FeaturedProjectsListTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/MoreProjectsTableTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/ProjectsPageTest.tsx.snap, apps/site/assets/ts/projects/components/Banner.tsx, apps/site/assets/ts/projects/components/FeaturedProjectsList.tsx, apps/site/assets/ts/projects/components/MoreProjectsTable.tsx, apps/site/assets/ts/projects/components/ProjectsPage.tsx
**Asana Ticket:** [🐞 Project Index | Overflow scrollbars (horizontal)](https://app.asana.com/0/555089885850811/1138657269150609)
Changed how the banner in SM/MD breaks out of the grid. Requires adding a third hidden banner element for SM/MD instead of sharing one with LG.
This changes how the featured projects below the banner look in SM/MD but it actually matches the design better now: https://app.zeplin.io/project/5c422a32bfb873bf2bf338c1/screen/5d279ca602ff559d5ea7a804
<br>
=> Project Index | Responsive overflow

apps/site/lib/site_web/templates/cms/paragraph/_fare_card.html.eex, apps/site/lib/site_web/templates/cms/paragraph/_grouped_fare_card.html.eex, apps/site/test/site_web/views/paragraph_view_test.exs
**Asana Ticket:** [Resolve clickability of fare card primary links](https://app.asana.com/0/555089885850811/1139655103949809)
If the fare card is linked, output the expected `u-linked-card` class on the container to allow primary links to stretch across surface of entire fare card block.
=> Resolve clickability of fare card primary links

apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleTableTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx, apps/site/assets/ts/schedule/components/schedule-finder/TableRow.tsx, apps/site/assets/ts/schedule/components/schedule-finder/UpcomingDepartures.tsx
**Asana Ticket:** [Schedules | Finder Tool - Wrapping times in mobile](https://app.asana.com/0/555089885850811/1137523575743818)
By adding the proper `colspan` of `3` to the "Trip Length" / "Fare" row, the table flexes correctly to fit the times on a single line. **Bonus**: Remove `whitespace: nowrap` on headsigns due to longer headsigns (eg, "Haverhill (Shuttle))" causing page overflow on XS.
**Before / After:**
**Before / After:**
=> Fix wrapping time in schedule finder table

apps/site/assets/css/_banner.scss, apps/site/assets/css/_page.scss, apps/site/assets/css/project-page.scss, apps/site/assets/ts/projects/__tests__/BannerTest.tsx, apps/site/assets/ts/projects/__tests__/MoreProjectsTableTest.tsx, apps/site/assets/ts/projects/__tests__/__snapshots__/BannerTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/FeaturedProjectsListTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/MoreProjectsRowTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/MoreProjectsTableTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/ProjectUpdateListTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/ProjectsPageTest.tsx.snap, apps/site/assets/ts/projects/components/Banner.tsx, apps/site/assets/ts/projects/components/FeaturedProject.tsx, apps/site/assets/ts/projects/components/FeaturedProjectsList.tsx, apps/site/assets/ts/projects/components/FeaturedProjectsRow.tsx, apps/site/assets/ts/projects/components/MoreProjectsRow.tsx, apps/site/assets/ts/projects/components/MoreProjectsTable.tsx, apps/site/assets/ts/projects/components/ProjectUpdateList.tsx, apps/site/lib/site_web/templates/page/_banner.html.eex, apps/site/lib/site_web/templates/page/_banner_content.html.eex, apps/site/lib/site_web/views/page_view.ex
**Asana Ticket:** [Clean up project page CSS classes](https://app.asana.com/0/555089885850811/1137132453918241)
- Elements used exclusively on the projects index page should use an `.m-` prefix (module)
- Elements common to two or more places are considered components and should us a `.c-` prefix
- Removed deprecated selector/class
Followed the rules set previously in our CSS Guidelines wiki (linked in Asana ticket).
=> Projects class cleanup (react)

apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/lib/site_web/router.ex, apps/site/test/site_web/controllers/schedule/line_test.exs
**Asana Ticket:** [⏱Schedules | Directionality - Existing Line Diagram API](https://app.asana.com/0/555089885850811/1127979261717809)
Added an endpoint that renders the existing line-diagram partial with the appropriate data as HTML, to be used in the new directionality feature until we swap in a shiny new line-diagram design.
<br>
=> Add endpoint to render route line diagram

apps/site/assets/css/_description-list.scss
**Asana Ticket:** [⭐ Fares | Description list component clean up](https://app.asana.com/0/555089885850811/1106988937203020)
Two small changes to how we render `<dl>` elements:
* Column proportions adjusted from 25%/75% to 33%/66%.
* `<dl>` only renders as single column at XS breakpoint, rather than SM or XS.
<br>
=> Clean up `<dl>`s

apps/cms/lib/partial/paragraph/content_list.ex, apps/cms/lib/repo.ex, apps/cms/test/paragraph_test.exs, apps/cms/test/repo_test.exs
**Asana Ticket:** [Diversions | Riders should see the most relevant diversion first](https://app.asana.com/0/555089885850811/1136755693816402)
Elixir integration for mbta/cms#304
- Map and use CMS "field_sort_by" value when requesting teasers
- Both `sort_by` and `sort_order` must be present, else both are stripped from request
- Allows authors to set their own sorting options where needed, rather than relying on hard-coded values in dotcom
=> Enable CMS-driven sort_by option

apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/components/Headsign.tsx, apps/site/assets/ts/stop/__tests__/stopData.json
The stop cards on stop pages use this Headsign component but their value for name is valid. 
We can't just overwrite the name value for TNM without significant changes to the data transforming javascript (no tests atm). The name value needs to be preserved because it's used as part of a key.
<br>
=> Fix headsign between stops and tnm

apps/cms/lib/field/image.ex, apps/site/assets/js/photo-gallery.js, apps/site/assets/js/test/photo-gallery_test.js, apps/site/lib/site_web/templates/cms/paragraph/_photo_gallery.html.eex
**Asana Ticket:** [Photo Gallery | Should allow proper captions (not default to alt text)](https://app.asana.com/0/555089885850811/1140952848446817)
Images now have an optional HTML caption. If present, display as the main title for a photo gallery image. If not present, fall back to the alt text.
- Adds new property to `Image` struct - key is optional in JSON response (may not be present)
- Groups image with caption in a `figure > figcaption` relationship
- Removes an unused variable definition from the JS
=> Separate photo gallery captions

apps/site/assets/ts/schedule/__tests__/ServiceSelectorTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
**Asana Ticket:** [🦊 🕸️ Foxboro | Foxboro Event Service Schedule Finder just disappears](https://app.asana.com/0/555089885850811/1142307757412137)
In the case that there was no current service for the route in question (e.g. Foxboro Event Service on most days), a bug made the whole schedule finder disappear. Fixed.
<br>
=> More robust default schedule ID for service selector

apps/alerts/lib/sort.ex, apps/alerts/test/sort_test.exs
**Asana Ticket:** [🐞 For high severity alerts, keep banner placement on all tabs of schedule page (even after it becomes "ongoing")](https://app.asana.com/0/555089885850811/board)
We now jump alerts with a severity of 7 ("up to 30 minutes" delay) or higher to the head of the list of alerts, regardless of its point in the alert lifecycle.
<br>
=> Prioritize a high-severity, low-priority alert over vice versa

apps/site/lib/site_web/controllers/schedule/timetable_controller.ex
**Asana Ticket:** [🦊 🕸️ Foxboro | Fairmount inbound timetable has Dedham Corp Center before Oct 21](https://app.asana.com/0/555089885850811/1142034065520071)
We were fetching the list of `all_stops` for CR timetables without filtering by date, leading to the problem described in the card. Fixed.
<br>
=> Use stops for given date in CR timetables

apps/site/assets/css/_schedule.scss, apps/site/assets/css/_stop-bubbles.scss, apps/site/lib/site_web/controllers/schedule/trip_view_controller.ex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/views/schedule_view_test.exs
**Asana Ticket:** [Foxboro | Franklin AND Fairmount schedule tab doesn't display inbound trips when origin = Foxboro](https://app.asana.com/0/555089885850811/1143031265509297)
- redirects CR route schedules to timetable tab
- hides CR Schedule tab
- hides "Schedules from here" for CR stop list
=> Hide CR schedule tab (redirect to timetable)

config/.credo.exs
This credo check failure has come up in code we've moved around lately. Since we're on 1.8, this check doesn't apply to us, see release notes here:
https://github.com/rrrene/credo/blob/master/CHANGELOG.md#102
We should update credo though. I tried doing that via mix.exs to the latest version and it ran OK via pronto...but I'm concerned about upgrading that right now and introducing a bunch of fix-up work on future branches. We should bite that bullet at some point though, @phildarnowsky up to you which you'd like to do now.
<br>
=> disable Credo.Check.Refactor.MapInto, N/A for 1.8+

apps/site/assets/js/algolia-facets.js, apps/site/assets/js/algolia-global-search.js, apps/site/assets/js/algolia-homepage-search.js, apps/site/assets/js/test/algolia-result_test.js
**Asana Ticket:** [Diversions don't show up in search results](https://app.asana.com/0/399597520748778/1139274691030753)
Include this this type of Drupal content in search results.
=> Include "diversion" content type in search results and autocomplete

apps/fares/lib/fares.ex, apps/fares/mix.exs, apps/site/lib/site/base_fare.ex, apps/site/lib/site_web/controllers/fare/commuter.ex, apps/site/lib/site_web/controllers/schedule/schedule_api.ex, apps/site/lib/trip_info.ex, apps/site/test/site/lib/base_fare_test.exs, apps/site/test/site_web/controllers/fare/commuter_test.exs, apps/zones/priv/crzones.csv
**Asana Ticket:** [Foxboro | Fix pricing ($20 special event vs. Zone 4 vs. Interzone 4)](https://app.asana.com/0/555089885850811/1140953760634051)
Examines trip name and route id to determine if fares should be adjusted for Foxboro related trips.
- Trip argument added to `base_fare` function. Contains train # for commuter rail.
- If trip train name is on exception list and traveling to/from zone 1A, force it to zone 1
- If any fare request involves the route id of "CR-Foxboro," return the $20 fare
- Fare Finder for CR now prints all Zone 4 fares if a Foxboro station is selected
- Fare Finder continues to output the $20 fare if a Foxboro station is selected
- Updated Schedule Finder to work with this as well
**Schedule Finder**
**Schedule Tab**
=> Adjust fares for Foxboro pilot

apps/stops/lib/route_stop.ex
**Asana Ticket:** [🦊 🕸️❗Foxboro | Fairmount line diagram displays Dedham Corp Center twice/disconnected](https://app.asana.com/0/555089885850811/1142034065520052)
The revised `Shape`s for the Fairmount Line don't cooperate well with our branch-deduction code that ultimately dictates the shape and content of the line diagram. In MVP fashion, fixed by adding a special case for the Fairmount line that tweaks the pertinent data by hand in such a way that the diagram comes out correctly.
<br>
=> Fix new Fairmount line diagram

apps/stops/lib/route_stop.ex
**Asana Ticket:** [🦊 🕸️❗Foxboro | Franklin line diagram is very wrong](https://app.asana.com/0/555089885850811/1142034065520053)
The problem was an extraneous shape; filtering it out restores the line diagram to its proper form.
<br>
=> Filter out Franklin shape that was breaking line diagram

apps/site/lib/site_web/controllers/schedule/timetable_controller.ex, apps/site/lib/site_web/templates/schedule/_timetable.html.eex, apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs
**Asana Ticket:** [🦊 🕸️❗Foxboro | Franklin timetable should include "via Fairmount Line"  on some trains](https://app.asana.com/0/555089885850811/1142379675259929)
There are 4 stops outbound and 3 stops (no Hyde Park) inbound in the Franklin "schedules". See details in ticket. Summary is that some Franklin non-via schedules include Hyde Park outbound but not inbound. We produce the timetable through the schedules from the API.
<br>
=> Foxboro | Franklin timetable "via Fairmount Line"

apps/fares/lib/fare.ex, apps/fares/lib/fare_info.ex, apps/fares/lib/format.ex, apps/site/lib/site/content_rewriters/liquid_objects/fare.ex, apps/site/lib/site_web/controllers/fare/commuter.ex, apps/site/lib/site_web/views/fare/description.ex, apps/site/test/site_web/controllers/fare/commuter_test.exs
**Asana Ticket:** [Exclude Zone 4 fares from CR Fare Finder prior to Foxboro Pilot launch date](https://app.asana.com/0/555089885850811/1144031495137785)
Follow on to https://github.com/mbta/dotcom/pull/239
- place special events fare first
- change label of fare to include "Special Event" verbiage
- link Gillette stadium to destination page
- correct media information for $20 fare (new `:special_event` media ticket)
- date-gate Zone 4 fares prior to Foxboro Pilot launch
=> Tighten up CR Fare Finder and Foxboro Special Event fare

apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/SchedulePageTest.tsx.snap, apps/site/assets/ts/schedule/components/LineDiagram.tsx, apps/site/assets/ts/schedule/components/__schedule.d.ts, apps/site/lib/site_web/controllers/schedule/line_api.ex, apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/test/site_web/controllers/line_api_test.exs
**Asana Ticket:** [Schedules | Line Diagram - Stop Component - Alert Icon](https://app.asana.com/0/555089885850811/1141229989083701)
If a stop has any high priority alerts, print the alert icon similar to Trip Planner itinerary. This is just for placement. Final styling to be done on a later pass, along with other stop card elements.
=> Line diagram alerts

apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleTableTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleTable.tsx, apps/site/assets/ts/schedule/components/schedule-finder/TableRow.tsx
Realized this while editing the accessibility document and looking at some eslint-a11y documentation. We should do an accessibility review of this interactive table (namely where a new table appears in a new table row on click/enter) but we could wait for IHCD's formal review.
"All <th> elements should generally always have a scope attribute. While screen readers may correctly guess whether a header is a column header or a row header based on the table layout, assigning a scope makes this unambiguous." - [WebAIM](https://webaim.org/techniques/tables/data)
Surprisingly thead/tbody elements do not confer anything to SRs so we need the scope set. And there was a missing tabIndex on the rows; since they are buttons, we should have them in the tab order.
<br> …
=> Table accessibility fix-ups for ScheduleFinder

apps/site/assets/css/_schedule.scss, apps/site/lib/site_web/templates/schedule/_line.html.eex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/views/schedule_view_test.exs
**Asana Ticket:** [Schedules | Rename "Info & Maps" tab](https://app.asana.com/0/555089885850811/1144985353924400)
Change Commuter Rail tabs only:
- Change "Info & Maps" to "Schedule & Maps"
- Shortens to "Schedule" on mobile
=> Rename info tab for CR

apps/site/assets/ts/projects/__tests__/__snapshots__/FeaturedProjectsListTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/ProjectUpdateListTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/ProjectsPageTest.tsx.snap, apps/site/assets/ts/projects/__tests__/__snapshots__/RoutePillListTest.tsx.snap, apps/site/assets/ts/projects/components/RoutePillList.tsx
**Asana Ticket:** [🐞 Bug | System icons misaligned on Project index](https://app.asana.com/0/477545582537986/1145601078296161/f)
In 0f80d0a a number of classnames that started with `c-` were renamed to start with `m-`, but we missed this one spot.
Fixed appearance:
Note that since the bus icon now has the correct margins, it can sometimes wrap onto a second line when it didn't before:
This seems okay to me but, backing up a bit, it seems odd that _only_ buses are represented by an icon here, where other transit modes are spelled out in text. The rest of the page (including the filter buttons at the top and the project list at the bottom) consistently uses icons for all transit modes. Maybe @ingridpierre can shed light on this decision.
=> Fix misaligned bus icon on Projects page

.envrc.template, .gitignore, README.md, docs/ENVIRONMENT.md
This is a quick suggestion based on my experience getting the app set up. The example `.envrc` works with both [`direnv`](https://github.com/direnv/direnv) and `source` out of the box, and serves as a place to document any default values for variables that aren't secrets, such as `V3_URL`.
This also consolidates all info on env vars into the existing `ENVIRONMENT` doc, rather than some of it being in the README. Admittedly this is a separate suggestion and could be split out.
=> Suggest using `direnv` to manage env vars

apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
**Asana Ticket:** [Feedback Form | Address spam issues](https://app.asana.com/0/477545582537986/1145937042305257/f)
This adds an invisible field to the contact form that must _not_ be filled in for the submission to succeed. The image below has the field un-hidden for illustrative purposes (this is also how a screen reader might "see" it, which is why the label is important).
---
I was unable to get Wallaby testing working for this — I could be missing something, but there seems to be an issue with the library where telling it to fill in a non-visible field just doesn't work, but acts as though it worked. I used this code:
```elixir
@tag :wallaby
test "Catches spam bots that fill every available field", %{session: session} do
session
|> visit("/customer-support")
|> …
```
=> Add basic antispam measure to contact form

README.md, docs/ENVIRONMENT.md, docs/TESTING.md
README changes:
* Specify that an API key should be obtained from `dev.api.mbtace.com` rather than the production site
* Move Java install to the testing docs as it seems this is only needed for Wiremock, which itself is only needed for Backstop
* Add workaround needed for compiling Erlang on OS X 10.15
* Remove manual Caskroom setup — Homebrew does this automatically
* Specify that Chrome must be explicitly installed to use ChromeDriver since it is not auto-installed as a dependency
ENVIRONMENT changes:
* Remove mention of Google billing information since it appears this is not needed (when using an MBTA Google account anyway)
TESTING changes:
* Remove instruction to manually start `phx.server` for testing since all tests pass without doing this (was necessary before?)
* Remove mention …
=> Update docs based on onboarding experience

apps/site/assets/css/_icons.scss, apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/SchedulePageTest.tsx.snap, apps/site/assets/ts/schedule/components/LineDiagram.tsx
**Asana Ticket:** [⏱Schedules | Line Diagram - Stop Component Style](https://app.asana.com/0/555089885850811/1141229989083699)
Added spacing between feature icons and connection icons. Also fixed the following presentational bugs:
* Multiple CR/ferry icons were appearing at stops, whereas only one is desired no matter how many lines connect there.
* Silver Line connections now uses pills rather than icons.
* If a stop had both bus and non-bus connections, the bus connections would get stretched vertically. Fixed.
<br>
=> Style basics of stop components, fix presentational bugs

apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
The client side already has validation for trying to attach non-images, so this is mostly an anti-spambot measure to prevent people from throwing viruses into the ticketing system (even though this would require a support person to intentionally download and open them).
The `filename` and `mime_type` of a Plug.Upload are both provided by the user and thus untrusted, but since we ultimately attach the upload to an email using its `filename`, that is what will control how the recipient's computer tries to open it.
**Asana Ticket:** [Feedback Form | Address file type security issue](https://app.asana.com/0/477545582537986/1148399311722825/f)
=> Add server check for support form uploads

apps/fares/lib/retail_locations_data.ex, apps/fares/test/retail_locations_data_test.exs
**Asana Ticket:** [retail sales listings should include vendor name](https://app.asana.com/0/555089885850811/1145005926601595)
V3 API change: use updated key for location name (`long_name`) -- `name` no longer exists.
**BEFORE:**
**AFTER:**
=> Fix missing retail location vendors

apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/ts/jest.config.js, package.json
I was on my way to write up a tech-debt Asana ticket for this issue, but wondered if it could be as simple as something being outdated. Turns out, it was! (the specific crash was [this one](https://github.com/facebook/jest/issues/8084)) This only took a few minutes to address.
For ease of access, this also adds a `npm run test:jest:watch` script. The default mode only runs tests related to files that have changed.
=> Fix Jest watch mode not working

semaphore/pronto.sh
This is a quick fix for Pronto breaking all our builds because its access token was removed. The relevant step is now green on this branch in Semaphore.
=> Disable Pronto GitHub PR status reporting

apps/site/lib/site_web/controllers/helpers.ex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/views/schedule_view_test.exs
Here we tweak the logic controlling whether or not the shuttle tab
appears, so that it only appears in the case of an ongoing (or
ongoing_upcoming) alert. We also add test coverage for this logic.
**Asana Ticket:** [Shuttles | Properly test appearance of shuttles tab](https://app.asana.com/0/555089885850811/1149377816922177)
<br>
Assigned to: @digitalcora
=> Update shuttle-tab logic, add tests

codecov.yml
**Asana Ticket:** [Fix Codecov for Dotcom](https://app.asana.com/0/1113179098808463/1149791411919817)
There are multiple ways to configure GitHub integrations with Codecov: One option is to use a [“bot user”](https://docs.codecov.io/docs/team-bot) that authenticates, and another is to use the [GitHub application integration](https://github.com/marketplace/codecov). We were using both in our org, and it was messy. 
So I’m trying to move away from the bot user. Apparently that means removing this line that explicitly tells Codecov to use the bot user instead of the integration.
<br>
=> Attempt Codecov Fix

semaphore/pronto.sh
As a follow-up to 1bd6412e6, we want to disable all GitHub integration.
=> Disable Pronto PR comment reporting

apps/site/assets/ts/__cms.d.ts, apps/site/assets/ts/projects/__tests__/BannerTest.tsx, apps/site/assets/ts/projects/__tests__/MoreProjectsTableTest.tsx, apps/site/assets/ts/projects/__tests__/ProjectUpdateListTest.tsx, apps/site/assets/ts/projects/__tests__/ProjectsPageTest.tsx, apps/site/assets/ts/projects/__tests__/SubwayFilterTest.tsx, apps/site/assets/ts/projects/components/Banner.tsx, apps/site/assets/ts/projects/components/FeaturedProject.tsx, apps/site/assets/ts/projects/components/FeaturedProjectsList.tsx, apps/site/assets/ts/projects/components/FeaturedProjectsRow.tsx, apps/site/assets/ts/projects/components/MoreProjectsRow.tsx, apps/site/assets/ts/projects/components/ProjectUpdateList.tsx, apps/site/assets/ts/projects/components/ProjectsPage.tsx, apps/site/assets/ts/projects/components/RoutePillList.tsx
I noticed we are conflating Projects (or "SimpleProjects") to a universal Teaser object/type. Doing this so in the future it's clearer that a Teaser can be more than just a Project-specific type.
- Moves typing to global scale, as Teasers can be relative and used by any page and context
- Continue to cast Teasers as SimpleProjects within the context of the Projects feature
=> Adjust nomenclature for CMS content

apps/trip_plan/lib/trip_plan/api/open_trip_planner/parser.ex, apps/trip_plan/lib/trip_plan/personal_detail.ex, apps/trip_plan/test/api/open_trip_planner/parser_test.exs
Steps in an OpenTripPlanner itinerary have an `absoluteDirection` field.
It's valid for that field to be missing, but we don't handle that case
correctly, leading to occasional failures in trip planning. Corrected.
**Asana Ticket:** [Handle OTP steps with a `nil` `absoluteDirection`](https://app.asana.com/0/555089885850811/1150314104323081)
<br>
=> Handle itineraries with steps without absolute direction

apps/site/assets/ts/shuttles/components/ShuttlesPage.tsx, apps/site/lib/site_web/controllers/schedule/green.ex, apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/lib/site_web/controllers/schedule/shuttles_controller.ex, apps/site/lib/site_web/templates/schedule/_shuttles.html.eex, apps/site/test/site_web/controllers/schedule_controller_test.exs
**Asana Ticket:** [Shuttles | Show BBT boilerplate in sidebar](https://app.asana.com/0/555089885850811/1148592031135767)
- Each of the three lines (red, orange, green) share 1-2 common paragraphs, and are output on each line's shuttle tab regardless of line.
- Add a switch to load certain, other paragraphs based on line name
- Fully render these paragraphs and show in sidebar if there is at least one
Testing: Connect your `DRUPAL_ROOT` env var to `https://live-mbta.pantheonsite.io`
=> Show CMS content in sidebar of shuttles page

apps/site/lib/site/shuttle_diversion.ex
Cristen pointed out that we need a `direction_id` on the shuttle stops to be able to show and hide them along with the route when the direction selector is changed.
This only applies to the shuttle stops, since the rail stops are "directionless". In reality we pick an arbitrary direction and only return the rail stops for that direction, but we don't expect to have diversions where the operational rail stops are different depending on the direction of travel.
=> Add direction to ShuttleDiversion stops

apps/site/lib/site/shuttle_diversion.ex
This is not a real route ID, but it's used in many places as though it is one, including the route pages that the Shuttles tab appears on. This expands "Green" to all Green Line routes.
=> Make ShuttleDiversion work with "Green" route ID

apps/site/lib/site/shuttle_diversion.ex
**Asana Ticket:** [Shuttles | Manually adjust data for Green Line weekday shuttles](https://app.asana.com/0/477545582537986/1150476402898529/f)
This may look like it's doing more work than it needs to, but the idea was to make `TripsHack` a clean drop-in replacement for `V3Api.Trips`, making it as easy as possible to delete it later, even if the rest of the code changes in the meantime.
Tagging @handorff for optional review 🙂
=> Add workaround for D line shuttle diversions

apps/site/lib/site/shuttle_diversion.ex
I made a silly mistake when implementing the Green Line workaround, and did not fully test that it still worked for the other lines.
=> Fix shuttle data crash for non-Green lines

apps/site/lib/site_web/controllers/schedule/green.ex
This occurred because the custom `green_alerts` function used here did not populate the `all_alerts_count` assign, which is used on the other line pages to display the Alerts tab badge.
Since `green_alerts` appears to be a subset of `assign_alerts` which would normally assign the alert count, and that function seems to work fine on the combined Green Line page, we can replace it wholesale.
**Asana Ticket:** [Bug  | Alerts badge missing on /schedules/Green](https://app.asana.com/0/477545582537986/1149844956579553/f)
=> Fix alert badge not appearing on combined GL page

apps/site/lib/site/shuttle_diversion.ex
**Asana Ticket:** [🐞 BUG | Shuttles | Map shows extraneous polylines](https://app.asana.com/0/477545582537986/1150937129144553/f)
This occurred because, when we run normal service for part of a day and shuttle service for the rest, all of those trips are grouped under one Service with a `schedule_typicality` of 4, despite only part of the day being "atypical". We should instead look at the RoutePattern, which has a typicality of 1 for the normal un-shuttled trips.
=> Fix shuttle data including normal route shapes

apps/routes/lib/parser.ex, apps/routes/lib/route.ex, apps/routes/test/repo_test.exs, apps/routes/test/route_test.exs, apps/site/test/site/realtime_schedule_test.exs, apps/site/test/site_web/controllers/helpers_test.exs
This will enable the Shuttles tab to draw the rail lines in the correct colors. The existing line maps use a set of hard-coded colors, which is why we'd never loaded this attribute from the API before.
As a side note, it's concerning how many unrelated tests failed with this change, and even how many different places we have to add the new field within the `routes` app. I think there's a lot of room for improvement and simplification in how we interact with the API.
=> Add color attribute to Route for shuttle maps

apps/site/lib/site/body_tag.ex
This fixes an issue where clicking a link from the Schedule Finder modal (e.g. one of the stops in the schedule) would result in the destination page, and possibly later visited pages, being un-scrollable until a full page reload was performed.
This was caused by the modal setting a `modal-open` class on the `html` element, which then persisted during Turbolinks navigation, which only replaces the `body`. It appears we intended to disable Turbolinks on the pages that open the modal, but the logic was wrong and would keep it enabled if it had ever been enabled on a previous page (without any full page reloads in between).
**Asana Ticket:** [🐞 Bug | Scroll disabled after Schedule Finder navigation](https://app.asana.com/0/477545582537986/1151166129170673/f)
=> Fix disabled scroll bug with Schedule Finder

docs/TESTING.md
Wiremock is in fact a regular Homebrew package and not a Cask.
=> Remove errant `cask` in Wiremock install doc

.github/PULL_REQUEST_TEMPLATE.md
No ticket.
This was redundant with setting reviewers and assignees in Github and
was a source of confusion. Removed.
=> Remove "Assigned to" from PR template

apps/holiday/lib/repo.ex, apps/holiday/test/repo_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs
Here we extend our hardcoded list of holidays to cover 2020 and 2021.
**Asana Ticket:** [Add 2020 (and further) holidays to Holiday.Repo.holidays](https://app.asana.com/0/555089885850811/1152004603671561)
<br>
=> Add holidays for 2020 and 2021

apps/site/lib/site/shuttle_diversion.ex
This fixes an issue I discovered in the process of testing #296, so it does not have a documented Asana ticket as yet.
Some shuttle routes include the same stop ID in both directions, but we were incorrectly uniq-ifying the stops returned from `ShuttleDiversion` by ID, ignoring direction. This uniqueness check does not appear to be necessary anyway, as removing it entirely has the same effect as making the stops unique by stop ID and direction ID.
=> Fix shuttle map missing stops in one direction

apps/site/lib/site/shuttle_diversion.ex, apps/site/lib/site_web/templates/schedule/_shuttles.html.eex, apps/site/test/site_web/controllers/schedule/line_test.exs
This takes the set of alerts we were already using to determine whether to display the Shuttles tab, and displays it *on* the Shuttles tab.
**Asana Ticket:** [Shuttles | Only show the relevant shuttle alert at top of page](https://app.asana.com/0/477545582537986/1148592031135815/f)
=> Only display relevant alerts on Shuttles tab

apps/site/config/config.exs, apps/site/lib/site_web/controllers/schedule/shuttles_controller.ex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/views/schedule_view_test.exs
This removes the feature flag and "noindex" tag from the Shuttles tab, making it generally available.
=> Release the Shuttles tab

apps/site/lib/site_web/templates/layout/_desktop_menu_more.html.eex, apps/site/lib/site_web/templates/static_page/about.html.eex
The old name and vanity URL were being used in a few spots.
**Asana Ticket:** [Fare Transformation | Rename in "More" top nav](https://app.asana.com/0/555089885850811/1152699235340689)
=> Rename AFC 2.0 to Fare Transformation

apps/site/assets/ts/jest.config.js, apps/site/assets/ts/shuttles/__tests__/DirectionButtonsTest.tsx, apps/site/assets/ts/shuttles/__tests__/ShuttlesPageTest.tsx, apps/site/assets/ts/shuttles/components/DirectionButtons.tsx, apps/site/assets/ts/shuttles/components/ShuttlesPage.tsx
Just refactoring some of my test code to allow us to restore the prior setting for Jest test coverage.
=> Revert "bump up global coverage threshold for statements"

apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/test/site_web/controllers/schedule/line_controller_test.exs
Services that are over are just noise in the schedule finder: leave them
out.
**Asana Ticket:** [Schedule finder | Don't display past schedules](https://app.asana.com/0/555089885850811/1152227770350445)
=> Omit past services from schedule finder

apps/site/assets/ts/helpers/__tests__/service-test.ts, apps/site/assets/ts/helpers/service.ts, apps/site/assets/ts/schedule/__tests__/ServiceOptGroupTest.tsx, apps/site/assets/ts/schedule/__tests__/ServiceOptionTest.tsx, apps/site/assets/ts/schedule/__tests__/ServiceSelectorTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/HolidayServiceOption.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ServiceOptGroup.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ServiceOption.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
**Asana Ticket:** [Schedule finder | Determine holiday services using typicality](https://app.asana.com/0/555089885850811/1152227770350433)
* We take advantage of the fact that holiday data will soon be more consistent (try this against dev-green) to determine which services represent holidays, and which holidays they represent, in a simpler and more robust manner.
* We drop some of the text out of the `option`s for holidays, bringing them in accordance with the new information design in the finder.
=> Rework how we handle holidays in the schedule finder

apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/test/site_web/controllers/schedule/line_controller_test.exs
Due to the way we already call out stops that are skipped on non-school
days in the regular weekday service, it's redundant to show the
no-school services in the service picker as well; leave them out.
**Asana Ticket:** [Services Picker | Filter out services that differ from standard services only in having no school service](https://app.asana.com/0/555089885850811/1152227770350425)
=> Omit no-school services

apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/test/site_web/controllers/schedule/line_controller_test.exs
We have logic in the service picker that gets rid of services with the
same start date, end date, and valid days as another service. However,
there are other cases in which we have two services, one of which is a
subset of another, rather than an exact match. These subsets are
redundant too: omit them.
**Asana Ticket:** [Services Picker | De-dupe services that differ only by what garage they run out of](https://app.asana.com/0/555089885850811/1152227770350437)
=> Omit services that are subsets of other services

apps/site/lib/site_web/templates/schedule/_line_page_stop_prediction_cr.html.eex
No ticket.
We check for a blank train number in this view, but not for a nil train
number, leading to crashes at the time of deploying a new rating with
new GTFS trip IDs. Corrected.
=> Check for nil, as well as blank, train number

apps/site/assets/static/robots.txt
No ticket.
A number of web crawler bots (the main offender is Bingbot but there are
others) are crawling our line pages, which is fine. However, they're
apparently trying to crawl schedules with varying `date`s in the query
params, with dates from years in the past to years in the future. This
is causing enough 500 errors on deploy to cause deploys to fail.
Here we update `robots.txt` to disallow crawling of line pages with
dates in the query params.
In dev-green this essentially put a stop to 500 errors:
=> Tell bots not to index line page with date param

apps/site/lib/site/transit_near_me.ex, apps/site/test/site/transit_near_me_test.exs
As of 65e97eb, the line page accepts a date query param, which enables
Backstop testing on that page to work properly again. However, it also
introduced a regression, where if the date given has no service
available in the API, rather than just returning live predictions,
TransitNearMe.time_data_for_route_by_stop/3 was choking on the error
struct indicating "no service". Fixed.
**Asana Ticket:** [Date in params outside of rating shouldn't blow up line page](https://app.asana.com/0/555089885850811/1153779766848073)
[Please include a brief description of what was changed]
=> Don't show schedules or predictions outside rating

apps/site/assets/css/_photo-gallery.scss, apps/site/assets/js/photo-gallery.js
**Asana Ticket:** [ Bug | Photo gallery: 6+ photos break padding, 7th breaks previous/next](https://app.asana.com/0/399597520748778/1122494857555453)
- Fix: spread thumbnails equally across available space using %
- Fix: use TOTAL thumbnail count instead of page thumbnail count to hide nav
=> Adjust style and behavior of Photo Gallery component

apps/cms/lib/partial/paragraph/content_list.ex, apps/cms/test/paragraph/content_list_test.exs
**Asana Ticket:** [Softer project/update teaser limit](https://app.asana.com/0/399597520748778/1154510548826576)
Prior to this PR, we were always forcing 2 results when a list of project or project_update teasers was requested -- **even when authors explicitly set it to only show 1 result**. With this PR, we only enforce the 2-item limit if more than 2 items are requested (as originally spec'd by design).
=> Allow a single project/project_update teaser in ContentList

apps/site/lib/site_web/controllers/mode_controller.ex
**Asana Ticket:** [Schedules call to /api/teasers should use array value for :type](https://app.asana.com/0/399597520748778/1154795529418209)
A while back we added support for querying multiple content :type values. Drupal requires this to be sent as an array instead of a single binary value now, or else the results will not be as expected.
We had updated most instances of this in the codebase, but missed this one.
See #116 and mbta/cms#286
=> Schedules call to /api/teasers should use array value for :type

apps/site/lib/site_web/router.ex
**Asana Ticket:** [🚍 BBP | Redirect /schedules/* pages of eliminated route 70A](https://app.asana.com/0/555089885850811/1146677757163682)
Eliminate the schedules pages for the 70A, which will no longer run after 12/22.
=> Redirect requests for eliminated route 70A

apps/util/lib/util.ex, apps/util/test/async_assign_test.exs, apps/util/test/util_test.exs
The issue was that `async_with_timeout`, which accepts a list of functions, was implemented on top of `yield_or_default_many`, which accepts a map where the values are functions. The map values were being collected back into a list, but since maps are not ordered, this result list would not have the same ordering as the input list.
Because the previous approach resulted in this data flow:
```
list -> map -> list -> Task.yield_many -> list -> map -> list
```
We can simplify to this:
```
list -> Task.yield_many -> list
```
**Asana Ticket:** [🐞💧 Paragraphs display in wrong order (follow-up)](https://app.asana.com/0/385363666817452/1153851471078822/f)
=> Fix CMS paragraph order being scrambled

apps/site/lib/site/shuttle_diversion.ex
**Asana Ticket:** [🐞  Shuttle map stops are sometimes misplaced](https://app.asana.com/0/385363666817452/1152828697682145/f)
Due to a documentation oversight in the API, we hadn't realized stops could be obtained directly from trips instead of going through shapes. Doing this gives more accurate results, and is preferred anyway since the existence of stops on shapes may be deprecated in the future.
The shuttle stop at Alewife is incorrectly displayed at the "overall location" of Alewife station.
The shuttle stop is correctly located within the Alewife busway.
=> Make shuttle stop locations more accurate

apps/site/assets/ts/shuttles/__tests__/ShuttlesMapTest.tsx, apps/site/assets/ts/shuttles/__tests__/ShuttlesPageTest.tsx, apps/site/assets/ts/shuttles/__tests__/__snapshots__/ShuttlesMapTest.tsx.snap, apps/site/assets/ts/shuttles/components/ShuttlesMap.tsx, apps/site/assets/ts/shuttles/components/ShuttlesPage.tsx, semaphore/backstop.sh
**Asana Ticket:** [🐞 Shuttle detail map is sometimes too zoomed-in](https://app.asana.com/0/385363666817452/1152815245059801/f)
I investigated doing the "quick fix" described in this ticket, but found that the required zoom levels for the detail map to be usable varied widely from stop to stop. Some required a zoom of 15 to even reach the nearest shuttle stop, but some required a zoom of 18 to prevent everything from being clustered too close together to tell what was going on.
Based on this, I decided to do the nicer thing and auto-fit to the nearest shuttle stop, which wasn't too much effort.
This also adds a default padding of 20% to the auto-fit (applies to the main map too), which really improves the initial appearance of both maps, in terms of having enough surrounding context to …
=> Improve default bounds for shuttle maps

apps/site/lib/site/react/react.ex, apps/site/test/site/lib/react_test.exs
Previously, in over half of test runs, a random test in `ReactTest` would fail with a `Task.await` timeout. The cause seems to be that we were starting a copy of the renderer process within one of the tests, which somehow interfered with the "real" process. At least, when this test is deleted, the intermittent failure disappears. The reason may have something to do with Poolboy, but it's hard to pursue further than that as Poolboy is written in Erlang and has zero documentation.
Since this test doesn't appear to provide much value, and neither does the one that stops the process, we can probably safely remove them. `React.stop` was only used in this test, so it can be deleted as well.
Finally, this change also removes a 10000ms timeout on the `Task.await` call that could never be reached. …
=> Fix intermittent react renderer test failure

apps/site/assets/css/_schedule-page-line-diagram.scss, apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/lineDiagramData/outward.json, apps/site/assets/ts/schedule/__tests__/lineDiagramData/simple.json, apps/site/assets/ts/schedule/__tests__/lineDiagramWithBranchesData.json, apps/site/assets/ts/schedule/components/LineDiagram.tsx, apps/site/assets/ts/schedule/components/direction/ScheduleDirectionMenu.tsx, apps/site/lib/site_web/controllers/schedule/line.ex, apps/site/lib/site_web/controllers/schedule/line/diagram_helpers.ex, apps/site/lib/site_web/controllers/schedule/line_api.ex
**Asana Ticket:** [Line Diagram | Draw expanded branches](https://app.asana.com/0/385363666817452/1153833236795997/f)
Continuing the schedules line diagram redesign work,
| Red Line Northbound  | Red Line Southbound |
| --- | --- |
| <img width="414" alt="image" src="https://user-images.githubusercontent.com/2136286/71548219-1c409e80-2979-11ea-8ea5-54ba1d64a9d1.png"> | <img width="406" alt="image" src="https://user-images.githubusercontent.com/2136286/71548224-2793ca00-2979-11ea-85de-2773c5f71a8a.png"> |
| **Providence/Stoughton CR**  | **Newburyport/Rockport CR** |
| <img width="370" alt="image" src="https://user-images.githubusercontent.com/2136286/71548262-d59f7400-2979-11ea-990c-9a8e8d38bc73.png"> | <img width="371" alt="image" …
=> Depict branches on schedules line diagram

apps/site/config/test.exs
This is aimed at resolving the remaining intermittent test failures we are getting on CI, which are all HTTP timeouts on API requests.
=> Increase HTTP timeout for API requests in test

apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
This reverts commit e4df0132643e4bdf08b1088b7491de44b05f8631.
This was intended as a quick fix to the high volume of spam coming into the helpdesk with all fields filled out as random letters and numbers. They have reported this didn't fix the issue, so it doesn't make sense to keep this code around.
=> Revert: Add basic antispam measure to contact form

apps/site/assets/ts/leaflet/components/__mapdata.d.ts, apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap, apps/site/assets/ts/schedule/components/ScheduleDirection.tsx, apps/site/assets/ts/schedule/schedule-loader.tsx, apps/site/lib/site_web/templates/schedule/_line.html.eex
**Asana Ticket:** [Line Diagram | Ferry](https://app.asana.com/0/385363666817452/1120016688269892/f)
Introducing a `StaticMapData` type: If this prop is given to `ScheduleDirection`, it will replicate the "static map image with PDF link" behavior from the old line diagram, and not attempt to fetch dynamic map data. Currently this only occurs for ferries, which is determined by the server-side `display_map_link?` helper.
=> Show static ferry map on new line diagram

semaphore/credo.sh, semaphore/scss_lint.sh
Since we were diffing the branch against the current tip of master, rather than the point where it diverged from master, linting would flag issues that had actually been resolved in master.
=> Fix linter false positives on CI

apps/stops/lib/route_stop.ex, apps/stops/test/route_stop_test.exs
**Asana Ticket:** [Line Diagram | Outbound Franklin Line (Foxboro stops)](https://app.asana.com/0/385363666817452/1154464073332369/f)
* Fixes glitchy/disconnected line diagram in the outbound direction
* Fixes Ruggles and Back Bay not showing up on the inbound direction
It turns out we didn't have a special case for Franklin outbound at all (only inbound), so either the outbound line diagram glitch wasn't a regression, or the data previously didn't require a special case but now does.
While in here I discovered an adjacent issue where the _inbound_ map and line diagram was displaying the trunk stops from the Fairmount line instead of the actual Franklin line. I attempted to fix this so it matches the outbound line diagram.
=> Fix Franklin line diagram issues around Foxboro

apps/cms/lib/partial/paragraph/content_list.ex, apps/cms/lib/repo.ex
**Asana Ticket:** [Update CMS API readme/wiki with teaser endpoint info](https://app.asana.com/0/399597520748778/863495051831139)
Endpoint documentation has been added/moved to: https://github.com/mbta/cms/pull/316
Also updated two typespecs which were outdated.
=> Update teaser endpoint type/docs

apps/site/lib/site/shuttle_diversion.ex, apps/site/lib/site_web/controllers/fare/commuter.ex, apps/site/lib/site_web/controllers/schedule/timetable_controller.ex, apps/site/lib/site_web/templates/schedule/_trip_info.html.eex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/controllers/fare/commuter_test.exs, apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs, apps/site/test/site_web/views/schedule_view_test.exs
I've noticed a few places in the code where we were making decisions based on whether a certain date had passed (I even wrote one of them), and where the date has now passed so the conditional is no longer needed.
Method: I did a global search for the regex `201[56789]`, excluding tests and fixture data. This website didn't exist prior to 2015, so is unlikely to have any "feature gates" going further back.
Best reviewed as separate commits.
=> Clean up past time-dependent logic

apps/cms/bin/validate_fixtures.exs, apps/schedules/lib/repo.ex, apps/site/assets/css/_bootstrap.scss, apps/site/assets/css/_button-group.scss, apps/site/assets/css/_buttons.scss, apps/site/assets/css/_datepicker.scss, apps/site/assets/css/_helpers.scss, apps/site/assets/css/_map.scss, apps/site/assets/css/_modal-component.scss, apps/site/assets/css/_search-bar.scss, apps/site/assets/css/_shuttles-page.scss, apps/site/assets/css/core.scss, apps/site/assets/css/style_guide.scss, apps/site/lib/site_web/controllers/places_controller.ex, apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/stops/lib/nearby.ex, apps/trip_plan/lib/trip_plan/api/open_trip_planner.ex, apps/v3_api/lib/v3_api.ex
This should make our future commits a bit less noisy if they touch files that happen to have linter failures. There are still ~160 Elixir files that lack moduledocs so Credo will continue to bug us about those, but the time it would take to address all of those in one big batch is prohibitive.
=> Fix all extant lint failures (except moduledocs)

apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx
**Asana Ticket:** [🐞 Schedule Finder | Combo GL has incorrect direction name](https://app.asana.com/0/385363666817452/1156654983519745/f)
Changes this awkward naming in the modal to "All branches" to match the direction picker.
=> Adjust naming of destination for Schedule Finder on the combination Green Line

semaphore/backstop.sh
The official download servers recently stopped supporting plain HTTP, returning a 501 error response which we were blindly trying to execute as a JAR file.
=> Use HTTPS to download Wiremock on CI

apps/site/lib/site_web/controllers/schedule/finder_api.ex, apps/site/test/site_web/controllers/schedule/finder_api_test.exs
FinderApi.departures implicitly assumed that all trips have associated
schedules, which is not true of added trips. This assumption led to a
nil creeping into an unexpected place, leading ultimately to an
UndefinedFunctionError. This case is now accounted for.
**Asana Ticket:** [Upcoming Departures 500s if it encounters an added trip](https://app.asana.com/0/555089885850811/1157538555249409)
=> Handle added trips in finder_api

apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/test/site_web/controllers/schedule/line_test.exs
**Asana Ticket:** No ticket yet.
There doesn't seem to be "backup" or "substitute" services in the system for many routes on MLK day, 2020. This resulted in NO valid services for the current day.
Current day service filtering assumed there would always be at least one service available.
This fix makes the filter more tolerant in this situation (no current services).
**Sample route:** http://localhost:4001/schedules/424/line
=> Prevent crash when there are no current services for the day

apps/cms/lib/helpers.ex, apps/cms/lib/page.ex, apps/cms/lib/page/basic.ex, apps/cms/lib/page/landing.ex, apps/cms/lib/page/project.ex, apps/cms/lib/page/project_update.ex, apps/cms/lib/partial/paragraph.ex, apps/cms/lib/partial/paragraph/accordion.ex, apps/cms/lib/partial/paragraph/accordion_section.ex, apps/cms/lib/partial/paragraph/column.ex, apps/cms/lib/partial/paragraph/column_multi.ex, apps/cms/lib/partial/paragraph/content_list.ex, apps/cms/lib/partial/paragraph/description_list.ex, apps/cms/lib/partial/paragraph/fare_card.ex, apps/cms/lib/repo.ex, apps/cms/test/helpers_test.exs, apps/cms/test/paragraph_test.exs, apps/site/lib/site_web/controllers/page_controller.ex, apps/site/lib/site_web/controllers/project_controller.ex, apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/lib/site_web/templates/cms/paragraph/_accordion_content.html.eex, apps/site/lib/site_web/templates/cms/paragraph/_column_multi.html.eex, apps/site/lib/site_web/templates/cms/paragraph/_description_list.html.eex, apps/site/lib/site_web/views/paragraph_view.ex, apps/site/lib/site_web/views/partial_view.ex, apps/site/test/site_web/controllers/project_controller_test.exs, apps/site/test/site_web/views/paragraph_view_test.exs
**Asana Ticket:** [Content authors can unpublish nested paragraphs without 500 error](https://app.asana.com/0/553506286097126/1117409475848341)
- Passes query parameters down from page response to paragraph parser
- Pass all nested paragraphs though paragraph parser, rather than direct rendering
- Prevent empty parent paragraphs from rendering when no published children are present
- Update logic for reusable paragraphs: top level type can be unpublished
Related CMS ticket: mbta/cms#318
=> Nested paragraph un/publishing and preview support

apps/routes/test/repo_test.exs, apps/site/lib/site_web/controllers/project_controller.ex, apps/site/test/site_web/controllers/project_controller_test.exs, apps/v3_api/test/routes_test.exs
Controllers should not send preview_opts. At this higher level, they need to pass the full conn.query_params. Extraction of preview_opts happens at a lower level, in the repo and deeper. Added an integration test that would have caught this. Also includes a fix for live-data-related test regressions that are unrelated but were blocking CI.
=> Fix preview_opts

apps/site/test/site_web/controllers/schedule/finder_api_test.exs
The finder API tests as written would occasionally fail due to the
relative paucity of commuter rail schedules and predictions in the
middle of the day. It would be difficult and tedious to mock this out
with our usual DI tricks, and we are hoping to mock out all live data
wholesale soon, so in this case we've replaced one set of live data with
another as a quick fix.
=> Use more robust live data for finder API tests

apps/cms/lib/partial/paragraph/title_card_set.ex
Follow on to mbta/cms#321
This paragraph type is being retained for historical purposes (which is why we're not pulling it), but it is no longer used in any current CMS content (and can no longer be added via the CMS). Use Descriptive Links and MultiColumn layout instead.
Also note that this struct is being hard coded at the bottom of news pages in Elixir land, but that is the only remaining artifact.
=> Add deprecation note for Title Card Set paragraph type

apps/site/assets/ts/schedule/components/schedule-finder/TripDetails.tsx, apps/site/assets/ts/schedule/components/schedule-finder/TripStop.tsx, apps/site/assets/ts/schedule/components/schedule-finder/UpcomingDepartures.tsx, apps/site/lib/site_web/controllers/schedule/finder_api.ex, apps/site/test/site_web/controllers/schedule/finder_api_test.exs
**Asana Ticket:** [Schedule Finder | "View schedules" doesn't work for combo GL](https://app.asana.com/0/385363666817452/1156654983519751/f)
We added some logic to enable us to use the appropriate route ID (e.g. "Green-D" instead of "Green") so that the appropriate API calls will return results!
Also includes some additional safeguards for added trips, where the modal opened from "View schedules" might show errors or abruptly close when a(n added) trip triggers backend errors or  provides a prediction for Upcoming Depatures but no schedule to populate the Accordion.
=> Schedule Finder | "View schedules" doesn't work for combo GL

apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx, apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx, apps/site/assets/ts/schedule/__tests__/ScheduleFinderTest.tsx, apps/site/assets/ts/schedule/__tests__/ScheduleModalTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleModalTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/UpcomingDeparturesTest.tsx.snap, apps/site/assets/ts/schedule/components/ScheduleDirection.tsx, apps/site/assets/ts/schedule/components/ScheduleFinder.tsx, apps/site/assets/ts/schedule/components/SchedulePage.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx, apps/site/assets/ts/schedule/schedule-loader.tsx
**Asana Ticket:** [Schedule Finder | Show schedule note instead of trips for subway](https://app.asana.com/0/385363666817452/1156654983519748/f)
If there is a schedule note present, which should happen on subway lines, the schedule note will display in place of the service picker + daily schedules listing.
It's mostly the same code from #354 so I'm hopeful review will be easy!
=> Add conditional display of schedule note to modal

apps/cms/lib/partial/paragraph.ex, apps/cms/lib/partial/paragraph/accordion.ex, apps/cms/lib/partial/paragraph/photo_gallery.ex, apps/cms/priv/landing_page_with_all_paragraphs.json, apps/cms/test/paragraph_test.exs, apps/site/lib/site_web/templates/cms/paragraph/_accordion.html.eex, apps/site/lib/site_web/templates/cms/paragraph/_photo_gallery.html.eex
**Asana Ticket:** [Photo galleries + tabbed interfaces should have a header option](https://app.asana.com/0/399597520748778/1156296908503857)
Adds common Header type paragraph inside Photo Gallery and Accordion types. Makes consistent with Multi Column and Descriptive List types.
CMS Ticket: mbta/cms#322
=> Add header sub-paragraphs to Photo Gallery and Accordion ¶ types

apps/site/assets/ts/helpers/service.ts, apps/site/assets/ts/schedule/__tests__/ServiceSelectorTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap
It's possible for a storm schedule to span several days; however, to
this point, we were implicitly assuming that all storm schedules are one
day long and only showing the start date. Corrected for storm schedules
that span multiple days.
**Asana Ticket:** [❄️ Service picker should be able to handle multi-day snow schedule](https://app.asana.com/0/555089885850811/1157331058180041)
=> Render multi-day storm schedule dates correctly

apps/site/lib/site_web/controllers/schedule/timetable_controller.ex, apps/site/lib/site_web/templates/schedule/_timetable.html.eex, apps/site/test/site_web/views/schedule/timetable_view_test.exs
The ARIA label for the commuter rail timetable had the route name, which
was useful, but was lacking the direction and date. Added.
**Asana Ticket:** [Timetable | Add direction to table aria label](https://app.asana.com/0/555089885850811/1130340429843892)
=> Add direction and date to CR timetable ARIA label

apps/site/assets/babel.config.js, apps/site/assets/tsconfig.webpack.json, apps/site/assets/webpack.config.base.js
**Asana Ticket:** [🐞 New schedules page is blank in IE11](https://app.asana.com/0/385363666817452/1159531751432025/f)
So as not to mess with our existing Webpack config at all, this creates a new config that explicitly compiles `react-async` using the same options. I've tested this using CBT and it allows IE11 to load the line diagram, though unfortunately the live data is still missing (and it's very unclear why).
=> Fix new schedules being a blank page in IE11

apps/site/assets/webpack.config.prod.js
These are regexes, not wildcard matching; `react*` matches the string "reac" followed by any number of "t", which is likely not what we want. This was harmless anyway since there was no end anchor on the regex.
=> Fix odd regex in Webpack prod config

package.json, semaphore/backstop.sh, semaphore/build_app.sh, semaphore/credo.sh, semaphore/dialyzer.sh, semaphore/mix_test.sh, semaphore/scss_lint.sh, semaphore/setup.sh, semaphore/wallaby.sh
This was a spare-time improvement following on from #332, with the key ideas: **1)** CI should automatically use the same versions of everything we use in development; **2)** we shouldn't spend time compiling the app for CI tasks that don't need it.
The following should be taken with a large chunk of salt since there is high variance in the reported times (sometimes the clock counts up for a minute or two before the first command starts), but the time difference for e.g. linting tasks is significant.
`master` | This Branch
:--:|:--:
The Dialyzer step is currently taking _longer_ than before due to an issue with the Semaphore cache not persisting the new PLTs. ~Semaphore support has acknowledged that it seems like a problem on their end but have not yet come up with a solution.~
After …
=> Align CI setup with development setup

apps/site/assets/ts/schedule/components/line-diagram/ExpandableBranch.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
A couple of elements in arrays didn't have unique keys, causing warnings from React.
=> Fix React key warnings in new line diagram

apps/site/assets/css/_schedule-page-line-diagram.scss, apps/site/assets/ts/schedule/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/SingleStopTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/ExpandableBranch.tsx, apps/site/assets/ts/schedule/components/line-diagram/SingleStop.tsx
**Asana Ticket:** [🐞 IE11 Line Diagram | Height of certain elements is wrong](https://app.asana.com/0/385363666817452/1159531751432030/f)
Tweaks some of the markup and styles to ensure consistency between how the line diagram looks in IE11 and other browsers.
=> 🐞 IE11 Line Diagram | Height of certain elements is wrong

apps/site/assets/ts/components/Alerts.tsx, apps/site/assets/ts/components/__tests__/AlertsTest.tsx, apps/site/assets/ts/components/__tests__/__snapshots__/AlertsTest.tsx.snap, apps/site/lib/site_web/controllers/stop_controller.ex, apps/site/lib/site_web/views/alert_view.ex, apps/site/test/site_web/controllers/stop_controller_test.exs, apps/site/test/site_web/views/alert_view_test.exs
**Asana Ticket:** [🐞 On station pages, URLs in alerts don't work (display as text only)](https://app.asana.com/0/385363666817452/1158582591739289/f)
Took this opportunity to refactor a bit, and introduced another small change: if a URL being linkified has no scheme and starts with `mbta.com`, we can default to `https` instead of `http` since we know our own website supports HTTPS.
=> Fix URLs not linkifying in alerts on stop pages

apps/site/assets/static/loaderio-b4c35b9431db61b4421fcf03e17c3818, apps/site/lib/site_web/plugs/static.ex
This static file validates to Loader.io that we own dev.mbtace.com,
allowing us to run Loader.io tests against it
=> Add Loader.io permission token

apps/site/lib/site_web/views/helpers.ex, apps/site/test/site_web/views/helpers_test.exs
At least one schedule page 500'ed because this one function was being passed a nil route.
=> Handle missing route in route_to_class function

apps/site/lib/site_web/templates/project/updates.html.eex
Quick fix. Some project updates (older ones) may not have images. Content authors have been notified and will fill in the blanks where needed, but this should catch other undiscovered instances.
Eventually there will be a small refactor ticket to make these teasers follow the standard teaser framework, instead of hardcoding them like this.
Sample: https://mbta.com/projects/wollaston-station-improvements/updates
=> hotfix: only output image if image exists

apps/site/lib/site_web/controllers/schedule/line_controller.ex
**Asana Ticket:** [⏱ Schedules | Urgent alerts should be at the top of page](https://app.asana.com/0/385363666817452/1120016688269890/f)
=> Remove direction filter for schedule page alerts

apps/site/assets/static/loaderio-392aa6a67825336b70393c6be61d56ce, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/lib/site_web/controllers/schedule/line_api.ex, apps/site/lib/site_web/plugs/static.ex, apps/site/lib/site_web/router.ex
We want to get an idea of how much of a reduction in requests we might get by only fetching realtime data in the line diagram when the tab is actually visible. This PR adds an endpoint and a JS callback to "phone home" and report the visibility of the line diagram periodically.
I load-tested this on dev-green and it cruises at 1750 requests/second, runs into trouble at 2000. That should be more than performant enough.
=> Log line diagram visibility

apps/predictions/lib/repo.ex, apps/site/test/mappings/mapping-predictions-O5C18.json, apps/site/test/mappings/mapping-predictions-YmT5j.json, apps/site/test/mappings/mapping-predictions-ejxGG.json, apps/site/test/mappings/mapping-predictions-hUsIX.json, apps/site/test/mappings/mapping-predictions-jfMR8.json, apps/site/test/mappings/mapping-predictions-zepnZ.json
Version 2018-07-23 of the API removed the `track` field from Prediction resources, but we were still (harmlessly) requesting it.
This doesn't touch the `track` field on our own `Prediction` structs, as that is still populated by the `Parser` which now looks at the associated `Stop` resource.
=> Remove nonexistent field from API requests

apps/site/assets/ts/helpers/__tests__/service-test.ts, apps/site/assets/ts/helpers/service.ts, apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceOptGroupTest.tsx.snap
On a holiday when viewing the daily schedules.
Turns this (misleading, though the holiday schedule is still selectable and viewable here):
Into this (correct):
=> Fix current service validity check

apps/site/assets/package.json, apps/site/assets/ts/schedule/__tests__/UpcomingDeparturesTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/lib/site/application.ex, apps/site/lib/site_web/controllers/schedule/line_api.ex, apps/site/mix.exs
**Asana Ticket:** [Polling | Introduce caching for the end points getting polled](https://app.asana.com/0/555089885850811/1160944420414821)
(Also includes https://app.asana.com/0/555089885850811/1160944420414816)
Here we introduce a cache to the line diagram realtime endpoint with a 60 second TTL. ~We also slow down polling of this endpoint to once per 60 seconds.~
=> Cache realtime endpoint response

apps/site/assets/ts/helpers/service.ts
Take two on tackling the issue noted in #391 with a hopefully better approach. 
Because we filter out `Weekday (no school)` services (as of #307 ), the frontend has no logical manner in which to determine what the day's valid current service is when it happens to be a Weekday (no school) day (as was/is the case every weekday this week after Monday). 
As happens to be the case, the regular weekday service, whose regular weekday schedules do apply this week, has a service start date next week, e.g. it is not in effect now and thus not considered a current service.
Handling this case deserves a more robust approach, but in the meantime we don't want to show customers "there is no service" when the regular weekday schedules are applicable. This change makes use of the fact that that future …
=> Mark as "current" if service in rating date range

apps/site/assets/ts/helpers/service.ts, apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
The logic around when to display this notice and when not to is trickier
than we first anticipated. To avoid misleading riders, we've pulled that
notice for the moment until we can correct that logic.
**Asana Ticket:** [Suppress "No scheduled service today" message](https://app.asana.com/0/555089885850811/1162903717378782)
=> Yank "No scheduled service for today" notice

apps/site/assets/ts/components/Headsign.tsx, apps/site/assets/ts/helpers/__tests__/prediction-helpers-test.ts, apps/site/assets/ts/helpers/prediction-helpers.tsx, apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/SingleStopTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/UpcomingDeparturesTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/StopPredictions.tsx, apps/site/assets/ts/schedule/components/schedule-finder/UpcomingDepartures.tsx
This also tweaks the rules for CR status displays: previously "Delayed X min" would override any manually-entered `status` string, but now the latter always takes precedence. This is in line with our published Best Practices for prediction data.
**Asana Ticket:** [CR says "On time" when we don't know the scheduled time](https://app.asana.com/0/385363666817452/1161689987228877/f)
=> Don't say CR is "On time" with no scheduled time

apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleTableTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/TableRow.tsx
**Asana Ticket:** [Change "Silver Line Way-South Station" pill for SLW to regular SL pill](https://app.asana.com/0/555089885850811/1160132048446105)
In the "Daily Schedules" section of the schedule modal, we were using round SL icons, when we should have been using mini-pills in SL color. Fixed.
=> Use SL pills instead of round SL icons in one spot

apps/site/assets/css/_schedule-page-line-diagram.scss
**Asana Ticket:** [Line Diagram | Terminus stops have lost their outlines](https://app.asana.com/0/385363666817452/1162964521241689/f)
I had inadvertently disturbed the CSS cascade, and Backstop failed to detect this change.
=> Change selector order, show terminus circle stroke

apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/lib/site_web/controllers/schedule/line_api.ex, apps/site/lib/site_web/router.ex
This reverts commit 4a46fbbfcd66dc6283bc4cb2c1539e9259e23a44. We've
established to our satisfaction that it's worth restricting polling of
the line diagram realtime endpoint to when the tab is actually visible.
With that settled, the visibility logging is just wasting resources.
**Asana Ticket:** [🔧 Remove visibility tracking for line diagram](https://app.asana.com/0/555089885850811/1161861385517913)
=> Revert "Add visibility logging to line diagram"

apps/site/assets/ts/schedule/components/Channel.ts, apps/site/assets/ts/schedule/components/Map.tsx
This is a tiny update mostly aiming to improve the ✨ developer experience ✨ 
This warning shows up on the new schedules page:
We don't want a memory leak! `useEffect()`'s first argument can be used to return a function that will fire when the React component is unmounted, so we use that here to turn off the event listeners that are activated by the `setupChannels` call in the `<Map>` component. At least, I think that's how channels here work. :)
=> Add cleanup function that turns off channel event listeners when component is unmounted

apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/lib/site_web/controllers/schedule/line_api.ex, apps/site/lib/site_web/router.ex, apps/site/test/site_web/controllers/line_api_test.exs
This reverts commit 5ff14ffd21bb251d5c8691d866c1655de97ad78f. It also
moves the endpoint to a different route. This is so that any browsers
out there that still have the polling code will not be hitting this
endpoint.
=> Turn no-longer-realtime endpoint back on

apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/schedule/__tests__/ScheduleFinderTest.tsx, apps/site/assets/ts/schedule/__tests__/ScheduleTableTest.tsx, apps/site/assets/ts/schedule/__tests__/TableRowTest.tsx, apps/site/assets/ts/schedule/__tests__/UpcomingDeparturesTest.tsx, apps/site/assets/ts/schedule/components/ScheduleFinder.tsx, apps/site/assets/ts/schedule/components/__schedule.d.ts, apps/site/assets/ts/schedule/components/schedule-finder/OriginListItem.tsx, apps/site/assets/ts/schedule/components/schedule-finder/OriginModalContent.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleTable.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx, apps/site/assets/ts/schedule/components/schedule-finder/TableRow.tsx, apps/site/assets/ts/schedule/components/schedule-finder/UpcomingDepartures.tsx
**Related to:** [Schedules | Add inputs to schedule finder modal](https://app.asana.com/0/385363666817452/1160795456837881/f)
These are a couple of other refactors that were left on Cristen's schedule-finder-inputs branch (see also #404). Since they are mostly independent of the feature work, and in the interest of keeping changes small and easily reviewed, I've separated them out.
=> Additional Schedule Finder refactors

apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/lib/site/application.ex, apps/site/lib/site_web/controllers/schedule/line_api.ex, apps/site/lib/site_web/router.ex, apps/site/mix.exs, apps/site/test/site_web/controllers/line_api_test.exs
This re-enables both the polling of the realtime endpoint and the
caching of same, only this time with the correct options.
**Asana Ticket:** [Restore caching and polling to realtime endpoint](https://app.asana.com/0/555089885850811/1164530949166961)
=> Re-enable realtime line diagram data

apps/site/assets/ts/jest.config.js, apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
**Asana Ticket:** [Line Diagram | Only poll when page is visible](https://app.asana.com/0/555089885850811/1160944420414819/f)
⚠️ Due to the need to restore the old polling code in order to implement this, it should not be merged until we also restore the old `realtime` endpoint with caching in place.
=> Poll for live data only when page is visible

apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
This reverts commit 8900bd518b2051c5104228a4ba5ae0d02f7e5aab. We suspect
that this may be making more requests than it is meant to, and it's only
auxiliary to the cache in making the realtime endpoint more performant.
=> Revert "Poll for live data only when page is visible"

apps/site/lib/site/application.ex
These options should prevent the locking related errors for the realtime API under heavy load. They were present originally, but in removing and restoring the `ttl` options repeatedly I accidentally removed these.
=> Add concurrency to realtime cache

apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/lib/site_web/controllers/schedule/line_api.ex
To prevent the odd remaining herd from thundering through our website.
=> Add version checking to realtime endpoint

apps/site/lib/site_web/controllers/schedule/finder_api.ex, apps/site/test/site_web/controllers/schedule/finder_api_test.exs
**Asana Ticket:** [Tech Debt | In finder_api, handle failures to look up trip info more gracefully](https://app.asana.com/0/555089885850811/1157508136093385)
This should eliminate one large source of noise in our Sentry logs.
=> Correct finder api 500s

apps/feedback/config/test.exs, apps/feedback/lib/mailer.ex, apps/feedback/lib/test.ex
No ticket. Missed one function that should be mocked out in testing; it worked on my machine without it but other engineers ran into trouble.
=> Mock out ExAWS config in test

apps/site/assets/css/_route.scss, apps/site/lib/site_web/templates/schedule/_hours_of_op.html.eex
**Asana Ticket:** [Bug | Schedules | Hours of Operation missing spacing](https://app.asana.com/0/385363666817452/1165381204331765)
I removed the restriction of width for class `hours-directions` because that was causing the spacing to be nonexistent.
I tested this with different widths but let me know if you still find issues.
=> Remove width restriction

apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceOptGroupTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ServiceOptGroup.tsx
Currently services with a `typicality` of `unplanned_disruption` are
labelled "Storm service" in the schedule finder, on the assumption that
we would reserve that typicality for winter storms. Given the
possibility of reduced service due to the COVID pandemic, however, here
we change our copy to the more general "Reduced service", which is still
accurate in case of a storm as well.
**Asana Ticket:** [Change "Storm Service" hardcoded copy in schedule selector to "Reduced Service"](https://app.asana.com/0/555089885850811/1166409415592881)
=> Change "Storm service" copy to "Reduced service"

apps/site/test/mappings/proxy.json
Cleaning out my Dotcom "junk drawer", I came across this small change I think could be useful in debugging Backstop/Wiremock issues. As you can see from the CI results, it doesn't change the status of any current Backstop tests — just adds a "guard" to ensure the proxy-to-the-live-API mapping isn't used unless there is actually a proxy header attached to the request, telling it where to proxy to.
You'll note some extra error output for when requests don't match any mapping. Unfortunately, as far as I can tell, there's no way to format this any better than "kinda broken ASCII tables".
=> Surface errors with Wiremock proxying in Backstop

apps/site/test/site_web/controllers/schedule/finder_api_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs
Some tweaks to fix Elixir tests. Backstop ones still broken and need re-recording.
=> Fix Elixir tests for spring 2020 rating

apps/alerts/lib/alert.ex, apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/components/Alerts.tsx, apps/site/assets/ts/components/__tests__/AlertsTest.tsx, apps/site/assets/ts/components/__tests__/__snapshots__/AlertsTest.tsx.snap, apps/site/assets/ts/stop/__tests__/AlertsTabTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageTest.tsx, apps/site/lib/site_web/templates/alert/_banner.html.eex, apps/site/lib/site_web/templates/alert/_item.html.eex, apps/site/lib/site_web/templates/trip_plan/index.html.eex, apps/site/lib/site_web/views/alert_view.ex, apps/site/test/site_web/controllers/stop_controller_test.exs, apps/site/test/site_web/views/alert_view_test.exs
**Asana Ticket:** [Alerts | Website should use URL field](https://app.asana.com/0/385363666817452/1116522101105763)
URL coming from Alerts wasn't being taken into account. Now it's being displayed in the header of each alert, in the format [Alert Message] [URL]
<br/>
This contains an unrelated fix for spacing in the Trip Planner, made in passing:
=> Alerts should use url field

apps/site/lib/site_web/templates/schedule/_empty.html.eex
Looking at the nonexistent direction of a unidirectional route on a date
other than the current service date was throwing a 500. Corrected by
adding a check that the direction in question is defined.
**Asana Ticket:** [Handle unidirectional bus routes more gracefully](https://app.asana.com/0/555089885850811/1166771847899436)
=> Prevent 500ing in one unidirectional case

apps/site/config/config.exs, apps/site/lib/sentry_filter.ex
We get a lot of Phoenix.NotAcceptable errors due to script kiddies
and/or poorly behaving apps. They take up a significant fraction of our
monthly Sentry error allowance. Sentry allows us to filter out arbitrary
errors, so we filter those out now.
**Asana Ticket:** [Investigate Phoenix.NotAcceptableErrors](https://app.asana.com/0/555089885850811/1166771847899433)
=> Don't send Phoenix.NotAcceptable errors to Sentry

apps/site/lib/site/realtime_schedule.ex, apps/site/test/site/realtime_schedule_test.exs
Although all predictions should have a trip ID, some are getting fetched
by the realtime schedule endpoint without one. To help the data team
debug this, we've added a bit of logging for when that happens.
**Asana Ticket:** [Log a warning to Splunk whenever the realtime schedule endpoint encounters a prediction without a trip.](https://app.asana.com/0/555089885850811/1167515632160323)
=> Log warning for prediction with nil trip

apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx, apps/site/assets/ts/schedule/__tests__/SchedulePageTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleDirectionTest.tsx.snap, apps/site/assets/ts/schedule/components/ScheduleDirection.tsx, apps/site/assets/ts/schedule/components/__schedule.d.ts, apps/site/assets/ts/schedule/components/direction/reducer.ts, apps/site/assets/ts/schedule/schedule-loader.tsx, apps/site/lib/site_web/controllers/schedule/line.ex, apps/site/lib/site_web/controllers/schedule/line_controller.ex
**Asana Ticket:** [Schedules | Variant parameters in URL](https://app.asana.com/0/555089885850811/1162914752771485)
If you pick a non-default variant on the line page, the URL updates a new `variant` query param accordingly, and that param allows deep-linking to a given variant of a route. This is much the same with what we do about direction IDs in the same URL.
=> Use variant ID in line page URL

apps/site/lib/site_web/controllers/style_guide_controller.ex, apps/site/lib/site_web/templates/style_guide/index.html.eex, apps/site/lib/site_web/views/style_guide_view.ex, apps/site/test/site_web/controllers/style_guide_controller_test.exs
**Asana Ticket:** [Retire /style-guide, 301 redirect to zeroheight](https://app.asana.com/0/385363666817452/1160793451440400/f)
The style_guide_controller now redirects requests to corresponding pages on the new zeroheight design site. I also updated the test for this controller to verify that the redirects are happening correctly. A note about the zeroheight slugs, for my reviewers: they seem to function equally well with or without the page title appended to the end with hyphens, i.e. https://zeroheight.com/2fedee66c/p/43fa10 functions just as well as https://zeroheight.com/2fedee66c/p/43fa10-about, which the former redirects to. I elected to include the title but am looking for feedback in that area as to what best practice should be.
---
Before getting review, please check the …
=> Redirect /style-guide to zeroheight

apps/site/assets/static/robots.txt, apps/site/lib/site_web/templates/layout/app.html.eex
**Asana Ticket:** No Ticket
Prevent search engines from indexing pages under the `/org` directory.
---
=> hide /org section from search engines

apps/site/assets/ts/schedule/__tests__/MapTest.tsx, apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx, apps/site/assets/ts/schedule/components/Map.tsx, apps/site/assets/ts/schedule/components/ScheduleDirection.tsx, apps/site/assets/ts/schedule/schedule-loader.tsx
On the line page, if you look at a branching subway line such as the RL
northbound or the GL in either direction, you'd see only markers for
one branch. Corrected.
**Asana Ticket:** [Bug | Map missing Southbound Braintree trains](https://app.asana.com/0/555089885850811/1169381171498584)
---
=> Show all vehicles in given direction in map

apps/site/assets/css/_schedule-page.scss, apps/site/assets/css/_utilities.scss, apps/site/assets/ts/schedule/__tests__/__snapshots__/ScheduleTableTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/TableRowTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/TripDetailsTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/UpcomingDeparturesTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleTable.tsx, apps/site/assets/ts/schedule/components/schedule-finder/TableRow.tsx, apps/site/assets/ts/schedule/components/schedule-finder/TripDetails.tsx, apps/site/assets/ts/schedule/components/schedule-finder/TripStop.tsx, apps/site/assets/ts/schedule/components/schedule-finder/UpcomingDepartures.tsx
**Asana Ticket:** [Schedule Finder | Missing table column spacing in IE11](https://app.asana.com/0/385363666817452/1166083075512706/f)
- Simplifies markup and CSS
- Removes use of flexbox within tables
- Aligns class names with current [guidelines](https://github.com/mbta/wiki/blob/4185fb315937c1370374a88f0555c32b6d44d090/website/development/guidelines/css_guidelines.md) and [conventions](https://github.com/mbta/wiki/blob/master/website/development/style-guide.md)
- Adds new utility class for tabular number display
- Updates snapshots
---
=> Revamp schedule finder table styles

apps/site/assets/css/_schedule-page-line-diagram.scss
**Asana Ticket:** [🐞 Line diagram visual glitch on Providence line](https://app.asana.com/0/385363666817452/1161660843757401/f)
For short branches that are by default expanded, there needed to be additional styling to achieve the desired appearance. This has now been implemented!
---
=> further specify style for expanded branch segment

apps/site/lib/site_web/endpoint.ex, apps/site/lib/site_web/plugs/canonical_hostname.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs, apps/site/test/site_web/controllers/page_controller_test.exs, apps/site/test/site_web/controllers/places_controller_test.exs, apps/site/test/site_web/controllers/transit_near_me_controller_test.exs, apps/site/test/site_web/controllers/trip_plan_controller_test.exs, apps/site/test/site_web/plugs/canonical_hostname_test.exs, apps/site/test/site_web/views/error_view_test.exs, apps/site/test/support/conn_case.ex
We want all users, including search engine robots, to use the canonical
mbta.com hostname. The exception is mTicket, which uses a special
hostname that we detect to flag the request for special handling; there
is a carveout for that special hostname.
**Asana Ticket:** [mbtace.com being indexed/viewed by public](https://app.asana.com/0/555089885850811/1169245762828233)
---
=> Redirect users away from mbtace.com

apps/site/lib/site_web/plugs/canonical_hostname.ex, apps/site/test/site_web/plugs/canonical_hostname_test.exs
The health checker runs on the same hosts as the application servers and
uses a private IP address to access the /_health endpoint. Whitelist local
IP addresses as well.
No ticket.
---
=> Consider private IPs to be canonical hostnames

apps/site/lib/site_web/endpoint.ex, apps/site/lib/site_web/plugs/canonical_hostname.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs, apps/site/test/site_web/controllers/page_controller_test.exs, apps/site/test/site_web/controllers/places_controller_test.exs, apps/site/test/site_web/controllers/transit_near_me_controller_test.exs, apps/site/test/site_web/controllers/trip_plan_controller_test.exs, apps/site/test/site_web/plugs/canonical_hostname_test.exs, apps/site/test/site_web/views/error_view_test.exs, apps/site/test/support/conn_case.ex
This un-reverts 1713c9a53c0060275350af9fb78c05d5e1c856f6 and
3d479fcba1aa86dfe6d35bd43ddf8c8c3de7c5e3. It also includes one fix, to
work around an apparent Phoenix bug whereby
SiteWeb.Endpoint.config(:url)[:host] is not set to the canonical
hostname as it should be. Instead we reach directly for System.get_env.
**Asana Ticket:** [mbtace.com being indexed/viewed by public](https://app.asana.com/0/555089885850811/1169245762828233)
---
=> Redirect users away from canonical hostnames

apps/site/assets/ts/helpers/service.ts, apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceOptGroupTest.tsx.snap, apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ServiceOptGroup.tsx
**Asana Ticket:** [Update reduced schedules to use the service description, hide validity dates from UI](https://app.asana.com/0/385363666817452/1169855995557655/f)
Prompted by the new abundance of reduced service, this PR cleans up the service picker by implementing the following changes:
* Uses the `service.description`text for services of type `unplanned_disruption`
* Allows services of type `unplanned_disruption` to be listed as "Current"
* Adds logic to omit from the dropdown the service of type `typical_service` that was replaced by the unplanned disruption, if applicable.
| original | updated |
| ------------- | ------------- |
| <img width="714" alt="image" src="https://user-images.githubusercontent.com/2136286/80148773-88c45680-8583-11ea-8234-e735ec097e1f.png"> | <img width="713" …
=> Better handle reduced services in the service picker

apps/site/assets/css/_schedule-page-line-diagram.scss
**Asana Ticket:** [🐞 Line Diagram | IE11 stop content width overflows](https://app.asana.com/0/385363666817452/1171464082559329)
Content overflows for IE in Line Diagram when the number of connections is too big. It needs to wrap.
Before:
After:
This has been checked in IE, Chrome, Firefox and Safari.
=> Specify width to avoid overflow

apps/site/assets/js/timetable-stick.js
Quick Javascript fix for handling when `document.querySelector(".js-timetable-train-labels")` is `undefined`.
=> Prevent error when timetable element not present

apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx
**Asana Ticket:** [Feature | Modal should appear if LineDiagram parameters are bookmarked](https://app.asana.com/0/555089885850811/1174031499922119)
For bookmarked pages that contain direction and origin, the schedule modal will automatically appear when the page loads.
---
Checked number of commits, their messages and how the page loads in IE. These changes are an enhancement on top of the functionality from #440
=> Show modal in LineDiagram if schedule_direction parameters exist

apps/site/assets/ts/schedule/__tests__/TableRowTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/TableRow.tsx
**Asana Ticket:** [🐞 Schedule Finder | Greenbush shuttles break the table](https://app.asana.com/0/385363666817452/1174808744035779)
Display CR shuttle buses using a CR row in the schedule table
---
=> Display CR shuttle buses using a CR row in the schedule table

apps/site/assets/ts/helpers/__tests__/service-test.ts, apps/site/assets/ts/helpers/service.ts, apps/site/assets/ts/schedule/__tests__/__snapshots__/ServiceSelectorTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ServiceOptGroup.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ServiceSelector.tsx
**Asana Ticket:** [Services Picker | Get all services in the current rating into the current optgroup](https://app.asana.com/0/385363666817452/1170658788930619/f)
Made a few adjustments to the service picker logic to achieve the following:
* Let the upcoming service in the current rating be categorized in the UI as "current"
* Order the service choices to align with the mockup
---
=> Get all services in the current rating into the current optgroup

apps/site/lib/site_web/templates/schedule/_line.html.eex
Fix warning when rendering ScheduleFinderForm (via SchedulePage) in the server
[Schedules | Schedule Finder works with URL parameters](https://app.asana.com/0/555089885850811/1162467761296251)
I left a 'lingering' warning that I had been meaning to fix. Previously we were getting the following warning from the server:
`[warn] react_renderer component=SchedulePage Cannot read property 'map' of undefined`
because there was no direction_id specified.
=> Avoid server-side rendering warning

apps/routes/lib/parser.ex, apps/routes/lib/route.ex, apps/routes/test/repo_test.exs, apps/routes/test/route_test.exs, apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/leaflet/components/MapTooltip.tsx, apps/site/assets/ts/stop/__tests__/StopCardTest.tsx, apps/site/assets/ts/stop/__tests__/__snapshots__/StopCardTest.tsx.snap, apps/site/assets/ts/stop/__tests__/stopData.json, apps/site/assets/ts/stop/components/StopCard.tsx, apps/site/assets/ts/stop/components/StopMap.tsx, apps/site/assets/ts/stop/components/StopMapContainer.tsx, apps/site/assets/ts/stop/components/StopPage.tsx, apps/site/assets/ts/stop/components/__stop.d.ts, apps/site/lib/site_web/controllers/stop_controller.ex, apps/site/test/site/map_helpers/markers_test.exs, apps/site/test/site/realtime_schedule_test.exs, apps/stops/lib/nearby.ex, apps/stops/test/nearby_test.exs
**Asana Ticket:** [🐞Stations/Stops | Tooltips for bus connections on map are wrong](https://app.asana.com/0/385363666817452/1147672918652027/f)
Because `<StopCard />` already has a `routesWithDirection` prop to render direction-specific routes, this change lets the `<StopMap />` make use of it. This is done by generating the requisite data from the stop controller and passing it through via `conn.stop_page_data` to `<StopPage />` to `<StopMapContainer />` to `<StopMap />` to `<MapTooltip />` (which will finally pass it to `<StopCard />`).
~The controller code is cobbled together with useful bits of code from elsewhere.~ I expose the `Nearby.merge_routes` function so that I can use it to get directions associated with the stop's routes. ~Much of the rest of the code involves route sorting …
=> Update bus connection tooltips

apps/services/lib/repo.ex, apps/services/test/repo_test.exs, apps/site/lib/site_web/channels/vehicle_channel.ex
**Asana Ticket:** [🐞 Schedule Finder | No scheduled trips found from the merged Green line page](https://app.asana.com/0/555089885850811/1174356662552522)
The logic to retrieve the services for the merged Green line was not receiving the parameter in the right format.
Also tests were added and a pre-processing of trips.<br/>
**Before**:
**After**:
=> Get services for the merged Green Line

apps/site/lib/site_web/controllers/schedule/cms.ex, apps/site/test/site_web/controllers/schedule/cms_test.exs
**Asana Ticket:** [⏱️Schedules | Display news entries for the specific route AND its parent mode](https://app.asana.com/0/555089885850811/1169031641902619)
The news section on the right will only contain a maximum of 5 teasers.
=> Show only 5 teasers max in the News section

apps/site/assets/css/_trip-plan-results.scss, apps/site/lib/site_web/views/helpers.ex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/helpers_test.exs
**Asana Ticket:** [🎫 Style update | Bus Route Mode Icons](https://app.asana.com/0/385363666817452/1169236529454067/f)
For bus routes, instead of generating the SVG icon in a circle, use a new view helper to create an icon similar to those used [elsewhere in dotcom](https://github.com/mbta/dotcom/blob/master/apps/site/assets/ts/schedule/components/schedule-finder/UpcomingDepartures.tsx#L45).
For [this trip](https://www.mbta.com/trip-planner?_utf8=%E2%9C%93&plan%5Bfrom%5D=Arlington+Heights+Busway&plan%5Bfrom_latitude%5D=42.424903&plan%5Bfrom_longitude%5D=-71.184975&plan%5Bto%5D=Terminal+C+-+Departures+Level&plan%5Bto_latitude%5D=42.366635&plan%5Bto_longitude%5D=-71.017167&plan%5Btime%5D=depart&plan%5Bdate_time%5D%5Bhour%5D=2&plan%5Bdate_time%5D%5Bminute%5D=10&plan%5Bdate_time%5D%5Bam_pm%5D=P …
=> Add helper to generate bus pill icon

apps/fares/lib/highest_lowest_fare.ex, apps/fares/test/highest_lowest_fare_test.exs, apps/site/lib/site_web/controllers/schedule/schedule_api.ex, apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/templates/trip_plan/index.html.eex, apps/site/lib/trip_info.ex, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/controllers/trip_plan_controller_test.exs, apps/trip_plan/lib/trip_plan/transit_detail.ex
**Asana Ticket:** [🎫 Trip Planner | Compile fare information for an itinerary](https://app.asana.com/0/555089885850811/1175370216290833)
Add highest and lowest fares to each leg of an itinerary. Not used anywhere yet, but will be in follow-up work.
---
=> Add highest and lowest fares to each leg of an itinerary

apps/site/lib/site/trip_plan/related_link.ex, apps/site/test/site/trip_plan/related_link_test.exs
**Asana Ticket:** [🎫 Trip Planner | Update fare information URLs](https://app.asana.com/0/555089885850811/1176023923687794)
Turns out these correct URLs are also [hardcoded](https://github.com/mbta/dotcom/blob/c917e4799930b7636a178f01cb1fabc2d8216a97/apps/site/lib/site_web/views/schedule_view.ex#L426) in a [number](https://github.com/mbta/dotcom/blob/98a19925be72ff28a9cffd797b774d1d2ca046bc/apps/site/lib/site_web/views/fare_view.ex#L133) of other [places](https://github.com/mbta/dotcom/blob/8999a512499c2b695aceb44b07458b4553ede8da/apps/site/lib/site_web/templates/schedule/_trip_info.html.eex#L54).
---
=> Update Trip Planner fares URLs for bus and subway

apps/site/assets/css/_trip-plan-results.scss, apps/site/assets/ts/trip-plan-results/__tests__/TripPlannerResultsTest.tsx, apps/site/assets/ts/trip-plan-results/__tests__/__snapshots__/TripPlannerResultsTest.tsx.snap, apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx, apps/site/assets/ts/trip-plan-results/components/TripPlannerResults.tsx, apps/site/lib/site/trip_plan/related_link.ex, apps/site/lib/site_web/templates/trip_plan/_itinerary_fares.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site/trip_plan/related_link_test.exs, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [Base Fares | One-way/base fare trips and total price](https://app.asana.com/0/555089885850811/1162903717356809)
This ticket adds the logic to include an estimation of the fares for the itineraries (one way and round trip):<br/>
=> Show highest one-way fare in accordion for Trip Planner

apps/fares/lib/format.ex, apps/fares/lib/month.ex, apps/fares/lib/one_way.ex, apps/fares/test/highest_lowest_fare_test.exs, apps/fares/test/month_test.exs, apps/fares/test/one_way_test.exs, apps/site/assets/css/_trip-plan-results.scss, apps/site/lib/site_web/controllers/schedule/schedule_api.ex, apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/templates/trip_plan/_itinerary_fares.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/lib/trip_info.ex, apps/site/test/site_web/controllers/trip_plan_controller_test.exs, apps/site/test/site_web/views/trip_plan_view_test.exs, apps/trip_plan/lib/trip_plan/itinerary.ex
**Asana Ticket:** [Base Fares | Recommend Monthly Passes](https://app.asana.com/0/555089885850811/1162903717356811)
Display recommended monthly pass in the trip plan results summary box. Add a new `Fare.Month` module to support finding monthly passes.
Targets the `feature/base-fares` branch.
Depends on  https://github.com/mbta/dotcom/pull/487
---
=> Display recommended monthly pass in the trip plan results summary

apps/site/assets/css/_trip-plan-results.scss, apps/site/lib/site_web/templates/trip_plan/_itinerary_fares.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [Base Fares | Add transfers note (not subway)](https://app.asana.com/0/555089885850811/1169236529454061)
Adds the "Total may be less with transfers" note to the itinerary fare summary. This note is added when the itinerary contains two consecutive transit legs which fit the following:
- Subway to subway **(to be removed upon completion of the Base Fares | Add transfers logic (subway) ticket)**
- Subway to local bus
- Local bus to subway
- Local bus to local bus
- Inner express bus to subway
- Outer express bus to subway
- Inner express bus to local bus
- Outer express bus to local bus
If none of the above are present, then no transfer note will be shown.
---
=> Add transfer note to trip planner itinerary

apps/site/lib/green_line.ex, apps/site/test/green_line_test.exs, apps/site/test/site_web/controllers/schedule/green_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/excluded_stops_test.exs, apps/site/test/site_web/views/partial_view_test.exs, apps/stops/test/route_stops_test.exs
No ticket, just a temporary fix to get the GreenLine-related tests to pass.
=> Adapt tests to changes in the Green Line.

apps/fares/lib/format.ex, apps/fares/test/format_test.exs
Add some tests for the full_name function while I'm in there.
No Asana ticket, we discussed this quick change during grooming this morning.
---
=> Update the display name for a shuttle with no fare

apps/site/assets/ts/models/__tests__/routeTest.ts, apps/site/assets/ts/models/route.ts, apps/site/assets/ts/schedule/__tests__/BusMenuTest.tsx, apps/site/assets/ts/schedule/__tests__/ScheduleDirectionTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/BusMenuTest.tsx.snap, apps/site/assets/ts/schedule/components/ScheduleDirection.tsx, apps/site/assets/ts/schedule/components/direction/BusMenu.tsx, apps/site/assets/ts/schedule/components/direction/GreenLineMenu.tsx, apps/site/assets/ts/schedule/components/direction/ScheduleDirectionButton.tsx, apps/site/assets/ts/schedule/components/direction/ScheduleDirectionMenu.tsx, apps/site/assets/ts/schedule/components/direction/reducer.ts, apps/site/assets/ts/schedule/components/line-diagram/SingleStop.tsx, apps/site/assets/ts/schedule/components/schedule-finder/UpcomingDepartures.tsx, apps/site/assets/ts/stop/components/RouteCard.tsx, apps/site/assets/ts/stop/components/StopCard.tsx, apps/site/assets/ts/tnm/__tests__/RoutesSidebarTest.tsx, apps/site/assets/ts/tnm/components/RouteCard.tsx, apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/lib/site_web/controllers/schedule/line/maps.ex, apps/site/lib/site_web/controllers/schedule/map_api.ex, apps/site/test/site_web/controllers/schedule/map_api_test.exs
**Asana Ticket:** [🐞 Schedules | Variant Selector](https://app.asana.com/0/555089885850811/1178546719272801)
Include the shape ID when requesting map data.
Don't filter out shapes with negative priority.
Fix server functions that were incorrectly calling the piece of data "variant" when it was actually a Shape ID.
Just the last commit is the actual fix to the bug and the only functional change. Before that is a hodgepodge of refactoring and adding tests I did on my way to figuring out how everything works. I tried to keep commits distinct to hopefully aid in walking through them, but let me know if anything isn't clear.
Screenshots showing the maps are correctly different now:
---
=> Include the shape ID when requesting map data

docs/TESTING.md
No ticket.
This is just a change to note that test files that have been modified due to the closure of Lechmere will have to be restored to its previous version once this station reopens.
=> Add note for the closure of Lechmere as test files have been affected

apps/fares/lib/format.ex, apps/fares/test/format_test.exs, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [Fare Calculator | Polish | Remove "Monthly Pass" from Commuter Rail and Inner and Outer Express bus pass names](https://app.asana.com/0/555089885850811/1179944684136548)
Remove "Monthly Pass" from CR & express bus pass names
---
=> Remove "Monthly Pass" from CR & express bus pass names

apps/site/assets/css/_trip-plan-results.scss
**Asana Ticket:** [Fare Calculator | Polish | Overflow on blue summary](https://app.asana.com/0/385363666817452/1179862274019473/f)
Changed it from using flexbox to using CSS grid. It even works in IE! Bonus: the two sides should stay the same width now too.
---
=> Fix text overflow on itinerary summary

apps/site/assets/css/_trip-plan-results.scss, apps/site/lib/site_web/templates/trip_plan/_itinerary_tab.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [🎫 Fare Calculator | Polish | Update Hrs/Mins](https://app.asana.com/0/385363666817452/1179323146835849/f)
Updates the abbreviation of hour and adds styling to force it to wrap rather than break the text.
---
=> Update time duration formatting in trip planner output

apps/fares/lib/fares.ex, apps/fares/lib/format.ex, apps/fares/lib/month.ex, apps/fares/lib/one_way.ex, apps/fares/test/fares_test.exs, apps/fares/test/format_test.exs, apps/fares/test/month_test.exs, apps/fares/test/one_way_test.exs, apps/site/assets/css/_trip-plan-results.scss, apps/site/assets/ts/trip-plan-results/__tests__/TripPlannerResultsTest.tsx, apps/site/assets/ts/trip-plan-results/__tests__/__snapshots__/TripPlannerResultsTest.tsx.snap, apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx, apps/site/assets/ts/trip-plan-results/components/TripPlannerResults.tsx, apps/site/lib/site/trip_plan/itinerary_row.ex, apps/site/lib/site/trip_plan/related_link.ex, apps/site/lib/site_web/controllers/schedule/schedule_api.ex, apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/templates/trip_plan/_itinerary_fares.html.eex, apps/site/lib/site_web/templates/trip_plan/_itinerary_tab.html.eex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/lib/trip_info.ex, apps/site/test/site_web/controllers/trip_plan_controller_test.exs, apps/site/test/site_web/views/schedule_view_test.exs, apps/site/test/site_web/views/trip_plan_view_test.exs, apps/trip_plan/lib/trip_plan/itinerary.ex, apps/trip_plan/lib/trip_plan/named_position.ex, apps/trip_plan/lib/trip_plan/transfer.ex, apps/trip_plan/lib/trip_plan/transit_detail.ex, apps/trip_plan/test/transfer_test.exs
Slightly redesigned trip planner output! This is the first chunk of work on our fare calculator. This is our chance to check this group of changes are good to go to deploy!
Covering a few tickets:
* [Base Fares | One-way/base fare trips and total price](https://app.asana.com/0/385363666817452/1162903717356809/f)
* [Base Fares | Add transfers note (not subway)](https://app.asana.com/0/385363666817452/1169236529454061/f)
* [Base Fares | Add transfers logic (subway)](https://app.asana.com/0/385363666817452/1169236529454063/f)
* [Base Fares | Recommend Monthly Passes](https://app.asana.com/0/385363666817452/1162903717356811/f)
* [Fare Calculator | Polish | "Monthly Pass" header](https://app.asana.com/0/555089885850811/1179944684136545)
* [Fare Calculator | Polish | Remove "Monthly Pass" from …
=> Fare Calculator | Trip Planner (top-level summary)

apps/fares/test/one_way_test.exs, apps/site/assets/css/_trip-plan-fare-calculator.scss, apps/site/assets/css/_trip-plan-results.scss, apps/site/assets/css/app.scss, apps/site/assets/ts/components/Accordion.tsx, apps/site/assets/ts/components/__tests__/AccordionTest.tsx, apps/site/assets/ts/trip-plan-results/__tests__/TripPlannerResultsTest.tsx, apps/site/assets/ts/trip-plan-results/__tests__/__snapshots__/TripPlannerResultsTest.tsx.snap, apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx, apps/site/assets/ts/trip-plan-results/components/TripPlannerResults.tsx, apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [Fare Calculator Accordion | One-Way/Round Trip fares](https://app.asana.com/0/555089885850811/1162903717356813)
Replaces https://github.com/mbta/dotcom/pull/499
---
=> Logic for the Fare Calculator in the Trip Planner (2nd accordion)

apps/fares/lib/fare.ex, apps/fares/lib/month.ex, apps/fares/test/fare_test.exs, apps/fares/test/month_test.exs, apps/site/assets/css/_trip-plan-fare-calculator.scss, apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex, apps/site/lib/site_web/templates/trip_plan/_monthly_pass_row.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs, apps/trip_plan/lib/trip_plan/itinerary.ex
**Asana Ticket:** [Fare Calculator Accordion | Recommended Passes](https://app.asana.com/0/555089885850811/1169236529454075)
Display monthly commuter pass for trip plans.
Include reduced pass where applicable.
Depends on https://github.com/mbta/dotcom/pull/499
---
=> Display monthly commuter pass for trip plans

apps/algolia/config/prod.exs
No ticket. Stop the [bleeding](https://sentry.io/organizations/mbtace/issues/1699282277/?project=194344&query=is%3Aunresolved+client+alert&statsPeriod=14d) while we figure out the solution to [🐞 Results on the search page can't be clicked](https://app.asana.com/0/555089885850811/1179421898312873).
---
=> Turn off Algolia click tracking temporarily

apps/site/lib/site_web/controllers/helpers.ex, apps/site/lib/site_web/controllers/places_controller.ex, apps/site/lib/site_web/controllers/schedule/finder_api.ex, apps/site/test/site_web/controllers/helpers_test.exs
No ticket, follow-up to https://github.com/mbta/dotcom/pull/524
Make error response functions general helpers
Use in both PlacesController and FinderApi.
---
=> Make error response functions general helpers

apps/site/lib/site/trip_plan/itinerary_row.ex, apps/site/lib/site/trip_plan/itinerary_row_list.ex, apps/site/test/site/trip_plan/itinerary_row_test.exs
**Asana Ticket:** [Trip Plan Language | Transfer](https://app.asana.com/0/385363666817452/1179317340719423/f)
Changes "Depart onto Transfer" to either "Transfer" or "Depart" depending on whether the subsequent leg is transit or not, respectively.
---
=> Trip Plan Language | Transfer

apps/fares/lib/format.ex, apps/fares/test/format_test.exs, apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex, apps/site/lib/site_web/templates/trip_plan/_monthly_pass_row.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [Fare Calculator Accordion | Shuttle Fare (free)](https://app.asana.com/0/555089885850811/1178333054166489)
Display shuttle fares properly
In the summary, the Monthly Pass is called "Shuttle: None".
Include a row for the shuttle fare in the accordion section.
Use "None" in recommended and reduced columns.
Display fare name as "Shuttle".
---
=> Display shuttle fares properly

apps/site/lib/site_web/controllers/schedule/trip_info.ex, apps/site/test/site_web/controllers/schedule/trip_info_test.exs
**Asana Ticket:** [🐞 Elixir.Phoenix.ActionClauseError: no function clause matching in SiteWeb.ScheduleController.FinderApi.trip/2](https://app.asana.com/0/555089885850811/1180647194087413)
Scenario: obtain trip information for a trip e.g. for ferry `https://www.mbta.com/schedules/finder_api/trip?id=Boat-F1-1000-Long-Sunday&route=Boat-F1&date=2020-08-23&direction=0&stop=Boat-Hingham`
When there is no trip information, a redirection is made with a new URL containing parameter `origin` (e.g. `https://www.mbta.com/schedules/finder_api/trip?origin=Boat-Hingham`). The `trip` function doesn't expect such parameter so it is sending errors to Sentry. This is a possible solution to just return an empty trip instead.
=> Avoid redirect for trips

apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/lib/site_web/controllers/schedule/line_api.ex
Reverts mbta/dotcom#416
No ticket. This check was added to ensure that there weren't problems with old versions of the client-side code calling the new version of the server-side code. I think we are well past the point of needing to worry about that.
=> Remove realtime endpoint version checking

apps/stops/test/route_stops_test.exs
No ticket. Fix for a test that was failing due to still referring to Dudley Station as Nubian Station.
=> Rename Dudley Station to Nubian Station

apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx, apps/site/assets/ts/schedule/__tests__/lineDiagramData/live-data.json, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/assets/ts/schedule/components/line-diagram/StopPredictions.tsx, apps/site/lib/site/transit_near_me.ex, apps/site/lib/site_web/templates/schedule/_line_page_stop_prediction.html.eex, apps/site/test/site/transit_near_me_test.exs
**Asana Ticket:** [👩‍👩‍👧‍👦 Crowding | Get crowding data given a prediction](https://app.asana.com/0/555089885850811/1180639549267087)
Include crowding data in data from time_data_for_route_by_stop
Adjust client-side to match new data structure.
Remove an unused function.
---
=> Include crowding data in data from time_data_for_route_by_stop

apps/cms/priv/cms/teasers_project.json, apps/cms/test/helpers_test.exs, apps/routes/lib/parser.ex, apps/routes/lib/route.ex, apps/routes/test/parser_test.exs, apps/site/lib/site_web/controllers/schedule/cms.ex, apps/site/test/site_web/controllers/transit_near_me_controller_test.exs, apps/site/test/site_web/views/partial/location_card_test.exs
**Asana Ticket:** [🔧 Remove deprecated route description parsers](https://app.asana.com/0/555089885850811/931777477470570)
Remove deprecated route description parsers
These were removed from GTFS in:
https://app.asana.com/0/727048923819421/829424034455337
---
=> Remove deprecated route description parsers

apps/vehicles/lib/parser.ex, apps/vehicles/test/parser_test.exs
No ticket. Updating this to use the [current values for vehicle occupancy status](https://api-v3.mbta.com/docs/swagger/index.html).
=> Update vehicle parser occupancy status handling

apps/stops/test/repo_test.exs
No ticket, tests are failing in master.
Skip a test failing because of schedule changes.
The Providence line is not currently skipping stops on the weekend,
which is making this test fail.
If anyone knows a line that does skip stops on the weekend we can always restore this with that new route.
---
=> Skip a test failing because of schedule changes

apps/site/test/site/transit_near_me_test.exs
No ticket, preliminary work for realtime crowding data.
Flesh out time_data_for_route_by_stop test a little.
Fix the function arity in a test description.
There's room for a lot more improvement, but this is at least an initial test that passes in master while failing in my branch and it better describes the desired behavior. 
---
=> Flesh out time_data_for_route_by_stop test a little

apps/zones/priv/crzones.csv
**Asana Ticket:** [Trip Planner Fares | Lynn/Riverworks Zone 1A](https://app.asana.com/0/555089885850811/1179825855722420)
Move Lynn and River Works to zone 1A-1
The official zone is `CR-zone-1A-1`, but based on the equivalent
situation at Quincy Center (place-qnctr) we apparently represent that
currently just as `1`.
This change updates the information on the station page. The zone data for the trip planner and associated fares comes from OTP so we'll pick up that change when it comes through.
Lynn:
River Works:
Compared with Quincy Center:
---
=> Move Lynn and River Works to zone 1A-1

apps/zones/priv/crzones.csv
Reverts mbta/dotcom#551
Based on clarifications from Paul: https://github.com/mbta/dotcom/pull/551#issuecomment-651983191
=> Revert "Move Lynn and River Works to zone 1A-1"

apps/site/assets/css/_helpers.scss, apps/site/assets/css/_schedule-page.scss, apps/site/assets/ts/schedule/__tests__/__snapshots__/TripDetailsTest.tsx.snap, apps/site/assets/ts/schedule/components/__trips.d.ts, apps/site/assets/ts/schedule/components/schedule-finder/TripStop.tsx
**Asana Ticket:** [🚍Schedule Finder | Cross out skipped/cancelled stops (all modes)](https://app.asana.com/0/385363666817452/1173665781696615/f)
Uses the existing but neglected `schedule_relationship` field on the prediction to identify skipped or cancelled stops. Also adds a short message for screen reader users: `This trip skips {schedule.stop.name}.`
I'm having trouble testing it on other modes, but the example below is from the 201 bus:
---
=> Cross out skipped/cancelled stops (all modes)

apps/site/assets/js/algolia-result.js, apps/site/assets/js/test/algolia-result_test.js, apps/site/assets/js/test/algolia-results_test.js
Reverts mbta/dotcom#470
Rolling this back temporarily as it caused a more pressing issue. Ticket for addressing both issues comprehensively: https://app.asana.com/0/555089885850811/1182047406568641
This does not revert the commit that contained unrelated test fixes.
=> Revert "Fix location icon"

apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx, apps/site/assets/ts/schedule/__tests__/lineDiagramData/live-data.json, apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/assets/ts/schedule/components/line-diagram/StopPredictions.tsx, apps/site/lib/site/transit_near_me.ex, apps/site/lib/site_web/templates/schedule/_line_page_stop_prediction.html.eex, apps/site/test/site/transit_near_me_test.exs
**Asana Ticket:** [👩‍👩‍👧‍👦 Crowding | Get crowding data given a prediction | LineApi/realtime](https://app.asana.com/0/555089885850811/1180639549267087)
Include crowding data in data from time_data_for_route_by_stop
Revert "Revert "Include crowding data in data from time_data_for_route_by_stop (#534)" (#543)"
7e5e36a9756c76f1dec6f6baa8e6fcb78a5ccef6
Fix predictions for multiple trips.
Include the trip headsign in the test to make it clear that times are not being grouped by headsign.
~~Depends on https://github.com/mbta/dotcom/pull/550~~
1:
111:
---
=> Include crowding data in data from time_data_for_route_by_stop, fixed

apps/site/test/site_web/controllers/schedule/green_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs
No ticket.
Update in tests to reflect changes in the Green Line C branch:
https://www.mbta.com/news/2020-07-02/reminder-building-better-t-green-line-c-branch-track-improvements-and-intersection
=> Update tests to reflect changes in the Green Line C branch

apps/cms/lib/partial/paragraph.ex, apps/cms/lib/partial/paragraph/trip_plan_widget.ex, apps/cms/test/paragraph_test.exs, apps/site/assets/css/_trip-plan-widget.scss, apps/site/lib/site_web/templates/cms/paragraph/_trip_plan_widget.html.eex, apps/site/lib/site_web/templates/partial/_trip_planner_widget.html.eex, apps/site/lib/site_web/templates/trip_plan/_submit_button.html.eex, apps/site/test/site_web/views/paragraph_view_test.exs
**Asana Ticket:** [🎫 Trip Planner | Add fare calculator widget to fares CMS pages](https://app.asana.com/0/385363666817452/1162903717356815/f)
This change, in tandem with [this change to the CMS](https://github.com/mbta/cms/pull/339), will enable content authors to add the existing trip planner widget to their pages, with the ability to customize text if desired. The initial use case is for adding a Fare Calculator to the sidebar of certain fares pages (example below):
---
=> Add fare calculator widget to fares CMS pages: the prequel

apps/site/lib/site_web/templates/layout/_desktop_menu_more.html.eex
**Asana Ticket:** [🔗 Main Nav | Swap "Wollaston" Link for "Building a Better T"](https://app.asana.com/0/555089885850811/1182865188439818)
Replace Wollaston main nav link with Building a Better T
Move it to the top of the list.
---
=> Replace Wollaston main nav link with Building a Better T

apps/predictions/lib/prediction.ex, apps/routes/lib/route.ex, apps/schedules/lib/schedule.ex, apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/models/__tests__/prediction-test.ts, apps/site/assets/ts/models/prediction.ts, apps/site/assets/ts/schedule/__tests__/LineDiagramTest.tsx, apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx, apps/site/assets/ts/schedule/__tests__/StopPredictionsTest.tsx, apps/site/assets/ts/schedule/__tests__/__snapshots__/StopPredictionsTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/StopPredictions.tsx, apps/site/assets/ts/schedule/components/schedule-finder/TripStop.tsx, apps/site/lib/predicted_schedule.ex, apps/site/lib/site/transit_near_me.ex, apps/site/test/site/transit_near_me_test.exs, apps/stops/lib/stop.ex
**Asana Ticket:** [🚍 Line Diagram | CR | Cross out skipped/cancelled stops](https://app.asana.com/0/555089885850811/1158407361173137)
Cross out skipped/canceled stops for CR predictions in the line diagram.
---
=> Cross out skipped/cancelled stops for CR predictions

apps/routes/lib/route.ex, apps/routes/test/route_test.exs, apps/site/lib/site/transit_near_me.ex
[👩‍👩‍👧‍👦 Crowding | Hide crowding column if no vehicles have crowding data](https://app.asana.com/0/555089885850811/1181994766435225)
[👩‍👩‍👧‍👦 Crowding | Schedule Pages, Line Diagram](https://app.asana.com/0/555089885850811/1177064032714383)
[👩‍👩‍👧‍👦 Crowding | Upcoming Departures](https://app.asana.com/0/555089885850811/1180063111128636)
Get rid of the list of bus routes from a crowding standpoint.
=> Remove filtering of bus routes for crowding purposes

apps/site/lib/site_web/controllers/schedule/map_api.ex, apps/site/test/site_web/controllers/schedule/map_api_test.exs
**Asana Ticket:** [🐞 Elixir.Phoenix.ActionClauseError: no function clause matching in SiteWeb.ScheduleController.MapApi.show/2](https://app.asana.com/0/555089885850811/1181695474176953)
Ensure that the map api doesn't 500 if given bad params
---
=> Ensure that the map api doesn't 500 if given bad params

apps/site/assets/ts/schedule/__tests__/UpcomingDeparturesTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/UpcomingDepartures.tsx
**Asana Ticket:** [👩‍👩‍👧‍👦 Crowding | Hide crowding column if no vehicles have crowding data](https://app.asana.com/0/555089885850811/1181994766435225)
The column containing the crowding information will not be shown if there's not at least one vehicle with those values:
With crowding:
Without crowding:
=> Do not show crowding if none of the Upcoming Departures for buses has that info

apps/site/assets/ts/helpers/css.ts, apps/site/assets/ts/models/__tests__/route-test.ts, apps/site/assets/ts/models/route.ts, apps/site/assets/ts/schedule/__tests__/TableRowTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/SingleStop.tsx, apps/site/assets/ts/schedule/components/schedule-finder/AccordionRow.tsx, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleTable.tsx, apps/site/assets/ts/tnm/__tests__/RoutesSidebarTest.tsx, apps/site/lib/site_web/controllers/schedule/finder_api.ex, apps/site/test/site_web/controllers/schedule/finder_api_test.exs
**Asana Ticket:** [🐞 Error loading trip details on Green Line page](https://app.asana.com/0/555089885850811/1185053800103665)
Fix trip details for the generic Green line page
---
=> Fix trip details for the generic Green line page

apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex, apps/site/lib/site_web/templates/trip_plan/_itinerary_fares.html.eex, apps/site/lib/site_web/views/trip_plan_view.ex, apps/site/test/site_web/views/trip_plan_view_test.exs, apps/trip_plan/lib/trip_plan/itinerary.ex, apps/trip_plan/test/itinerary_test.exs
**Asana Ticket:** [Trip Planner | SL Trips from Airport to South Station - Monthly Pass Fare](https://app.asana.com/0/555089885850811/1183525584398249)
Hide monthly pass sections for free Logan trips
This is specifically just for Silver Line only (no transfers) trips
starting at one of the Logan terminals.
---
=> Hide monthly pass sections for free Logan trips

apps/site/assets/css/_colors.scss, apps/site/assets/css/_transit-near-me.scss, apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/components/Headsign.tsx, apps/site/assets/ts/components/__tests__/HeadsignTest.tsx, apps/site/assets/ts/components/__tests__/__snapshots__/DirectionTest.tsx.snap, apps/site/assets/ts/components/__tests__/__snapshots__/HeadsignTest.tsx.snap, apps/site/assets/ts/helpers/__tests__/prediction-helpers-test.ts, apps/site/assets/ts/helpers/prediction-helpers.tsx, apps/site/assets/ts/schedule/__tests__/SingleStopTest.tsx, apps/site/assets/ts/schedule/__tests__/StopPredictionsTest.tsx, apps/site/assets/ts/schedule/components/__trips.d.ts, apps/site/assets/ts/stop/__tests__/__snapshots__/DeparturesTest.tsx.snap, apps/site/assets/ts/stop/__tests__/__snapshots__/StopPageTest.tsx.snap, apps/site/assets/ts/tnm/__tests__/__snapshots__/RoutesSidebarTest.tsx.snap, apps/site/assets/ts/tnm/__tests__/state.json, apps/site/assets/ts/tnm/helpers/process-realtime-data.ts, apps/site/lib/site/transit_near_me.ex, apps/site/test/site/transit_near_me_test.exs
**Asana Ticket:** [🚍 Stops/Station/TNM | CR | Cross out skipped/cancelled stops](https://app.asana.com/0/385363666817452/1175248604991146/f)
* Adds `schedule_relationship` to the predictions used on stop pages and transit near me
* Shows predictions with `schedule_relationship` of skipped or canceled as "Canceled" with strikethrough
* Shows the absence of a prediction as "Scheduled" instead of "On time". 
* Adjusts the `$text-muted` color to use a darker gray to ensure good contrast.
Stops
Transit Near Me
---
=> 🚍 Stops/Station/TNM | CR | Cross out skipped/cancelled stops

apps/alerts/lib/parser.ex, apps/alerts/test/parser_test.exs, apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/components/Alerts.tsx, apps/site/assets/ts/components/__tests__/AlertsTest.tsx, apps/site/lib/site_web/plugs/banner.ex
**Asana Ticket:** [Alerts | URL field still doesn't work](https://app.asana.com/0/555089885850811/1176599342634997)
Even though the alerts for dotcom included a URL for more information, it was not 'passed down' and hence not displayed.
Content team members had to manually include said URL in the description.
Also included here a fix to anticipate URLs being null.
Before:
After:
=> Include URL in list of fields to parse

apps/site/test/site_web/controllers/schedule_controller_test.exs
No ticket, the test started failing in CI.
Skip Mattapan test temporarily while the shuttle is running
---
=> Skip Mattapan test temporarily while the shuttle is running

apps/site/test/site_web/controllers/schedule/finder_api_test.exs, apps/site/test/site_web/controllers/schedule/green_test.exs
No ticket, tests are failing in CI.
Skip Heath test instead of Cleveland Circle
Construction projects have moved on to the E line.
Use a non-E line stop for another test.
---
=> Skip Heath test instead of Cleveland Circle

apps/predictions/test/repo_test.exs
Set bypass to handle all requests being made
Fix test that breaks locally.
No ticket
---
=> Set bypass to handle all requests being made

apps/predictions/lib/repo.ex, apps/predictions/test/repo_test.exs, apps/schedules/lib/repo.ex, apps/schedules/lib/repo_condensed.ex, apps/site/lib/vehicle_helpers/vehicle_tooltip.ex, apps/util/lib/util.ex, apps/util/test/util_test.exs
**Asana Ticket:** [RTR Subway Predictions | Drop subway predictions in the past](https://app.asana.com/0/555089885850811/1184691535835665)
Drop subway predictions from the prediction repo if the predicted time is earlier than the current time. This will only affect subway predictions—we want to continue showing commuter rail trains that have recently departed.
=> Drop subway predictions in the past

apps/site/assets/ts/schedule/components/__tests__/ScheduleLoaderTest.tsx, apps/site/assets/ts/schedule/schedule-loader.tsx
Related to [🔥 Schedules | Fix right rail on suspended routes](https://app.asana.com/0/555089885850811/1187736907832137)
I noticed that there was a bug even though the "pinning on the right" was still working. This fix will avoid unnecessary renders of specific components.
=> Account for empty route patterns

bin/.gitignore
No ticket, just noticed this when I moved to a computer with wiremock installed.
Ignore wiremock jar files
---
=> Ignore wiremock jar files

README.md
No ticket. This is something I ran into. My key was set to the wrong API version and it was causing tests to fail for me that pass on CI.
Document the current API version for the site
Developers should set their key to the same version to avoid
discrepancies in the data they see.
---
=> Document the current API version for the site

apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/DailySchedule.tsx, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/DailyScheduleTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/__snapshots__/DailyScheduleTest.tsx.snap
**Asana Ticket:** [🐞 Schedule Finder | Service Picker doesn't update schedule](https://app.asana.com/0/555089885850811/1187746923806232)
Riders may be falsely led to believe that all days have the same schedule because the schedules were not refreshing properly.
=> Fix for no fetching journeys when selecting a different service

apps/site/lib/site_web/plugs/rewrite_urls.ex, apps/site/test/site_web/plugs/rewrite_urls_test.exs
**Asana Ticket:** [Schedules | Show 62/76 combined service page](https://app.asana.com/0/555089885850811/1187743350599921)
Redirect routes 62 and 76 to the combined 627 pages
Use a temporarily redirect. This is because all trips are now scheduled
on the combined Route 62/76, and will continue to be as such for the
entirety of the fall 2020 rating.
---
=> Redirect routes 62 and 76 to the combined 627 pages

apps/site/assets/js/photo-gallery.js
**Asana Ticket:** [🐞 Photo galleries on IE11](https://app.asana.com/0/555089885850811/1164009353180158)
Fix for image galleries not being displayed when using IE.<br/>
_Before_:
_After_:
=> Use fallback retrieval strategy to display photos

apps/route_patterns/lib/repo.ex, apps/route_patterns/test/repo_test.exs, apps/site/assets/ts/schedule/components/ScheduleDirection.tsx, apps/site/assets/ts/schedule/components/__tests__/ScheduleDirectionTest.tsx, apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/lib/site_web/controllers/schedule/line_api.ex, apps/site/lib/site_web/controllers/schedule/map_api.ex, apps/site/test/site_web/controllers/line_api_test.exs, apps/site/test/site_web/controllers/schedule/line/diagram_helpers_test.exs, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs, apps/site/test/site_web/controllers/schedule/map_api_test.exs, apps/stops/lib/route_stop.ex, apps/stops/lib/route_stops.ex, apps/stops/test/route_stop_test.exs, apps/stops/test/route_stops_test.exs, apps/v3_api/lib/route_patterns.ex, apps/v3_api/test/route_patterns_test.exs
**Asana Ticket:** [Tech Debt | Line page: remove dependency on shape.stops](https://app.asana.com/0/555089885850811/1145443859488281)
Use route patterns to get branch route stops
Get data for a specific route pattern, where applicable, only for buses.
Only the final commit includes functional changes. Before that, I refactored a bit to remove duplicate functionality and added a bunch of tests to prove the behavior I needed to match with the route pattern change.
---
=> Use route patterns to get branch route stops

apps/fares/lib/fare_info.ex, apps/fares/test/fare_info_test.exs, apps/site/lib/site_web/templates/mode/index.html.eex
**Asana Ticket:** [Fare Change | Fare cards updates for 9/1 transition](https://app.asana.com/0/399597520748778/1186724915893667)
After the changeover date, adjust fare matches so charlie_card, charlie_ticket, and cash all have equal prices on subway/bus single trips (one-way). This affects the descriptive output around the site, such as "with a CharlieCard, CharlieTicket, or Cash."
I tried to make this as small as possible, rather than creating branches for each modes' existing `mapper/1` fare mapping. I recommend yanking this and the other sep_1_2020 logic after the changeover date.
---
=> Combine CharlieCard and Ticket/Cash media prices after Sep. 1, 2020

apps/site/assets/js/photo-gallery.js
**Asana Ticket:** [🐞 Photo galleries on IE11 only showing first image](https://app.asana.com/0/555089885850811/1190988214208156)
In IE11 (works fine in other browsers), the photo galleries do nothing: clicking on the thumbnails should display the selected image in the bigger area.
=> Fix for photo galleries not working in IE11

apps/fares/lib/fare_info.ex, apps/fares/test/fare_info_test.exs, apps/site/assets/css/_trip-plan-fare-calculator.scss, apps/site/lib/site_web/templates/trip_plan/_fare_calculator.html.eex
**Asana Ticket:** [🎫 Trip Planner | Eliminate CharlieCard - CharlieTicket/Cash differential](https://app.asana.com/0/555089885850811/1187029333962715)
Remove "Recommended" column from Fare Calculator after the fare transition on 9/1.
~~Depends on https://github.com/mbta/dotcom/pull/602~~
---
=> Remove "Recommended" column from Fare Calculator

apps/site/test/site_web/controllers/schedule/finder_api_test.exs
Use Date sorting to properly sort dates
No ticket, tests were failing because we were using the wrong service.
---
=> Use Date sorting to properly sort dates

apps/site/mix.exs, apps/site/test/site_web/controllers/schedule/finder_api_test.exs
Define route_patterns before stops for dependencies
No ticket, dev builds have been failing since https://github.com/mbta/dotcom/pull/599
Depends on https://github.com/mbta/dotcom/pull/606
---
=> Define route_patterns before stops for dependencies

apps/site/assets/css/_schedule-page-line-diagram.scss, apps/site/assets/ts/models/prediction.ts, apps/site/assets/ts/schedule/components/line-diagram/LineDiagramWithStops.tsx, apps/site/assets/ts/schedule/components/line-diagram/LiveCrowdingIcon.tsx, apps/site/assets/ts/schedule/components/line-diagram/StopPredictions.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/LineDiagramWithStopsTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LiveCrowdingIconTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/StopPredictionsTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/lineDiagramData/live-data.json, apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/UpcomingDepartures.tsx, apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/__tests__/UpcomingDeparturesTest.tsx
**Asana Ticket:** [🐞 Regression/Bug | Crowding column not collapsed properly on routes w/o crowding](https://app.asana.com/0/385363666817452/1190437676035289/f)
Introduced a CSS class to add to the parent element to handle hiding all the crowding icons when needed.
---
=> 🐞 Regression/Bug | Crowding column not collapsed properly on routes w/o crowding

apps/feedback/config/dev.exs, apps/feedback/lib/mock_aws.ex
**Asana Ticket:** [🔧 Mock version of ExAws.Operation.perform for dev](https://app.asana.com/0/555089885850811/1193042951805049)
Add a mock version of ExAws.Operation.perform for dev
NB to use, set the `LOGGER_LEVEL` env var: `LOGGER_LEVEL=info`.
---
=> Add a mock version of ExAws.Operation.perform for dev

apps/site/assets/css/_accordion-ui.scss, apps/site/assets/css/_customer-support.scss, apps/site/assets/css/_mixins.scss, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_call_us.html.eex, apps/site/lib/site_web/templates/customer_support/_lost_and_found.html.eex, apps/site/lib/site_web/templates/customer_support/_report.html.eex, apps/site/lib/site_web/templates/customer_support/_request_public_records.html.eex, apps/site/lib/site_web/templates/customer_support/_service_updates.html.eex, apps/site/lib/site_web/templates/customer_support/_transit_police.html.eex, apps/site/lib/site_web/templates/customer_support/_write_to_us.html.eex, apps/site/lib/site_web/templates/customer_support/index.html.eex, apps/site/lib/site_web/templates/partial/_expandable_block.html.eex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
**Asana Ticket:** [☎️ Make a new sidebar for static information](https://app.asana.com/0/555089885850811/1188535657153252)
The page has been rearranged. Content is now displayed on the right side and there is a flag that can be set to initially set the blocks as expanded when loading the page.
Before:
After:
=> Sidebar with static information

apps/site/lib/site_web/controllers/schedule/timetable_controller.ex, apps/site/test/site_web/controllers/schedule/timetable_controller_test.exs
**Asana Ticket:** [⏱️ Commuter Rail Schedules | Some "via Fairmount" trips missing from Franklin Line ](https://app.asana.com/0/385363666817452/1188018759297667/f)
Added a few missing trips so the timetable display matches the PDF.
---
=> ⏱️ Commuter Rail Schedules | Some "via Fairmount" trips missing from Franklin Line 

apps/feedback/lib/mailer.ex, apps/feedback/lib/message.ex, apps/feedback/test/mailer_test.exs, apps/site/lib/site_web/controllers/customer_support_controller.ex
**Asana Ticket:** [☎️ Add support for First and Last names (to replace Full Name)](https://app.asana.com/0/555089885850811/1188547161220115)
Update message and mailer logic (and adjust tests): account for first & last name instead of just one field for name.
=> ☎️ Add support for First and Last names (to replace Full Name)

apps/site/test/site_web/controllers/schedule/origin_destination_test.exs
Update test to handle both sides of the Nubian stop ID change
This will pass against either the old or the new value. Once the
`place-nubn` data change is live in production, we can revert to the
simple equality check.
No ticket, just noticed the failure when investigating the new data on dev-green.
---
=> Update test to handle both sides of the Nubian stop ID change

apps/site/assets/css/_customer-support.scss, apps/site/assets/css/_utilities.scss, apps/site/assets/js/support-form.js, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/lib/site_web/templates/customer_support/index.html.eex, apps/site/lib/site_web/views/customer_support_view.ex
**Asana Ticket:** [☎️ Organize the customer support form](https://app.asana.com/0/385363666817452/1188535657153272/f)
Implements the intermediate customer support form design that will reign until we complete the epic.
* Adds reworded section headings
* Restructures the grey sections to match the mockup
* Arranges the category radio buttons vertically
* Moves and rephrases the "responses may take up to 5 days disclaimer"
There's a fair amount of code cleanup since I wanted to leave things in good shape for us to start adding new fields! Mostly I'm trying to reduce some duplication in the templates by moving a few key pieces over to functions in the Elixir view we can use to generate error messages, placeholder text, and help text. Tried to do all of this carefully as to not break any of …
=> ☎️ Organize the customer support form

apps/site/assets/css/_customer-support.scss, apps/site/assets/css/_utilities.scss, apps/site/assets/js/support-form.js, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/lib/site_web/templates/customer_support/index.html.eex, apps/site/lib/site_web/views/customer_support_view.ex
Reverts mbta/dotcom#624
After submitting the form the confirmation message does not appear and the sidebar incorrectly appears on the left-hand side of the screen. Reverting until we can correct this behavior.
=> Revert "☎️ Organize the customer support form"

apps/feedback/test/mailer_test.exs
Use configuration settings for test expectations
If you've changed these values in your `.env` file the tests would fail
for you.
No ticket, just fixes a problem I've been experiencing.
---
=> Use configuration settings for test expectations

apps/feedback/lib/mailer.ex, apps/feedback/lib/message.ex, apps/feedback/test/mailer_test.exs, apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/test/site_web/controllers/customer_support_controller_test.exs, apps/site/test/site_web/integration/support_form_test.exs
**Asana Ticket:** [☎️ Reverse the "I would like a response" default](https://app.asana.com/0/385363666817452/1188535657153270/f)
Changes the copy on the frontend, shows the response form on the front end by default, and aligns the logic on the `CUSTREQUIRERESP` field.
Also decided to change the _name_ of the relevant variable from request_response to no_request_response such that a "positive" response (checked) means "No" (it's less confusing for my brain, at least).
---
=> Reverse the "I would like a response" default

apps/feedback/lib/mailer.ex, apps/feedback/lib/message.ex, apps/feedback/test/mailer_test.exs, apps/feedback/test/message_test.exs, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
**Asana Ticket:** [☎️ Add support for a new Subject field](https://app.asana.com/0/555089885850811/1188535657153274)
Add back-end support for a new Subject field
Submit subject to Heat in `CATEGORY` field.
Generate Heat `TOPIC` based on the service and subject.
---
=> Add back-end support for a new Subject field

apps/site/lib/site_web/templates/layout/app.html.eex
Asana ticket: [Remove Facebook verification meta-tag](https://app.asana.com/0/385363666817452/1193278706153525)
Reverts mbta/dotcom#620
Our domain has been associated with our Facebook account, so this is no longer needed.
=> Remove Facebook domain verification meta tag

apps/feedback/lib/mailer.ex, apps/feedback/lib/message.ex, apps/feedback/test/mailer_test.exs
**Asana Ticket:** [☎️ Add support for CharlieCard or Ticket number](https://app.asana.com/0/385363666817452/1188535657153277/f)
Adds backend support for a new ticket_number field that will be submitted along with the comments.
---
=> ☎️ Add support for CharlieCard or Ticket number

apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/lib/site_web/views/customer_support_view.ex
**Asana Ticket:** [☎️ Add Subject field to the customer support form](https://app.asana.com/0/385363666817452/1188535657153281/f)
Front end support for the (not yet required) subject field and its interaction with the value selected from the service category radio inputs.
---
=> Add Subject field to the customer support form

apps/feedback/lib/mailer.ex, apps/feedback/lib/message.ex, apps/site/assets/css/_customer-support.scss, apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/lib/site_web/views/customer_support_view.ex, apps/site/lib/site_web/views/helpers.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
[☎️ Additional Details: Mode, Route, and Vehicle number (frontend)](https://app.asana.com/0/555089885850811/1188547161220086)
[☎️ Additional Details: Mode, Route, and Vehicle number (backend)](https://app.asana.com/0/555089885850811/1188535657153279)
These three extra fields have been added to the Customer Support form:
The routes and label for the vehicle field are both refreshed depending on the choice for mode.
=> Support for mode, route and vehicle number

apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/assets/package-lock.json, apps/site/assets/package.json
**Asana Ticket:** [☎️ Profanity sanitizer](https://app.asana.com/0/385363666817452/1188547161220113/f)
Uses the `bad-words` package to filter the text in the comments field before sending to the backend.
I didn't have the heart to put curse words in our codebase, so the test that I wrote for it modifies the library's behavior a bit to add a fake curse word... hopefully you get the idea 😅
=> Run message body through profanity sanitizer

apps/site/lib/site_web/templates/customer_support/index.html.eex
No ticket, just a regression I'd noticed. Right now the customer support form always says at top "Your comments have been sent to our Customer Support team." :)
=> Move confirmation message inside the hidden div

apps/site/assets/css/_transit-near-me.scss, apps/site/assets/ts/__v3api.d.ts, apps/site/assets/ts/components/StopCard.tsx, apps/site/assets/ts/components/__tests__/AlertsTest.tsx, apps/site/assets/ts/models/__tests__/alert-test.ts, apps/site/assets/ts/models/alert.ts, apps/site/assets/ts/stop/__tests__/AlertsTabTest.tsx, apps/site/assets/ts/stop/__tests__/RouteCardTest.tsx, apps/site/assets/ts/stop/__tests__/StopPageTest.tsx, apps/site/assets/ts/stop/components/RouteCard.tsx, apps/site/assets/ts/tnm/components/RouteCard.tsx
**Asana Ticket:** [Stops | Shuttle Alert should be restricted to affected stations](https://app.asana.com/0/385363666817452/1190590218814913/f)
In Transit Near Me and on the Stop pages, route cards show an alert icon and effect text when there is a diversion anywhere on the route. This update refines the logic and restricts showing this unless the relevant _stop_ is also affected.
Also includes a bugfix to remove duplicate texts.
Without changes, Boylston (not affected by shuttle) vs Copley (affected by shuttle):
With changes, Boylston vs. Copley:
---
=> Stops | Shuttle Alert should be restricted to affected stations

apps/site/lib/site_web/templates/trip_plan/vote.html.eex
just fixing an unclosed `h5` tag that was causing slight styling issues.
=> fix: unclosed  h5 tag in template

apps/fares/lib/fares.ex, apps/fares/test/fares_test.exs
**Asana Ticket:** [🐞 Elixir.ArgumentError: argument error](https://app.asana.com/0/385363666817452/1191566494821186)
The trip details could not be loaded because the logic was trying to convert "1A-2" to an integer.
Before:
After:
=> Fix for error when trying to convert "1A-2" to integer

bin/.gitignore, bin/lib/git.py, bin/lib/input.py, bin/lib/tag.py, bin/release, docs/DEPLOYMENT.md
**Asana Ticket:** [Determine the info from git to be able to print out everything you need to make a release manually](https://app.asana.com/0/385363666817452/1198965985597277/f)
which is the first step for [🔧 Use a script to automate GitHub releases](https://app.asana.com/0/385363666817452/1185680283158788/f)
Add a script to assist with creating GitHub releases
Currently, it asks you to confirm some defaults and generates everything
you'll need to create a release manually in your browser. For a next
phase, it would be nice if it used the GitHub API to create the release
for you. I want to get that going next, but this already provides substantial value during the deploy process so it seems like it's worth getting in right away.
---
=> Add a script to assist with creating GitHub releases

.envrc.template, apps/site/lib/site/schedule_note.ex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/detailed_stop_group_test.exs, build.sh
**Asana Ticket:** [Authenticate Docker pulls in Semaphore](https://app.asana.com/0/555089885850811/1198513525489765)
In Semaphore, we use DOCKER_USERNAME and DOCKER_PASSWORD for our DockerHub credentials. This changes the `build.sh` script to log in to DockerHub before doing other actions if those credentials are available.
The removal of `-x` from the `set` command prevents the password from being echoed during the build.
---
=> feat: authenticate with Docker Hub if credentials are available

apps/site/assets/css/_accordion-ui.scss, apps/site/assets/css/_customer-support.scss, apps/site/lib/site_web/templates/partial/_accordion_ui.html.eex, apps/site/lib/site_web/templates/partial/_expandable_block.html.eex, apps/site/test/site_web/views/paragraph_view_test.exs
**Asana Ticket:** [🐞 Translation | Accordions do not open in Google Translate tool](https://app.asana.com/0/555089885850811/1191214531803714)
Google translate seems to translate the `href` content as well, so we are using buttons instead of anchors and making the necessary readjustments on the CSS side accordingly.
These changes actually shouldn't have any visual impact.
=> Fix for accordions not expanding (when translating page)

README.md, docs/SeasonalFeatures.md
I wanted to document how to bring the polling location map back and figured I can start a page to store notes on similar features, welcome any thoughts!
=> docs: add new doc for temporary features

apps/trip_plan/lib/trip_plan/api/open_trip_planner/parser.ex, apps/trip_plan/mix.exs
**Asana Ticket:** [🐞 Elixir.ArithmeticError: bad argument in arithmetic expression](https://app.asana.com/0/385363666817452/1196095462687838)
Use of `fast_local_datetime` to prevent errors when calculating the trip duration in the Trip Planner.
=> Prevent error when formatting duration

apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
**Asana Ticket:** [🐞 Silver Line should not show under Subway mode](https://app.asana.com/0/555089885850811/1198980474686141)
Removing Silver Line from the list of options for Subway.
=> Customer support form: subway should not include Silver Line

apps/site/assets/css/_buttons.scss
**Asana Ticket:** [🐞 Button text should wrap](https://app.asana.com/0/385363666817452/1186495960085451)
Small fix to this bug.
Before:
After:
=> Prevent text of button from overflowing

apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/UpcomingDepartures.tsx
**Asana Ticket:** Partial solution to [🐞 Schedule Finder | Error Loading Trip Details](https://app.asana.com/0/555089885850811/1191999214380060)
Filter trips with a `tripInfo` value of `null` in Upcoming Departures.
=> Filter trips without tripInfo

apps/feedback/lib/mailer.ex, apps/feedback/test/mailer_test.exs, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/util/lib/util.ex, apps/util/test/util_test.exs
**Asana Ticket:** [🐞 Times (not) coming through in UTC time](https://app.asana.com/0/555089885850811/1198956720242891)
Ensure the date and time of incident is properly converted to UTC time in the message sent to HEAT.
=> Convert incident datetime to UTC

apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
Previously, we only assigned this data in the `index/2` function. However,
this is also required if the submission fails, when we re-render the form. We
can see this by removing all of extra `assign/3` calls in the unit tests.
To fix, we pull this behavior into a plug, so that we will always assign this
data regardless of function is originally called.
Asana: https://app.asana.com/0/555089885850811/1198960312594553
---
=> fix: always assign `:all_options_per_mode`

apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/assets/package-lock.json, apps/site/assets/package.json
**Asana Ticket:** [Restore profanity sanitizer in Customer Support form](https://app.asana.com/0/555089885850811/1199207412558094)
It's essentially the same changes from PR #646 but with the downgraded version so the new customer support form works in IE without breaking.
=> Restore profanity sanitizer to an IE-compatible version

apps/site/assets/css/_banner.scss
**Asana Ticket:** [🐞 Projects | SCSS: Focus state causes blue underlines below white text](https://app.asana.com/0/555089885850811/1156601525508738)
Set a color for the `Banner` text when focused depending on the mode.
=> Banner in focused state

.dialyzer.ignore-warnings, apps/site/lib/site_web/banneralert.ex, apps/site/lib/site_web/templates/alert/_banner.html.eex, apps/site/lib/site_web/templates/layout/_alert_announcement.html.eex, apps/site/lib/site_web/views/alert_view.ex, apps/site/test/site_web/banneralert_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs
Fix for the `Elixir.BadMapError: expected a map, got: nil` bug with the following trace
```shell
Elixir.BadMapError: expected a map, got: nil
File "lib/site_web/templates/layout/_alert_announcement.html.eex", line 2, in SiteWeb.LayoutView."_alert_announcement.html"/1
File "lib/site_web/templates/layout/app.html.eex", line 53, in SiteWeb.LayoutView."app.html"/1
File "lib/phoenix/view.ex", line 399, in Phoenix.View.render_to_iodata/3
File "lib/phoenix/controller.ex", line 729, in Phoenix.Controller.__put_render__/5
File "lib/phoenix/controller.ex", line 746, in Phoenix.Controller.instrument_render_and_send/4
...
(3 additional frame(s) were not displayed)
(BadMapError) expected a map, got: nil
```
, which appears in a variety of tickets.
Since `Alerts.Repo.by_id/1` can potentially return …
=> Adjust _alert_announcement.html.eex to handle nil alert

apps/site/test/site_web/controllers/schedule/line_test.exs
The new winter rating probably threw off these test results that involves services and service dates. This change makes a quick edit to the dates involved.
=> fix(LineTest): Bump service dates to next year

apps/site/lib/site_web/controllers/schedule/trip_info.ex, apps/site/test/site_web/controllers/schedule/trip_info_test.exs
**Asana Ticket:** [🐞 Elixir.UndefinedFunctionError: function nil.id/0 is undefined](https://app.asana.com/0/555089885850811/1196094168100899)
We weren't taking into account when something other than a list is returned: https://github.com/mbta/dotcom/blob/a34a39656e3cbc86ab0f5178e8511b9281526963/apps/site/lib/site_web/controllers/schedule/trip_info.ex#L96
<br/> With this fix we make sure even the error is returned for its subsequent handling (in `handle_trip`).
=> Return the error when one is received

apps/site/assets/css/_customer-support.scss, apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/lib/site_web/templates/customer_support/_form.html.eex, apps/site/lib/site_web/views/customer_support_view.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
**Asana Ticket:** [Customer Support | Don't allow letters in the vehicle number field](https://app.asana.com/0/385363666817452/1199530274677105/f)
Adds front and back end validation for the vehicle number field. Blank/no entry is ok since the field is optional, but if filled it should contain numeric characters only.
---
=> feat: Add validation for vehicle number field

apps/site/lib/site_web/controllers/schedule/map_api.ex, apps/site/test/site_web/controllers/schedule/map_api_test.exs
**Asana Ticket:** [🐞 Elixir.FunctionClauseError: no function clause matching in Stops.RouteStops.branch/1](https://app.asana.com/0/555089885850811/1191546277787129)
I'm not sure if this is a valid solution, hence the draft PR. If it is, I will create the corresponding test for it.
=> Account for empty list of stops

apps/site/lib/site_web/views/date_time_selector.ex, apps/site/test/site_web/controllers/trip_plan_controller_test.exs
[Elixir.ArgumentError: unrecognized time %{"hour" => "6"}](https://app.asana.com/0/385363666817452/1199213920216686)
[Elixir.ArgumentError: unrecognized date %{"am_pm" => "PM", "hour" => "4", "minute" => "20"}](https://app.asana.com/0/385363666817452/1199148636489026)
Ensure all fields for the date selector are included
=> Default to today's date and time values if they are missing

apps/site/assets/ts/tnm/transit-near-me-loader.tsx
A [recent failed build](https://semaphoreci.com/mbta/dotcom/branches/dependabot-npm_and_yarn-apps-site-react_renderer-typescript-4-1-3/builds/3) inspired to me look into this... and it seems these functions aren't used by anything else, so I'm removing this.
=> Remove unused functions

apps/site/assets/js/support-form.js, apps/site/assets/js/test/support-form_test.js, apps/site/lib/site_web/templates/customer_support/_form.html.eex
**Asana Ticket:** [Customer Support | Indicate customers need to choose category before subject](https://app.asana.com/0/385363666817452/1199530274677101/f)
On the Customer Support form, dynamically show the Subject selector once the user selects a Category. Deploying on [dev-blue](https://dev-blue.mbtace.com/ ) for review.
=> fix: Hide subject when category is not selected

bin/lib/git.py, bin/release
**Asana Ticket:** [🔧 Use a script to automate GitHub releases](https://app.asana.com/0/385363666817452/1185680283158788/f)
I pretty much used the approach described in the ticket. I thought about using GitHub actions, but this was easier for me to wrap my head around and quick enough to implement for now!
One change to the previous functionality is that it no longer looks at `HEAD` - it'll default to the latest commit on `origin/master`. This made it easier for me to use and I think makes more sense for this case.
It worked to create https://github.com/mbta/dotcom/releases/tag/2021.01.08.1 for me.
=> 🔧 Use a script to automate GitHub releases

apps/site/lib/site/map_helpers.ex
**Asana Ticket:** [Subway map image missing on hub page](https://app.asana.com/0/385363666817452/1199557225682592/f)
Updating the file URL so we don't have a broken map.
=> fix: Update file URL for subway map

apps/site/lib/site/map_helpers.ex, apps/site/test/site_web/controllers/schedule_controller_test.exs
**Asana Ticket:** [⛴️ Update ferry map image on schedule pages on 1/23](https://app.asana.com/0/385363666817452/1199557187663968)
Changed the Ferry images' URL (to go live on January 23rd, 2021).
=> Change image in Ferry pages

apps/site/assets/js/datepicker-input.js, apps/site/assets/js/test/datepicker-input_test.js
**Asana Ticket:** [☎️ Form focus should start at the first form entry](https://app.asana.com/0/1149164109017504/1199512946850968)
The date picker input (which I learned is distinct from the date picker! haha!) had no tests so I added some.
I interpreted the spirit of the ticket to be more "don't focus on the date picker on page load" rather than "must focus on the first input on page load", so that's what I did.
---
=> fix: Don't focus on the datepicker input on load

apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/test/site_web/controllers/schedule/line_test.exs
**Asana Ticket:** [Elixir.CaseClauseError: no case clause matching: {:error, [:missing_input_response]}](https://app.asana.com/0/385363666817452/1199384885875519)
A POST submission encountered an [error captured in Sentry](https://sentry.io/organizations/mbtace/issues/1574387026/?project=194344) due to a scenario that we were not taking into account. This is just a small PR to fix that.
Contains an unrelated fix for a test to make it pass.
=> Add recaptcha error to the list of errors to prevent crash

README.md
**Asana Ticket:** [Dotcom README | Add items learned from recent onboarding](https://app.asana.com/0/555089885850811/1199640127454896) and [Add API onboarding doc / link to it from Dotcom](https://app.asana.com/0/555089885850811/1199177600097662) 
This covers 2 tickets.  
1. Added the link to the API onboarding doc from the mbta/wiki
2. Made adjustments learned from my recent onboarding (documented in the Asana ticket)
=> README:  Added onboarding fixes and link to API wiki document

apps/site/lib/site_web/templates/alert/_banner.html.eex, apps/site/lib/site_web/templates/alert/_item.html.eex
**Asana Ticket:** [Lack of a space between the alert type and the upcoming/ongoing pill](https://app.asana.com/0/555089885850811/1199649873115875)
Before:
<br/>
After:
=> Add space between alert type and pill

upload_assets.sh
**Asana Ticket:** [🔧 uploaded fonts have the wrong content-type](https://app.asana.com/0/385363666817452/1130215014531939)
Initial attempt at fixing the font content-type issue. AWS tries to guess the mime-types for files, and it's usually correct, except for fonts.
I have no idea when this upload_assets.sh script is run, or where it's expected to be run from, so I'm not sure this would actually fix anything! Hoping someone who knows more than me here can chime in.
=> Add content-type to aws s3 sync for fonts

apps/site/test/site/lib/vehicle_helpers_test.exs, apps/site/test/site_web/controllers/schedule/finder_api_test.exs, apps/site/test/site_web/controllers/schedule/green_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/controllers/stop_controller_test.exs, apps/stops/test/repo_test.exs, apps/stops/test/route_stop_test.exs, apps/stops/test/route_stops_test.exs
No ticket. Some test-related work:
- Skip tests that are related to ferries since there is currently almost no service.
- Readjust test for Commuter Rail schedule
- _Unskip_ tests that were skipped in the past.
=> Readjust tests

apps/stops/test/repo_test.exs
The newly added shuttle for CR-Fitchburg has Alewife as a stop, which wasn't accounted for in our test. Let's update this value to match so CI can finally pass.
=> chore: Update test for CR-Fitchburg shuttle stop

apps/site/lib/site_web/controllers/schedule/finder_api.ex, apps/site/test/site_web/controllers/schedule/finder_api_test.exs, apps/site/test/site_web/controllers/trip_plan_controller_test.exs
**Asana Ticket:** [Elixir.BadMapError: expected a map, got: nil](https://app.asana.com/0/385363666817452/1199209865060987)
As mentioned in [this comment from a previous PR](https://github.com/mbta/dotcom/pull/755#discussion_r562965381), we don't want to discard journeys where the schedule is nil and the prediction is not, but when _both_ are nil we might want to, since they contain no useful information.
=> Remove journeys without a prediction nor a schedule

apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/stops/lib/repo.ex, apps/stops/test/repo_test.exs
**Asana Ticket:** [🐞 Stations/Stops | South Station should have SL icon](https://app.asana.com/0/555089885850811/1163960794131366)
Show the silver line for South Station.
Before:
After:
<br/>
=> Show the Silver Line icon for South Station instead of the bus one

apps/cms/lib/helpers.ex, apps/cms/test/helpers_test.exs
**Asana Ticket:** [Accessibility | Page History, July 1, 2018](https://app.asana.com/0/inbox/443102729541666/1199897989131032/1199901496261429)
On rare occasion, the CMS may provide a NULL paragraph in its JSON response. Add a clause for this and don't attempt to render it. Related to mbta/cms#353
---
=> WIP - don't choke on NULL paragraphs

apps/site/assets/css/_events.scss, apps/site/lib/site_web/controllers/event_controller.ex, apps/site/lib/site_web/query_builders/event_date_range.ex, apps/site/lib/site_web/templates/event/_event_list.html.eex, apps/site/lib/site_web/templates/event/index.html.eex, apps/site/lib/site_web/views/event_view.ex, apps/site/test/site_web/controllers/event_controller_test.exs, apps/site/test/site_web/query_builders/event_date_range_test.exs, apps/site/test/site_web/views/event_view_test.exs
**Asana Ticket:** [Put all the months on the same page (show all events for the year)](https://app.asana.com/0/385363666817452/1199915858612058/f)
Removes the month navigation header entirely.
I thought about removing/replacing the `EventDateRange` functions that work with months, but I figure we'll want them for the calendar view later on so I left them in. 
---
=> Put all the months on the same page (show all events for the year)

apps/site/lib/site_web/templates/stop/_detailed_stop.html.eex, apps/site/lib/site_web/templates/stop/_hub_stops.html.eex, apps/stops/lib/api.ex
**Asana Ticket:** [Schedules | Fare Zones should not show for bus, ferry, and subway](https://app.asana.com/0/555089885850811/1199882294203912)
In the Stations page we won't be showing fare zones. Before:
After:
In the schedule finder modal, we won't be showing zones unless it's a commuter rail route. E.g. for buses:
For commuter rail:
Same for a specific stop:
Commuter rail:
Bus before:
Bus now:
=> Show fare zones only for commuter rail

apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs
**Asana Ticket:** [Line Diagram | Shuttles should not break the line](https://app.asana.com/0/385363666817452/1199904083874239/f)
There are actually two different problems being tackled here. Going to deploy on dev green to make it easier to check many routes with the green dev API data.
CR-Kingston was broken because the line diagram decided that _South Station - Kingston_ and _South Station - Plymouth via Kingston_ were two separate branches. The latter route pattern covers all of the same stops the former one does, so we choose to show only _South Station - Plymouth via Kingston_ on the line diagram.
The chosen fix adds a new function, `overall_branch`, that takes lists of stops and finds the list whose stops cover all of the stops on all other lists. E.g. one branch to rule them all. …
=> Fixing various broken line diagram issues

apps/site/lib/site/trip_plan/map.ex, apps/site/lib/site_web/controllers/trip_plan_controller.ex, apps/site/lib/site_web/router.ex, apps/site/test/site_web/controllers/schedule/finder_api_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/controllers/trip_plan_controller_test.exs, apps/site/test/site_web/router_test.exs, apps/trip_plan/lib/trip_plan/leg.ex
**Asana Ticket:** [Trip Planner | Add ability to link to Trip Planner with pre-filled destination](https://app.asana.com/0/555089885850811/1199926921659622)
A new route `/to/[address]` has been created to geolocate the destination address in the Trip Planner. Example:
https://mbta.com/trip-planner/to/Boston%20Common will render:
Similarly, it will identify places as well:
https://mbta.com/trip-planner/to/mgh
=> Prepopulate 'to' field in Trip Planner

apps/site/assets/css/_schedule.scss, apps/site/lib/site_web/controllers/schedule/green.ex, apps/site/lib/site_web/controllers/schedule/trip_view_controller.ex, apps/site/lib/site_web/templates/schedule/_line.html.eex, apps/site/lib/site_web/views/schedule_view.ex, apps/site/test/site_web/controllers/schedule/green_test.exs, apps/site/test/site_web/controllers/schedule_controller_test.exs, apps/site/test/site_web/views/schedule_view_test.exs
**Asana Ticket:** [⏱Remove Schedule Tab](https://app.asana.com/0/385363666817452/1144217912503868/f)
For March 1 - this change (a) hides the schedules tab, (b) redirects schedule tab URLs to the info & maps tab, bringing along query params, (c) renames "info & maps" tab to "schedules & maps"
=> Remove schedule tab

apps/site/assets/css/_events.scss, apps/site/assets/js/app.js, apps/site/assets/js/view-previous-events.js, apps/site/lib/site_web/templates/event/_event_list.html.eex, apps/site/lib/site_web/views/event_view.ex, apps/site/test/site_web/views/event_view_test.exs
**Asana Ticket:** [Add "previous listing for the month" link to top of the page](https://app.asana.com/0/555089885850811/1199915858612052)
Currently, simplified to a button that says "View Previous { current month / year } Events".  Once we separate pages by month, we'll need to make button visibility conditional on whether we're looking at the current month.
---
=> Previous event listings for month

apps/site/config/config.exs, apps/site/lib/site_web/templates/event/show.html.eex, apps/site/test/site_web/controllers/event_controller_test.exs
Recently, we'd been using feature branches to manage the development of medium-to-long-term work. This has proven to be somewhat tricky to manage, particularly as the master branch diverges over time.
Earlier we used to use flags to enable/disable big features. I don't think you're all familiar with the `Laboratory` module -- so I will add some details over Slack on how to find it and use it! 😉
This PR implements that approach for the **event page**. (I should've done this with the current events listing work, but I think we're too far into it to set up a flag for that now. Better late than never!)
With this enabled, we can proceed with development while continuing to merge into master. When finally ready for the reveal, we can remove the flag and tweak the code to permanently show the …
=> Add event page flag

apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/ServiceOptGroup.tsx
**Asana Ticket:** [Schedules | Services picker should show distinctive title for CR shuttles](https://app.asana.com/0/385363666817452/1199903984955228/f)
Prior logic wouldn't show the description in the services picker when it's for a planned disruption. Probably will deploy on dev green.
Thanks @jfabi for tipping us off on this!
=> fix: Show description for planned disruptions

apps/fares/lib/proposed_locations.ex, apps/fares/lib/proposed_locations/location.ex, apps/fares/mix.exs, apps/fares/test/proposed_locations_test.exs, apps/google_maps/lib/google_maps/geocode.ex, apps/google_maps/test/google_maps/geocode_test.exs, apps/site/lib/site_web/controllers/fare_controller.ex, apps/site/lib/site_web/controllers/fare_transformation_controller.ex, apps/site/lib/site_web/plugs/transit_near_me.ex, apps/site/lib/site_web/templates/fare_transformation/proposed_sales_locations.html.eex, apps/site/lib/site_web/views/fare_transformation_view.ex, apps/site/test/site_web/controllers/fare_controller_test.exs, apps/site/test/site_web/controllers/fare_transformation_controller_test.exs, apps/util/lib/distance.ex
Polish work for the Proposed Sales Location page:
- Minor tweaks (increase radius, rewording sentences).
- sort locations by distance
- stronger address validation to accept a string with different location formats (address or lat/lon).
=> PSL polish

apps/route_patterns/lib/repo.ex, apps/site/lib/predicted_schedule.ex, apps/site/lib/site_web/controllers/schedule/finder_api.ex, apps/site/lib/site_web/controllers/schedule/vehicle_locations.ex, apps/site/test/site_web/controllers/schedule/vehicle_locations_test.exs
**Asana Tickets:** 
- [Elixir.UndefinedFunctionError: function nil.id/0 is undefined](https://app.asana.com/0/0/1200037415890637/f) (https://github.com/mbta/dotcom/commit/eab4b374185b7e8c8269b004e4b236101916fb11)
- [Elixir.Protocol.UndefinedError: protocol Enumerable not implemented for {:error, %HTTPoison.Error{id: nil, reason: :checkout_time...](https://app.asana.com/0/0/1200037380808745/f) (https://github.com/mbta/dotcom/commit/12dd7b9257dfc10abe9f0773e8e82eee5fdf6f1d)
- [Elixir.Protocol.UndefinedError: protocol Enumerable not implemented for {:error, %HTTPoison.Error{id: nil, reason: :checkout_time...](https://app.asana.com/0/0/1200037278955026/f) - (https://github.com/mbta/dotcom/commit/6a97d1909728ac25b610c3e27dfda89f29f3332e and …
=> assorted error catching 🐞🔨

apps/site/assets/.stylelintrc, apps/site/assets/ts/schedule/components/direction/__tests__/reducer-test.tsx, apps/site/assets/ts/schedule/components/direction/reducer.ts, apps/site/test/predicted_schedule_test.exs, apps/site/test/site_web/controllers/schedule/finder_api_test.exs
**Asana Ticket:** [🐞 The schedule view changes your route variant when you change direction](https://app.asana.com/0/555089885850811/1179129122227742)
When toggling `directionId` having an existing route pattern, an attempt to get the "analogous" route pattern for the toggled directionId will be made.
E.g.: if we toggle from `directionId=0` and `route pattern=111-5-0` to `directionId=1`, we'll try to see if `route pattern=111-5-1` exists. Otherwise, default to the first route pattern from the list (for the new directionId).
=> Attempt to find the analogous route pattern

apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs
**Asana Ticket:** [Schedules | Should not include route patterns for multi route trips](https://app.asana.com/0/385363666817452/1200081044003352/f)
Added in after a test failure led me to find broken line diagrams as described in the ticket.
Also includes fixes for a few failing Green-E tests.
This fixes the line diagram but does not fix the map polylines -- I have a tentative approach for those but wanted to prioritize fixing the branching on the line diagram here, and also wanted to hold off since I know the map is being worked on right now anyway.
=> Hide line diagram branches created by multi route trips

apps/site/assets/css/_events.scss, apps/site/assets/js/event-page-setup.js, apps/site/assets/js/test/address-search_test.js, apps/site/assets/js/test/algolia-global-search_test.js, apps/site/assets/js/test/event-page-setup__test.js, apps/site/assets/js/test/trip-plan_test.js, apps/site/lib/site_web/templates/event/_calendar.html.eex, apps/site/lib/site_web/templates/event/index.html.eex, apps/site/lib/site_web/views/event_view.ex
**Asana Ticket:** [Add event listings to the grid](https://app.asana.com/0/385363666817452/1199915858612066/f)
There are a few noticeable issues which I plan to address in the 'Add toggle between views to navigation' ticket, including:
* rename URL parameter from calendar to cal
* keep all months in the left nav, not just the current one
* hide the calendar on mobile (presumably showing the list in its place)
* adding the working toggle
=> Add calendar grid

apps/site/assets/js/event-page-setup.js, apps/site/assets/package-lock.json, apps/site/assets/package.json, apps/site/assets/webpack.config.dev.js, apps/site/lib/site_web/templates/event/_event_list.html.eex, apps/site/lib/site_web/templates/event/index.html.eex
**Asana Ticket:** [Events listing page renders poorly in IE](https://app.asana.com/0/555089885850811/1200032439670460)
I had to use polyfills to avoid errors.
I also removed the class `fixedsticky` as it was causing issues on IE (and the "stickiness" seems to work even after said removal).
Also, the remaining errors in IE get fixed upgrading `phoenix_live_reload` to at least 1.1.4 (I checked): https://github.com/phoenixframework/phoenix_live_reload/blob/master/CHANGELOG.md
=> Events page renders poorly in IE

apps/site/lib/site_web/templates/fare_transformation/_nearby_locations.html.eex
**Asana Ticket:** [PSL | Add links to station/stop pages](https://app.asana.com/0/555089885850811/1200107561895262)
For PSL location cards, the stop / station name links to the stop / station page.
---
=> PSL stops link to stop page

apps/site/lib/site_web/controllers/event_controller.ex, apps/site/lib/site_web/templates/event/_year_select.html.eex, apps/site/lib/site_web/views/event_view.ex, apps/site/test/site_web/controllers/event_controller_test.exs, apps/site/test/site_web/views/event_view_test.exs
**Asana Ticket:** [Years without events should not appear in the year dropdown](https://app.asana.com/0/555089885850811/1200111821763338)
The logic makes sure that years without events are not part of the dropdown so they cannot be selected.
=> Hide years without events

apps/site/assets/ts/helpers/service.ts
The schedule finder defaults to selecting Saturday service today, which is definitely a weekday and not a Saturday.
Turns out it's because this week there's no school! And we have separate `services` for that.
With this change, I'm enabling the service picker to pick the weekday service as today's default, even though (if you look at the service data in the API) the weekday service listed in the dropdown technically starts _next week_, and a different service (that's filtered out in our backend) covers today. From a user perspective those two services (which are basically `weekday` and `weekday (no school)`) can be treated as the same service, but from a technical perspective we need this... 😅 
**Asana Ticket:** [Schedule Finder | Service picker defaults to wrong …
=> fix: Update isCurrentValidService logic

apps/site/assets/js/event-page-setup.js
**Asana Ticket:** [Overlays don't automatically close in IE](https://app.asana.com/0/555089885850811/1200196372897038)
Polyfill to avoid crashes in IE (although they're not visible/noticeable).
=> Add polyfill for `composedPath`

apps/site/assets/css/_events.scss, apps/site/lib/site_web/templates/event/index.html.eex
**Asana Ticket:** [The anchor link of the primary month in view should be emboldened in the left-hand menu](https://app.asana.com/0/555089885850811/1200111821763337)
Just some small changes to highlight the primary month.
=> Embolden primary month

apps/site/assets/ts/schedule/components/ScheduleNote.tsx, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/ScheduleNoteTest.tsx.snap, apps/site/lib/site/schedule_note.ex
**Asana Ticket:** [Schedules | Fix current hardcoded times in "schedule note"](https://app.asana.com/0/555089885850811/1200183759760091)
Updated headways to match https://docs.google.com/spreadsheets/d/15c8yVzkr-NgRqbMqJiT4zXTG4-09Z2zQwvainq9uIVI/edit#gid=1202875852.
Replaced hyphens with en dashes
Removed redundant AM in the Peak Service time listing.
=> Updated headways, en dashes

apps/schedules/test/repo_test.exs
No ticket, just a fix for a test related to the Lowell CR line that was failing due to shuttles. Replaced by Worcester.
=> Fix for test

apps/site/lib/site_web/controllers/schedule/line/maps.ex
**Asana Ticket:** [Schedules Map API | Elixir.FunctionClauseError: no function clause matching in SiteWeb.ScheduleController.Line.Maps.do_build_stop_marker/1](https://app.asana.com/0/555089885850811/1200280599638079)
Sometimes, when build_stop_marker tries to find a stop by id from the api, the stop can't be found (even though it was in the stop_id list).  In these rare cases, build_stop_marker will just return nil for that stop, and the calling function (`dynamic_map_data`) will filter out the nils from the stop_marker list.
I also removed the function `dynamic_markers` because there was duplicate code, and removing the extra function layer made the logic clearer and more readable to me.
=> Sentry bug | Handle nil stops when building stop markers

apps/site/assets/css/_events.scss, apps/site/assets/js/event-page-setup.js, apps/site/assets/js/test/event-page-setup__test.js, apps/site/assets/js/test/view-previous-events__test.js, apps/site/lib/site_web/templates/event/_event_list.html.eex, apps/site/lib/site_web/templates/event/_expandable_month.html.eex, apps/site/lib/site_web/templates/event/_month.html.eex
**Asana Ticket:** [With js disabled "View previous ..." links don't do anything (Firefox on Mac)](https://app.asana.com/0/555089885850811/1200154247705852)
Enclosed the existing logic in a div that will be shown if JS is enabled. Otherwise, this div will be hidden and the `<noscript>` block will be displayed.
=> Account for JS disabled in the "View Previous ... Events" button

apps/site/assets/css/_event-details.scss, apps/site/assets/css/_utilities.scss, apps/site/lib/site_web/templates/event/_meeting_info.html.eex, apps/site/lib/site_web/templates/event/show.html.eex
**Asana Ticket:** [Add Meeting info section to right-hand rail](https://app.asana.com/0/555089885850811/1199945602717945)
Meeting info details moved to sidebar.  The location doesn't match the design perfectly, because the "Location" field on events includes the floor number.  If that was a separate field, then I could tweak the design a little more precisely.
---
=> Meeting info in sidebar

apps/fares/lib/fares.ex
**Asana Ticket:** [Trip Planner + Line Pages | update route 553/554/556/558 fares to the local fare $1.70](https://app.asana.com/0/555089885850811/1200267766698596)
Those 4 routes have now a fare of $1.70
=> Remove 553/554/556/558 from inner express routes

apps/site/assets/css/_events.scss, apps/site/lib/site_web/templates/event/_calendar.html.eex
**Asana Ticket:** [Overlays don't appear when JS disabled](https://app.asana.com/0/555089885850811/1200196372897040)
When JS is disabled, instead of overlays, we'll have a system tooltip and a link to the corresponding event page:
=> Account for JS disabled in overlays

apps/site/lib/site/icalendar_generator.ex, apps/site/test/site/lib/icalendar_generator_test.exs
**Asana Ticket:** [Events hub | ICS file validation errors](https://app.asana.com/0/555089885850811/1200114012363890)
Most adjustments were slight and formatting-related.  One additional change:  ICS files can't be validated without an end-time, so if there's no end-time, I just added an hour to the start-time.  Of course, this might not always be accurate, like in the case of FMCB meetings.  But I think Google calendar defaults to an hour for new meetings anyway, so does that make sense in our case?
=> ical generator makes an ICS file that passes validation

apps/cms/lib/page/basic.ex
**Asana Ticket:** [Elixir.FunctionClauseError: no function clause matching in CMS.Partial.MenuLinks.from_api/1](https://app.asana.com/0/555089885850811/1199555004763320)
If a CMS page has the attribute field_sidebar_menu, the value should either be populated or an empty array.  But there was a continual issue with the page http://mbta.com/sustainability/community-programs/, in which the field_sidebar_menu value was getting parsed as [nil] (an array with just the value nil.)
In the solution, I was able to adjust the function match for this situation.  Still, I don't know how to determine why that value was getting parsed as [nil] instead of nil or [], since the above link redirects to http://mbta.com/sustainability/, a different page.
=> Sentry Bugfix:  Function Clause Error in CMS.Page.Basic.from_api

semaphore/build_push.sh
This is causing authentication errors in Semaphore:
https://semaphoreci.com/mbta/dotcom/servers/docker-test/deploys/4
I had included this fix in PR #693 but it got overwritten somehow 😞
=> Update command to use AWS CLI v2

apps/site/lib/site_web/controllers/schedule/line.ex, apps/site/test/site_web/controllers/schedule/line_test.exs
**Asana Ticket:** [Line Diagram | Elixir.ArgumentError: argument error](https://app.asana.com/0/555089885850811/1200334263746937)
I think all possible ill-formed direction_ids from the URL should be filtered out now!  Added tests to catch all those cases.
=> Sentry:  URL with a faulty direction_id caused breakage

apps/site/lib/site_web/controllers/customer_support_controller.ex, apps/site/test/site_web/controllers/customer_support_controller_test.exs
**Asana Ticket:** [Customer Support | Elixir.Phoenix.ActionClauseError: no function clause matching in SiteWeb.CustomerSupportController.submit/2](https://app.asana.com/0/555089885850811/1200334203657800)
This Sentry issue was triggered often from the customer feedback form, but all the submissions looked like they were from bots.  Sure enough, looks like bots were trying to bypass the recaptcha by posting directly to the page without the correct "g-recaptcha-response" value in the request.  We didn't have a function that matched this malformed request, so it threw a Sentry error.  I added one that does match, and it just captures the error.
To recreate the issue and test the fix, I used Postman to submit requests like the ones getting submitted by the bot.  Here's an example.  Submit …
=> Sentry 🐛| Added func to catch (& discard) feedback submissions from bots

apps/site/lib/site_web/controllers/schedule/line/helpers.ex
This work will need to be done eventually, but the way it was done in this PR was incorrect and undertested.
https://github.com/mbta/dotcom/commit/8fefd340dcfdf2f79026546556c037600c127242
=> Roll back removal of references to the shape endpoint

.github/workflows/crawler.yml, .github/workflows/deploy-dev.yml
The website crawler was running as a part of the Dev deploy, which failed the [latest build](https://github.com/mbta/dotcom/actions/runs/947166638). This pulls the checker into a separate workflow step so that it runs, but doesn't fail the deployment.
Run: https://github.com/paulswartz/dotcom/actions/runs/947340267
---
=> ci: pull website crawler out into a separate action

apps/site/lib/site_web/views/partial_view.ex, apps/site/test/site_web/views/partial_view_test.exs
**Asana Ticket:** [⏱️ Schedules | Clicking an alert filter should not change which line page you are on](https://app.asana.com/0/385363666817452/1199671198523838)
E.g. for the case of the Green Line branches, it shouldn't show the generic Green Line alerts but the ones for the particular branch (see link at bottom of screenshot):
=> Ensure alerts are for the proper route using its id

apps/site/assets/js/event-page-setup.js
**Asana Ticket:** [Events | When you're in a previous year, you can't click to a different year in the drop down](https://app.asana.com/0/555089885850811/1200448490117396)
Turns out, the JS setup function wasn't running all the way because we didn't check to make sure the the "previous events" button existed before trying to alter its classlist.  Simple conditional fixed the whole shebang.
=> Uncaught error was preventing some JS from loading

apps/site/lib/site_web/views/partial_view.ex, apps/site/test/site_web/views/partial_view_test.exs
Undo PR #965 because it contains breaking changes for the alerts page.
=> Undo breaking changes

apps/site/assets/js/event-page-setup.js, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/TripDetails.tsx
**Asana Ticket:** [⏱️ Schedule Finder | Don't show normal fare next to shuttle](https://app.asana.com/0/385363666817452/1199903976071291)
showFares was already set up for another component in the same file, so only needed to copy it so it shows up in the ScheduleFinder
=> Hide fares from CR shuttle trips in Schedule Finder

apps/site/assets/js/event-page-setup.js, apps/site/assets/ts/helpers/date.ts, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleModalContent.tsx, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/ServiceOptGroup.tsx
**Asana Ticket:** [Schedule Finder | Says no service on date with service](https://app.asana.com/0/385363666817452/1200532032193761/f)
Even though the `today` parameter was correct (2021-06-28), inputting it into `new Date()` brought it back to yesterday (a Sunday with no service on this and many lines), thanks UTC. 🤦🏻‍♀️ So when we checked if there was service today, today meant yesterday instead of today.
This corrects for that so that `CR-Franklin` can now show upcoming departures instead of the "there is no schedule service today" message.
I also decided to apply the same correction in a couple other locations where I'd similarly used `new Date()`.
=> hotfix: Handle service date correctly

apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/lib/site_web/controllers/schedule/line/diagram_helpers.ex, apps/site/test/site_web/controllers/schedule/line_test.exs, apps/stops/lib/route_stops.ex, apps/stops/test/route_stops_test.exs
**Asana Ticket:** [Elixir.FunctionClauseError: no function clause matching in Stops.RouteStops.branch/1](https://app.asana.com/0/385363666817452/1200033257113092)
I was unable to reproduce the error but I did force an 'empty list scenario' and added this fix for it.
=> Handle an empty list of RouteStop structs

apps/site/react_renderer/package-lock.json, apps/site/react_renderer/package.json
No ticket, just part of the ongoing chore of updating dependencies.
I eventually realized that this whole module was kind of simple, just a single `app.js` that webpack builds. And dependabot keeps trying to update each of its dependencies. So I thought... how hard could this be? To just update _everything_?
It turns out it was quite easy, so I'm opening a PR here.
I'm just aiming for not breaking anything! So I've deployed it onto dev blue so I could poke around it and check if anything broke. I invite reviewers to help me with this check. :)
Not sure what to look for? 👇🏼 Read on.
---
As far as I can tell, the node script takes each of these React components:
https://github.com/mbta/dotcom/blob/d6f1b7c41be84768697108b7b3750e2b1ce3b7ef/apps/site/react_renderer/app.js#L56-L65
and takes in …
=> Upgrade react_renderer dependencies

apps/site/assets/js/app.js, apps/site/assets/js/turbolinks-mods.js, apps/site/assets/ts/ie-warning-entry.ts, apps/site/assets/ts/ie-warning/IEWarning.tsx, apps/site/assets/ts/ie-warning/__tests__/IEWarningTest.tsx, apps/site/assets/ts/ie-warning/components/IEWarningBanner.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/__snapshots__/TripDetailsTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/__tests__/TripDetailsTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/upcoming-departures/__tests__/__snapshots__/TripDetailsTest.tsx.snap, apps/site/assets/webpack.config.base.js, apps/site/lib/site_web/templates/layout/app.html.eex
A different way of loading the files needed to display the IE warning without making use of Turbolinks. Should go together with/fixes faulty behavior from #963.
=> Fix for IE warning logic

apps/site/lib/site_web/views/partial_view.ex, apps/site/test/site_web/views/partial_view_test.exs
**Asana Ticket:** [Alerts | Alerts should be for proper route_id when route_id is relevant](https://app.asana.com/0/555089885850811/1200500758083708)
Refining the work done in #965 because it was breaking the alert page for modes. With these changes, all alert pages should not give any errors.
=> Item can be a mode or a Route in Alerts pages

apps/site/assets/ts/helpers/service.ts, apps/site/assets/ts/schedule/components/schedule-finder/ScheduleFinderModal.tsx, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/ScheduleModalContentTest.tsx, apps/site/assets/ts/schedule/components/schedule-finder/__tests__/__snapshots__/ScheduleFinderModalTest.tsx.snap, apps/site/assets/ts/schedule/components/schedule-finder/daily-schedule/__tests__/ServiceOptGroupTest.tsx
**Asana Ticket:** [⏱️ Schedule Finder | Weekend schedule defaulting on a weekday](https://app.asana.com/0/385363666817452/1199963269146218/f)
I'm somewhat sure this particular issue was fixed in #893 or #994 but in the meantime I've added at least a few basic test cases around the schedule finder displaying the no-trips-today message and the service selector indicating which schedule is 'now'.
There's more tech debt to tackle than I'd like, so no big changes here 😓 
---
=> Some tests  improvements around schedule finder's default day

apps/site/assets/ts/schedule/components/ScheduleLoader.tsx, apps/site/assets/ts/schedule/components/__tests__/ScheduleLoaderTest.tsx, apps/site/assets/ts/schedule/schedule-loader.tsx
**Asana Ticket:** [Schedules | 🐞 Right side accordions don't open on suspended routes](https://app.asana.com/0/555089885850811/1200532824750507)
`renderAdditionalLineInformation` should also be called for suspended routes, so that React _kicks in_ and enables the expand/collapse functionality of the blocks on the right rail.
Also, for these same suspended routes, we only want to show teasers and upcoming holidays, no other information like fares or connections, etc.
=> Expandable blocks in line page for suspended routes

apps/site/assets/css/_accordion-ui.scss, apps/site/assets/css/_trip-plan-results.scss, apps/site/assets/css/_trip-plan.scss, apps/site/assets/ts/components/Accordion.tsx, apps/site/assets/ts/trip-plan-results/__tests__/TripPlannerResultsTest.tsx, apps/site/assets/ts/trip-plan-results/__tests__/__snapshots__/TripPlannerResultsTest.tsx.snap, apps/site/assets/ts/trip-plan-results/components/Itinerary.tsx, apps/site/lib/site_web/templates/partial/_accordion_ui.html.eex, apps/site/lib/site_web/templates/partial/_expandable_block.html.eex, apps/site/test/site_web/views/trip_plan_view_test.exs
**Asana Ticket:** [Accordions | Accordions should work without JS](https://app.asana.com/0/555089885850811/1200191571993850)
Added some blocks to show content that wasn't being shown earlier and might be relevant for riders. Some examples are:
- Itineraries in Trip Planner results.
- Blocks in the right rail in the Customer Support form and in the line page.
- Icon Key section in the Commuter Rail timetable.
- /fares/reduced page
- ...
=> Account for JS disabled for accordions and expandable blocks

apps/site/lib/site_web/controllers/schedule/line_controller.ex, apps/site/test/site_web/controllers/schedule/line_controller_test.exs
**Asana Ticket:** [Elixir.UndefinedFunctionError: function nil.calendar/0 is undefined](https://app.asana.com/0/555089885850811/1199903866102716)
This error happened back in late January and the details are not available in Sentry anymore.
I tried my best to investigate what happened and it looks like `Schedules.Repo.end_of_rating` might return nil in some scenarios. So I added a small tweak to avoid `Date.compare` to break.
=> Account for `end_of_rating` returning nil

apps/site/assets/js/datepicker-input.js
**Asana Ticket:** [🐞Trip Planner | Fields should clear when new form submitted](https://app.asana.com/0/555089885850811/1150378678618193)
The affected piece of code was mixing JS and jQuery. I updated it so the dreaded `[object Object]` doesn't get added to the selector.
=> Fix for year not updating properly in Trip Planner selection (left panel)

.github/workflows/tests.yml, apps/site/assets/css/_ie-warning.scss, apps/site/config/test.exs, apps/site/test/site/application_test.exs, cypress/integration/customer-support-form/support_form.spec.js, package.json
**Asana Ticket:** [Tech Debt | All CI steps should run on main branch](https://app.asana.com/0/385363666817452/1200549651204429/f)
The first commit is unrelated to the linked Asana ticket. It restructures the `tests.yml` workflow jobs, mainly adding a `build` job that basically does the same as `npm run build` but more methodically and with caching. The whole workflow ends up a bit faster since it's not building the same build several times.
You can see the effect of this change: https://github.com/thecristen/dotcom/actions/runs/1054828882
The second and third commit: lets the `tests.yml` workflow run on pushes to the master branch. Tweaks the job logic so that every test will run on master (whereas in PRs, some tests might get skipped depending on the types of files that have changed). …
=> Github Actions: build cache, run all tests on master branch

apps/site/lib/site_web/controllers/helpers.ex, apps/site/lib/site_web/endpoint.ex, apps/site/lib/site_web/plugs/uri_checker.ex, apps/site/lib/site_web/redirector.ex, apps/site/test/site_web/controllers/helpers_test.exs, apps/site/test/site_web/plugs/uri_checker_test.exs
**Asana Ticket:** [Elixir.ArgumentError: malformed URI "Potential%20MBTA%"](https://app.asana.com/0/555089885850811/1198971266994640)
I created a simple plug that attempts to check whether `conn.path_info` contains malformed information before calling the router. If so, it redirects to the 404 page.<br/>
Refactor: since I was going to use `render_not_found` in this new plug, I moved it to `SiteWeb.ControllerHelpers`.
=> Add a plug so that if URI is malformed, the 404 page is rendered

apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs
**Asana Ticket:** [Schedules Map API | Elixir.CaseClauseError: no case clause matching: %JsonApi{data: %JsonApi.Item{attributes: %{"color" => "DA291C", "descri...](https://app.asana.com/0/555089885850811/1200280548002897)
A small check to avoid a crash when route_id is empty.
=> Account for empty route id

apps/site/assets/ts/schedule/components/line-diagram/VehicleIcons.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/MergeTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/VehicleIconsTest.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/LineDiagramWithStopsTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/__tests__/__snapshots__/VehicleIconsTest.tsx.snap, apps/site/assets/ts/schedule/components/line-diagram/graphics/Diagram.tsx
**Asana Ticket:** [Add arriving track number to vehicle tooltip on the timetable, line diagram, and map when we have it](https://app.asana.com/0/1200650448662357/1199653833933398)
Partial solution to the ticket. This PR only addresses showing the track number in the Line Diagram:<br/>
=> Track number in tooltip in line diagram

apps/site/lib/predicted_schedule.ex, apps/site/lib/site/transit_near_me.ex, apps/site/test/predicted_schedule_test.exs
**Asana Ticket:** [Stops | Elixir.UndefinedFunctionError: function nil.id/0 is undefined](https://app.asana.com/0/385363666817452/1200280592452254/f)
This error prominently came up while creating a new map via the `PredictedSchedule.group_transform` function, so I added some more logic to mitigate against those errors.
=> Stops | Elixir.UndefinedFunctionError: function nil.id/0 is undefined

apps/site/assets/css/_schedule.scss, apps/site/assets/css/_variables.scss
**Asana Ticket:** [CR Schedules | Schedules & Maps tab disappears on mobile](https://app.asana.com/0/1200650448662357/1200689234093004)
There was a CSS rule to hide the tab, I assume this must be an old snippet that was forgotten. Tab does not hide anymore!
**Before**:<br/>
**After**:<br/>
=> Do not hide schedule and maps tab when mobile for CR

apps/site/assets/ts/components/__tests__/HeadsignTest.tsx, apps/site/assets/ts/components/__tests__/__snapshots__/HeadsignTest.tsx.snap, apps/site/assets/ts/helpers/__tests__/date-test.ts, apps/site/assets/ts/helpers/date.ts, apps/site/assets/ts/helpers/prediction-helpers.tsx, apps/site/assets/ts/schedule/components/__tests__/ScheduleDirectionTest.tsx, apps/site/assets/ts/tnm/__tests__/__snapshots__/RoutesSidebarTest.tsx.snap
**Asana Ticket:** [⏱ Schedules | "Arrival" time is confusing to customers](https://app.asana.com/0/555089885850811/1200119447648715)
Putting this together in case it's a valid solution.<br/>
I just added a slight modification whenever the commuter rail's status is 'On time'. If so, the time displayed is the one from the scheduled time and not the prediction.
=> Show scheduled time (not predicted) for CR when status is 'on time'

apps/site/assets/ts/leaflet/components/Map.tsx, apps/site/assets/ts/schedule/components/__tests__/MapTest.tsx, apps/site/assets/ts/schedule/components/__tests__/__snapshots__/MapTest.tsx.snap
Asana ticket TBA
This change listens to Leaflet's `onload` event to add a class to the component after all visible tiles have loaded.
I plan to use that class in the future to get visual tests to wait until all the tiles are loaded before taking a screenshot!
=> feat: Add class name when map tiles loaded

apps/routes/lib/route.ex, apps/routes/test/route_test.exs, apps/site/lib/site_web/views/helpers.ex, apps/site/test/site_web/views/helpers_test.exs, apps/trip_plan/lib/trip_plan/leg.ex
**Asana Ticket:** [Trip Planner | 🐛 Massport trip plans don't cause 500 errors](https://app.asana.com/0/385363666817452/1200911564672884/f)
Massports GTFS file was slightly tweaked at the start of Sept, which I believe created this issue! I'd guess most trip plans involving Logan Airport were affected. Here's a fix!
You can test with this trip plan url - /trip-planner?_utf8=✓&plan%5Bfrom%5D=Boston+Logan+Airport&plan%5Bfrom_latitude%5D=42.365396&plan%5Bfrom_longitude%5D=-71.017547&plan%5Bto%5D=Suffolk+Downs&plan%5Bto_latitude%5D=42.390501&plan%5Bto_longitude%5D=-70.997123&plan%5Btime%5D=depart&plan%5Bdate_time%5D%5Bhour%5D=2&plan%5Bdate_time%5D%5Bminute%5D=15&plan%5Bdate_time%5D%5Bam_pm%5D=PM&plan%5Bdate_time%5D%5Bmonth%5D=9&plan%5Bdate_time%5D%5Bday%5D=9&plan%5Bdate_time%5D%5Byear%5D=2021& …
=> Massport trip plan fix

apps/site/assets/ts/schedule/components/line-diagram/LineDiagram.tsx, apps/site/assets/ts/schedule/components/line-diagram/__tests__/LineDiagramTest.tsx
**Asana Ticket:** [Schedules | Don't poll for live data on the ferry pages](https://app.asana.com/0/385363666817452/1200767316460648/f)
To be honest I'm not sure _why_ conditionally defining the URL as `""` works to achieve my goal. The internal workings of `useSWR` are beyond me. But it totally stops polling `/realtime` on ferry pages!
---
=> fix(LineDiagram): Don't poll live data for ferry

apps/site/lib/site/application.ex
Now the endpoint will wait for the other processes to initialize before itself starting.
Asana ticket: [Tech Debt | Call supervisor children in correct order](https://app.asana.com/0/385363666817452/1200943226791246/f)
=> fix(Application): Make SiteWeb.Endpoint last child

.github/workflows/tests-dependabot.yml, .github/workflows/tests.yml
**Asana Ticket:** [Fix CI tests for Dependabot PRs](https://app.asana.com/0/385363666817452/1200701591068667/f)
Turns out it seems to make more sense to create two similar-but-different CI workflows, one which gets triggered by Dependabot PRs, and other by everything else.
The Dependabot PR CI workflow uses the `pull_request_target` event to get around the issues around accessing secrets (which are needed to run a few CI tests) cited here: https://github.com/dependabot/dependabot-core/issues/3253#issuecomment-852541544
I mainly identify Dependabot PRs by checking `github.head_ref` and `github.actor`. 
* The head ref value will be the branch name in the case of PRs (e.g. `refs/heads/dependabot/npm_and_yarn/apps/site/react_renderer/babel/core-7.15.5`). I don't believe this has a value on …
=> Fix CI tests for Dependabot PRs

apps/site/config/dev.exs, cypress/integration/customer-support-form/support_form.spec.js, cypress/integration/screenshots.spec.js, cypress/plugins/index.js, cypress/support/commands.js, package.json
Asana ticket [Assorted fixes for aiding consistent snapshot recording](https://app.asana.com/0/385363666817452/1200881265733025/f)
Not much to _see_ here but if you unskip the new tests you can see the screenshots it generates! I didn't want to commit screenshots to this repo quite yet, so that's why the tests that create the screenshots are skipped here.
Also threw in the ability to specify a port to run tests on on the fly, and added a baseUrl configuration so that tests don't have to specify the base URL every time.
=> a few Cypress enhancements

apps/site/lib/site_web/controllers/helpers.ex, apps/site/test/site_web/controllers/helpers_test.exs
**Asana Ticket:** [Really block dev environments from search engines](https://app.asana.com/0/385363666817452/1201031900628965/f)
It turns out a function was adding an `unavailable_after` value for `x-robots-tag` indiscriminately for events and news entries, which was butting against how we add the `noindex` value for `x-robots-tag` for all pages in our non-prod environments. This change aims to fix that.
---
=> fix(ControllerHelpers): no overwrite x-robots-tag

apps/site/lib/site_web/views/partial_view.ex
**Asana Ticket:** [Schedules | Elixir.FunctionClauseError: no function clause matching in List.first/1](https://app.asana.com/0/555089885850811/1201042269068385)
We assign CMS teasers with an async function.  The default value for "featured_content" teasers is set to nil until the content is populated by the async function.  We didn't have a render_teaser function that could accept nil, so any time the assign was going on too long, an error is generated.
=> List.first Sentry bug

apps/site/config/dev.exs, apps/site/test/site_web/controllers/helpers_test.exs, apps/site/test/site_web/controllers/news_entry_controller_test.exs
No ticket - quick fix for some failing Elixir tests as a result of merging in #1088. 
These values change based on the application configuration, which varies between prod/dev/test environments. So these particular tests need to make sure to be set a particular way to enable these tests to test the things they are trying to test. 🙂
=> Fix tests affected by how we set x-robots-tag

apps/site/lib/site_web/controllers/transit_near_me/location.ex, apps/site/lib/site_web/controllers/transit_near_me_controller.ex
**Asana Ticket:** [Transit Near Me | Elixir.FunctionClauseError: no function clause matching in SiteWeb.TransitNearMeController.Location.parse_float/1](https://app.asana.com/0/555089885850811/1200280531064861)
Not quite sure how "nil" lat or lng is getting input in the url string -- is there any way for us to verify whether we generate a url like that anywhere?  That seems like an impossibly hard to answer question.  But anywho -- now the nil value is getting handled properly.
=> Sentry issue: nil lat / lng should be discarded in Transit Near Me

apps/site/lib/site_web/controllers/trip_plan_controller.ex
Our last workaround, accommodating "Massport-1" as a route type, stopped working because now the Massport buses are returning as route type "1". So for the sake of the Trip Planner, let's stop relying on the given type and stick to "Massport-1". This ensures that the correct icon (bus) and naming ("Massport shuttle") shows in the itinerary information.
**Asana Ticket:** [Trip Planner | Crashes when using Massport routes](https://app.asana.com/0/385363666817452/1201105996476530/f)
=> fix(TripPlanController): set Massport route type

apps/routes/lib/mock_repo_api.ex, apps/site/test/site_web/controllers/schedule/line/helpers_test.exs
... to catch cases where there aren't scheduled trips.  Prompted during the development of this branch, waaaay back when:  https://github.com/mbta/dotcom/pull/848 
**Asana Ticket:** [Testing | Cover route without scheduled trips](https://app.asana.com/0/555089885850811/1200172434828846)
=> Added a `get_shapes_by_direction` test 

apps/site/lib/green_line.ex, apps/site/lib/site/content_rewriter.ex, apps/site/lib/site/content_rewriters/embedded_media.ex, apps/site/lib/site_web/controllers/schedule/line/helpers.ex, apps/site/test/green_line_test.exs, apps/site/test/site/content_rewriters/responsive_tables_test.exs, apps/site/test/site/floki_helpers_test.exs, apps/site/test/site_web/controllers/schedule/finder_api_test.exs, apps/site/test/site_web/controllers/schedule/line_test.exs, apps/site/test/site_web/excluded_stops_test.exs, apps/site/test/site_web/views/helpers_test.exs, apps/site/test/site_web/views/mode_view_test.exs, apps/site/test/site_web/views/partial_view_test.exs, apps/site/test/site_web/views/schedule_view_test.exs, apps/site/test/site_web/views/trip_plan_view_test.exs
No ticket, just took some time to dig into what was going on with the tests that we'd recently skipped. 
* The first two commits make additional fixes that were needed after we updated the GL eastbound termini, and updates the corresponding tests. 
* The third commit unskips a test that now works. 
* The fourth commit refactors several tests to get rid of the `Floki.parse` deprecation message. And then I decided to stop and make this PR. :)
=> More retroactive test fixes + updates

apps/site/lib/site_web/controllers/trip_plan_controller.ex
**Asana Ticket:** [Trip Planner | Remove duplicate related link](https://app.asana.com/0/385363666817452/1200984438570060/f)
Filtered out duplicate schedule links in trip planner itinerary.
=> Remove duplicate related links from trip planner

apps/site/config/config.exs, apps/site/config/prod.exs, apps/v3_api/lib/headers.ex, apps/v3_api/test/headers_test.exs
Configurable via environment variable, defaults to enabled on non-production environments.
**Asana Ticket:** [Enable MBTA V3 API experimental features](https://app.asana.com/0/555089885850811/1201306297717355/f)
=> feat: Enable experimental features in API requests

apps/schedules/lib/parser.ex, apps/schedules/lib/repo.ex, apps/schedules/lib/schedule.ex, apps/schedules/test/parser_test.exs, apps/schedules/test/repo_test.exs, apps/stops/test/api_test.exs, apps/v3_api/lib/trips.ex, apps/vehicles/lib/parser.ex
**Asana Ticket:** [Retrieve crowding info for commuter rail routes](https://app.asana.com/0/385363666817452/1201303796115902/f)
Updated the API request for trips to get occupancy information via `[include: "occupancies"]`, and parse and save the resulting data.
=> Retrieve crowding info for commuter rail routes

apps/site/assets/js/algolia-autocomplete.js
Instead of sending queries on every input change, limit queries to being sent every .5 second. This should dramatically reduce the number of extraneous requests sent to Google's Places API while maintaining the interactivity and accuracy of autocomplete search results.
=> debounce the Algolia autocomplete result list

apps/site/lib/site_web/templates/event/show.html.eex
**Asana Ticket:** [Hide registration section when registration URL isn't provided](https://app.asana.com/0/385363666817452/1201348288803391/f)
Don''t show registration link if it isn't available. Instead uses previous copy of `Virtual meeting registration will be available soon`
=> Hide  Registration if Null

apps/site/lib/site_web/controllers/schedule/finder_api.ex, apps/site/lib/site_web/views/layout_view.ex
No ticket, just noticed a `[warn] route_id_not_found route_id=Green, trip_id=ADDED-1591071232` logged while working on another task. Similar warnings are logged many times a day (see chart from Splunk below!).
---
Sometimes trips don't have associated schedules: for example trip id `ADDED-1591071232` was added to the rotation but wasn't originally scheduled to run. This can also happen with shuttle trips. In these cases, using `Schedules.Repo.schedule_for_trip()` will return empty.
Since `get_route_id` is just trying to fetch the route ID for the trip, we can do that by fetching the trip directly, and then fetching the trip's associated route pattern, from which we can get the ID.
=> refactor(FinderApi): Get trip route ID via route pattern

apps/site/config/config.exs, apps/site/lib/site_web/templates/event/show.html.eex, apps/site/test/site_web/controllers/event_controller_test.exs
**Asana Ticket:** [Remove feature flag for new event agendas](https://app.asana.com/0/555089885850811/1201507862161340/f)
Remove feature flag from new event agendas. If new agenda is not used fallback to old style.
=> Remove Feature Flag for New Event Agendas

apps/site/lib/site_web/templates/page/_secondary_nav.html.eex
**Asana Ticket:** [Mobile menu: Missing secondary nav](https://app.asana.com/0/385363666817452/1201529194279319/f)
Removed the check to hide the secondary nav bar if the mobile nav redesign flag was set.
=> dont remove secondary nav bar if mobile nav redsign flag is set

apps/site/lib/site_web/templates/layout/app.html.eex
**Asana Ticket:** [Mobile menu: Dark blue background should extend to very top of screen](https://app.asana.com/0/385363666817452/1201529194279336/f)
Change via the theme-color meta tag which explicitly sets the status bar background color rather than the os/browser trying to determine what color it should be.
=> add theme-color meta tag to app template

apps/site/assets/ts/app/mobile-menu.ts
**Asana Ticket:** [Investigation: Blue bars appear above and below open sub-menu](https://app.asana.com/0/385363666817452/1201529194279341/f)
Awkwardly, this was mainly a Safari problem. 
I tried...
* unsetting the blue outline through CSS, but no `!important` or higher specificity made the Safari user agent stop rendering its blue outline.
* listening to the `show.bs.collapse` or `shown.bs.collapse` events from Bootstrap's collapse plugin (which the accordions use when opening/closing) to intercept the adding of the blue outline. But I couldn't get this working either.
I settled on listening to the `focus` event on the accordion target, and removing the outline there.
=> fix for Investigation: Blue bars appear above and below open sub-menu

apps/site/assets/ts/app/mobile-menu.ts
**Asana Ticket:** [Scroll disabled after clicking mobile menu link](https://app.asana.com/0/555089885850811/1201708898492559/f)
Added event listeners to menu links to close menu when clicked. This allows the page content to be scrollable again.
=> Allow Scrolling After Link Click

apps/site/assets/css/_header.scss
**Asana Ticket:** [Add spacing at the end of the open menu](https://app.asana.com/0/555089885850811/1201764117487425/f)
Before:
After:
Let me know if this is overkill, but this should give us pretty close to the 200px spacing that Yinka mentioned in the ticket.
=> Add additional spacing below the sidebar language selector

apps/site/assets/css/_global-navigation.scss
restore `$brand-primary` background and `$white` foreground to the old navigation bar's tablet view.
**Asana Ticket:** [Revert old desktop nav button color](https://app.asana.com/0/385363666817452/1201817254333359/f)
old:
new... same as it looks on current mbta.com
=> fix: revert old desktop nav to original style
